### ISSUE TITLE
Microsoft Edge浏览器无法使用

### ISSUE THREAD

**Issue by vastskymiaow** [andywang425/BLTH#10]
Microsoft Edge浏览器加载暴力猴扩展无法使用此脚本，不显示抽奖窗口。
前几天还能使用来着。

版本 84.0.522.40 (官方内部版本) (64 位)
此浏览器基于 Chromium 开源项目及其他 开源软件。

**Comment by andywang425** [comment]
最近也有一位群友反馈说edge用不了，具体原因不明。
他重装edge后就能用了。你也可以重装一下，或者换个浏览器用。

**Comment by andywang425** [comment]
现在基本可以确定是一个GM函数导致的，只能等暴力猴自己修复这个bug。

**Comment by LanceLiaoYuan** [comment]
> 最近也有一位群友反馈说edge用不了，具体原因不明。
> 他重装edge后就能用了。你也可以重装一下，或者换个浏览器用。

我手机yandex用的暴力猴（半个月了），三天前开始也加载不出这个脚本了。

**Comment by 15726238368** [comment]
实测Microsoft Edge浏览器(Chromium)用油猴(Tampermonkey)是可以正常运行这个脚本的

**Comment by vastskymiaow** [comment]
确实是暴力猴的问题，edge浏览器用油猴[Tampermonkey](https://microsoftedge.microsoft.com/addons/detail/iikmkjmpaadaobahmlepeloendndfphd)可以正常使用。

**Comment by Tech-Wang** [comment]
Edge 84.0.522.40 用油猴目前正常
