### ISSUE TITLE
5.6.7.3版本载入卡死

### ISSUE THREAD

**Issue by Fireblossom** [andywang425/BLTH#100]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README和脚本的内置说明。  
**描述bug**  
载入脚本后直播间网页卡死

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. 打开脚本进入直播间
2. 提示CACHE载入成功
3. 卡死，网页无法操作

**预期行为**  
卡死

**截图**  
![image](https://user-images.githubusercontent.com/16226671/116401742-e2f99680-a82b-11eb-8c83-d3f97b70b214.png)

**运行日志**  
无法导出日志，网页卡死

**使用环境:**  
 - 操作系统：`Windows 10`
 - 浏览器及版本: `Chrome 90.0.4430.93`
 - 用户脚本管理器及版本：`Tampermonkey 4.13.6135`
 - 脚本的版本: 如`5.6.7.3`
 - 网络情况(网速): `好`
 - 其他浏览器插件/脚本: 在此写上您认为可能会对本脚本产生影响的插件/脚本

**其他**  
海外

**Comment by Fireblossom** [comment]
是SteamWebIntegration
我眼瞎（

**Comment by andywang425** [comment]
感觉用SteamWebIntegration的人还挺多，以后我会想办法兼容
