### ISSUE TITLE
小心心获取问题

### ISSUE THREAD

**Issue by Tinpa** [andywang425/BLTH#105]
**描述bug**  
弹窗会显示`[小心心]开始获取小心心`，但实际获取不了小心心，似乎是移动端那边的心跳包的问题

**预期行为**  
在未开播的直播间用电脑端挂机会获得24个小心心，

**截图**  
![屏幕快照 2021-05-06 10 39 40](https://user-images.githubusercontent.com/36250538/117392924-985fd480-af25-11eb-9439-39f248de92e1.png)

**运行日志**  
[live.bilibili.com-1620357434613.log](https://github.com/andywang425/BLTH/files/6438794/live.bilibili.com-1620357434613.log)

  

**使用环境:**  
 - 操作系统：`macOS high Sierra 10.13.6`
 - 浏览器及版本：`Chrome 版本 90.0.4430.93（正式版本） (x86_64)`
 - 用户脚本管理器及版本：`Tampermonkey 4.12`
 - 脚本的版本：`5.6.7.6`
 - 网络情况(网速)：`良好`

**Comment by andywang425** [comment]
我看了下你发的日志但是没找到和BLTH有关的内容。  
请确认你是否打开了脚本的控制台日志，打开方式为勾选控制面板上的`其他设置 - 控制台日志`。

**Comment by Tinpa** [comment]
[live.bilibili.com-1620388144576.log](https://github.com/andywang425/BLTH/files/6441785/live.bilibili.com-1620388144576.log)

**Comment by andywang425** [comment]
看了下你的日志但没看出原因，好像是小心心模块在获取完粉丝勋章后卡住了。以后我会再做测试来确定问题根源。

**Comment by kanonmelodis** [comment]
个人为win10+edge+tampermonkey 均为最新版 出现同样的问题 持续大概半个多月了

**Comment by Tinpa** [comment]
> 个人为win10+edge+tampermonkey 均为最新版 出现同样的问题 持续大概半个多月了

我这边倒是已经解决了

**Comment by kanonmelodis** [comment]
> > 个人为win10+edge+tampermonkey 均为最新版 出现同样的问题 持续大概半个多月了
> 
> 我这边倒是已经解决了

能问一下是怎么解决的吗，谢谢

**Comment by Tinpa** [comment]
> > > 个人为win10+edge+tampermonkey 均为最新版 出现同样的问题 持续大概半个多月了
> > 
> > 
> > 我这边倒是已经解决了
> 
> 能问一下是怎么解决的吗，谢谢

就是版本更新了 就解决了，我也没仔细看哪改了

**Comment by andywang425** [comment]
> > > 个人为win10+edge+tampermonkey 均为最新版 出现同样的问题 持续大概半个多月了
> > 
> > 
> > 我这边倒是已经解决了
> 
> 能问一下是怎么解决的吗，谢谢

问一下有没有在同一个浏览器上登陆过多个B站账号？目前已知这么做会导致只能获取其中一个账号的小心心。

**Comment by kanonmelodis** [comment]
> > > > 个人为win10+edge+tampermonkey 均为最新版 出现同样的问题 持续大概半个多月了
> > > 
> > > 
> > > 我这边倒是已经解决了
> > 
> > 
> > 能问一下是怎么解决的吗，谢谢
> 
> 问一下有没有在同一个浏览器上登陆过多个B站账号？目前已知这么做会导致只能获取其中一个账号的小心心。

没有 等过0点我自己先试试吧

**Comment by kanonmelodis** [comment]
> 问一下有没有在同一个浏览器上登陆过多个B站账号？目前已知这么做会导致只能获取其中一个账号的小心心。

虽然没有登录过多个账号 但是根据这条线索清除了b站cookies重新登录之后解决了

**Comment by andywang425** [comment]
> > 问一下有没有在同一个浏览器上登陆过多个B站账号？目前已知这么做会导致只能获取其中一个账号的小心心。
> 
> 虽然没有登录过多个账号 但是根据这条线索彻底清除了b站cookie重新登录之后解决了

感谢反馈，那我大概知道该怎么改进了

**Comment by andywang425** [comment]
请问最新版是否还存在该问题？

**Comment by andywang425** [comment]
如果仍有问题请另开issue讨论。
