### ISSUE TITLE
自己原先已经关注的主播抽奖时也会被加入相关分组，结果到时候统一取关时被一同取关了

### ISSUE THREAD

**Issue by luotianyiismywife** [andywang425/BLTH#114]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README和脚本的内置说明。  
**描述bug**  
简要描述所遇到的bug

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. 自己原先已经关注的主播抽奖时也会被加入相关分组，结果到时候统一取关时被一同取关了

**预期行为**  
统一取关时被一同取关了

**运行日志**  
脚本日志窗口中的普通日志或控制台日志。  
控制台日志的打开方式见README中[控制台日志](https://github.com/andywang425/BLTH/blob/master/README.md#控制台日志)一节。  
普通日志请直接截图。控制台日志可截图或右键导出。  

**使用环境:**  
 - 操作系统：如`Windows 10`
 - 浏览器及版本: 如`Chrome 81.0.3147.89`
 - 用户脚本管理器及版本：如`Tampermonkey 4.11`
 - 脚本的版本: 如`5.6`
 - 网络情况(网速): `好`/`一般`/`坏`
 - 其他浏览器插件/脚本: 在此写上您认为可能会对本脚本产生影响的插件/脚本

**其他**  
若您有其他想要补充的内容，请在此说明

**Comment by andywang425** [comment]
首先，请完整填写所有反馈项目。如果你觉得没必要写请直接删掉那几节。  
> 自己原先已经关注的主播抽奖时也会被加入相关分组，结果到时候统一取关时被一同取关了  

然后你在预期行为里写：  

> 统一取关时被一同取关了

这不是相符的吗。我这里猜想你是不想这些UP被一同取关。  
目前脚本在不出bug的情况下是不会把在白名单内或天选功能运行前在默认/特别关注分组内的UP移入`BLTH天选关注UP`分组的。请给出更多信息以便我找到问题所在。

**Comment by andywang425** [comment]
如果仍有问题请另开issue讨论。
