### ISSUE TITLE
微软edge dev浏览器加载5.6.9.2版本没有反应

### ISSUE THREAD

**Issue by jkluio78** [andywang425/BLTH#116]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README和脚本的内置说明。  
**描述bug**  
微软edge dev浏览器加载5.6.9.2版本没有反应，浏览器只开启了此插件

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. 进入直播间之前确认脚本已开启
2. 进入后没有出现 控制面板 和 日志 ，多次刷新也没有反应

**预期行为**  
出现 控制面板 和 日志 

**截图**  
![image](https://user-images.githubusercontent.com/74967641/119614593-0a468200-be31-11eb-9d4b-d5b5776fd4df.png)

**运行日志**  
  
![image](https://user-images.githubusercontent.com/74967641/119614731-395cf380-be31-11eb-880b-6d19c1cce579.png)

**使用环境:**  
 - 操作系统：`Windows 8.1`
 - 浏览器及版本: 如`Microsoft Edge 90.0.818.66 (64 位)`
 - 用户脚本管理器及版本：如`Tampermonkey 4.13`
 - 脚本的版本: 如`5.6.9.2`
 - 网络情况(网速): `好`
 - 其他浏览器插件/脚本: 无

**其他**  
若您有其他想要补充的内容，请在此说明

**Comment by andywang425** [comment]
看了你的日志应该是有个库文件(`jQuery`)出错，根据我的经验似乎在网特别差的时候容易出这个bug，但你网络情况好还bug我就
不清楚具体原因了。    

我可以先给个临时解决方案，可能有效：  

在油猴里打开这个脚本，在代码中搜索`document-start`，替换成`document-end`，然后ctrl+s保存。  
缺点就是部分功能会失效（弹幕修改，拦截直播流之类的）

**Comment by jkluio78** [comment]
> 看了你的日志应该是有个库文件(`jQuery`)出错，根据我的经验似乎在网特别差的时候容易出这个bug，但你网络情况好还bug我就
> 不清楚具体原因了。
> 
> 我可以先给个临时解决方案，可能有效：
> 
> 在油猴里打开这个脚本，在代码中搜索`document-start`，替换成`document-end`，然后ctrl+s保存。
> 缺点就是部分功能会失效（弹幕修改，拦截直播流之类的）

感谢作者，方法奏效了，这两天进直播间都能正常加载脚本了

**Comment by andywang425** [comment]
我翻了下jquery的相关issue [Cannot read property 'createElement' of undefined](https://github.com/jquery/jquery/issues?q=is%3Aissue+Cannot+read+property+%27createElement%27+of+undefined ) ，发现这好像是个历史遗留问题，当jquery在特殊环境中运行时就有概率报这个错。  
然后我琢磨了半天解决方法，写了个[测试脚本](https://cdn.jsdelivr.net/gh/andywang425/mycdn@6a5b335dadadf86469792dcbf2a559d91cdaf6cb/BLTH-jquery-bug-fix-test.js)出来，你可以点链接然后复制代码到油猴试试能不能运行。因为我这边出这个问题的概率极低，所以没法测试有没有修复成功，只好麻烦你试试了。

**Comment by jkluio78** [comment]
> 我翻了下jquery的相关issue [Cannot read property 'createElement' of undefined](https://github.com/jquery/jquery/issues?q=is%3Aissue+Cannot+read+property+%27createElement%27+of+undefined) ，发现这好像是个历史遗留问题，当jquery在特殊环境中运行时就有概率报这个错。
> 然后我琢磨了半天解决方法，写了个[测试脚本](https://cdn.jsdelivr.net/gh/andywang425/mycdn@6a5b335dadadf86469792dcbf2a559d91cdaf6cb/BLTH-jquery-bug-fix-test.js)出来，你可以点链接然后复制代码到油猴试试能不能运行。因为我这边出这个问题的概率极低，所以没法测试有没有修复成功，只好麻烦你试试了。


我试着运行了下测试脚本，`document-start`的时候，刷新30次直播间只会加载出来2次。`document-end`的时候每次都能加载出来。
![B46FF`$KVTEN_5T{7(4I6G5](https://user-images.githubusercontent.com/74967641/120070237-21e56b00-c0bc-11eb-8d72-9e6a4d330d2b.png)


还有个疑问就是，脚本运行过程中是否还会出现 **加载不出jQuery库** 的情况，我把浏览器放在前台运行，过了一段时间再去看运行日志，有很长一段时间的空白时间，好像功能全部停止了，类似运行一段时间休眠一段时间这样，浏览器的休眠我也关掉了，应该不是浏览器的问题

**截图**
1.参与天选从9点开始，持续到12点才结束。分别在9:08，11:28，11:55参加了3次
![image](https://user-images.githubusercontent.com/74967641/120070551-aa184000-c0bd-11eb-8b42-b4479152cdde.png)
2.我查看日志的时候，11:28参加的天选还有156秒才开奖，而11:55参与的已经开奖了
![image](https://user-images.githubusercontent.com/74967641/120070571-c2885a80-c0bd-11eb-8346-bb86c5dde83c.png)

**Comment by andywang425** [comment]
那这个bug就先搁置吧，我实在无能为力。  
> 有很长一段时间的空白时间   

这我也不知道为啥。大概只能换个浏览器试试了？

**Comment by jkluio78** [comment]
问了群友知道了一个解决的办法，如果刷新浏览器加载不出来插件的话，先关闭油猴，刷新页面，然后再打开油猴，等大约10s插件就可以加载出来了（全程不用关闭插件重启，只对油猴重启）

**Comment by andywang425** [comment]
> 问了群友知道了一个解决的办法，如果刷新浏览器加载不出来插件的话，先关闭油猴，刷新页面，然后再打开油猴，等大约10s插件就可以加载出来了（全程不用关闭插件重启，只对油猴重启）

感谢，我把你这个方法记下了，下次更新的时候会在README里写一下。
