### ISSUE TITLE
中奖后消息通知无效

### ISSUE THREAD

**Issue by labilio** [andywang425/BLTH#117]
天选中将之后，脚本无法通过酷推/server酱/推送加  推送中奖信息   我全部都勾选了，并且填写了正确的token 

预期行为
通过 酷推/server酱/推送加  推送中奖信息

**截图**  

![反馈1](https://user-images.githubusercontent.com/83277902/119938918-b027f700-bfbf-11eb-9479-725b1df12019.jpg)

一切都正常

**运行日志**  
日志一切正常

**使用环境:**  
 - 操作系统：‘Windows 10’
 - 浏览器及版本: ‘Chrome 91.0.4472.77’
 - 用户脚本管理器及版本：‘Tampermonkey 4.13’
 - 脚本的版本: 如`5.6.9.2
 - 网络情况(网速): `好`
 - 其他浏览器插件/脚本: 无

**其他**  
4月29日时，酷推还能正常推送，那是我收到的最后一条推送了。在这之后就从没有QQ/微信推送
更改sendkey 也没有用

**Comment by andywang425** [comment]
请问脚本能否正确检测到中奖？是检测到了但没推送还是压根没检测到。目前已知如果主播连着开天选（间隔小于3秒）是检测不到中奖的。

可以在下次中奖之后在控制台里搜`PP_sendMsg response`，`CP_sendMsg response`，`ServerTurbo_sendMsg response`。这三条日志分别对应推送加，酷推，server酱turbo。把这几条日志展开来看看可能可以看出无法推送的原因。  

现在有些人说能推送，有些人说不行，我也不知道为啥。。。

**Comment by labilio** [comment]
中奖了，系统能检测到中奖，如图
![QQ截图20210529093821](https://user-images.githubusercontent.com/83277902/120054428-6ba16780-c062-11eb-9489-e3097ca82973.jpg)
这是控制台的信息
![QQ截图20210529093913](https://user-images.githubusercontent.com/83277902/120054446-8f64ad80-c062-11eb-87fc-99fbfb394b8e.jpg)
然后我试着去搜索推送加，酷推，server酱turbo的时候，发现根本搜不到
![QQ截图20210529094217](https://user-images.githubusercontent.com/83277902/120054454-a1dee700-c062-11eb-8409-ca3822a143f3.jpg)
![QQ截图20210529094227](https://user-images.githubusercontent.com/83277902/120054456-a3101400-c062-11eb-9160-7fe2193a3d21.jpg)
![QQ截图20210529094238](https://user-images.githubusercontent.com/83277902/120054457-a4414100-c062-11eb-8198-d7683f25f573.jpg)
不知道是什么原因呢？

**Comment by andywang425** [comment]
感谢提供控制台日志，我发现代码里有个地方应该是`.`被我不小心打成`,`了，所以就出了bug。  
下个版本会修复这个Bug，到时候推送应该就没问题了。
