### ISSUE TITLE
天选抽奖的缓存房间数量积累过多

### ISSUE THREAD

**Issue by jkluio78** [andywang425/BLTH#118]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README和脚本的内置说明。  
**描述bug**  
检查的房间只勾选了 获取个人简介和获取已关注主播 两种途径，但是随时间推移缓存的房间积累数量过多，每次抽奖的房间数量远大于搜索的数量

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. 天选勾选以下两项
![W7 408HZ1%W OV`U{)} D1F](https://user-images.githubusercontent.com/74967641/120014457-aa103580-c014-11eb-8a27-3d9c5c6c3f77.jpg)
2. 运行一段时间后，缓存房间数积累过多，执行天选的房间数远超于搜索到的房间数（470>100+30）
![R4HY@B8HM 3$3B}L700~K%3](https://user-images.githubusercontent.com/74967641/120014571-d330c600-c014-11eb-8bb2-3da708ab2e31.jpg)
3.在取消掉获取数据的两项后（时间为12：15）
![15~ Q1G18MP JMMMW@ ~I4Q](https://user-images.githubusercontent.com/74967641/120014714-fa879300-c014-11eb-80f3-069d01ea440f.png)
4.再次检查天选，缓存房间的数量已经达到了500（时间为12：20）
![7BL PS%5E)1GLV9){JCT(4F](https://user-images.githubusercontent.com/74967641/120014820-1d19ac00-c015-11eb-9090-8a870df5b2d3.png)

**预期行为**  
简要描述进行以上操作后预期的脚本行为
执行天选的房间数=搜索到的房间数

**使用环境:**  
 - 操作系统：如`Windows 8.1`
 - 浏览器及版本: 如`Microsoft Edge 90.0.818.66 (64 位)`
 - 用户脚本管理器及版本：如`Tampermonkey 4.13`
 - 脚本的版本: 如`5.6.9.2`
 - 网络情况(网速): `好`
 - 其他浏览器插件/脚本: 无

**其他**  
我想随时能查看天选的日志，所以一直没有刷新页面。
最后我想提一点点建议
我希望脚本能够在 **每隔XX分钟刷新一次页面** 下面增加一个 **刷新页面时导出日志** 的功能，这样就能够设置定时刷新页面从而清掉缓存并且保存日志；或者是有一个**设置脚本定时清理缓存而不刷新页面**的功能

**Comment by jkluio78** [comment]
不刷新页面的另一个原因是之前反应的加载不出脚本的问题 https://github.com/andywang425/BLTH/issues/116 
刷新页面将会导致脚本加载不出来，重新开启脚本只能不停的进直播间直到某次运气好，脚本才能启动

**Comment by andywang425** [comment]
> 执行天选的房间数=搜索到的房间数

缓存房间的最大数量是由`检查房间最大数量`这个设置决定的，你填了500所以最大就是500。如果只想检索100个把这个设置改一下即可。  
之所以每次获取100个但最终会变成500个是因为获取到的100个房间一直在变，经过去重后房间总数还是会慢慢增加。  

> 我希望脚本能够在 每隔XX分钟刷新一次页面 下面增加一个 **刷新页面时导出日志**  的功能，这样就能够设置定时刷新页面从而清掉缓存并且保存日志；或者是有一个**设置脚本定时清理缓存而不刷新页面**的功能。

1. **刷新页面时导出日志** 我猜你指普通日志？普通日志我认为没必要导出。而且导出之后可读性很差。同时记录日志也会消耗资源。如果我在今后发现有更多用户有和你相同的需求会考虑做这个功能。目前先记在todo里。   
2. **设置脚本定时清理缓存而不刷新页面** 我当初做了个刷新页面的功能是因为我当时比较菜，代码中有潜在的内存泄漏问题。如今很多地方都设置了数据记录数量的上限，再加上现代浏览器有很成熟的js垃圾回收机制，基本上已经没有刷新页面的必要了。至于你说的清理缓存，这不是咱想清就能清的，只能在写代码的过程中注意及时释放内存，控制数据量。我在测试时发现在长期运行过程中内存占用量基本能保持稳定。如果不放心可以设置成1天甚至几天刷新一次页面。

所以，如果想看日志直接设置成不刷新页面就行。

顺便问一下 https://github.com/andywang425/BLTH/issues/116 里我回复的临时解决方法有用吗
