### ISSUE TITLE
建议添加硬币换抽奖直播间勋章按钮功能

### ISSUE THREAD

**Issue by zkzssf** [andywang425/BLTH#119]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README和脚本的内置说明。  
**描述bug**  
有些情况下，抽奖要求用户有对应的直播间勋章才可进行。在排除存疑天选的情况下，如果添加“自动硬币换对应直播间勋章”的按钮，可以提升一些中奖率

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. 天选现金抽奖要求用户有对应直播间的勋章（1级），才可以进行，此时用户有很多硬币，完全可以为了此次抽奖，兑换直播间的勋章。

**预期行为**  
简要描述进行以上操作后预期的脚本行为
对于未参加的天选，首先判定该天选非存疑天选，其次判定该天选是否需要对应直播间勋章，检查用户的剩余硬币量（大于某个用户的设定值才可以，比如口袋里不能少于30枚），如果满足要求，使用20个硬币兑换直播间的勋章，满足抽奖要求，然后参与天选

**截图**  
如果可以，请提供有关截图  
![image](https://user-images.githubusercontent.com/29770284/120069079-987f6a00-c0b6-11eb-91c6-e63e79a0e2c9.png)

**运行日志**  
脚本日志窗口中的普通日志或控制台日志。  
控制台日志的打开方式见README中[控制台日志](https://github.com/andywang425/BLTH/blob/master/README.md#控制台日志)一节。  
普通日志请直接截图。控制台日志可截图或右键导出。  
![image](https://user-images.githubusercontent.com/29770284/120069175-0e83d100-c0b7-11eb-9dad-6290f99278e7.png)

**使用环境:**  
 - 操作系统：如`mac os 10.14.5`
 - 浏览器及版本: 如`Chrome 90.0.4430.212`
 - 用户脚本管理器及版本：如`Tampermonkey 4.12`
 - 脚本的版本: 如`5.6.9.2`
 - 网络情况(网速): `好`
 - 其他浏览器插件/脚本: 在此写上您认为可能会对本脚本产生影响的插件/脚本

**其他**  
若您有其他想要补充的内容，请在此说明
辛苦开发人员了，多谢

**Comment by andywang425** [comment]
这个可以有

**Comment by zkzssf** [comment]
> 这个可以有

感谢
