### ISSUE TITLE
推送部分的问题

### ISSUE THREAD

**Issue by EdwardXiaoran** [andywang425/BLTH#120]
天选中奖之后，目前脚本未能通过酷推/server酱/推送加 推送中奖信息希望能解决下
另外希望增加推送测试功能，以手动测试推送部分能否正常工作。

**Comment by andywang425** [comment]
目前确实因为bug推送不了（[#117](https://github.com/andywang425/BLTH/issues/117#issuecomment-850775970)），以后会修复。  
推送测试功能等我有空了就加上。
