### ISSUE TITLE
5.7版本运行天选时刻一分钟后报错

### ISSUE THREAD

**Issue by jkluio78** [andywang425/BLTH#122]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README和脚本的内置说明。  
**描述bug**  
5.7版本运行天选时刻一分钟后报错

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. 9:32运行5.7版本并开启控制台日志
![image](https://user-images.githubusercontent.com/74967641/121619460-3a318e80-ca9b-11eb-922d-8d7b8466365f.png)

2. 9:33天选停止运行，查看控制台日志看到报错
![image](https://user-images.githubusercontent.com/74967641/121619542-5c2b1100-ca9b-11eb-9e22-1c907d699bd4.png)

**预期行为**  
正常持续运行天选

**截图**  
如果可以，请提供有关截图  

**运行日志**  

**使用环境:**  
 - 操作系统：如`Windows 8.1`
 - 浏览器及版本: 如`Chrome 90.0.4430.85`
 - 用户脚本管理器及版本：`Tampermonkey 4.13`
 - 脚本的版本: `5.7`
 - 网络情况(网速): `好`
 - 其他浏览器插件/脚本: 无

**其他**  
若您有其他想要补充的内容，请在此说明

**Comment by andywang425** [comment]
试试看这个测试脚本
[B站直播间挂机助手 - #122.txt](https://github.com/andywang425/BLTH/files/6635544/B.-.122.txt)

**Comment by jkluio78** [comment]
运行测试脚本，同样的报错
![image](https://user-images.githubusercontent.com/74967641/121635707-47f60c80-cab9-11eb-93d5-77ee191ad00a.png)

**Comment by andywang425** [comment]
问个问题，报错时所检查到的房间是否有天选？另外能否发一下你天选时刻部分的脚本设置，这样我好进一步排查原因。

**Comment by mzth** [comment]
> 问个问题，报错时所检查到的房间是否有天选？另外能否发一下你天选时刻部分的脚本设置，这样我好进一步排查原因。

我的也是会卡死，重置为默认后可以参加天选，但忽略直播间这个选项一但修改就会卡死，添加云端直播间都会卡死
![屏幕截图 2021-06-11 165823](https://user-images.githubusercontent.com/53244094/121661440-c7460900-cad6-11eb-8f84-82cc9f23fc70.png)

**Comment by jkluio78** [comment]
> > 问个问题，报错时所检查到的房间是否有天选？另外能否发一下你天选时刻部分的脚本设置，这样我好进一步排查原因。
> 
> 我的也是会卡死，重置为默认后可以参加天选，但忽略直播间这个选项一但修改就会卡死，添加云端直播间都会卡死
> ![屏幕截图 2021-06-11 165823](https://user-images.githubusercontent.com/53244094/121661440-c7460900-cad6-11eb-8f84-82cc9f23fc70.png)

应该是跟**忽略直播间**有关。
我做了测试，忽略直播间的勾去掉就能正常跑，打上勾后运行一分钟左右就报错了

**Comment by andywang425** [comment]
感谢二位的反馈 @mzth @jkluio78 ，目前已经确定了bug的原因，下个版本会修复。这里我先传一份临时脚本：
[B站直播间挂机助手 - #122.txt](https://github.com/andywang425/BLTH/files/6638160/B.-.122.txt)

**Comment by andywang425** [comment]
已在最新版5.7.1中修复该bug。

**Comment by jkluio78** [comment]
5.7版本的pushplus推送似乎仍然存在问题，6.12晚上11点中奖，但是没有收到推送

日志里有检测到中奖
![image](https://user-images.githubusercontent.com/74967641/121798035-807f1d00-cc56-11eb-9bde-92910610e425.png)
控制台没有6.12的推送日志，唯一一条是6.13号14点我再次测试推送时发的
![image](https://user-images.githubusercontent.com/74967641/121798061-b02e2500-cc56-11eb-897e-bd38d284f30e.png)
![image](https://user-images.githubusercontent.com/74967641/121798116-07cc9080-cc57-11eb-919c-db9139afcc32.png)
![image](https://user-images.githubusercontent.com/74967641/121798145-3fd3d380-cc57-11eb-97c7-591fefbecf87.png)
