### ISSUE TITLE
pushplus推送似乎仍然存在问题，没有收到推送

### ISSUE THREAD

**Issue by andywang425** [andywang425/BLTH#124]
5.7版本的pushplus推送似乎仍然存在问题，6.12晚上11点中奖，但是没有收到推送

日志里有检测到中奖
![image](https://user-images.githubusercontent.com/74967641/121798035-807f1d00-cc56-11eb-9bde-92910610e425.png)
控制台没有6.12的推送日志，唯一一条是6.13号14点我再次测试推送时发的
![image](https://user-images.githubusercontent.com/74967641/121798061-b02e2500-cc56-11eb-897e-bd38d284f30e.png)
![image](https://user-images.githubusercontent.com/74967641/121798116-07cc9080-cc57-11eb-919c-db9139afcc32.png)
![image](https://user-images.githubusercontent.com/74967641/121798145-3fd3d380-cc57-11eb-97c7-591fefbecf87.png)

_Originally posted by @jkluio78 in https://github.com/andywang425/BLTH/issues/122#issuecomment-860163539_

**Comment by andywang425** [comment]
按理来说中奖后会有一条关于pushplus的控制台日志，文字部分应该为`PP_sendMsg response`，如果能找到这条日志然后把能展开的部分展开一下发上来会有帮助。 @jkluio78

**Comment by jkluio78** [comment]
> 按理来说中奖后会有一条关于pushplus的控制台日志，文字部分应该为`PP_sendMsg response`，如果能找到这条日志然后把能展开的部分展开一下发上来会有帮助。 @jkluio78

我尝试搜了send、push两个关键词，均没有在控制台看到6.12的记录，同时也没有看到任何报错的日志

**Comment by EdwardXiaoran** [comment]
我这用相同的问题
同时酷推无法工作，手动测试也不行
控制台日志为：

[BLTH][11:53:1:971] CP_sendMsg test response: {response: Function, body: {…}}body: {code: 500, message: "Post \"http://127.0.0.1:5719/send_private_msg\": dial tcp 127.0.0.1:5719: connect: connection refused", send_content: null, data: {…}}response: Function {readyState: 4, responseHeaders: "access-control-allow-credentials:true\naccess-contr…Tue, 15 Jun 2021 03:53:02 GMT\nserver:nginx/1.14.1", finalUrl: "https://push.xuthus.cc/send/8e8b5eea0150884ca4502d152a9d5851", status: 200, statusText: "", …}__proto__: Object
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=763b3514-4ab9-4778-a6e9-e978868653ba:188

 [BLTH][11:53:1:973] toast-error: [天选时刻] 酷推推送测试消息发送失败 Post "http://127.0.0.1:5719/send_private_msg": dial tcp 127.0.0.1:5719: connect: connection refused

**Comment by andywang425** [comment]
> 我这用相同的问题
> 同时酷推无法工作，手动测试也不行
> 控制台日志为：
> 
> [BLTH][11:53:1:971] CP_sendMsg test response: {response: Function, body: {…}}body: {code: 500, message: "Post "[http://127.0.0.1:5719/send_private_msg\](http://127.0.0.1:5719/send_private_msg%5C)": dial tcp 127.0.0.1:5719: connect: connection refused", send_content: null, data: {…}}response: Function {readyState: 4, responseHeaders: "access-control-allow-credentials:true\naccess-contr…Tue, 15 Jun 2021 03:53:02 GMT\nserver:nginx/1.14.1", finalUrl: "https://push.xuthus.cc/send/8e8b5eea0150884ca4502d152a9d5851", status: 200, statusText: "", …}**proto**: Object
> userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=763b3514-4ab9-4778-a6e9-e978868653ba:188
> 
> [BLTH][11:53:1:973] toast-error: [天选时刻] 酷推推送测试消息发送失败 Post "http://127.0.0.1:5719/send_private_msg": dial tcp 127.0.0.1:5719: connect: connection refused

这个是酷推自己的问题

**Comment by jkluio78** [comment]
这次我勾选的是server酱，一样没有收到推送
控制台存储的日志有限，当我查看的时候相关日志已经没了，只看到有这个报错
![image](https://user-images.githubusercontent.com/74967641/122324353-369a7d80-cf5b-11eb-947e-ef95f1f501ac.png)

**Comment by jkluio78** [comment]
5.7.1版本使用 从高热度直播间获取数据 参加天选出错。
昨天用的是 从个人简介获取数据没有出现报错，今天切换成 高热度 就出错了
![image](https://user-images.githubusercontent.com/74967641/122634863-570d3800-d113-11eb-9467-9334f229b1a9.png)
![image](https://user-images.githubusercontent.com/74967641/122634933-90de3e80-d113-11eb-8dad-126f5ecc5809.png)

**Comment by jkluio78** [comment]
推送server酱和push+都能收到了，问题已解决
