### ISSUE TITLE
也许是bug的程序卡住问题

### ISSUE THREAD

**Issue by EdwardXiaoran** [andywang425/BLTH#125]
这边留意到每次日志出现到：

“  2021/6/13下午5:18:13         ”
   [天选时刻] 忽略直播间
  不参加直播间xxxxxxxx的天选

的时候，就会卡住，日志再无新内容出现，不再参与任何抽奖，除非手动刷新或设置自动刷新页面，否者就会一直卡着。不清楚这是我这边的个例还是脚本本身有问题。

**Comment by andywang425** [comment]
请问是最新版的脚本吗，5.7版本有这个问题

**Comment by EdwardXiaoran** [comment]
> 是最新版的剧本吗，5.7版本有这个问题
是的，是最新版本

**Comment by andywang425** [comment]
这边测试下来并无问题，请给出控制台日志

**Comment by EdwardXiaoran** [comment]
[Uploading live.bilibili.com-1623586571433.log…]()

**Comment by EdwardXiaoran** [comment]
[live.bilibili.com-1623586571433.log](https://github.com/andywang425/BLTH/files/6643857/live.bilibili.com-1623586571433.log)

**Comment by EdwardXiaoran** [comment]
新问题，中奖了但没能收到推送，手动点击推送测试则可推送，日志如下
[live.bilibili.com-1623588743460.log](https://github.com/andywang425/BLTH/files/6643898/live.bilibili.com-1623588743460.log)

**Comment by andywang425** [comment]
请按反馈格式再补充一下剩余的信息，我看了下日志，但目前无法确定原因。

**Comment by EdwardXiaoran** [comment]
**使用环境:**  
 - 操作系统：Windows 10 专业版 1909
 - 浏览器及版本: Chrome 91.0.4472.77（正式版本）（64 位）
 - 用户脚本管理器及版本：Tampermonkey 4.13
 - 脚本的版本: 5.7
 - 网络情况(网速): 一般
 - 其他浏览器插件/脚本: 无

**Comment by EdwardXiaoran** [comment]
更新到了5.7.1 ，又暂时没问题了
