### ISSUE TITLE
5.7.1版本使用 从高热度直播间获取数据 参加天选出错。

### ISSUE THREAD

**Issue by andywang425** [andywang425/BLTH#126]
5.7.1版本使用 从高热度直播间获取数据 参加天选出错。
昨天用的是 从个人简介获取数据没有出现报错，今天切换成 高热度 就出错了
![image](https://user-images.githubusercontent.com/74967641/122634863-570d3800-d113-11eb-9467-9334f229b1a9.png)
![image](https://user-images.githubusercontent.com/74967641/122634933-90de3e80-d113-11eb-8dad-126f5ecc5809.png)

_Originally posted by @jkluio78 in https://github.com/andywang425/BLTH/issues/124#issuecomment-864370076_

**Comment by andywang425** [comment]
这看起来是【从已关注正在直播的直播间获取天选时刻数据】导致的问题，请点一下错误日志里的链接并把出错的代码发上来。  

另外，如果要反馈其他问题请新开一个issue不要在无关issue中反馈。

**Comment by jkluio78** [comment]
收到
代码截图如下
![image](https://user-images.githubusercontent.com/74967641/122638243-ad837200-d125-11eb-8b5d-78d965ac8029.png)

**Comment by andywang425** [comment]
已找到原因，下个版本修复。

**Comment by andywang425** [comment]
已修复
