### ISSUE TITLE
自动投币功能获取投稿视频会失败

### ISSUE THREAD

**Issue by MephistoSatanDevil** [andywang425/BLTH#127]
不知道从哪个版本开始，自动投币功能失效。
提示为：
[自动每日奖励]获取UID = XXXXXXXX 的“空间-投稿视频”失败 请求被拦截

无论自动投币处设置为哪个，都会有此错误，区别只有XXXXXXX为设置的不同UID。

**Comment by andywang425** [comment]
出现`请求被拦截`说明是被B站风控了，过半小时再试试或者直接换个ip。
