### ISSUE TITLE
插件冲突

### ISSUE THREAD

**Issue by soyuzom** [andywang425/BLTH#13]
可能添加了 购买勋章功能，导致和 [bilibili直播间工具](https://greasyfork.org/zh-CN/scripts/368635) 冲突，导致 直播间工具 无法查看弹幕栏底部的 勋 章列表了。

**Comment by andywang425** [comment]
已解决，原因是拦截直播流的同时误伤了其它请求，导致 直播间工具  的查询勋章请求没有携带用户cookie。  
晚上更新。
