### ISSUE TITLE
每日分享(得经验)功能无效

### ISSUE THREAD

**Issue by Janet-Baker** [andywang425/BLTH#131]
**描述bug**  
每日分享(得经验)功能无效。在 `https://account.bilibili.com/account/home` 查看经验值，`每日分享视频(客户端)`任务未完成。

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. 打开浏览器，进入直播间，加载脚本。
2. 查看经验获得情况

**预期行为**  
简要描述进行以上操作后预期的脚本行为
在 `https://account.bilibili.com/account/home` 查看经验值，`每日分享视频(客户端)`任务应该为已完成状态。

**运行日志**  
https://paste.ubuntu.com/p/FbrMM22p7D/

**使用环境:**  
 - 操作系统：`Windows 10`
 - 浏览器及版本: `Microsoft Edge 版本 91.0.864.54 (64 位)`
 - 用户脚本管理器及版本：`Tampermonkey 4.13.6138`
 - 脚本的版本: 如`5.7.2.2`
 - 网络情况(网速): `好`

**其他**  
https://api.bilibili.com/x/member/web/exp/reward

**Comment by andywang425** [comment]
有时候每日奖励显示会不正确或者有很大的延迟，主要体现在投币和分享上。可以晚些时候再去看看。  
有极少数人是每天都完成不了分享任务的，这个我也不清楚原因。

**Comment by Janet-Baker** [comment]
嗯……到账了，果然有延迟。
这就很神奇了……
