### ISSUE TITLE
开启后会导致天选图标不显示

### ISSUE THREAD

**Issue by Malus-Mill** [andywang425/BLTH#133]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README和脚本的内置说明。  
**描述bug**  
简要描述所遇到的bug

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. xxx
2. xxx

**预期行为**  
简要描述进行以上操作后预期的脚本行为

**截图**  
如果可以，请提供有关截图  

**运行日志**  
脚本日志窗口中的普通日志或控制台日志。  
控制台日志的打开方式见README中[控制台日志](https://github.com/andywang425/BLTH/blob/master/README.md#控制台日志)一节。  
普通日志请直接截图。控制台日志可截图或右键导出。  

**使用环境:**  
 - 操作系统：如`Windows 10`
 - 浏览器及版本: 如`Chrome 81.0.3147.89`
 - 用户脚本管理器及版本：如`Tampermonkey 4.11`
 - 脚本的版本: 如`5.6`
 - 网络情况(网速): `好`/`一般`/`坏`
 - 其他浏览器插件/脚本: 在此写上您认为可能会对本脚本产生影响的插件/脚本

**其他**  
若您有其他想要补充的内容，请在此说明

**Comment by andywang425** [comment]
请按格式填写信息并描述一下你说的天选图标是什么。
