### ISSUE TITLE
5.7.3版本获取已关注开播直播间号失败

### ISSUE THREAD

**Issue by jkluio78** [andywang425/BLTH#135]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README和脚本的内置说明。  
**描述bug**  
[天选时刻] 获取已关注开播直播间号失败

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. [天选时刻]勾选 获取已关注开播直播间号，运行开始时间为6/23下午一点，持续运行约一天后报错，报错后天选停止
![image](https://user-images.githubusercontent.com/74967641/123227390-1cd2da80-d507-11eb-8c53-5de535c6c0d3.png)
2.错误报告
![image](https://user-images.githubusercontent.com/74967641/123227125-daa99900-d506-11eb-9a74-a69a4c4d1736.png)
![image](https://user-images.githubusercontent.com/74967641/123227199-f0b75980-d506-11eb-9892-fa951f8ae599.png)

**预期行为**  
简要描述进行以上操作后预期的脚本行为
持续获取并参与抽奖

**截图**  
如果可以，请提供有关截图  

**运行日志**  
脚本日志窗口中的普通日志或控制台日志。  
控制台日志的打开方式见README中[控制台日志](https://github.com/andywang425/BLTH/blob/master/README.md#控制台日志)一节。  
普通日志请直接截图。控制台日志可截图或右键导出。  

**使用环境:**  
 - 操作系统：如`Windows 8.1`
 - 浏览器及版本: 如`Chrome  91.0.4472.106`
 - 用户脚本管理器及版本：如`Tampermonkey 4.13`
 - 脚本的版本: 如`5.7.3`
 - 网络情况(网速): `好`
 - 其他浏览器插件/脚本: 无

**其他**  
若您有其他想要补充的内容，请在此说明

**Comment by andywang425** [comment]
现在的最新版本是5.7.3.1，更新一下试试。
