### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by EdwardXiaoran** [andywang425/BLTH#14]
建议增加自动发弹幕，在其他房间抽节奏风暴时随机发一些弹幕，在挂机的房间定期发一点弹幕。我这简单测试发现发弹幕貌似能减少风控的几率，弹幕内容什么都行，最好是bilibili直播间里提供的字符表情。

**Comment by andywang425** [comment]
这个脚本几乎抢不到节奏风暴，所以我觉得没必要加这个功能。

**Comment by wallleap** [comment]
> 建议增加自动发弹幕，在其他房间抽节奏风暴时随机发一些弹幕，在挂机的房间定期发一点弹幕。我这简单测试发现发弹幕貌似能减少风控的几率，弹幕内容什么都行，最好是bilibili直播间里提供的字符表情。

我也想要这功能啊，在一些影映馆中可以发#签到、#打卡获取积分

**Comment by andywang425** [comment]
> > 建议增加自动发弹幕，在其他房间抽节奏风暴时随机发一些弹幕，在挂机的房间定期发一点弹幕。我这简单测试发现发弹幕貌似能减少风控的几率，弹幕内容什么都行，最好是bilibili直播间里提供的字符表情。
> 
> 我也想要这功能啊，在一些影映馆中可以发#签到、#打卡获取积分

可以告诉我几个影映馆的直播间号吗，我还是第一次听说这个。

**Comment by luwangblog** [comment]
> 可以告诉我几个影映馆的直播间号吗，我还是第一次听说这个。

就是播放音频或者视频的，直播标签里找，好像现在改名字了，叫”影音馆“(也许是我记错了)，在【娱乐】分类里。
我常看的是这个直播间：【193】，直接到搜索框中搜一下就能看到了。

**Comment by andywang425** [comment]
> > 可以告诉我几个影映馆的直播间号吗，我还是第一次听说这个。
> 
> 就是播放音频或者视频的，直播标签里找，好像现在改名字了，叫”影音馆“(也许是我记错了)，在【娱乐】分类里。
> 我常看的是这个直播间：【193】，直接到搜索框中搜一下就能看到了。

谢谢，下个版本会更新自动发弹幕功能。

**Comment by luwangblog** [comment]
> 谢谢，下个版本会更新自动发弹幕功能。

感谢大佬！(另：才发现用的另一个账号，哈哈)
