### ISSUE TITLE
关于 自动送礼 的疑惑

### ISSUE THREAD

**Issue by jkluio78** [andywang425/BLTH#140]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README和脚本的内置说明。  
**描述bug**  
填写了优先送礼的房间但似乎没有生效，脚本只按粉丝牌送礼优先级送了礼物

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. 我有三个粉丝牌分别是2级、7级、11级。优先送礼的房间填写了7级粉丝牌的房间号，粉丝牌送礼优先级选择的是`低等级优先`。
![image](https://user-images.githubusercontent.com/74967641/124719122-62e16280-df39-11eb-9625-16f432c586a5.png)

2. 昨天送的是7级粉丝牌的房间，符合预期。结果今天送的是2级的牌子升到了6级，7级粉丝牌没有收到任何礼物，100亲密度是弹幕打卡加的。优先送礼房间似乎没有生效。
![image](https://user-images.githubusercontent.com/74967641/124718699-f2d2dc80-df38-11eb-84e0-aeffea25e6f0.png)

**预期行为**  
先送满`优先送礼的房间`，有剩余礼物再按粉丝牌等级排序给低等级粉丝牌送出

**截图**  
如果可以，请提供有关截图  

**运行日志**  
脚本日志窗口中的普通日志或控制台日志。  
控制台日志的打开方式见README中[控制台日志](https://github.com/andywang425/BLTH/blob/master/README.md#控制台日志)一节。  
普通日志请直接截图。控制台日志可截图或右键导出。  

**使用环境:**  
 - 操作系统：如`Windows 8.1`
 - 浏览器及版本: 如`Chrome 91.0.4472.106`
 - 用户脚本管理器及版本：如`Tampermonkey 4.13`
 - 脚本的版本: 如`5.7.3.4`
 - 网络情况(网速): `好`
 - 其他浏览器插件/脚本: 在此写上您认为可能会对本脚本产生影响的插件/脚本

**其他**  
若您有其他想要补充的内容，请在此说明

**Comment by andywang425** [comment]
我测试了一下并未发现问题，暂不修复。

**Comment by andywang425** [comment]
我测试了一下并未发现问题，暂不修复。

**Comment by jkluio78** [comment]
那么自动送礼是
先给`优先送礼房间`填写的房间号送礼，有剩余礼物再按粉丝牌等级排序给低/高等级粉丝牌送出
这样的逻辑吗

**Comment by jkluio78** [comment]
`优先送礼房间`这个框填了房间号也是没有用的吗？
再次用辣条做了测试，`优先送礼房间`填了A房间号，勋章等级为8级，粉丝牌优先级为`优先低等级粉丝牌`，而我最低级的粉丝牌为7级，对应的房间号是B。点击立刻开始送礼，我想要的是给A房间送礼，结果给了B房间送礼，那么`优先送礼房间`这个框填了是没有生效吗？

**Comment by andywang425** [comment]
> `优先送礼房间`这个框填了房间号也是没有用的吗？
> 再次用辣条做了测试，`优先送礼房间`填了A房间号，勋章等级为8级，粉丝牌优先级为`优先低等级粉丝牌`，而我最低级的粉丝牌为7级，对应的房间号是B。点击立刻开始送礼，我想要的是给A房间送礼，结果给了B房间送礼，那么`优先送礼房间`这个框填了是没有生效吗？

如果是这样那确实是没有生效，但我测试时是能生效的。请告诉我你在本issue中打码的房间号和勋章房间号，不然我很难做进一步排查。

**Comment by jkluio78** [comment]
> > `优先送礼房间`这个框填了房间号也是没有用的吗？
> > 再次用辣条做了测试，`优先送礼房间`填了A房间号，勋章等级为8级，粉丝牌优先级为`优先低等级粉丝牌`，而我最低级的粉丝牌为7级，对应的房间号是B。点击立刻开始送礼，我想要的是给A房间送礼，结果给了B房间送礼，那么`优先送礼房间`这个框填了是没有生效吗？
> 
> 如果是这样那确实是没有生效，但我测试时是能生效的。请告诉我你在本issue中打码的房间号和勋章房间号，不然我很难做进一步排查。

并不只是截图中的房间号，我填了其他高于7级的房间号，然后点击自动送礼，仍然给7级的房间送礼，又因为我7级的牌子不只一个，每次送礼送的7级房间又不同

**Comment by jkluio78** [comment]
我大概知道原因了，如果一个主播真实房间号为12，伪装房间号为3456，输入伪装房间号3456就会跳转到真实房间12号房，如果在`优先送礼房间`填的是伪装房间号，那么就会判定为送的房间没有牌子而不送礼，转而按`粉丝牌优先级`执行送礼

**Comment by andywang425** [comment]
> 我大概知道原因了，如果一个主播真实房间号为12，伪装房间号为3456，输入伪装房间号3456就会跳转到真实房间12号房，如果在`优先送礼房间`填的是伪装房间号，那么就会判定为送的房间没有牌子而不送礼，转而按`粉丝牌优先级`执行送礼

你的意思是你填的是长房间号？直播间url里是什么你填什么就行。

**Comment by jkluio78** [comment]
> > 我大概知道原因了，如果一个主播真实房间号为12，伪装房间号为3456，输入伪装房间号3456就会跳转到真实房间12号房，如果在`优先送礼房间`填的是伪装房间号，那么就会判定为送的房间没有牌子而不送礼，转而按`粉丝牌优先级`执行送礼
> 
> 你的意思是你填的是长房间号？直播间url里是什么你填什么就行。

对的，我原来填的是长房间号，现在改了就好了
