### ISSUE TITLE
取关该分组内的UP功能出现错误

### ISSUE THREAD

**Issue by SakuraSayaka** [andywang425/BLTH#142]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README和脚本的内置说明。  
**描述bug**  
点击[取关天选关注UP分组的UP主] 然后右上角弹出来"[取关不在白名单内的UP主]请先点击[保存当前关注列表为白名单]"的报错 并且没有进行取关操作

**预期行为**  
当然是正常取关天选关注UP分组里的UP

**运行日志**  
![image](https://user-images.githubusercontent.com/15071507/125264984-f8646400-e336-11eb-8b84-2c69564f9db7.png)

**Comment by andywang425** [comment]
已找到原因，下个版本修复。

**Comment by andywang425** [comment]
已修复
