### ISSUE TITLE
功能需求 自动切换画质功能

### ISSUE THREAD

**Issue by ysv587** [andywang425/BLTH#143]
可否增加一个直播间自动切换画质功能
刷新或者页面打开强制切换标清画质 + 是否静音

**Comment by andywang425** [comment]
可以有

**Comment by andywang425** [comment]
是否静音不会做到脚本里，因为b站本来就会记住你的音量设置。

**Comment by akiakise** [comment]
同样需要这个功能，我这边B站默认清晰度是第二个，希望脚本支持设置默认清晰度
