### ISSUE TITLE
5.7.5版本无法花费20硬币购买粉丝勋章，提示购买失败 兑换失败，请升级到最新版本

### ISSUE THREAD

**Issue by iwoorst** [andywang425/BLTH#145]
![Snipaste_2021-07-17_20-30-02](https://user-images.githubusercontent.com/21360958/126036908-704a1f81-36f7-4fcb-aa9a-9e91ee54ea78.png)

**Comment by andywang425** [comment]
有人向B站反馈了这件事，接口已被封禁，以后再也不能用硬币买牌子了。
“请更新到最新版本”是B站的返回信息，意思是b站觉得你用的app版本太老（正常情况下只有旧版本app能硬币买牌子）。

**Comment by EldersJavas** [comment]
请问现在该如何买牌子

**Comment by andywang425** [comment]
> 请问现在该如何买牌子

给UP充电5B币，或者送一个B克拉。
