### ISSUE TITLE
粉丝勋章手动设置

### ISSUE THREAD

**Issue by 0xbba** [andywang425/BLTH#146]
可以增加手动设置佩戴粉丝勋章的功能吗
我的号在没有勋章的房间总是自动带lol的

**Comment by andywang425** [comment]
> 我的号在没有勋章的房间总是自动带lol的

暂时没有观察到你所说的bug。

> 可以增加手动设置佩戴粉丝勋章的功能吗

请详细描述一下，你具体是想手动设置什么？

**Comment by 0xbba** [comment]
> > 我的号在没有勋章的房间总是自动带lol的
> 
> 暂时没有观察到你所说的bug。
> 
> > 可以增加手动设置佩戴粉丝勋章的功能吗
> 
> 请详细描述一下，你具体是想手动设置什么？

就是想自己设置一直佩戴某一个粉丝牌,不自动切换

**Comment by andywang425** [comment]
> 就是想自己设置一直佩戴某一个粉丝牌,不自动切换

那你把自动佩戴勋章的功能关掉不就行了。

**Comment by 0xbba** [comment]
> > 就是想自己设置一直佩戴某一个粉丝牌,不自动切换
> 
> 那你把自动佩戴勋章的功能关掉不就行了。

啊,我没找到哪一个选项是关闭自动佩戴勋章,然后发现是Evolved脚本开启了自动佩戴,抱歉
