### ISSUE TITLE
自动送礼剩余礼物异常

### ISSUE THREAD

**Issue by X-Holmes** [andywang425/BLTH#15]
在4.2.1版本中，脚本中【优先送礼房间】设置为0、【剩余礼物送礼直播间(及ID)】设置为对应直播间号和UID，包裹中有1天辣条，自动送礼时出现如下异常：
[自动送礼] 【剩余礼物】房间[xxx] 送礼异常:参数错误(348)
![IMG20200815020534](https://user-images.githubusercontent.com/35630677/90279469-d995ed00-de9b-11ea-94cf-ca6df2587272.jpg)
在4.2版本及之前没有遇到该错误，且更新至4.2.1后各项参数均未改动。不确定是脚本更新导致的错误还是B站自身改动导致。

另外在4.2版本中，送出剩余礼物也只会送辣条而不送小心心，不知道在4.2.1版本中是否一并修复了(暂时没有1天小心心来验证)。

最后再次请求将定义“剩余礼物”的剩余时间由默认1天改为自定义天数。虽然之前你跟我说可以自己改 `let limit = 86400`，但脚本更新频率太高，每次都要手动去改太麻烦了(仅建议)

**Comment by andywang425** [comment]
这个bug我已经找到原因了。因为送礼模块测试起来很困难所以总是出bug，抱歉。  
我不是很理解为什么要改“剩余礼物”的剩余时间，直接改礼物到期时间不行吗。这个bug我已经找到原因了。因为送礼模块测试起来很困难所以总是出bug，抱歉。  
我不是很理解为什么要改“剩余礼物”的剩余时间，直接改礼物到期时间不行吗。剩余礼物本来就不送小心心，因为小心心送出去以后不会获得经验。以后会在说明中写一下这点。

**Comment by X-Holmes** [comment]
是因为我没有那个主播的粉丝勋章(up没有开通粉丝勋章)，用20硬币也买不了，所以只能通过剩余礼物的方式自动送礼(普通自动送礼没有勋章送不了)。
小心心送出去虽然不会获得经验，但反正都是要过期的了，不送也就消失了，那为什么不送出去呢？毕竟可以让收到礼物的主播获得主播经验。

**Comment by andywang425** [comment]
那我就改改吧，反正送不送都一样。  
剩余礼物送礼好像还是有点小问题，我打算之后把礼物模块再优化一遍。
