### ISSUE TITLE
功能建议 优化每日小心心上限检测逻辑

### ISSUE THREAD

**Issue by msm8976** [andywang425/BLTH#150]
**功能建议**  
当前检测每日小心心获取上限的逻辑为"检测到包裹内有24个7天的小心心后会停止"，但粉丝勋章不足24个时无法单次获取24个触发停止，且该次获取的小心心会在自动送礼中被送出，因此背包中不会在某一时刻拥有24个7天的小心心，脚本会提示"小心心未全部获取，60秒后将再次运行"并反复尝试获取无法停止
B站在每天获取到第24个小心心时会提示"你的小心心已到每日上限"（见截图），建议在接收到"你的小心心已到每日上限"提示后今日不再自动获取小心心

**预期行为**  
检测到"包裹内有24个7天的小心心"或接收到"你的小心心已到每日上限"提示后今日不再自动获取小心心

**截图**  
![你的小心心已到每日上限](https://user-images.githubusercontent.com/32473245/126891110-38f72b8e-0657-425d-819a-2f66271f3a40.png)

**使用环境:**  
 - 操作系统：Windows 10
 - 浏览器及版本: Chrome 91.0.4472.164
 - 用户脚本管理器及版本：Tampermonkey 4.13
 - 脚本的版本: 5.7.7
 - 网络情况(网速): 一般
 - 其他浏览器插件/脚本: Bilibili Evolved

**Comment by andywang425** [comment]
确实是个问题，一边获取小心心一边送出去会导致一直重试。  

> 接收到"你的小心心已到每日上限"提示后今日不再自动获取小心心

暂时没有搞清楚这个提示是在什么条件下触发的。

我之前猜测有个api会获取今日是否拿全了小心心，如果是就提示，但并没有找到。以后会再研究研究。  

如果有大佬知道这个提示的触发条件的话麻烦告知一下，万分感谢。

**Comment by lzghzr** [comment]
这个提示是弹幕池websocket推过来的

**Comment by andywang425** [comment]
> 这个提示是弹幕池websocket推过来的

感谢告知，没想到能在这见到大佬本人_(:з)∠)_

**Comment by andywang425** [comment]
既然是通过弹幕池websocket推过来的，那我还是想办法用其它方式来检测吧。为了检测小心心上限额外去连接一个websocket不划算。

目前的设想是在送七天过期的小心心时记录一下，如果包里剩下的加上送出去的等于24就停止获取。

**Comment by lzghzr** [comment]
> 既然是通过弹幕池websocket推过来的，那我还是想办法用其它方式来检测吧。为了检测小心心上限额外去连接一个websocket不划算。
> 
> 目前的设想是在送七天过期的小心心时记录一下，如果包里剩下的加上送出去的等于24就停止获取。

我看你引用了bliveproxy，这个用来监听弹幕消息还是可以的

**Comment by andywang425** [comment]
> > 既然是通过弹幕池websocket推过来的，那我还是想办法用其它方式来检测吧。为了检测小心心上限额外去连接一个websocket不划算。
> > 目前的设想是在送七天过期的小心心时记录一下，如果包里剩下的加上送出去的等于24就停止获取。
> 
> 我看你引用了bliveproxy，这个用来监听弹幕消息还是可以的

也是个办法，我再考虑考虑。

**Comment by Windrunner20** [comment]
希望能出云函数部署或docker的版本

**Comment by andywang425** [comment]
> 希望能出云函数部署或docker的版本

请不要在反馈bug的issue里讨论无关内容。  
node版本有人在写了，就是可能一时半会做不好。
