### ISSUE TITLE
无法呼出面板

### ISSUE THREAD

**Issue by kevinluo6188** [andywang425/BLTH#157]
### 描述bug

无法呼出脚本面板

### 重现bug

升级脚本后出现了这个bug

### 预期行为

正常情况下应该出现脚本的面板入口

### 截图

![X4C S_5UUA)}@%XRXUZ9U(0](https://z3.ax1x.com/2021/08/05/feOYd0.png)

### 运行日志

2021/8/5 下午11:17:03
脚本载入配置成功
2021/8/5 下午11:17:10
[转盘抽奖] 将会在48.56分钟后运行转盘抽奖

### 操作系统

Windows 10 21H1

### 浏览器

Google Chrome 92.0.4515.131(64x)

### 用户脚本管理器

tampermonkey 4.13

### 挂机助手版本

5.7.8.3

### 网络情况

好

### 其他浏览器插件/脚本

N/A

### 其他

希望修改面板入口的位置

**Comment by kevinluo6188** [comment]
#156

**Comment by andywang425** [comment]
你确定和 #156 提到的一样吗，从你的截图中来看你并没有开bilibili evolved

**Comment by kevinluo6188** [comment]
如果您这么说的话 那我的确没开bilibili evolved 那我的确不同

**Comment by FztTony** [comment]
一点情况的补充：
1、我遇到的情况与这个相同，同时我在bilibili.com下没有添加任何其他插件或脚本；
2、我尝试回滚到5.7.1版本的js脚本，但是情况仍然不变（脚本入口消失）；
3、在出现这个bug之前的设置为：自动获取小心心、自动签到发言、自动应援团打卡、每5分钟自动送礼；出现这个bug之后，自动获取小心心功能正常，其余三个功能失效；
4、日志、右上角的提示可以正常出现和显示。

**Comment by Rbqwow** [comment]
同
未加载其他脚本 设置入口消失 但功能全部正常

**Comment by kevinluo6188** [comment]
emmmmm 看下#156 好像有个解决方案 ---- 回复的原邮件 ***@***.***>发送日期2021年08月07日 22:42 ***@***.***> ***@***.******@***.***>主题Re: [andywang425/BLTH] 无法呼出面板 (#157)

同

未加载其他脚本 设置入口消失 但功能全部正常



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/andywang425/BLTH/issues/157#issuecomment-894663353",

"url": "https://github.com/andywang425/BLTH/issues/157#issuecomment-894663353",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by benaify** [comment]
按照 #156 下YimingZhanshen回复，添加// 初次运行时tips”然后在它前面加上“$('.follow-ctnr').append(btn);确实成功呼出了面板。但是需要脚本非压缩（非github源）才能这样修改。

**Comment by Rbqwow** [comment]
> 按照 #156 下YimingZhanshen回复，// 初次运行时tips前面加上$('.follow-ctnr').append(btn);确实成功呼出了面板，前提需要脚本非压缩（非github源）

还在疑惑为什么这边找不到注释 多谢提醒

**Comment by dong-jpg** [comment]
> 同
> 未加载其他脚本设置入口退出但功能全部正常



> ### 描述错误
> 呼不能出脚本
> 
> ### 重现错误
> 升级剧本后出现了这个bug
> 
> ### 预期行为
> 正常情况下应该出现脚本的面板入口
> 
> ### 截图
> ![X4C S_5UUA)}@%XRXUZ9U(0](https://camo.githubusercontent.com/790baa20f273969225196258b16dbe41c45cb6a128dab4ed241302b6b5aced1c/68747470733a2f2f7a332e617831782e636f6d2f323032312f30382f30352f66654f5964302e706e67)
> 
> ### 运行日志
> 2021/8/5下午11:17:03脚本
> 载入配置成功
> 2021/8/5下午11:17:10
> [转盘抽奖]将在48.56分钟后运行转盘抽奖
> 
> ### 操作系统
> 视窗 10 21H1
> 
> ### 浏览器
> 谷歌浏览器 92.0.4515.131(64x)
> 
> ### 用户脚本管理器
> 篡改猴子 4.13
> 
> ### 挂机助手版本
> 5.7.8.3
> 
> ### 网络情况
> 好
> 
> ### 其他浏览器插件/脚本
> 不适用
> 
> ### 其他
> 希望修改门入口的位置


> ### 描述bug
> 无法呼出脚本面板
> 
> ### 重现bug
> 升级脚本后出现了这个bug
> 
> ### 预期行为
> 正常情况下应该出现脚本的面板入口
> 
> ### 截图
> ![X4C S_5UUA)}@%XRXUZ9U(0](https://camo.githubusercontent.com/790baa20f273969225196258b16dbe41c45cb6a128dab4ed241302b6b5aced1c/68747470733a2f2f7a332e617831782e636f6d2f323032312f30382f30352f66654f5964302e706e67)
> 
> ### 运行日志
> 2021/8/5 下午11:17:03
> 脚本载入配置成功
> 2021/8/5 下午11:17:10
> [转盘抽奖] 将会在48.56分钟后运行转盘抽奖
> 
> ### 操作系统
> Windows 10 21H1
> 
> ### 浏览器
> Google Chrome 92.0.4515.131(64x)
> 
> ### 用户脚本管理器
> tampermonkey 4.13
> 
> ### 挂机助手版本
> 5.7.8.3
> 
> ### 网络情况
> 好
> 
> ### 其他浏览器插件/脚本
> N/A
> 
> ### 其他
> 希望修改面板入口的位置



> 同
> 未加载其他脚本 设置入口消失 但功能全部正常



> 一点情况的补充：
> 1、我遇到的情况与这个相同，同时我在bilibili.com下没有添加任何其他插件或脚本；
> 2、我尝试回滚到5.7.1版本的js脚本，但是情况仍然不变（脚本入口消失）；
> 3、在出现这个bug之前的设置为：自动获取小心心、自动签到发言、自动应援团打卡、每5分钟自动送礼；出现这个bug之后，自动获取小心心功能正常，其余三个功能失效；
> 4、日志、右上角的提示可以正常出现和显示。


**该问题需要等待aw修复，目前的解决办法是使用非GitHub源安装脚本后，打开编辑脚本：
1.在脚本编辑页面按Ctrl+F输入：‘’初次运行时tips‘’。
2.然后在它前面加上“$('.follow-ctnr').append(btn);”即可解决！（不需要加双引号）**
