### ISSUE TITLE
无法正常点亮牌子

### ISSUE THREAD

**Issue by zerosherd** [andywang425/BLTH#159]
### 描述bug

在数个版本前，牌子一下子全部都点亮了，但是最近数个版本似乎会遗漏掉一些牌子，甚至一个都没点亮。而且也出现了无法开启设置面板的Bug，所以没办法给你看设置项，我确定我没改过设置，之前版本正常的。

已关闭广告拦截功能，因为脚本的其他功能都是正常的。

### 重现bug

1. 开启点亮牌子功能

### 预期行为

无法正常点亮

### 截图

![2021-8-8 18-15-17](https://user-images.githubusercontent.com/45382820/128628877-8170947f-f0cf-499c-87b3-effa410f2c58.png)

### 运行日志

![image](https://user-images.githubusercontent.com/45382820/128628801-b94a0c06-4341-480a-8a18-32c54e9bc5b4.png)

### 操作系统

WIndows 10

### 浏览器

Chromium 86.0.4240.198

### 用户脚本管理器

Tampermonkey 4.13

### 挂机助手版本

5.7.8.3

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
请问你用的哪种点亮方式，发弹幕还是送小心心？
还有，运行日志里的日志不是咱这个脚本的。

**Comment by zerosherd** [comment]
无法查看设置了，如果按照以前我的设置的话是送小心心。

**Comment by andywang425** [comment]
我测试时无异常。点亮失败有以下几种可能：  
+ 直播间不允许送礼
+ 无直播间
+ 粉丝牌等级大于20级  

你看看点亮失败的房间是否是这样？

**Comment by zerosherd** [comment]
![image](https://user-images.githubusercontent.com/45382820/128632364-f037318e-8084-45d8-9a5d-653f1445263c.png)

因为是大幅没有点亮，所以我认为这三个问题都可以被排除，但是有的牌子亮了，所以我应该没有被黑号。

**Comment by konglinSoul** [comment]
发弹幕点亮亲密度会+100，送小心心点亮也会亲密度+50，但是你上面的图片所有牌子的本日亲密度都是0，所以脚本应该是没运行或者设置出现了问题，试试在#156 控制面板按钮消失的解决办法，脚本编辑页面按Ctrl+F输入“// 初次运行时tips”然后在它前面加上“$('.follow-ctnr').append(btn);” ，按Ctrl+S保存。把控制面板整出来看看设置有没有问题

**Comment by andywang425** [comment]
嗯，先把控制面板搞出来吧。然后把控制台日志打开再运行一下，把控制台日志发出来。没有日志不好分析。

**Comment by zerosherd** [comment]
> 发弹幕点亮亲密度会+100，送小心心点亮也会亲密度+50，但是你上面的图片所有牌子的本日亲密度都是0，所以脚本应该是没运行或者设置出现了问题，试试在#156 控制面板按钮消失的解决办法，脚本编辑页面按Ctrl+F输入“// 初次运行时tips”然后在它前面加上“$('.follow-ctnr').append(btn);” ，按Ctrl+S保存。把控制面板整出来看看设置有没有问题



> 嗯，先把控制面板搞出来吧。然后把控制台日志打开再运行一下，把控制台日志发出来。没有日志不好分析。

好的，请等我今晚下班给各位发日志，办公室电脑不好搞。

**Comment by zerosherd** [comment]
设置如下：
![image](https://user-images.githubusercontent.com/45382820/128886670-31df01f2-2703-4403-b2f6-309c4d855da2.png)
![image](https://user-images.githubusercontent.com/45382820/128886433-c6440cfd-d8b0-48c4-aaca-249e256a6e9f.png)
因此我的过往设置没问题。
而且我手动发弹幕测试过：
![image](https://user-images.githubusercontent.com/45382820/128886883-83aea009-79da-47ec-9ce3-a6e17383d063.png)

下一条回复会是日志。

**Comment by zerosherd** [comment]
![image](https://user-images.githubusercontent.com/45382820/128887381-0753b33a-949c-4c61-81f3-dad270b90dda.png)
![image](https://user-images.githubusercontent.com/45382820/128887465-d09c3ceb-26e3-4d03-a2bb-ad82b9cd2ef8.png)
这就是所附日志，感谢各位的耐心。

**Comment by andywang425** [comment]
我感觉大概率和这个`14275133`房间有关，这个直播间被封了送不出去礼物，导致脚本报错直接不点亮后续勋章了。  
我建议你把点亮模式设为黑名单，然后把`14275133`这个房间号填进去再点亮试试。

**Comment by andywang425** [comment]
以后会想办法避免这种情况。

**Comment by zerosherd** [comment]
问题已解决，解决方法如你所说，感谢。
