### ISSUE TITLE
实物抽奖会重复且频繁的访问已开奖的宝箱

### ISSUE THREAD

**Issue by dong-jpg** [andywang425/BLTH#161]
### 描述bug

![4](https://user-images.githubusercontent.com/53105222/128703005-99b267fe-e678-4e1d-a9ca-bee176786f9c.png)
![1](https://user-images.githubusercontent.com/53105222/128703033-d6924c13-a946-4db8-96bf-2e08e6531cca.png)
![2](https://user-images.githubusercontent.com/53105222/128703035-26955a4f-9b87-42a4-9266-30881f5d1588.png)
![3](https://user-images.githubusercontent.com/53105222/128703037-af0f997e-783b-4e84-b5c4-6c2759fdc877.png)

### 重现bug

1.开启宝箱抽奖
2.开始了频繁而坚定的抽取已过期的宝箱

### 预期行为

1.宝箱抽奖前先验证此抽奖是否已开奖，若已开奖则过滤

### 运行日志

么的

### 操作系统

Win10

### 浏览器

Chrome、Edge

### 用户脚本管理器

油猴

### 挂机助手版本

5.7.8.3

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
> 宝箱抽奖前先验证此抽奖是否已开奖，若已开奖则过滤

目前就是这样的。第一次抽奖的时候肯定是没过期的，但因为风控了所以自动重试。问题不大。  

ps：你这反馈的有问题啊，描述bug里不描述，截图里没截图，浏览器，用户脚本管理器都不写版本，普通日志贴错位置，控制台日志怎么可能没有。  
我有点担心你能不能帮忙答issue👀

**Comment by dong-jpg** [comment]
以前都用bugfree，么得关系下次就了解了，关于此次问题：
1.风控了自动重试的机制是会一直重试直到下一次出现宝箱抽奖吗？那像这种一直对过期的宝箱的请求行为是会造成风控吗？(瞎几把猜的dog)，那是否可以增加一层判断，我重试的那个抽奖在开奖了之后就停止重试行为。
2.或者可以增加一个重试次数限制？一般重试也就是一分钟到三分钟一次，一次抽奖总共也就多少分钟吧。

**Comment by andywang425** [comment]
> 以前都用bugfree，么得关系下次就了解了，关于此次问题：
> 1.风控了自动重试的机制是会一直重试直到下一次出现宝箱抽奖吗？那像这种一直对过期的宝箱的请求行为是会造成风控吗？(瞎几把猜的dog)，那是否可以增加一层判断，我重试的那个抽奖在开奖了之后就停止重试行为。
> 2.或者可以增加一个重试次数限制？一般重试也就是一分钟到三分钟一次，一次抽奖总共也就多少分钟吧。

1. 会自动重试到不风控为止。一直对过期的宝箱的请求行为会风控，但是宝箱不过期也很容易风控，所以我觉得不是过期了的问题。但检查宝箱状态的API也容易风控，而且某一个API风控和其相关的会一起风控（参考天选时刻），所以加了也没什么用。
2. 目前所有API采用了统一的出错重试机制，单独给这个加次数限制不好办。不过我可以把重试间隔拉高一点，2分钟可能有点短。
