### ISSUE TITLE
直播间无法显示大航海

### ISSUE THREAD

**Issue by zt0408** [andywang425/BLTH#163]
### 描述bug

直播间无法显示大航海

### 重现bug

直播间点击大航海无法显示

### 预期行为

无

### 截图

![image](https://user-images.githubusercontent.com/63178522/128885054-b2c0c86b-1404-4492-8480-bcb9a429ed32.png)

### 运行日志

无

### 操作系统

windows 10

### 浏览器

edge 92.0.902.67 

### 用户脚本管理器

tampermonkey 4.13.6138

### 挂机助手版本

5.7.8.4

### 网络情况

好

### 其他浏览器插件/脚本

Bilibili Evolved 哔哩哔哩助手

**Comment by dong-jpg** [comment]
> ### 描述bug
> 直播间无法显示大航海
> 
> ### 重现bug
> 直播间点击大航海无法显示
> 
> ### 预期行为
> 无
> 
> ### 截图
> ![image](https://user-images.githubusercontent.com/63178522/128885054-b2c0c86b-1404-4492-8480-bcb9a429ed32.png)
> 
> ### 运行日志
> 无
> 
> ### 操作系统
> windows 10
> 
> ### 浏览器
> edge 92.0.902.67
> 
> ### 用户脚本管理器
> tampermonkey 4.13.6138
> 
> ### 挂机助手版本
> 5.7.8.4
> 
> ### 网络情况
> 好
> 
> ### 其他浏览器插件/脚本
> Bilibili Evolved 哔哩哔哩助手
> 
> ### 其他
> _No response_

宝贝，这个问题我自己尝试复现之后发现的几个需要确认的问题：
1.你是否有开启屏蔽广告的插件或脚本
2.是否有开启其他作者的优化b站界面屏蔽广告的脚本
经测试无论是Chrome还是Edge浏览器，上述这两种类型的脚本和插件一般都会把这块给你屏蔽隐藏掉，诸如：Ublock插件此类，广告终极者我找不到资源了没有测，但是大概率也是屏蔽的，你可以关闭这些广告屏蔽插件测试一下看看奥~

**Comment by zt0408** [comment]
> > ### 描述bug
> > 直播间无法显示大航海
> > ### 重现bug
> > 直播间点击大航海无法显示
> > ### 预期行为
> > 无
> > ### 截图
> > ![image](https://user-images.githubusercontent.com/63178522/128885054-b2c0c86b-1404-4492-8480-bcb9a429ed32.png)
> > ### 运行日志
> > 无
> > ### 操作系统
> > windows 10
> > ### 浏览器
> > edge 92.0.902.67
> > ### 用户脚本管理器
> > tampermonkey 4.13.6138
> > ### 挂机助手版本
> > 5.7.8.4
> > ### 网络情况
> > 好
> > ### 其他浏览器插件/脚本
> > Bilibili Evolved 哔哩哔哩助手
> > ### 其他
> > _No response_
> 
> 宝贝，这个问题我自己尝试复现之后发现的几个需要确认的问题：
> 1.你是否有开启屏蔽广告的插件或脚本
> 2.是否有开启其他作者的优化b站界面屏蔽广告的脚本
> 经测试无论是Chrome还是Edge浏览器，上述这两种类型的脚本和插件一般都会把这块给你屏蔽隐藏掉，诸如：Ublock插件此类，广告终极者我找不到资源了没有测，但是大概率也是屏蔽的，你可以关闭这些广告屏蔽插件测试一下看看奥~

原来是ublock的锅，我调了一下就好了，顺便问一下怎么给所有bili直播间都设置上白名单？

**Comment by dong-jpg** [comment]
ublock的设置里有一个白名单设置，你可以直接加一条https://live.bilibili.com/*试一下

**Comment by zt0408** [comment]
> ublock的设置里有一个白名单设置，你可以直接加一条[https://live.bilibili.com/*试一下](https://live.bilibili.com/*%E8%AF%95%E4%B8%80%E4%B8%8B)

好使了，谢谢

**Comment by andywang425** [comment]
@dong-jpg 👍

**Comment by asf00404** [comment]
吧ublock里 CHN: AdGuard Chinese (中文) 这个规则取消勾选就行了 这俩有冲突
