### ISSUE TITLE
把有自动回复的up单独分一组

### ISSUE THREAD

**Issue by glowingtorch** [andywang425/BLTH#166]
### 描述

取关的时候能直接清空没有自动回复的分组，不然自动回复太多会不发

**Comment by andywang425** [comment]
收到，会考虑做。

**Comment by dong-jpg** [comment]
> ### 描述
> 取关的时候能直接清空没有自动回复的分组，不然自动回复太多会不发

现在其实绝大多数的up主都有设置自动回复的，按照我们平时的消息数量来看，这个比例大概有85%甚至90以上，我是建议你平时不要勾选脚本的天选未中奖取关up主选项，你可以每个礼拜或者半个月一次性清理取关一次，反正每天发起抽奖的就是那些人，半个月不清理也不会攒下很多人。这样就不会频繁收到自动回复，中奖了up主也更愿意发奖。
