### ISSUE TITLE
自动点亮勋章功能出现问题，程序显示送礼失败，请检查网络和运行时出现异常已停止

### ISSUE THREAD

**Issue by cyslm** [andywang425/BLTH#17]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README。  
**描述bug**  
简要描述所遇到的bug

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. xxx
2. xxx

**预期行为**  
简要描述进行以上操作后预期的脚本行为

**截图**  
如果可以，请提供有关截图  

**运行日志**  
控制台中出现的日志或错误提示。  
可以截图或者直接复制。  

**使用环境:**
 - 浏览器: 如Chrome/Opera
 - 浏览器版本: 如Chromium 81.0.3147.89
 - 脚本的版本: 如3.5
 - 网络情况(网速): 好/一般/坏
 - 其他浏览器插件/脚本: 在此写上您认为可能会对本脚本产生影响的插件/脚本
 - bug出现时间: (精确到分钟)

**其他**  
若您有其他想要补充的内容，请在此说明

**Comment by andywang425** [comment]
你得按上面的格式填一下信息啊，不是复制一遍

**Comment by affiaabbhjt** [comment]
最近自动送礼和点亮勋章功能无法使用

每次点击“立刻开始送礼”或“立刻点亮勋章”后会提示“送礼失败，请检查网络”“运行时出现异常，已停止”

可以手动送礼和点亮勋章

日志：
![image](https://user-images.githubusercontent.com/36633239/91735110-664fe300-ebde-11ea-8e2e-3f5e5ae5eb0e.png)

浏览器：
PC chrome 84.0.4147.135正式版

脚本版本：
最新4.4.1.2和之前两三个版本均出现此问题

网络状态正常，观看直播流畅，插件的其他功能和其他插件暂时未发现问题
感谢作者的维护

**Comment by andywang425** [comment]
谢谢反馈，现已找到原因。  
如果你现在就想用这个功能的话，点一下保存按钮，或者重置所有为默认应该就能解决。
