### ISSUE TITLE
关于自动签到后自动送礼功能无法正确获取当前亲密度

### ISSUE THREAD

**Issue by kanonmelodis** [andywang425/BLTH#172]
### 描述bug

其实就是自动签到会多100亲密度但是自动送礼还是会按之前的亲密度算

### 重现bug

在1天当中先进行自动签到（+100亲密度），未刷新网页直接进行自动送礼，将会送出等价1500亲密度的礼物（正常情况下应为1400）

### 预期行为

如上述

### 运行日志

（今天只送出28个是因为小心心恰好只有28个了...）

[BLTH][12:21:20:94] [自动送礼]: 处理前的礼物列表 30607
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:20:95] [自动送礼]: 处理后得到的礼物id列表 30607
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:20:275] Gift.getBagList: API.gift.bag_list: {code: 0, msg: 'success', message: 'success', data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:20:280] [自动送礼] else分支 过滤后的礼物: (4) [{…}, {…}, {…}, {…}]
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:20:280] Gift.bag_list (sorted): (4) [{…}, {…}, {…}, {…}]
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:20:281] [自动送礼] if分支 过滤后的礼物: (2) [{…}, {…}]
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:20:281] Gift.bag_list (sorted): (2) [{…}, {…}]
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:20:577] [自动送礼] API.room.room_init(9680769): {code: 0, msg: 'ok', message: 'ok', data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:20:586] toast-info: [自动送礼]勋章[JS兔] 今日亲密度未满[0/1500]，预计需要[1500]送礼开始
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:172 [BLTH][12:21:20:589] [自动送礼]送出礼物类型小心心，该项礼物数量4，送出礼物数量4: []
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:20:794] Gift.sendGift: API.gift.bag_send: {code: 0, msg: 'success', message: 'success', data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:20:795] toast-success: [自动送礼]勋章[JS兔] 送礼成功，送出4个小心心，[200/1500]距离今日亲密度上限还需[1300]
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:172 [BLTH][12:21:20:818] [自动送礼]送出礼物类型小心心，该项礼物数量24，送出礼物数量24: []
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:21:464] Gift.sendGift: API.gift.bag_send: {code: 0, msg: 'success', message: 'success', data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:21:464] toast-success: [自动送礼]勋章[JS兔] 送礼成功，送出24个小心心，[1400/1500]距离今日亲密度上限还需[100]
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:21:478] toast-info: [自动送礼] 本次送礼结束
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:21:482] [getIntervalTime]获取间隔时间: 34719000毫秒
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=e2b1039e-ce61-4a38-bbc9-85c61f1b0376:171 [BLTH][12:21:21:482] [自动送礼]: 将在2021/9/26 下午10:00:00进行自动送礼

### 操作系统

Windows10

### 浏览器

Edge 93.0.961.52

### 用户脚本管理器

Tampermonkey v4.13

### 挂机助手版本

5.7.8.6

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
脚本已经对这个问题做过优化了，我这边测试下来没有问题，暂时不清楚原因。  
下次出现这个问题的时候把控制台日志发上来吧，我再分析分析。

**Comment by PODF-x** [comment]
我好像也注意到有这个情况
（打卡后手动点击送礼按钮显示了1500的上限而不是1400）
可惜被我刷新了（

**Comment by andywang425** [comment]
> 我好像也注意到有这个情况 （打卡后手动点击送礼按钮显示了1500的上限而不是1400） 可惜被我刷新了（

上限还是1500，但脚本知道目前已经有了多少亲密度，所以按理来说是不会多送礼物的。
