### ISSUE TITLE
小心心送礼计数异常

### ISSUE THREAD

**Issue by msm8976** [andywang425/BLTH#177]
### 描述bug

粉丝勋章小于24个时每天在累计送出24个小心心后脚本依然会提示"小心心未全部获取，60秒后将再次运行"并反复尝试获取无法停止

### 重现bug

粉丝勋章小于24个时5分钟无法获得当天全部的小心心，自动送礼后会送出当前获得的全部的小心心，但小心心计数仅加了1，导致每天无法在累计送出24个小心心后停止获取小心心

### 预期行为

截图中两处LITTLE_HEART_COUNT++（可能）应改成LITTLE_HEART_COUNT+=feed_num，当前版本位于3347、3351行
![image](https://user-images.githubusercontent.com/32473245/135716398-29c189e4-2228-4a6b-9c00-6b3812a400da.png)

### 操作系统

Windows 10

### 浏览器

Chrome 94.0.4606.71

### 用户脚本管理器

Tampermonkey 4.13

### 挂机助手版本

5.7.8.6

### 网络情况

一般

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
好像确实是我写错了，感谢指正。

**Comment by andywang425** [comment]
已更新。
