### ISSUE TITLE
投币机制

### ISSUE THREAD

**Issue by mintAqrua** [andywang425/BLTH#18]
**其他**  
众所周知，每日任务投币前五枚有经验，而一个原创稿件可以投两个币。目前插件投过一个币的稿件不会下次补上另一个币。这意味着1/3的视频能投2个币却只投了1个币。既然能设置给谁投币，希望将来能调整下检测视频还能不能投币的机制，让我们能补上没投的币。

**Comment by andywang425** [comment]
目前有检测机制但还不够完善，所以造成了你所说的情况。下个版本会改进~
