### ISSUE TITLE
获取粉丝勋章列表失败

### ISSUE THREAD

**Issue by Ivanwxt** [andywang425/BLTH#180]
### 描述bug

进入直播间后，弹出“获取粉丝勋章列表失败，Pagesize最多10个”，无法完成正常打卡操作

### 重现bug

无异常操作，仅进入直播间突然发生bug

### 预期行为

进入直播间后正常进行签到打卡流程

### 运行日志

[live.bilibili.com-1633625355382.log](https://github.com/andywang425/BLTH/files/7305602/live.bilibili.com-1633625355382.log)

### 操作系统

Windows 10

### 浏览器

Chrome 94.0.4606.71

### 用户脚本管理器

tampermonkey 4.13

### 挂机助手版本

5.7.8.6

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by dong-jpg** [comment]
关于“获取粉丝勋章列表失败 pageSize最多10个”的临时解决方案：
打开脚本编辑页面，移至第6450行代码，将括号内的“，25”删除
修改后的代码为：
await BAPI.i.medal(page).then((response) => {
修改完成后保存即可
若脚本只有55行代码，请去greasyfork安装原格式脚本再修改
链接：https://greasyfork.org/scripts/406048-b%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B

**Comment by 13579diana** [comment]
麻烦请问一下大佬，粉丝勋章列表获取失败怎么回事，昨天卡了1000个牌子后就失效了
![Uploading MQH%5(R(E4CM~EMQVRZ0935(1).png…]()

**Comment by 13579diana** [comment]
是获取粉丝勋章列表超时，无法打卡

**Comment by andywang425** [comment]
> 是获取粉丝勋章列表超时，无法打卡

应该是粉丝牌太多导致的。除了增加获取粉丝勋章的间隔（目前只能修改代码）以外暂时没有什么特别好的办法。
ps：请新开一个issue，不要在已关闭的issue中讨论。
