### ISSUE TITLE
购买不了粉丝勋章？

### ISSUE THREAD

**Issue by Malus-Mill** [andywang425/BLTH#183]
### 描述bug

点击购买粉丝勋章后、点击不了“是”，或者说点击之后没有反应

### 重现bug

1、https://live.bilibili.com/23240551；
2、点击购买勋章；
3、点击“是”

### 预期行为

没有反应？

### 截图

![image](https://user-images.githubusercontent.com/53999738/140488879-b3985abd-3e54-48b8-9af7-9f715900fff1.png)
![image](https://user-images.githubusercontent.com/53999738/140488917-fe0209f3-0a83-4f0e-81e2-06561d5bf5d0.png)

### 运行日志

![image](https://user-images.githubusercontent.com/53999738/140488996-ff5a48bd-53c3-4a97-81fa-e6010db586df.png)

### 操作系统

WIN11 21H2 操作系统版本：22000.282

### 浏览器

Chrome 版本 95.0.4638.69（正式版本） （64 位）

### 用户脚本管理器

 Tampermonkey 4.13

### 挂机助手版本

5.7.9

### 网络情况

好

### 其他浏览器插件/脚本

无 （Bilibili Evolved (Offline)）

**Comment by dong-jpg** [comment]
可以尝试重新更新脚本至最新版本，或者更换浏览器试一下？我使用Edge92.0.902.78版本、百分4.3.9.248测试点击“是”按钮后，后续弹窗均可以正常弹出。

**Comment by xiaoyan915** [comment]
我也遇到了这个问题，具体是这样的。现在最新5.8嘛，上个版本我准备花费10B币购买两个粉丝勋章，第一个成功购买，第二个购买时点了是选项后没有反应，和上面兄弟情况一样，我想着等版本更新后再试试，现在最新版本5.8，还是购买不了，chrome和edge两个浏览器都不行

**Comment by andywang425** [comment]
测试这个功能得花钱，所以没怎么测试过。我之后再测试一下。

**Comment by Malus-Mill** [comment]
> 测试一下这个功能需要经过。所以我没怎么测试过。

表示可能已经找到原因了、表示没开充电的话、就会买不了而且不显示

**Comment by xiaoyan915** [comment]
> 测试这个功能得花钱，所以没怎么测试过。我之后再测试一下。
sry，我想我找到原因了，点击是按钮没反应的up没有开通充电功能，其余开了充电的可以正常花费5B币购买。希望能在下个版本中增加提示，购买不了的话让用户检查当前up主是否开通充电功能了。俺还以为是脚本的问题，sry
