### ISSUE TITLE
无法正确检测当日小心心获取状态

### ISSUE THREAD

**Issue by chenyl0426** [andywang425/BLTH#184]
### 描述bug

当日小心心已获取并送出后（于凌晨通过其他自动项目完成），脚本提示【今日小心心未完全获取，5分钟后再次获取】

### 重现bug

获取小心心并全部送出

### 预期行为

toast提示【今日小心心未完全获取，5分钟后再次获取】，5分钟后重新开始发送心跳包

### 运行日志

[live.bilibili.com-1636206549272.log](https://github.com/andywang425/BLTH/files/7490593/live.bilibili.com-1636206549272.log)

### 操作系统

Windows 11

### 浏览器

Chrome 95.0.4638.69（正式版本） （64 位）

### 用户脚本管理器

Tampermonkey V4.13

### 挂机助手版本

5.7.9.1

### 网络情况

好

### 其他浏览器插件/脚本

Github-XiaoMiku01/bili-live-heart

**Comment by andywang425** [comment]
如果你通过其他方式获取小心心并送出了的话，脚本是没法知道的（或者说检测起来很困难）。 直接把获取小心心的功能关掉就行啦。
