### ISSUE TITLE
【海外】无法进行直播间弹幕打卡

### ISSUE THREAD

**Issue by DanLCJ** [andywang425/BLTH#186]
### 描述bug

其实一共有两个bug，但是由于跨版本，我本以为更新后能解决这个问题，但是反而演变成更严重的问题，因此提交issue

首先是在5.7.9.1版本，由于我现在人在海外，右上角日志会提示弹幕打卡“打卡失败，xxxx 当前地区不支持弹幕发送”，但是我自己手动发送是可以的。我尝试在console中寻找关于“BLTH”的error提示，但是没有找到。直到我注意到今天更新到最新的5.7.9.2版本。

其次就是今天使用的5.7.9.2版本，我现在无法进行弹幕打卡，右上角日志没有显示，且没有进行打卡操作。获取小心心的功能是正常的，同样的在console中没有找到“BLTH”的error提示，所以我将提交所有error含有“bilibili“的字样的log

### 重现bug

无法进行弹幕打卡

### 预期行为

应当进行粉丝牌弹幕打卡，且右上角有提示

### 运行日志

[live.bilibili.com-1636353381291.log](https://github.com/andywang425/BLTH/files/7494782/live.bilibili.com-1636353381291.log)
[live.bilibili.com-1636353404267.log](https://github.com/andywang425/BLTH/files/7494783/live.bilibili.com-1636353404267.log)

### 操作系统

Windows 10 20H2 19042.1288

### 浏览器

Chrome 95.0.4638.69

### 用户脚本管理器

Tampermonkey 4.13

### 挂机助手版本

5.7.9.2

### 网络情况

好

### 其他浏览器插件/脚本

uBlock Origin; 哔哩哔哩助手：bilibili.com 综合辅助扩展 （这两个都是chrome插件）

**Comment by DanLCJ** [comment]
我更新一下截图 如图所示
![QQ截图20211108125448](https://user-images.githubusercontent.com/40844774/140793318-77da3e2c-2041-47ba-8011-3e6a25135d28.png)

**Comment by linhonghuang** [comment]
+1，我在美国，也是更新完后遇到了地区无法发言的问题，之前推送的第一个新版本明明用的很顺利的，不知道为啥更新新版本后出了这个bug。

**Comment by andywang425** [comment]
发弹幕的API没有变过，估计是B站做了什么改动。  
我会尽可能想办法解决。

**Comment by DanLCJ** [comment]
我再次更新一下：我的浏览器现在设置了访问国内的全局vpn，可以实现正常的打卡【但是网速会超慢】，如果关闭会再次提示打卡失败。我认为可能是B站对于直播板块也设置了地域检测，但是我目前还没注意到具体代码在哪里。

**Comment by andywang425** [comment]
> 我再次更新一下：我的浏览器现在设置了访问国内的全局vpn，可以实现正常的打卡【但是网速会超慢】，如果关闭会再次提示打卡失败。我认为可能是B站对于直播板块也设置了地域检测，但是我目前还没注意到具体代码在哪里。

感谢反馈，我之后也会挂个国外的梯子测试一下。

**Comment by linhonghuang** [comment]
十分感谢大佬，一直在用大佬的脚本，帮大忙了。
________________________________

**Comment by wangpr0606** [comment]
遇到了同样的bug
