### ISSUE TITLE
【海外】无法粉丝勋章每日打卡

### ISSUE THREAD

**Issue by szmarcos** [andywang425/BLTH#187]
### 描述bug

粉丝勋章打卡弹幕无效

### 重现bug

正常点开任意一个直播间后无法打卡

### 预期行为

所有有勋章的直播间发送一条打卡弹幕

### 截图

![QQ截图20211109094406](https://user-images.githubusercontent.com/93978296/140902597-3ff7862a-2adc-4376-9c74-c4ebd470cda2.png)

### 运行日志

[BLTH][9:57:22:92] getInfoByUser request: {headers: {…}, method: 'GET', url: '//api.live.bilibili.com/xlive/web-room/v1/index/getInfoByUser?room_id=14047&from=0', async: true, user: undefined, …}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:22:254] toast-info: 正在获取礼物 / 用户 / 账号 / 粉丝勋章数据...
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:22:351] getInfoByUser response: {response: '{"code":0,"message":"0","ttl":1,"data":{"user_leve…w":0,"guard_compensate":0,"interact_toasts":[]}}}', status: 200, statusText: '', config: {…}, headers: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:23:299] InitData: API.gift.gift_config: {code: 0, msg: '', message: '', data: Array(373)}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:23:604] InitData: API.getuserinfo: {code: 'REPONSE_OK', msg: 'success', message: 'success', data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:23:901] InitData: API.x.getAccInfo: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:23:905] Live_info: {room_id: 14047, short_room_id: 14047, uid: 32147038, ruid: 19193, gift_list: Array(373), …}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:24:230] before init() getMedalList: API.i.medal: {code: 510001, msg: '用户不存在', message: '用户不存在', data: Array(0)}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:24:231] toast-error: 获取粉丝勋章列表失败 用户不存在 部分功能将无法正常运行
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:24:235] runTomorrow: 获取粉丝勋章列表 Tue Nov 09 2021 16:01:00 GMT+0000 (格林尼治标准时间)
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:24:235] medla_info: {status: {…}, medal_list: Array(0)}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:24:257] MY_API.GIFT_COUNT: {COUNT: 0, ANCHOR_COUNT: 0, MATERIAL_COUNT: 0, LITTLE_HEART_COUNT: 0, CLEAR_TS: 1636450192906}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:24:261] toast-success: CACHE载入成功
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:24:273] MY_API.CONFIG: {AUTO_DANMU: false, AUTO_GIFT: false, AUTO_GIFT_ROOMID: Array(1), AUTO_GROUP_SIGN: true, ANCHOR_LOTTERY: false, …}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:24:273] runExactMidnight: 重置统计 Tue Nov 09 2021 16:00:00 GMT+0000 (格林尼治标准时间)
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:29:413] toast-error: [粉丝牌打卡] 粉丝勋章列表未被完全获取，暂停运行
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:29:609] runTomorrow: 应援团签到 Wed Nov 10 2021 00:01:00 GMT+0000 (格林尼治标准时间)
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:29:809] runMidnight: 每日任务 Tue Nov 09 2021 16:01:00 GMT+0000 (格林尼治标准时间)
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:30:8] runMidnight: 直播签到 Tue Nov 09 2021 16:01:00 GMT+0000 (格林尼治标准时间)
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:30:208] runMidnight: 瓜子换硬币 Tue Nov 09 2021 16:01:00 GMT+0000 (格林尼治标准时间)
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:31:72] [小心心] 获取包裹列表: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=d5cebcd7-d383-42ea-b0e0-d7450d6cbe7b:173 [BLTH][9:57:31:73] toast-info: [小心心] 开始获取今日小心心

### 操作系统

Win10 21H1

### 浏览器

Chrome  95.0.4638.69

### 用户脚本管理器

Tampermonkey 4.13

### 挂机助手版本

5.7.9.2

### 网络情况

好

### 其他浏览器插件/脚本

bilibili直播间工具

### 其他

本人在海外，前两天打卡时会出现所在地区不可用这个提示 但实际手动发弹幕的话没有问题。另外，出现地区不可用时挂上回国的梯子又可以正常打卡

**Comment by oneole** [comment]
+1

**Comment by andywang425** [comment]
了解，有空会测试并尝试修复。

**Comment by dong-jpg** [comment]
兄弟我人在国内，挂全局香港和美国的梯子都可以正常打卡，有点难复现啊，关于这个问题有几个难搞的点：
1.aw没有改换过相关api，说明可能b站又搞幺蛾子了，修复只能看aw能否找到b站新加的限制。
2.国外的人挂全局的国内梯子才可以正常打卡，但是我挂梯子出国还是能正常打卡。

**Comment by andywang425** [comment]
我挂梯子测试了一下也都可以正常打卡，有点难搞。

> 兄弟我人在国内，挂全局香港和美国的梯子都可以正常打卡，有点难复现啊，关于这个问题有几个难搞的点： 1.aw没有改换过相关api，说明可能b站又搞幺蛾子了，修复只能看aw能否找到b站新加的限制。 2.国外的人挂全局的国内梯子才可以正常打卡，但是我挂梯子出国还是能正常打卡。

**Comment by ForsakenRei** [comment]
> 我挂梯子测试了一下也都可以正常打卡，有点难搞。
> 
> > 兄弟我人在国内，挂全局香港和美国的梯子都可以正常打卡，有点难复现啊，关于这个问题有几个难搞的点： 1.aw没有改换过相关api，说明可能b站又搞幺蛾子了，修复只能看aw能否找到b站新加的限制。 2.国外的人挂全局的国内梯子才可以正常打卡，但是我挂梯子出国还是能正常打卡。

推测是国内在开会所以海外用户无法在直播间发弹幕，所以没有办法打卡？我连手动打卡都失败的，挂了国内的VPN就正常了

@szmarcos 你可以测试一下你发的弹幕能不能上主播的屏，我测试过的所有在直播的人我发弹幕都会直接被过滤掉，根本不会上屏。我找了没有人的直播间，我发一条弹幕让朋友看，并没有人能看到我发的弹幕。所以实际上是海外IP根本不能发弹幕233

我觉得可以等两天会开完了再试试……

**Comment by andywang425** [comment]
> 推测是国内在开会所以海外用户无法在直播间发弹幕，所以没有办法打卡？我连手动打卡都失败的，挂了国内的VPN就正常了
> 
> @szmarcos 你可以测试一下你发的弹幕能不能上主播的屏，我测试过的所有在直播的人我发弹幕都会直接被过滤掉，根本不会上屏。我找了没有人的直播间，我发一条弹幕让朋友看，并没有人能看到我发的弹幕。所以实际上是海外IP根本不能发弹幕233
> 
> 我觉得可以等两天会开完了再试试……

有道理，我过几天再试试。

**Comment by szmarcos** [comment]
> > 我挂梯子测试了一下也都可以正常打卡，有点难搞。
> > > 兄弟我人在国内，挂全局香港和美国的梯子都可以正常打卡，有点难复现啊，关于这个问题有几个难搞的点： 1.aw没有改换过相关api，说明可能b站又搞幺蛾子了，修复只能看aw能否找到b站新加的限制。 2.国外的人挂全局的国内梯子才可以正常打卡，但是我挂梯子出国还是能正常打卡。
> 
> 推测是国内在开会所以海外用户无法在直播间发弹幕，所以没有办法打卡？我连手动打卡都失败的，挂了国内的VPN就正常了
> 
> @szmarcos 你可以测试一下你发的弹幕能不能上主播的屏，我测试过的所有在直播的人我发弹幕都会直接被过滤掉，根本不会上屏。我找了没有人的直播间，我发一条弹幕让朋友看，并没有人能看到我发的弹幕。所以实际上是海外IP根本不能发弹幕233
> 
> 我觉得可以等两天会开完了再试试……

2021-11-13 英国
经测试已经可以正常发弹幕，应该还是开会导致的
