### ISSUE TITLE
无法获取小心心

### ISSUE THREAD

**Issue by DEabcdp** [andywang425/BLTH#189]
### 描述bug

最近几个版本包括最新版均无法获得小心心，也没有提示。

### 重现bug

开启插件的情况下，打开直播间。

### 预期行为

选中【自动获取小心心】后能够自动获取。

### 运行日志

脚本: 搜索引擎快捷跳转 --- 开始执行 --- 发布者: qxin --- GitHub:https://github.com/qxinGitHub/searchEngineJump ← 问题反馈地址
userscript.html?name=%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6%E8%A7%A3%E9%99%A4(%E6%94%B9).user.js&id=d8f23f18-5e5e-482d-878d-c680eef3b6b7:204 脚本: 复制限制解除(改) --- 开始执行 --- 发布者: qxin --- GitHub: https://github.com/qxinGitHub/Remove-web-limits-
userscript.html?name=%E7%BD%91%E7%9B%98%E8%87%AA%E5%8A%A8%E5%A1%AB%E5%86%99%E8%AE%BF%E9%97%AE%E7%A0%81%E3%80%90%E5%A8%81%E5%8A%9B%E5%8A%A0%E5%BC%BA%E7%89%88%E3%80%91.user.js&id=1635afbb-c27d-4fb6-82af-f6d2a115815a:912 Object
userscript.html?name=%E7%BD%91%E7%9B%98%E8%87%AA%E5%8A%A8%E5%A1%AB%E5%86%99%E8%AE%BF%E9%97%AE%E7%A0%81%E3%80%90%E5%A8%81%E5%8A%9B%E5%8A%A0%E5%BC%BA%E7%89%88%E3%80%91.user.js&id=1635afbb-c27d-4fb6-82af-f6d2a115815a:917 conf:  undefined
bilibili.5dd478bd9c58fa848a82.js:2 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
bilibili.5dd478bd9c58fa848a82.js:2 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
VM6664:12 no matchMedal, fallback to defaultMedal (28927)
room-player.min.js:31 fMp4Player v1.37
room-player.min.js:31 Chrome verion: 95
room-player.min.js:31 seek to: 65/171.747s, pos=7034788
179.70929035910cd1a653b1.js:2 Bilibili Live V4.0.0 "Life Experience" Lovingly By © 2014 - 2021 Bilibili Live Department  ...(●'◡'●)ﾉ♥   # Renascence #
179.70929035910cd1a653b1.js:2 Version: V4.0.0 "Life Experience", CodeName: Neptune.
VM6636:1 draw button =  null
userscript.html?name=searchEngineJump%20%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E%E5%BF%AB%E6%8D%B7%E8%B7%B3%E8%BD%AC.user.js&id=5fc9b2f7-f261-42ad-919f-bb842dac2ed1:7648 脚本: 搜索引擎快捷跳转 --- 开始执行 --- 发布者: qxin --- GitHub:https://github.com/qxinGitHub/searchEngineJump ← 问题反馈地址
179.70929035910cd1a653b1.js:2 animationsConfig Object
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=5b6d79dc-1489-44f2-b906-f78d32e8840c:192 live watch
179.70929035910cd1a653b1.js:2 animations--preload {__ob__: Et}
DevTools 无法加载源映射： 无法加载chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/jquery.min.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/sm/3d96fbc9c4b130ad115376d0c7b95546d355bb7fbeaa7676f9f25f30c6ddc4bc.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/jquery.min.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载https://activity.hdslb.com/room-player.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载https://activity.hdslb.com/room-player.css.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3635 
        
       Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at getGiftNum (userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3635)
    at run (userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3602)
getGiftNum @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3635
run @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3602
async function(异步)
run @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:3597
eval @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:6555
s @ VM6583:8
n.<computed> @ VM6612:39
s @ VM6583:8
i @ VM6612:3
eval @ VM6612:3
(匿名) @ VM6583:5
_ @ VM6583:5
s @ content.js:96
n @ content.js:97
setTimeout(异步)
setTimeout @ content.js:112
processMessage @ content.js:116
(匿名) @ content.js:119
(匿名) @ content.js:97
s @ VM6583:8
E.safeDocument.<computed> @ VM6583:4
s @ VM6583:8
b @ VM6583:5
send @ VM6583:6
r @ VM6612:3
setTimeout @ VM6612:4
s @ VM6583:8
t @ VM6612:39
enhance @ VM6612:51
eval @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:6555
s @ VM6583:8
n.<computed> @ VM6612:39
s @ VM6583:8
i @ VM6612:3
eval @ VM6612:3
(匿名) @ VM6583:5
_ @ VM6583:5
s @ content.js:96
n @ content.js:97
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:6061 
        
       Uncaught (in promise) TypeError: MY_API.PLATE_ACTIVITY.plateData is not iterable
    at run (userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:6061)
run @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:6061
async function(异步)
run @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:6060
eval @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:6555
s @ VM6583:8
n.<computed> @ VM6612:39
s @ VM6583:8
i @ VM6612:3
eval @ VM6612:3
(匿名) @ VM6583:5
_ @ VM6583:5
s @ content.js:96
n @ content.js:97
setTimeout(异步)
setTimeout @ content.js:112
processMessage @ content.js:116
(匿名) @ content.js:119
(匿名) @ content.js:97
s @ VM6583:8
E.safeDocument.<computed> @ VM6583:4
s @ VM6583:8
b @ VM6583:5
send @ VM6583:6
r @ VM6612:3
setTimeout @ VM6612:4
s @ VM6583:8
t @ VM6612:39
enhance @ VM6612:51
eval @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:6555
s @ VM6583:8
n.<computed> @ VM6612:39
s @ VM6583:8
i @ VM6612:3
eval @ VM6612:3
(匿名) @ VM6583:5
_ @ VM6583:5
s @ content.js:96
n @ content.js:97
7[Violation]Forced reflow while executing JavaScript 用时 <N> 毫秒
[Violation]Forced reflow while executing JavaScript took 36ms
[Violation]Forced reflow while executing JavaScript took 36ms
[Violation]Forced reflow while executing JavaScript took 34ms
[Violation]Forced reflow while executing JavaScript took 56ms
[Violation]Forced reflow while executing JavaScript took 40ms
[Violation]Forced reflow while executing JavaScript took 36ms
[Violation]Forced reflow while executing JavaScript took 39ms
room-player.min.js:60 [Violation]Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
I @ room-player.min.js:60
m @ room-player.min.js:60
zt @ room-player.min.js:60
m @ room-player.min.js:60
m @ room-player.min.js:60
p @ room-player.min.js:60
mt @ room-player.min.js:60
vt @ room-player.min.js:60
set @ room-player.min.js:60
y.show @ room-player.min.js:62
r @ room-player.min.js:62

### 操作系统

Windows 10

### 浏览器

Microsoft Edge 版本 95.0.1020.53 (官方内部版本) (64 位) chromium

### 用户脚本管理器

Tampermonkey BETA  版本4.14.6146

### 挂机助手版本

5.7.9.3

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by dong-jpg** [comment]
已收到Bug，我明天测试一下

**Comment by DEabcdp** [comment]
> 

在已关注且正在直播列表内自动参与天选时刻，也没有生效。

**Comment by IskandarZhang** [comment]
> 

请问是否已经修复？昨天可以正常获取，今天仍然无法获取。网络环境相同

**Comment by andywang425** [comment]
看了下貌似是获取包裹列表的时候失败了，明天再试试？  
以后我会在这里加个获取包裹列表失败的提示。

**Comment by WDonny** [comment]
> 看了下貌似是获取包裹列表的时候失败了，明天再试试？ 以后我会在这里加个获取包裹列表失败的提示。

这两天又失效了
控制台日志如下：
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. B站直播间挂机助手.user.js:143:100445
源映射错误：Error: NetworkError when attempting to fetch resource.
源 URL：moz-extension://aeb55a00-9afb-42bf-bd22-f7b050898613/userscripts/B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js?id=64003862-b08d-4ac4-9a8d-bfb2cb60694f
源映射 URL：/sm/3d96fbc9c4b130ad115376d0c7b95546d355bb7fbeaa7676f9f25f30c6ddc4bc.map

源映射错误：Error: request failed with status 404
源 URL：https://activity.hdslb.com/blackboard/static/edfd7948d5ca04de779233922773e479/room-player.min.js
源映射 URL：/room-player.js.map

已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. B站直播间挂机助手.user.js:143:100445
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. B站直播间挂机助手.user.js:143:100445
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. B站直播间挂机助手.user.js:143:100445
此网站似乎使用 scroll-linked 定位效果。这可能无法与异步平移一起使用；参见 https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html 详细了解，也可加入我们一起讨论相关的工具和功能！ 23193752
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/rdata-interface/v1/heartbeat/webHeartBeat?hb=NTF8MjMxOTM3NTJ8MXww&pf=web 的远程资源。（原因：CORS 请求未能成功）。

[Request Error] "" 请求失败: Network Error 179.8386b9abbea09fc9e80d.js:2:1958571
Error: Promised response from onMessage listener went out of scope

**Comment by kokoryh** [comment]
根据控制台的data.list为null的报错，我在getGiftNum方法中修改判断条件为if(null===bagList.data.list||0===bagList.data.list.length) return 0;可以暂时解决无法获取小心心的问题。
但是data.list为null的触发条件很奇怪，获取小心心的功能在我的设备上是隔天生效一次。还有就是本来获取的全是null，有牌子的主播开播，看一段时间突然就触发脚本开始获取小心心了，不知道是B站的问题还是脚本的问题

**Comment by shanmiteko** [comment]
#191

**Comment by andywang425** [comment]
该问题在最新版中已得到修复 #192。
