### ISSUE TITLE
脚本偶尔加载失败

### ISSUE THREAD

**Issue by X-Holmes** [andywang425/BLTH#19]
描述bug
Tampermonkey中显示此脚本正在运行，但实际却没有运行(没有显示面板、浮动通知，也没有执行脚本功能)。

重现bug
偶尔发生，用同一台电脑+相同浏览器+相同脚本在不同时间打开脚本，有时正常运行有时不能正常加载（不正常时即使多次刷新也依然无法加载）

运行日志
图中被选中的3条(倒数第2~4条)是在Tampermonkey中开启此脚本后新增的日志(其他日志即使不开启此脚本也会显示)。
![4](https://user-images.githubusercontent.com/35630677/92343853-6e84b280-f0f7-11ea-8c71-ddc19430f6dc.png)
此3条日志的文本形式附于文后

使用环境:
浏览器: Microsoft Edge
浏览器版本: Microsoft Edge 85.0.564.44
脚本的版本: 4.5
网络情况(网速): 一般
其他浏览器插件/脚本: 无
bug出现时间: 2020-9-7 09:55

其他
脚本日志文本：

`Access to XMLHttpRequest at 'https://api.live.bilibili.com/live_user/v1/UserInfo/get_info_in_room?roomid=23058' from origin 'https://live.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

`GET https://api.live.bilibili.com/live_user/v1/UserInfo/get_info_in_room?roomid=23058 net::ERR_FAILED`
1|2
 -- | -- 
send|@userscript.html?name…8b23-c387c3860418:5
ajax|@userscript.html?name…8b23-c387c3860418:5
eval|@userscript.html?name…b23-c387c3860418:18
eval|@userscript.html?name…b23-c387c3860418:18
(匿名)|@VM4061:3
I.c.<computed>|@VM4071:42
setTimeout(异步)|
(匿名)|@VM4061:3
d.<computed>|@VM4061:9
(匿名)|@VM4061:3
I|@VM4071:42
enhance|@VM4071:54
runUntilSucceed|@userscript.html?name…b23-c387c3860418:18
ajax|@userscript.html?name…b23-c387c3860418:18
get_info_in_room|@userscript.html?name…b23-c387c3860418:18
eval|@userscript.html?name…23-c387c3860418:582
(匿名)|@VM4061:3
I.c.<computed>|@VM4071:42
setTimeout(异步)|
(匿名)|@VM4061:3
d.<computed>|@VM4061:9
(匿名)|@VM4061:3
I|@VM4071:42
enhance|@VM4071:54
loadInfo|@userscript.html?name…23-c387c3860418:582
window.onload|@userscript.html?name…23-c387c3860418:582
(匿名)|@VM4061:3
f|@VM4071:51
load(异步)|
(匿名)|@VM4061:3
d.<computed>|@VM4061:9
set|@VM4071:51
eval|@userscript.html?name…23-c387c3860418:582
tms_b7ceb1dd_690e_489a_8b23_c387c3860418|@userscript.html?name…3-c387c3860418:1115
(匿名)|@VM4061:3
eval|@userscript.html?name…8b23-c387c3860418:1
eval|@userscript.html?name…8b23-c387c3860418:1
eval|@userscript.html?name…3-c387c3860418:1116
eval|@userscript.html?name…3-c387c3860418:1118
(匿名)|@VM4061:3
c|@VM4061:2
(匿名)|@VM4061:3
ka|@VM4071:59
create|@VM4071:71
d|@VM4071:13
runListeners|@VM4071:13
eval|@VM4071:72
Q|@VM4061:11
send|@content.js:7
(匿名)|@content.js:27
processQueue|@content.js:3
a|@content.js:9

`Uncaught (in promise) {readyState: 0, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}`
1|2
-- | --
eval|@userscript.html?name…23-c387c3860418:582
async function(异步)|
eval|@userscript.html?name…23-c387c3860418:582
(匿名)|@VM4061:3
I.c.<computed>|@VM4071:42
setTimeout(异步)|
(匿名)|@VM4061:3
d.<computed>|@VM4061:9
(匿名)|@VM4061:3
I|@VM4071:42
enhance|@VM4071:54
loadInfo|@userscript.html?name…23-c387c3860418:582
window.onload|@userscript.html?name…23-c387c3860418:582
(匿名)|@VM4061:3
f|@VM4071:51
load(异步)|
(匿名)|@VM4061:3
d.<computed>|@VM4061:9
set|@VM4071:51
eval|@userscript.html?name…23-c387c3860418:582
tms_b7ceb1dd_690e_489a_8b23_c387c3860418|@userscript.html?name…3-c387c3860418:1115
(匿名)|@VM4061:3
eval|@userscript.html?name…8b23-c387c3860418:1
eval|@userscript.html?name…8b23-c387c3860418:1
eval|@userscript.html?name…3-c387c3860418:1116
eval|@userscript.html?name…3-c387c3860418:1118
(匿名)|@VM4061:3
c|@VM4061:2
(匿名)|@VM4061:3
ka|@VM4071:59
create|@VM4071:71
d|@VM4071:13
runListeners|@VM4071:13
eval|@VM4071:72
Q|@VM4061:11
send|@content.js:7
(匿名)|@content.js:27
processQueue|@content.js:3
a|@content.js:9

**Comment by andywang425** [comment]
我看了下主要就是因为`https://api.live.bilibili.com/live_user/v1/UserInfo/get_info_in_room?roomid=23058`这个请求失败导致的。
这是个获取用户信息的请求，所以如果没法成功请求的话脚本确实没法运行。  
偶尔我也会出现这种情况但过几分钟就又正常了。遇到这种情况我真的无能为力，因为这是b站限制了这个请求，并不是脚本代码逻辑上的问题。

**Comment by X-Holmes** [comment]
我有一点小疑问。
这个脚本的功能应该大部分都是通过api实现的吧？那么脚本所挂的网页是不是直播间对脚本功能会有影响吗？
比如说设置成脚本在B站主页也可以运行，那么每日任务应援团这些功能应该都还可以正常运行吧？
我不清楚脚本有多少功能依赖于必须挂在直播间的页面，但我想可不可以先加载一些不需要用到直播间页面的功能呢？
这样就不会因为上面那个请求出问题而什么都做不了了(我只是想自动完成每日任务+签到)
或者就像Bilibili Evolved脚本那样在不同页面展示不同的功能(可能工作量有点大)

另外我怀疑我的ip被B站列为黑名单了，因为我同一时间用另一台电脑在另一个网络下就可以正常运行。

**Comment by andywang425** [comment]
> 我有一点小疑问。
> 这个脚本的功能应该大部分都是通过api实现的吧？那么脚本是否挂在直播间页面对脚本功能会有影响吗？
> 比如说设置成脚本在B站主页也可以运行，那么每日任务应援团这些功能应该都还可以正常使用吧？
> 我不清楚脚本有多少功能依赖于必须挂在直播间的页面，但我想可不可以先加载一些不需要用到直播间页面的功能呢？
> 这样就不会因为上面那个请求出问题而什么都做不了了(我只是想自动完成每日任务+签到)
> 或者就像Bilibili Evolved脚本那样在不同页面展示不同的功能(可能工作量有点大)
> 
> 另外我怀疑我的ip被B站列为黑名单了，因为我同一时间用另一台电脑在另一个网络下就可以正常运行。

脚本是否挂在直播间页面对脚本功能没影响，脚本仅在直播间运行主要是为了方便绘制UI，还有就是节约性能。  
如果脚本在任意B站页面都能运行的话，设计UI会很麻烦。  
那个请求我发现已经不需要了，下个版本会删除。

**Comment by X-Holmes** [comment]
4.5.2版本中上述问题已修复。
但还遇到了类似的问题，自动送礼失败：
![log](https://user-images.githubusercontent.com/35630677/92842937-c0d71380-f416-11ea-97e7-ac9354b9ca2b.png)
脚本选项配置如下图：
![config](https://user-images.githubusercontent.com/35630677/92843254-21fee700-f417-11ea-9293-4efe26769b5e.png)
配置说明：此账号仅有3号直播间的粉丝勋章，但希望通过脚本将礼物送给14xxx57直播间。

**Comment by andywang425** [comment]
自动送礼只会给有粉丝勋章的房间送礼，如果没有优先送礼房间的粉丝勋章填了也不会送的，只填剩余礼物送礼直播间就ok了。  
至于自动送礼失败，看上去是获取信息的一个跨域请求被浏览器限制了，意思就是需要一个叫做`Access-Contro-Allow-Origin`的请求头，但脚本应该是可以发起跨域请求的，我测试的时候没有问题。可能和你的浏览器设置有关？

**Comment by X-Holmes** [comment]
浏览器环境就是主楼那个，至于细节上的设置我也不能确定。
主要是我看到主楼反馈的那个错误跟这个错误几乎是一样的，就怀疑是不是有相同的原因。二者都是
`Access to XMLHttpRequest at 'https://api.live.bilibili.com/live_user/v1/UserInfo/get_xxxx_in_room?roomid=xxxx' from origin 'https://live.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
`GET https://api.live.bilibili.com/live_user/v1/UserInfo/get_xxxx_in_room?roomid=xxxx net::ERR_FAILED`

你说主楼那个问题`“偶尔我也会出现这种情况但过几分钟就又正常了”`，那或许后面这个问题也是间歇发生的、你测试时刚好是正常状态？
不知道后面这个请求是否也已经不需要了、可以删去？

**Comment by andywang425** [comment]
> 浏览器环境就是主楼那个，至于细节上的设置我也不能确定。
> 主要是我看到主楼反馈的那个错误跟这个错误几乎是一样的，就怀疑是不是有相同的原因。二者都是
> `Access to XMLHttpRequest at 'https://api.live.bilibili.com/live_user/v1/UserInfo/get_xxxx_in_room?roomid=xxxx' from origin 'https://live.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
> `GET https://api.live.bilibili.com/live_user/v1/UserInfo/get_xxxx_in_room?roomid=xxxx net::ERR_FAILED`
> 
> 你说主楼那个问题`“偶尔我也会出现这种情况但过几分钟就又正常了”`，那或许后面这个问题也是间歇发生的、你测试时刚好是正常状态？
> 不知道后面这个请求是否也已经不需要了、可以删去？

这个请求删不了，因为需要通过这个请求获取剩余礼物直播间号对应的UID。送礼的时候需要UID作为参数。  
我以后会试着修复，但可能不会马上就修好。我对这方面的知识了解的不多，需要花点时间研究一下。

**Comment by X-Holmes** [comment]
> 这个请求删不了，因为需要通过这个请求获取剩余礼物直播间号对应的UID。送礼的时候需要UID作为参数。

那可以简单粗暴地恢复之前同时填写UID和房间号的方式，就可以避免使用这个请求了吧。或者如果只需要UID就不用填房间号了。

**Comment by andywang425** [comment]
我想问下现在还有这个问题吗？如果没问题了的话我就不修复了。

**Comment by X-Holmes** [comment]
> 我想问下现在还有这个问题吗？如果没问题了的话我就不修复了。

最近一周没有遇到这个问题。剩余礼物自动赠送正常。
