### ISSUE TITLE
无法获取小心心（CORS）

### ISSUE THREAD

**Issue by andywang425** [andywang425/BLTH#193]
这两天又失效了
控制台日志如下：
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. B站直播间挂机助手.user.js:143:100445
源映射错误：Error: NetworkError when attempting to fetch resource.
源 URL：moz-extension://aeb55a00-9afb-42bf-bd22-f7b050898613/userscripts/B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js?id=64003862-b08d-4ac4-9a8d-bfb2cb60694f
源映射 URL：/sm/3d96fbc9c4b130ad115376d0c7b95546d355bb7fbeaa7676f9f25f30c6ddc4bc.map

源映射错误：Error: request failed with status 404
源 URL：https://activity.hdslb.com/blackboard/static/edfd7948d5ca04de779233922773e479/room-player.min.js
源映射 URL：/room-player.js.map

已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. B站直播间挂机助手.user.js:143:100445
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. B站直播间挂机助手.user.js:143:100445
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/E 的远程资源。（原因：CORS 请求未能成功）。

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. B站直播间挂机助手.user.js:143:100445
此网站似乎使用 scroll-linked 定位效果。这可能无法与异步平移一起使用；参见 https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html 详细了解，也可加入我们一起讨论相关的工具和功能！ 23193752
已拦截跨源请求：同源策略禁止读取位于 https://live-trace.bilibili.com/xlive/rdata-interface/v1/heartbeat/webHeartBeat?hb=NTF8MjMxOTM3NTJ8MXww&pf=web 的远程资源。（原因：CORS 请求未能成功）。

[Request Error] "" 请求失败: Network Error 179.8386b9abbea09fc9e80d.js:2:1958571
Error: Promised response from onMessage listener went out of scope

_Originally posted by @WDonny in https://github.com/andywang425/BLTH/issues/189#issuecomment-981054967_

**Comment by andywang425** [comment]
@WDonny 这个问题在5.7.9.4版本中还未得到修复，我再找找原因。

**Comment by andywang425** [comment]
今天我这也出现这个问题了，会尽早修复。

**Comment by ForsakenRei** [comment]
今天好像正常了，但是我在直播间看不到自己发的弹幕，新的奇怪的问题

**Comment by abigtreenj** [comment]
我这边也出现这个问题了, 就这几天的事.

**Comment by dangger** [comment]
最近也遇到了这个情况，排查了一下后解决了，附上排查思路：
1.是否使用了屏蔽广告的dns？是否使用了屏蔽广告工具（ublock origin等）
主要看 live-trace.bilibili.com 这个链接能否点进去。
2.是否使用firefox浏览器？
我这边测试firefox无论如何调整，都会有CORS问题，哪怕是我装了几个扩展重写了CORS为*。

到这一步我已经正常使用了，附上正常的浏览器版本：
Chrome版本 96.0.4664.93（正式版本） （64 位）

**Comment by andywang425** [comment]
看来就是广告拦截插件的问题，我把ublock origin关掉就正常了。当时太忙忘记回复了，抱歉。
