### ISSUE TITLE
获取粉丝列表超时，无法完成打卡.

### ISSUE THREAD

**Issue by 13579diana** [andywang425/BLTH#194]
### 描述bug

直播间无法打卡

### 重现bug

昨天卡了1000个粉丝勋章后出现的问题，小号几个勋章打卡正常.

### 预期行为

麻烦作者大大看看有没有什么解决方法.

### 截图

![图片](https://user-images.githubusercontent.com/95542899/144744288-43cc9cda-0645-4813-a003-91c9540cd865.png)
![图片](https://user-images.githubusercontent.com/95542899/144744295-ec7dfe2b-07f9-4398-8cd1-146df22dd206.png)

### 运行日志

无

### 操作系统

Windows10

### 浏览器

Edge 93.0.961.52

### 用户脚本管理器

Tampermonkey v4.13

### 挂机助手版本

5.7.9.4

### 网络情况

好

### 其他浏览器插件/脚本

无

### 其他

无

**Comment by andywang425** [comment]
收到，会想办法解决

**Comment by bingdu748** [comment]
相同的问题，每天获取勋章花了半个小时都获取不完，一直超时超时超时
![获取粉丝列表超时](https://user-images.githubusercontent.com/50004335/146111610-e65a2b3c-77db-49b8-aeed-a547094ec92d.png)
