### ISSUE TITLE
[实物抽奖] 获取抽奖(aid=846)状态失败 未登录

### ISSUE THREAD

**Issue by mrzxc1230** [andywang425/BLTH#195]
### 描述bug

[实物抽奖] 获取抽奖(aid=846)状态失败 未登录这是什么情况？正常吗？

### 重现bug

无

### 预期行为

无

### 运行日志

2021/12/8 下午7:50:12
[实物抽奖] 获取抽奖(aid=846)状态失败 未登录

### 操作系统

win10

### 浏览器

chrome94.0.4606.81

### 用户脚本管理器

Tampermonkey4.13

### 挂机助手版本

5.7.9.4

### 网络情况

好

### 其他浏览器插件/脚本

广告拦截

**Comment by andywang425** [comment]
收到，现在期末正忙，放假了就开始修这个bug。

**Comment by andywang425** [comment]
还是没找到原因。。。

**Comment by 1542155354** [comment]
呜呜呜呜，好吧qwq




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月28日(星期一) 中午11:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [andywang425/BLTH] [实物抽奖] 获取抽奖(aid=846)状态失败 未登录 (Issue #195)





 
还是没找到原因。。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by andywang425** [comment]
已在新版本5.7.9.6中修复该问题。
