### ISSUE TITLE
无法进行弹幕打卡

### ISSUE THREAD

**Issue by DanLCJ** [andywang425/BLTH#196]
### 描述bug

在默认设置情况下，无法进行粉丝团的弹幕打卡；如果在设置中设置白名单房间号则正常。
另外，似乎b站对于海外用户增加了限制，不能正常在直播间发送弹幕，但是不清楚这个是否有影响。

### 重现bug

右上角除了弹幕打卡成功以外，其他均正常，包括获取小心心和签到等功能。

### 预期行为

正常在不设置房间白名单的情况下，应该是默认打卡所有的有牌子的房间

### 运行日志

![image](https://user-images.githubusercontent.com/40844774/145672853-f99cb5a1-4825-4de0-af8b-6fd9e20eb812.png)
![image](https://user-images.githubusercontent.com/40844774/145672864-51320e2f-d8e8-4723-971b-2b9bf80163ba.png)
![image](https://user-images.githubusercontent.com/40844774/145672875-02a96627-2c5f-4d66-90df-467789ed39a9.png)
![image](https://user-images.githubusercontent.com/40844774/145672888-8586c811-ae51-40d2-b4c6-a6c3316611c8.png)

### 操作系统

Windows 10 20H2 19042.1288

### 浏览器

Chrome 96.0.4664.93

### 用户脚本管理器

Tampermonkey 4.13

### 挂机助手版本

5.7.9.4

### 网络情况

好

### 其他浏览器插件/脚本

uBlock Origin; 哔哩哔哩助手：bilibili.com 综合辅助扩展 （这两个都是chrome插件）

**Comment by andywang425** [comment]
请问控制台中是否有带`BLTH`字样的日志？截图中似乎没有和脚本相关的日志。  
ps：脚本默认关闭控制台日志。勾选控制面板上的`其他设置 - 控制台日志`即可开启。

**Comment by xjiaf** [comment]
同样遇到这个问题。粉丝牌打卡功能失效

**Comment by andywang425** [comment]
海外用户似乎是不能正常发弹幕，之前有海外用户反馈过这个问题。暂时无解决方法。
