### ISSUE TITLE
通过seconds推送QQ信息失效

### ISSUE THREAD

**Issue by nyano** [andywang425/BLTH#197]
### 描述bug

通过seconds推送QQ信息失效，错误码为200.
账号最后一次有效使用为12月5日。仅供参考

### 重现bug

无

### 预期行为

无

### 运行日志

无

### 操作系统

win11

### 浏览器

edge

### 用户脚本管理器

tamp

### 挂机助手版本

5.7.9.4

### 网络情况

好

### 其他浏览器插件/脚本

Bilibili Evolved 2.0

**Comment by andywang425** [comment]
最近运维说go-cqhttp（qq机器人框架）启动不起来，所以推送挂了。  
这个问题先暂时搁置一下，等我放寒假了再研究。

**Comment by andywang425** [comment]
qq机器人框架跑起来了，但可能还是会因为未知原因导致加不上好友，这个我暂时没解决方法。
