### ISSUE TITLE
直播间不能自动参与天选时刻

### ISSUE THREAD

**Issue by DEabcdp** [andywang425/BLTH#198]
### 描述bug

选中参与天选时刻，不会自动参加已关注up的天选时刻。

### 重现bug

1.选中参与天选时刻
2.打开已关注正在天选时刻的up直播间

### 预期行为

能够自动参与天选时刻

### 运行日志

​ 脚本: 搜索引擎快捷跳转 --- 开始执行 --- 发布者: qxin --- GitHub:https://github.com/qxinGitHub/searchEngineJump ← 问题反馈地址
userscript.html?name=%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6%E8%A7%A3%E9%99%A4(%E6%94%B9).user.js&id=d8f23f18-5e5e-482d-878d-c680eef3b6b7:204 脚本: 复制限制解除(改) --- 开始执行 --- 发布者: qxin --- GitHub: https://github.com/qxinGitHub/Remove-web-limits-
bilibili.bd49d0037ee6d42ac67b.js:2 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
bilibili.bd49d0037ee6d42ac67b.js:2 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
VM3129:12 no matchMedal, fallback to defaultMedal (28927)
room-player.min.js:29 Hls7Player v1.76
room-player.min.js:29 Chrome verion: 96
room-player.min.js:67 [SistersPlayer] Misaka Network Check: Unsupported
room-player.min.js:14 
        
       unsupported bilibili p2p
a @ room-player.min.js:14
room-player.min.js:14 
        
       Error: launch bili_p2p failed
    at room-player.min.js:77
    at room-player.min.js:16
    at room-player.min.js:16
    at Set.forEach (<anonymous>)
    at o.emit (room-player.min.js:16)
    at E.emit (room-player.min.js:53)
    at E.createCorePlayer (room-player.min.js:53)
    at E.load (room-player.min.js:53)
    at room-player.min.js:77
    at new Promise (<anonymous>)
a @ room-player.min.js:14
room-player.min.js:29 track 1 start dts: 7275
179.a0709ddd460aaf7f9bb4.js:2 Bilibili Live V4.0.0 "Life Experience" Lovingly By © 2014 - 2021 Bilibili Live Department  ...(●'◡'●)ﾉ♥   # Renascence #
179.a0709ddd460aaf7f9bb4.js:2 Version: V4.0.0 "Life Experience", CodeName: Neptune.
VM3101:1 draw button =  null
app.e1bcc1dd3698a9d3f32f.js:2 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at t.<anonymous> (app.e1bcc1dd3698a9d3f32f.js:2)
    at f (vendors.bce5235de275bf4fd2f1.js:2)
    at Generator._invoke (vendors.bce5235de275bf4fd2f1.js:2)
    at Generator.next (vendors.bce5235de275bf4fd2f1.js:2)
    at a (app.e1bcc1dd3698a9d3f32f.js:2)
DevTools 无法加载源映射： 无法加载chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/jquery.min.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/sm/3d96fbc9c4b130ad115376d0c7b95546d355bb7fbeaa7676f9f25f30c6ddc4bc.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/jquery.min.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
DevTools 无法加载源映射： 无法加载https://activity.hdslb.com/room-player.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
userscript.html?name=searchEngineJump%20%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E%E5%BF%AB%E6%8D%B7%E8%B7%B3%E8%BD%AC.user.js&id=5fc9b2f7-f261-42ad-919f-bb842dac2ed1:7648 脚本: 搜索引擎快捷跳转 --- 开始执行 --- 发布者: qxin --- GitHub:https://github.com/qxinGitHub/searchEngineJump ← 问题反馈地址
userscript.html?name=Bilibili%20Evolved%20(Preview).user.js&id=5b6d79dc-1489-44f2-b906-f78d32e8840c:194 live watch
VM2503 include.preload.js:1016 [Violation]'setTimeout' handler took 81ms
DevTools 无法加载源映射： 无法加载chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/jquery.min.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
7430.d64fe6e69981e9b11b49.js:1 [Violation]Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(匿名) @ 7430.d64fe6e69981e9b11b49.js:1
Yt._initCanvas @ 7430.d64fe6e69981e9b11b49.js:1
Yt @ 7430.d64fe6e69981e9b11b49.js:1
t.init @ 7430.d64fe6e69981e9b11b49.js:1
(匿名) @ 7430.d64fe6e69981e9b11b49.js:1
f @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ 7430.d64fe6e69981e9b11b49.js:1
e @ vendors.bce5235de275bf4fd2f1.js:2
V @ 7430.d64fe6e69981e9b11b49.js:1
e.init @ 7430.d64fe6e69981e9b11b49.js:1
(匿名) @ 7430.d64fe6e69981e9b11b49.js:1
f @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ 7430.d64fe6e69981e9b11b49.js:1
e @ vendors.bce5235de275bf4fd2f1.js:2
V @ 7430.d64fe6e69981e9b11b49.js:1
e.mounted @ 7430.d64fe6e69981e9b11b49.js:1
Gt @ vendors.bce5235de275bf4fd2f1.js:2
sr @ vendors.bce5235de275bf4fd2f1.js:2
insert @ vendors.bce5235de275bf4fd2f1.js:2
k @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ vendors.bce5235de275bf4fd2f1.js:2
t._update @ vendors.bce5235de275bf4fd2f1.js:2
n @ vendors.bce5235de275bf4fd2f1.js:2
br.get @ vendors.bce5235de275bf4fd2f1.js:2
br.run @ vendors.bce5235de275bf4fd2f1.js:2
mr @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ vendors.bce5235de275bf4fd2f1.js:2
te @ vendors.bce5235de275bf4fd2f1.js:2
Show 2 more frames
7430.d64fe6e69981e9b11b49.js:1 [Violation]Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(匿名) @ 7430.d64fe6e69981e9b11b49.js:1
Yt._initCanvas @ 7430.d64fe6e69981e9b11b49.js:1
Yt @ 7430.d64fe6e69981e9b11b49.js:1
t.init @ 7430.d64fe6e69981e9b11b49.js:1
(匿名) @ 7430.d64fe6e69981e9b11b49.js:1
f @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ 7430.d64fe6e69981e9b11b49.js:1
e @ vendors.bce5235de275bf4fd2f1.js:2
V @ 7430.d64fe6e69981e9b11b49.js:1
e.init @ 7430.d64fe6e69981e9b11b49.js:1
(匿名) @ 7430.d64fe6e69981e9b11b49.js:1
f @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ 7430.d64fe6e69981e9b11b49.js:1
e @ vendors.bce5235de275bf4fd2f1.js:2
V @ 7430.d64fe6e69981e9b11b49.js:1
e.mounted @ 7430.d64fe6e69981e9b11b49.js:1
Gt @ vendors.bce5235de275bf4fd2f1.js:2
sr @ vendors.bce5235de275bf4fd2f1.js:2
insert @ vendors.bce5235de275bf4fd2f1.js:2
k @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ vendors.bce5235de275bf4fd2f1.js:2
t._update @ vendors.bce5235de275bf4fd2f1.js:2
n @ vendors.bce5235de275bf4fd2f1.js:2
br.get @ vendors.bce5235de275bf4fd2f1.js:2
br.run @ vendors.bce5235de275bf4fd2f1.js:2
mr @ vendors.bce5235de275bf4fd2f1.js:2
(匿名) @ vendors.bce5235de275bf4fd2f1.js:2
te @ vendors.bce5235de275bf4fd2f1.js:2
Show 2 more frames
DevTools 无法加载源映射： 无法加载https://activity.hdslb.com/room-player.css.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:16 [Violation]Added synchronous DOM mutation listener to a 'DOMNodeInserted' event. Consider using MutationObserver to make the page more responsive.
add @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:16
eval @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:16
each @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:15
each @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:15
ya @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:16
on @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:16
success @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:760
l.pt.callback @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:62
l.pt.creat @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:62
l @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:62
r.open @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:62
myopen @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:7087
init @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:743
init @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:6288
eval @ userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=129144cf-f21e-4cf6-ba0e-841932892a9b:557
[Violation]'setTimeout' handler took 86ms
content.js:93 [Violation]'setTimeout' handler took 86ms
[Violation]Forced reflow while executing JavaScript took 39ms

### 操作系统

Window10

### 浏览器

Microsoft Edge 版本 96.0.1054.62 (官方内部版本) (64 位)

### 用户脚本管理器

Tampermonkey 4.13

### 挂机助手版本

5.7.9.4

### 网络情况

好

**Comment by DEabcdp** [comment]
如果勾选了“启用awpush”和下面的“从已关注且正在直播的直播间获取天选时刻数据”，没有勾选其他的，也会自动给我关注其他up，不知道是为啥？

**Comment by DEabcdp** [comment]
![image](https://user-images.githubusercontent.com/62452364/146756025-de33bf55-820a-4890-b15b-bc09b8ed81c7.png)

**Comment by andywang425** [comment]
> 如果勾选了“启用awpush”和下面的“从已关注且正在直播的直播间获取天选时刻数据”，没有勾选其他的，也会自动给我关注其他up，不知道是为啥？

勾选“启用awpush”后下面那几个选项就不生效了。

**Comment by andywang425** [comment]
暂时不清楚出现该bug的原因，请问不勾选“启用awpush”的话能参加天选吗？
