### ISSUE TITLE
有没有办法购买指定用户的牌子 在他没开充电和直播的情况下

### ISSUE THREAD

**Issue by xmxmxmmmm** [andywang425/BLTH#199]
### 描述

锡兰小号的牌子之前拿到一份写死uid的挂机助手小号买到了
lanzouy.com/iUDiIo9ii8h
现在老的js无法运行
没有20硬币购买选项了
现在能不能有方法获得?

**Comment by andywang425** [comment]
目前无法通过这种方法获得粉丝牌，原因是用硬币买粉丝勋章的接口已经被删除了。
