### ISSUE TITLE
【自动参加天选时刻】功能细节

### ISSUE THREAD

**Issue by X-Holmes** [andywang425/BLTH#20]
1. 设置忽略所需金瓜子大于0的天选时，对于需要有粉丝勋章或大航海才能发弹幕参加的天选时刻，是如何处理的？
> 【注】参加天选时刻有两层限制：
>参与条件【是否关注/勋章等级/大航海/主站等级/直播用户等级】和参与方式【赠送礼物/发送弹幕口令】
2. 轮询的房间来源于各分区小时榜和热门房间列表。可以考虑在此基础上优先轮询已关注的正在开播的直播间，因为这些房间里恰好有粉丝勋章/大航海的几率更高些。
3. 对于因为天选而由脚本自动关注的主播，可以在脚本中临时记录一下。等下一次轮询时检查该主播的天选是否已经结束，若已结束则取消关注该主播。这样仅有少数因为中途关闭脚本或程序错误而没有取关的主播需要手动取关，减少一键取关时短时间内取关的主播数量从而降低被风控的风险。

**Comment by andywang425** [comment]
1. 目前有粉丝勋章要求的天选会直接抛弃，有大航海/主站等级/直播用户等级要求的天选这些我还没抓到过包，不清楚检查这类天选的返回数据是什么，所以会尝试参加，参加失败会警告然后继续运行，问题不大。等我以后遇到了这类天选（或者有人反馈了相关数据）会进一步优化判断逻辑。  
2,3 两个建议都挺好，等我把目前天选模块存在的bug修好以后会去写这两个功能。

**Comment by X-Holmes** [comment]
要求粉丝勋章的直接抛弃是技术原因吗？可否改为检测若原本已有该房间主播勋章则参加抽奖，否则舍弃？

粉丝勋章抽奖的中奖率比仅关注即可抽奖的中奖率高很多，毕竟有门槛，参与人数少。

**Comment by andywang425** [comment]
要求粉丝勋章的天选直接抛弃是因为我没收集过检查这类天选的返回信息，判断自己是否有该勋章，勋章等级是否达到要求的代码也没来得及写。  
目前天选模块还有很多细节没做好，就比如你说的自动取关，检查是否中奖。我自己也有一些想做的功能，比如检测到中奖后自动给主播发私信等。我会慢慢完善这些内容。

**Comment by X-Holmes** [comment]
实测这个脚本确实可以中奖。。(欧洲非酋)
只不过这个奖品有点…甚至怀疑是钓鱼
请问那个忽略关键字忽略的是奖品信息里的关键字还是弹幕口令的关键字呀？我想把xx券的奖品给忽略掉
![IMG_20200923_161830](https://user-images.githubusercontent.com/35630677/93986408-e837c400-fdb8-11ea-8e9c-7b9ac84c8a7d.jpg)

**Comment by andywang425** [comment]
奖品信息和弹幕口令任意一个匹配了都会抛弃

**Comment by wulifuji** [comment]
希望可以把屏蔽词的框改为`富文本`框，可拉伸的那种。
附上一些屏蔽词吧：`测试,钓鱼,炸鱼,test,写真,自拍,照片,素颜`

抽到不少自拍、写真，还有女装大佬的，我都无语了。

**Comment by wulifuji** [comment]
> 希望可以把屏蔽词的框改为`富文本`框，可拉伸的那种。
> 附上一些屏蔽词吧：`测试,钓鱼,炸鱼,test,写真,自拍,照片,素颜`
> 
> 抽到不少自拍、写真，还有女装大佬的，我都无语了。

养眼啊😁👌

**Comment by andywang425** [comment]
> 希望可以把屏蔽词的框改为`富文本`框，可拉伸的那种。
> 附上一些屏蔽词吧：`测试,钓鱼,炸鱼,test,写真,自拍,照片,素颜`
> 
> 抽到不少自拍、写真，还有女装大佬的，我都无语了。

我打算改成点击按钮跳出弹窗，让用户在窗口中编辑屏蔽词。  
刚刚在README里加了一个正则样例，`/(([^十百千万拾佰仟01234][零0oO]|^[零0oO])[\.点、。][01234一二三四零壹贰叁肆Oo])|[01234一二三四零壹贰叁肆Oo][分]|(图片|照片|写真|相片|排位|车位|一起|代打|好友|专属头衔|素颜照|卸妆照|美照|皮肤|空气)/`，如果有人想用自己复制就行。  
这些屏蔽词就不加到默认值里了，也不是每个人都不想抽自拍、写真和女装大佬的照片🤣

**Comment by X-Holmes** [comment]
> 也不是每个人都不想抽自拍、写真和女装大佬的照片

这句话笑死我了🤣

想问一下`/图片|照片|写真/`这样把多个词放到一个正则表达式里，跟直接写成很多条`图片,照片,写真`用逗号隔开，有什么区别吗？比如说哪一种写法效率更高？

还有催更一下未中奖自动取关功能🥺谢谢🥰

**Comment by andywang425** [comment]
> 想问一下`/图片|照片|写真/`这样把多个词放到一个正则表达式里，跟直接写成很多条`图片,照片,写真`用逗号隔开，有什么区别吗？比如说哪一种写法效率更高？

没啥区别，效率上的差异完全可以忽略不计。  
> 还有催更一下未中奖自动取关功能🥺谢谢🥰

这个功能等国庆放假了再开始写。

**Comment by X-Holmes** [comment]
感谢大佬假期加班！5.2版本已更新，有一些看起来有点弱智的问题_(:з」∠)_

> 新功能：检测到未中奖后自动取关发起抽奖的UP，上传天选数据至直播间个人简介，从个人简介获取天选数据，隐身入场。

1. 自动取关功能是依赖于【上传天选数据至直播间个人简介】的吗？
(因为整段都是逗号导致我有些迷惑，主要是不知道上传的是什么数据。我看文档理解的是只上传了天选房间列表，并没有上传抽奖、取关等功能所需要的缓存数据，所以应该是不依赖的吧……)
2. 隐身入场是指进房间时不会显示“xx用户进入了直播间”吗？
该功能依赖于【上传天选数据至直播间个人简介】的吗？
3. 选择【轮询直播间获取天选时刻数据】并不勾选【上传天选数据至直播间个人简介】，
与选择【轮询直播间获取天选时刻数据】并勾选【上传天选数据至直播间个人简介】的区别是什么？
（个人理解是对此直播间的脚本运行效果来说没有区别，只是为了辅助其他账号挂脚本时使用该直播间的数据？
4. 选择【从直播间的个人简介获取天选时刻数据】并且保证填写的直播间正在运行脚本并且脚本配置为【上传天选数据至直播间个人简介】，
与在本直播间选择【轮询直播间获取天选时刻数据】并勾选【上传天选数据至直播间个人简介】的抽奖效果是否是相同的？
(除了不需要重复轮询房间)

**Comment by andywang425** [comment]
1.不依赖  
2.是的，这样就没人知道你进直播间了。不依赖【上传天选数据至直播间个人简介】。  
3.区别就在于上不上传天选数据，运行效果没区别。你的理解是对的。  
4.这两种情况下最终参与的抽奖效果应该是几乎一样的。前提是上传数据的间隔，保存天选数据的多少，以及获取数据的间隔这几个设置必须要合理，否则可能会漏掉一部分抽奖。  

感觉这文档得再改改，现在的文档确实有点难理解。

**Comment by andywang425** [comment]
> 哪里有抢天选，没看到啊

所有和抽奖有关的功能从版本7开始均已删除。
