### ISSUE TITLE
插件里的获取小心心的调用优先级很低吗？

### ISSUE THREAD

**Issue by ddd-zero** [andywang425/BLTH#200]
### 描述bug

我挂在云服务器上的，2h4g。服务器满载挖矿的时候，插件的每日打卡都可以正常运行（就是每天发言续一下牌子的100经验），但获取小心心却一直不行。每次都是我看到今天没有获取到小心心，然后就连接上服务器，这时候那个获取小心心的任务就开始跑了（浏览器右边就开始提示获取小心心），有时候就算登进去也不行，还得手动刷新一下页面才开始获取。
最开始的时候，我以为是页面挂的太久了可能不自动获取，所以我找了一个每隔几个小时就自动刷新网页的插件挂上，但依旧还是正常打卡都是运行的，唯独小心心获取不到，好像自动送礼物也不行。
为了排除是Chrome浏览器的问题，我下过别的Chrome套壳浏览器都是这样，也尝试停止其他插件，还是这样。也尝试过把油猴换成其他的，也没有用。

### 重现bug

重现概率很大

### 预期行为

无

### 运行日志

现在日志没了，要是有需要 过几天看看吧

### 操作系统

winserve2012

### 浏览器

Chrome 最新

### 用户脚本管理器

最新

### 挂机助手版本

最新

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by XiaoMiku01** [comment]
https://github.com/XiaoMiku01/bili-live-heart 请

**Comment by andywang425** [comment]
> https://github.com/XiaoMiku01/bili-live-heart 请

这广告打得妙啊。

要不你就试试楼上这位大佬的项目吧。当然如果能获取到日志的话请发出来让我看看。

**Comment by DEabcdp** [comment]
> > https://github.com/XiaoMiku01/bili-live-heart 请
> 
> 这广告打得妙啊。
> 
> 要不你就试试楼上这位大佬的项目吧。当然如果能获取到日志的话请发出来让我看看。

还必须关注某up，夹带私货成这样魔怔了

**Comment by XiaoMiku01** [comment]
> > > https://github.com/XiaoMiku01/bili-live-heart 请
> > 
> > 
> > 这广告打得妙啊。
> > 要不你就试试楼上这位大佬的项目吧。当然如果能获取到日志的话请发出来让我看看。
> 
> 还必须关注某up，夹带私货成这样魔怔了

爱用用，不用滚蛋，老子写的，什么傻卵东西😅

**Comment by andywang425** [comment]
请问5.8版本中现在还存在这个现象吗？我在前几个版本有对小心心获取做过优化。
