### ISSUE TITLE
报错：获取粉丝勋章列表失败 用户不存在

### ISSUE THREAD

**Issue by Tinpa** [andywang425/BLTH#201]
### 描述bug

报错 “获取粉丝勋章列表失败............”

### 重现bug

1.进入直播间
2.显示 红色气泡“获取粉丝勋章列表失败 用户不存在”（见截图）

### 预期行为

显示 “获取粉丝勋章列表失败”，似乎b站改了点东西？因为我使用的一个另一个插件（切换粉丝勋章）也报错了，该插件的报错：

 ![屏幕快照 2022-01-01 16 14 23](https://user-images.githubusercontent.com/36250538/147846898-413d3f8c-71fa-4aa7-aebb-5cdb0bf05f23.png)

但是b站自带的垃圾切换功能是能读到我的粉丝勋章的：

![屏幕快照 2022-01-01 16 14 35](https://user-images.githubusercontent.com/36250538/147846910-29bdaa97-8e74-4dd9-bd9f-bca53f1ff46f.png)

### 截图

![屏幕快照 2022-01-01 16 20 13](https://user-images.githubusercontent.com/36250538/147846920-9312bbb6-fdf9-43c3-b9ad-4c352da817c3.png)

### 运行日志

[live.bilibili.com-1641025407669.log](https://github.com/andywang425/BLTH/files/7797488/live.bilibili.com-1641025407669.log)

### 操作系统

macOS High Sierra 10.13.6

### 浏览器

Chrome 96.0.4664.110（正式版本） (x86_64)

### 用户脚本管理器

tampermonkey 4.13

### 挂机助手版本

5.7.9.4

### 网络情况

好

### 其他浏览器插件/脚本

-

**Comment by glyceryl** [comment]
我今天也出现了这个问题😢

**Comment by hejanward** [comment]
+1

**Comment by benaify** [comment]
+1

**Comment by yeqianjia** [comment]
+1

**Comment by keivnluo6191** [comment]
Duplicate of #202

**Comment by dandandashi** [comment]
+1
