### ISSUE TITLE
运行时报错+小心心无法获取

### ISSUE THREAD

**Issue by Jethary** [andywang425/BLTH#204]
### 描述bug

自动运行时报错：【获取粉丝勋章列表失败】【用户不存在】【部分功能无法运行】。并且小心心的获取无法正常运行

### 重现bug

1、一打开/刷新直播间即报错；
2、小心心获取在包裹无/有物品时均不能正常获取；

### 预期行为

正常运行

### 截图

![屏幕截图 2022-01-03 200745](https://user-images.githubusercontent.com/73475802/147928633-7a245c7d-a6d2-4b2f-b284-f40442214f06.png)

### 运行日志

![image](https://user-images.githubusercontent.com/73475802/147928724-dc600573-650d-415c-90d7-24f7e9994308.png)

### 操作系统

Windows 10

### 浏览器

Chrome 96.0.4664.110

### 用户脚本管理器

暴力猴v2.13.0

### 挂机助手版本

5.7.9.4

### 网络情况

好

### 其他浏览器插件/脚本

无

### 其他

无

**Comment by Tinpa** [comment]
与issue #201  #202 #205 问题相似，解决方法见：pull request https://github.com/andywang425/BLTH/pull/203
