### ISSUE TITLE
获取粉丝勋章数据失败

### ISSUE THREAD

**Issue by ZhuAoA** [andywang425/BLTH#205]
### 描述bug

打开直播间后，先弹出“正在获取礼物 / 用户 / 账号 / 粉丝勋章数据...”，然后弹出“获取粉丝勋章列表失败 用户不存在 部分功能将无法正常运行”，再弹出“CACHE载入成功”，显示“[粉丝牌打卡] 粉丝勋章列表未被完全获取，暂停运行”，最后显示“[小心心] 开始获取今日小心心”。 

### 重现bug

并没有进行任何操作，在安装好脚本后就无法获取粉丝勋章列表。重新安装脚本也不行。

### 预期行为

打开直播间弹出“正在获取礼物 / 用户 / 账号 / 粉丝勋章数据...”后，在各个直播间打卡签到。
显示“[小心心] 开始获取今日小心心”，快速获取小心心。

### 截图

![755d8cc14b0fb9f5e2c94c161bbb554](https://user-images.githubusercontent.com/97110321/148079301-b0ac0be0-6e21-4a93-a79f-8bb0988b485c.png)
![b04e9676a1ccdf2514b3c5fdf8ecd28](https://user-images.githubusercontent.com/97110321/148079308-c9865590-6dd3-4278-85cc-1183de80cbca.png)

### 运行日志

![78c2966dd2620d367fa660a3cd8206e](https://user-images.githubusercontent.com/97110321/148079501-586c243d-720e-4417-8987-847f64ef679d.png)

### 操作系统

Windows 10

### 浏览器

Chrome 96.0.4664.110

### 用户脚本管理器

Tampermonkey v4.13

### 挂机助手版本

5.7.9.4

### 网络情况

好

### 其他浏览器插件/脚本

IDM Integration Module

**Comment by WenjingBao** [comment]
我也遇到了同样的情况
十二月月中还一切正常，上周左右开始就不能弹幕打卡了
运行日志
![image](https://user-images.githubusercontent.com/25001011/148302284-ebe8e781-fda9-4ab8-9306-d73c5d79bfe1.png)

操作系统
Windows 10 专业版 19044.1415

浏览器
Chrome 96.0.4664.110

用户脚本管理器
Tampermonkey v4.13

挂机助手版本
5.7.9.4

网络情况
好

其他浏览器插件/脚本
网页限制解除(改) v4.4.6
AdBlock Plus

**Comment by Tinpa** [comment]
与issue #201 #202 #204  问题相似，解决方法见：pull request https://github.com/andywang425/BLTH/pull/203
