### ISSUE TITLE
每日任务的分享视频无法完成

### ISSUE THREAD

**Issue by yuijker** [andywang425/BLTH#206]
### 描述bug

在每日任务设置中启用分享视频选项并未完成任务，右上角会一直弹出错误。

### 重现bug

1.在每日任务设置中启用分享视频选项
2.等待脚本自动执行任务。
3.脚本产生错误。

### 预期行为

分享视频这一主站任务始终无法完成，且右上角持续因自动执行任务而持续提醒。

### 截图

![屏幕截图 2022-01-12 223714](https://user-images.githubusercontent.com/72558803/149162133-6aa2f21f-b059-4f83-975f-93ccf05ea9be.png)

### 运行日志

[BLTH][22:42:23:992] DailyReward.share: API.DailyReward.share: 
{code: 137004, message: '账号异常，操作失败', ttl: 1}
userscript.html?name…34-01b0b9ae0569:173 [BLTH][22:42:23:995] toast-caution: [自动每日奖励][每日分享] 出错 undefined
﻿
​

### 操作系统

Windows 10

### 浏览器

edge 97.0.1072.55

### 用户脚本管理器

tampermonkey 4.13.6138

### 挂机助手版本

5.7.9.4

### 网络情况

好

### 其他浏览器插件/脚本

AdGuard

### 其他

此现象为偶发，今日（1月13日）无法复现了。

**Comment by andywang425** [comment]
账号异常，感觉可能和你的号有关系。  
如果只是偶发的话就不修复了。
