### ISSUE TITLE
拥有大量粉丝勋章时无法一次性获取完小心心

### ISSUE THREAD

**Issue by kawaiishiro** [andywang425/BLTH#207]
### 描述bug

我现在有144个牌子,当我有24个牌子时，所有小心心可以在五分钟内全部获取，但现在每次都只能有23个小心心，要再等五分钟才能满

### 重现bug

正常挂机

### 预期行为

正常5分钟内获取24个小心心

### 截图

<img width="106" alt="截屏2022-01-20 下午2 42 57" src="https://user-images.githubusercontent.com/98079313/150288213-64af3819-f670-4954-a561-8a9c642dacce.png">

### 运行日志

无特殊通知

### 操作系统

mac os 

### 浏览器

Chrome 97.0.4692.71

### 用户脚本管理器

Tampermonkey beta

### 挂机助手版本

5.7.9.4

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
这个我尽力找找原因吧，因为小心心相关的代码是从其他作者那来的。  
请问获取小心心的过程中有没有报错？目前已知在部分情况下获取小心心时会报错，错误提示可能是“分区数据错误”。

**Comment by kawaiishiro** [comment]
貌似修好了呢

**Comment by andywang425** [comment]
是吗，不过我貌似没改过小心心相关的代码诶 . . .
那就这样吧。
