### ISSUE TITLE
粉絲牌打卡有特定直播間自動發送失敗

### ISSUE THREAD

**Issue by EVOLUTION-CIAO** [andywang425/BLTH#208]
### 描述bug

直播間11588230，14917277

### 重现bug

打開直播頁面
粉絲勛章自動打卡-黑名單模式
自動簽到失敗

### 预期行为

打開直播頁面
粉絲勛章自動打卡-黑名單模式
自動簽到失敗

### 运行日志

未找到，只有小心心獲取錯誤的日誌

### 操作系统

win10

### 浏览器

Opera GX

### 用户脚本管理器

Tampermonkey 4.13.6138

### 挂机助手版本

	5.7.9.4

### 网络情况

一般

### 其他浏览器插件/脚本

插件-Bilibili-Evolved

**Comment by andywang425** [comment]
收到，之后会做一下测试。

**Comment by andywang425** [comment]
今天测试了一下，发现这两位的直播间我是天天都在打卡，我自己都忘了（笑）。
但一切正常，并没有什么问题。请先更新到最新版，然后提供一下控制台日志。找不到相关日志的话可以在粉丝牌打卡结束后提交所有的控制台日志。

**Comment by EVOLUTION-CIAO** [comment]
> 今天测试了一下，发现这两位的直播间我是天天都在打卡，我自己都忘了（笑）。 但一切正常，并没有什么问题。请先更新到最新版，然后提供一下控制台日志。找不到相关日志的话可以在粉丝牌打卡结束后提交所有的控制台日志。
![Snipaste_2022-01-23_19-46-39](https://user-images.githubusercontent.com/97382367/150677161-7212b53c-ff76-4025-911a-92f0b780f295.png)
![Snipaste_2022-01-23_19-46-46](https://user-images.githubusercontent.com/97382367/150677172-3e2cfda9-77c6-455b-b6e3-8324972f0b81.png)
![image](https://user-images.githubusercontent.com/97382367/150677209-303e6ef8-b188-45f8-bda7-40f3bc27db34.png)
剛更新到5.7.9.5還是這樣

**Comment by EVOLUTION-CIAO** [comment]
> 收到，之后会做一下测试。



> 今天测试了一下，发现这两位的直播间我是天天都在打卡，我自己都忘了（笑）。 但一切正常，并没有什么问题。 请先更新到最新版，然后提供一下控制台日志。 找不到相关日志的话可以在粉丝牌打卡结束后提交所有的控制台日志。



> > 今天测试了一下，发现这两位的直播间我是天天都在打卡，我自己都忘了（笑）。 但一切正常，并没有什么问题。 请先更新到最新版，然后提供一下控制台日志。 找不到相关日志的话可以在粉丝牌打卡结束后提交所有的控制台日志。
> > ![Snipaste_2022-01-23_19-46-39](https://user-images.githubusercontent.com/97382367/150677161-7212b53c-ff76-4025-911a-92f0b780f295.png)
> > ![Snipaste_2022-01-23_19-46-46](https://user-images.githubusercontent.com/97382367/150677172-3e2cfda9-77c6-455b-b6e3-8324972f0b81.png)
> > ![image](https://user-images.githubusercontent.com/97382367/150677209-303e6ef8-b188-45f8-bda7-40f3bc27db34.png) 剛更新到5.7.9.5還是這樣

Snipaste_2022-01-23_19-46-39
Snipaste_2022-01-23_19-46-46
image
剛更新到5.7.9.5還是這樣

**Comment by EVOLUTION-CIAO** [comment]
> 今天测试了一下，发现这两位的直播间我是天天都在打卡，我自己都忘了（笑）。 但一切正常，并没有什么问题。 请先更新到最新版，然后提供一下控制台日志。 找不到相关日志的话可以在粉丝牌打卡结束后提交所有的控制台日志。

Snipaste_2022-01-23_19-46-39
Snipaste_2022-01-23_19-46-46
image 剛更新到5.7.9.5還是這樣

**Comment by EVOLUTION-CIAO** [comment]
> 今天测试了一下，发现这两位的直播间我是天天都在打卡，我自己都忘了（笑）。 但一切正常，并没有什么问题。请先更新到最新版，然后提供一下控制台日志。找不到相关日志的话可以在粉丝牌打卡结束后提交所有的控制台日志。

![image](https://user-images.githubusercontent.com/97382367/150677361-a76b177c-c921-4e39-a666-8c7
![Snipaste_2022-01-23_19-46-39](https://user-images.githubusercontent.com/97382367/150677380-066d0238-99d3-4ad9-96be-13313a515d12.png)
![Snipaste_2022-01-23_19-46-46](https://user-images.githubusercontent.com/97382367/150677382-1bd825e2-910d-4a27-8be2-3ef08ac98e48.png)
273b20267.png)
還是這樣

**Comment by EVOLUTION-CIAO** [comment]
> 今天测试了一下，发现这两位的直播间我是天天都在打卡，我自己都忘了（笑）。 但一切正常，并没有什么问题。请先更新到最新版，然后提供一下控制台日志。找不到相关日志的话可以在粉丝牌打卡结束后提交所有的控制台日志。

![image](https://user-images.githubusercontent.com/97382367/150677486-a78f75e1-cdad-4e35-822a-dd8fa11b3df5.png)
![image](https://user-images.githubusercontent.com/97382367/150677489-f163feaa-5a82-4369-b6e3-be8b0b4f4305.png)
![image](https://user-images.githubusercontent.com/97382367/150677492-7d68f175-b6e0-46cf-9d70-965229a73c83.png)
還是這樣

**Comment by andywang425** [comment]
我忘记`k`对应的是哪种错误了。有几种可能：
1.你在黑名单里
2.弹幕内容不合适
3.ip问题，貌似海外用户发的弹幕是显示不出来的，不知道B站对台湾有没有相关限制。

获取小心心出错很正常，我也天天出错但不知道怎么改。
