### ISSUE TITLE
出现关于网络错误的提示

### ISSUE THREAD

**Issue by wulifuji** [andywang425/BLTH#21]
![image](https://user-images.githubusercontent.com/61496038/94354883-07349f80-00b2-11eb-8525-3fe90a4a7ef7.png)

在打开直播间的一段时间后会出现这样的提示，请问其他人有无这样的情况？

**Comment by andywang425** [comment]
如果网络没问题的话，那就是被B站风控了。过一段时间会恢复，或者换个ip。  
可以尝试将【请求间隔】【天选检查房间间隔】调高，【检查房间最大数量】调低。
