### ISSUE TITLE
直播加载失败

### ISSUE THREAD

**Issue by MaxwellXiao** [andywang425/BLTH#212]
### 描述bug

开启脚本后直播间大概率不能加载出来，而后直播间显示“status:21001 直播时空次元异常，正在努力恢复中”

### 重现bug

1.本机（联想小新 Pro-13IML 2019）大概率复现，重开浏览器无效，重启电脑无效。
2.另一台机子（联想R7000P 2020）也有此情况，使用不多，但也经常复现。

### 预期行为

正常加载直播间

### 截图

![图片](https://user-images.githubusercontent.com/47251656/150641247-af649c57-3de2-4bf7-8f9a-809e8e0bfb5c.png)

![图片](https://user-images.githubusercontent.com/47251656/150641280-80bb9e57-06cc-45f1-8b1e-26c67377d1c5.png)

### 运行日志

![图片](https://user-images.githubusercontent.com/47251656/150641462-bf0bf9f2-63c2-4123-a03f-9b1711cfb149.png)

### 操作系统

Windows 10 21H1（操作系统内部版本 19043.1466）

### 浏览器

Firefox 96.0.2

### 用户脚本管理器

Tampermonkey 4.13.6136

### 挂机助手版本

5.7.9.5

### 网络情况

好

### 其他浏览器插件/脚本

Bilibili Evolved 2.0.8，uBlock Origin，pakku（https://github.com/xmcp/pakku.js），隐私獾

**Comment by andywang425** [comment]
请问是否开启了本脚本的拦截直播流功能？
![image](https://user-images.githubusercontent.com/56548456/150666733-d4fceea8-da13-4c51-bffc-b984f70df8c9.png)

**Comment by MaxwellXiao** [comment]
没开，重置设置再加载也不行

**Comment by andywang425** [comment]
请提供控制台日志。

**Comment by MaxwellXiao** [comment]
[console-export-2022-1-27_15-25-1.txt](https://github.com/andywang425/BLTH/files/7948402/console-export-2022-1-27_15-25-1.txt)
请用json解析

**Comment by andywang425** [comment]
已下载，因为含有敏感信息所以删除了。

**Comment by andywang425** [comment]
日志中没看出来什么问题。有试过把其他的脚本、浏览器拓展全关掉然后单独运行BLTH吗？

**Comment by MaxwellXiao** [comment]
额，电脑出了点问题，被安全擦除了，复现不了了，但是我估计就是其他插件和脚本有影响。我自己close吧。新年快乐！
