### ISSUE TITLE
自动投币时获取投稿视频被拒绝

### ISSUE THREAD

**Issue by kkkkkkmmmmm** [andywang425/BLTH#213]
### 描述bug

自动投币时获取投稿视频被拒绝

### 重现bug

1.勾选自动投币
2.弹出黄色提示框：获取某uid的投稿视频被拒绝
3.进入个人空间看不到投稿视频，但下方的视频合集是正常的

### 预期行为

正常自动投币

### 截图

![QQ截图20220203130136](https://user-images.githubusercontent.com/74656166/152284162-cac091fa-6ea5-456d-82f1-3026578abe3d.png)

### 运行日志

一开始没开日志，不敢再重现了

### 操作系统

win 10

### 浏览器

firefox

### 用户脚本管理器

tampermonkey v4.13.6136

### 挂机助手版本

5.7.9.5

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by kkkkkkmmmmm** [comment]
大概一段时间后会恢复正常，能看到投稿视频了。但无法自动投币。

**Comment by kkkkkkmmmmm** [comment]
大概一段时间后会恢复正常，能看到投稿视频了。但无法自动投币。暂时先关了自动投币。

感谢脚本作者的辛勤付出。

**Comment by andywang425** [comment]
我有空的时候测试一下，这个功能挺久没维护了。

**Comment by kkkkkkmmmmm** [comment]
已解决
