### ISSUE TITLE
天选时刻自动用包裹中的b克拉购买粉丝勋章

### ISSUE THREAD

**Issue by lchypwx** [andywang425/BLTH#215]
### 描述

当前为“检测到有1级粉丝牌要求的天选后，如果没有该勋章，则自动用5B币充电购买再参加。”，建议新增自动使用包裹中的免费b克拉购买

**Comment by andywang425** [comment]
这个功能已经写好了，下个版本更新。

**Comment by lchypwx** [comment]
> 这个功能已经写好了，下个版本更新。

感谢
