### ISSUE TITLE
直播挂机助手实物抽奖无法获取登录状态导致抽奖失败

### ISSUE THREAD

**Issue by 1542155354** [andywang425/BLTH#216]
### 描述bug

直播挂机助手实物抽奖无法获取登录状态导致抽奖失败

### 重现bug

来回关闭开启后刷新脚本仍然无法自动实物抽奖

### 预期行为

进行实物抽奖

### 截图

![image](https://user-images.githubusercontent.com/58895795/155840436-902b5f0a-55f3-416b-bc46-37e0d0d64e96.png)

### 运行日志

不会。。。。。

### 操作系统

Windows 10

### 浏览器

谷歌

### 用户脚本管理器

油猴4.11

### 挂机助手版本

5.6

### 网络情况

好

### 其他浏览器插件/脚本

没有

### 其他

无

**Comment by andywang425** [comment]
已在新版本5.7.9.6中修复该问题。

**Comment by funnyyan** [comment]
> 已在新版本5.7.9.6中修复该问题。

没报错，但是获取不到实物抽奖，最近手机发布会比较多，可以多测试测试

**Comment by andywang425** [comment]
> 没报错，但是获取不到实物抽奖，最近手机发布会比较多，可以多测试测试 @andywang425

好，我有空测试一下。
