### ISSUE TITLE
有没有可能添加一个直播间签到的时候自动佩戴对应直播间的勋章

### ISSUE THREAD

**Issue by FztTony** [andywang425/BLTH#217]
### 描述

有的直播间要求>=n级牌子才能发言导致签到失败，这个功能能做吗

即把“手动发弹幕前自动佩戴当前房间勋章-一直自动佩戴”应用到直播间签到里

**Comment by andywang425** [comment]
可以。不过我想最好是签到前先找出哪些直播间有粉丝牌限制，然后仅在这些直播间打卡时佩戴勋章。频繁佩戴勋章可能导致风控。
