### ISSUE TITLE
APl.x.getAcclnfo 获取账号信息失败 请求被拦截 并且脚本重复运行多个

### ISSUE THREAD

**Issue by shoucandanghehe** [andywang425/BLTH#219]
### 描述bug

正常运行时报错`APl.x.getAcclnfo 获取账号信息失败 请求被拦截`
然后会重复运行多个脚本

### 重现bug

进入直播间，等待

### 预期行为

脚本不会重复运行多个

### 截图

![image](https://user-images.githubusercontent.com/51957264/157091507-3e0ced7a-1978-4c54-9077-96e4ff61aa99.png)
![image](https://user-images.githubusercontent.com/51957264/157091584-ae9aa368-61cf-488b-a9c6-00deb06cfef8.png)

### 运行日志

![image](https://user-images.githubusercontent.com/51957264/157092016-896a6fbd-5574-42f4-81cb-36aaf42fb626.png)

### 操作系统

Windows11

### 浏览器

Chrome 98.0.4758.102

### 用户脚本管理器

tampermonkey 4.14

### 挂机助手版本

5.7.9.6

### 网络情况

好

### 其他浏览器插件/脚本

DD@Browser

**Comment by andywang425** [comment]
请问在关闭其他所有浏览器拓展，脚本的情况下单独运行BLTH仍会出现该问题吗？

**Comment by shoucandanghehe** [comment]
目前运行没有问题
我猜测可能是DD@Browser和BLTH短时间内向B站发送请求过多导致412风控（日志里可以看到
我认为可以针对412风控添加保护机制，请求412后延迟脚本的运行，不影响正常观看直播就行（

**Comment by andywang425** [comment]
这个功能已经有了，DDBrowser向B站发请求的频率不高应该也不会导致风控才对。。。

**Comment by shoucandanghehe** [comment]
![image](https://user-images.githubusercontent.com/51957264/160190604-7b4c6345-b968-4f61-b052-0d311c5930f3.png)
又出现了（
不过这次整个B站的视频和直播似乎都不能正常看了
不过奇怪的是同一个网络环境下的移动端没问题 pc清cache换浏览器都是爆炸

**Comment by andywang425** [comment]
已在6.1.3版本中修复该问题。

**Comment by Rinko4396** [comment]
> 

如果访问权限不足应该怎么办
