### ISSUE TITLE
从直播间22474988获取天选数据失败

### ISSUE THREAD

**Issue by gq20110204** [andywang425/BLTH#220]
### 描述bug

日志出现如下报错 去直播间的简介看了一下似乎也没有天选直播间数据 是不是这个功能不能用了
[天选时刻] 直播间22474988个人简介的数据格式不符合要求
TypeError: Cannot read properties of null (reading '1')

### 重现bug

勾选从直播间22474988的个人简介获取天选时刻数据

### 预期行为

正常从该直播间获取天选数据

### 运行日志

![image](https://user-images.githubusercontent.com/22221191/157225762-17b999a9-c114-45d5-b379-9fe871779da2.png)

### 操作系统

Windows Server 2019

### 浏览器

Chrome 98.0.4758.102

### 用户脚本管理器

Tampermonkey BETA v4.14.6152

### 挂机助手版本

5.7.9.6

### 网络情况

好

### 其他浏览器插件/脚本

应该没有

**Comment by andywang425** [comment]
这个功能能用，但是已经没必要用了，用awpush就行。
