### ISSUE TITLE
[非BUG]自动发送弹幕会发到另外一个房间

### ISSUE THREAD

**Issue by blmulang** [andywang425/BLTH#226]
### 描述bug

RT所述，自动发送弹幕会发到另外一个房间，设置的房间没有发送弹幕，发送内容也不是所设置的

### 重现bug

1.打开油猴和脚本后，自动运行，进入直播间；
2.滑到自动发送弹幕设置栏，发现设置好自动发送弹幕和房间号刷新后不会保存所设置的值就只能重新设置
3.重新填写设置后点立即发送弹幕就出现了bug图所示

### 预期行为

设置自动发送弹幕房间号和自动发送内容后，点立即发送会发送，只会在默认房间号发送默认弹幕内容，并没有发送设定值；

### 截图

![QQ截图20220319144825](https://user-images.githubusercontent.com/48040829/159111296-bd47cb53-9e6e-45d8-84d6-d5971d4a67fa.png)

### 运行日志

![image](https://user-images.githubusercontent.com/48040829/159111288-cbbc7e6f-4577-4725-95b0-bd11187ee7e5.png)

### 操作系统

Windows 10

### 浏览器

Cent Browser 4.3.9.248（正式版本）

### 用户脚本管理器

Tampermonkey 4.14

### 挂机助手版本

v5.7.9.7

### 网络情况

好

### 其他浏览器插件/脚本

ublock

**Comment by andywang425** [comment]
修改房间号之后要保存设置，可以点击控制面版上方的按钮或者在输入框内回车。多余的逗号建议删掉。

**Comment by blmulang** [comment]
> 修改房间号之后要保存设置，可以点击控制面版上方的按钮或者在输入框内回车。多余的逗号建议删掉。
原来是这样  感谢作者大佬~快关闭吧 阿巴阿巴
![32](https://user-images.githubusercontent.com/48040829/159112259-3e211aa6-8d08-46ec-8f3b-16033147a7c1.gif)
