### ISSUE TITLE
抽奖自动关注的up主少部分在"BLTH天选关注UP"分组, 大量在"默认分组"

### ISSUE THREAD

**Issue by FairyWorld** [andywang425/BLTH#227]
### 描述bug

- 已经勾上天选关注up移动到新的分组, 一开始的几个小时是正常的, 过了一段时间或者第二天"BLTH天选关注UP"分组不在增加，全部自动关注的用户放到了"默认分组"

- 有可能是网络异常或者接口请求太频繁导致的, 点击取消关注"BLTH天选关注UP"分组后(大概500个用户左右), 因为用户数太多导致取关太频繁接口异常, 点击头像卡片的关注按钮进入关注列表页, 关注的用户列表无法加载(api请求异常), 并且脚本也没有成功取消关注用户, 过一段时间就正常了。这段时间也在跑直播间抽奖脚本, 可能拿不到关注列表全部存放到了"默认分组"

- 希望加入天选关注移动到自定义分组, 或者批量取关指定分组用户的功能

### 重现bug

没有任何操作

### 预期行为

抽奖自动关注的用户全部在"BLTH天选关注UP"分组里

#### 关注分组变成默认分组
![image](https://user-images.githubusercontent.com/32956212/159127255-96d59d4e-0a93-49b3-baa5-5c507c0c0fc6.png)
![image](https://user-images.githubusercontent.com/32956212/159127264-e23c3296-9e3c-4e3e-a75b-02b28fbae682.png)

#### 批量取关后关注列表异常
![image](https://user-images.githubusercontent.com/32956212/159128051-1e9fb627-9d85-4231-9960-4ce6173f00a3.png)

### 运行日志

没有BLTH日志
![image](https://user-images.githubusercontent.com/32956212/159127967-bb609559-fac0-4fd8-ab04-9e457c626997.png)

### 操作系统

win11

### 浏览器

Microsoft Edge 99.0.1150.30 

### 用户脚本管理器

Tampermonkey4.14

### 挂机助手版本

5.7.9.7 和前面1-2个小版本都是

### 网络情况

好

### 其他浏览器插件/脚本

Bilibili Evolved

### 其他

 希望加入天选关注移动到自定义分组, 或者批量取关指定分组用户的功能

**Comment by FairyWorld** [comment]
> ### 描述bug
> * 已经勾上天选关注up移动到新的分组, 一开始的几个小时是正常的, 过了一段时间或者第二天"BLTH天选关注UP"分组不在增加，全部自动关注的用户放到了"默认分组"
> * 有可能是网络异常或者接口请求太频繁导致的, 点击取消关注"BLTH天选关注UP"分组后(大概500个用户左右), 因为用户数太多导致取关太频繁接口异常, 点击头像卡片的关注按钮进入关注列表页, 关注的用户列表无法加载(api请求异常), 并且脚本也没有成功取消关注用户, 过一段时间就正常了。这段时间也在跑直播间抽奖脚本, 可能拿不到关注列表全部存放到了"默认分组"
> * 希望加入天选关注移动到自定义分组, 或者批量取关指定分组用户的功能
> 
> ### 重现bug
> 没有任何操作
> 
> ### 预期行为
> 抽奖自动关注的用户全部在"BLTH天选关注UP"分组里
> 
> ### 截图
> #### 关注分组变成默认分组
> ![image](https://user-images.githubusercontent.com/32956212/159127255-96d59d4e-0a93-49b3-baa5-5c507c0c0fc6.png) ![image](https://user-images.githubusercontent.com/32956212/159127264-e23c3296-9e3c-4e3e-a75b-02b28fbae682.png)
> 
> #### 批量取关后关注列表异常
> ![image](https://user-images.githubusercontent.com/32956212/159128051-1e9fb627-9d85-4231-9960-4ce6173f00a3.png)
> 
> ### 运行日志
> 没有BLTH日志 ![image](https://user-images.githubusercontent.com/32956212/159127967-bb609559-fac0-4fd8-ab04-9e457c626997.png)
> 
> ### 操作系统
> win11
> 
> ### 浏览器
> Microsoft Edge 99.0.1150.30
> 
> ### 用户脚本管理器
> Tampermonkey4.14
> 
> ### 挂机助手版本
> 5.7.9.7 和前面1-2个小版本都是
> 
> ### 网络情况
> 好
> 
> ### 其他浏览器插件/脚本
> Bilibili Evolved
> 
> ### 其他
> 希望加入天选关注移动到自定义分组, 或者批量取关指定分组用户的功能

关注列表异常可能是取关太频繁被b站限制了ip或者设备, 手机是正常的

**Comment by andywang425** [comment]
移动分组太频繁了确实容易导致失败，暂时没有很好的解决办法。

> + 希望加入天选关注移动到自定义分组, 或者批量取关指定分组用户的功能

我最近比较忙，可能没空去做这个功能，我想可以留给本项目的Contributors去完成。

**Comment by ZiuChen** [comment]
> * 希望加入天选关注移动到自定义分组, 或者批量取关指定分组用户的功能

批量取关可以用这个工具 [`BiliBiliToolPro`](https://github.com/RayWangQvQ/BiliBiliToolPro)

**Comment by zjqwtm543** [comment]
> * 的

提一嘴，似乎是B站会对太频繁的操作直接拒绝，5秒内操作10个关注还是可以的。
