### ISSUE TITLE
"老板大气！点点红包抽礼物"弹幕文本意外出现并且发送在错误的直播间

### ISSUE THREAD

**Issue by FairyWorld** [andywang425/BLTH#228]
### 描述bug

1. 配置了参与天选和红包抽奖配置
2. 在已下播或者轮播的直播间挂机, 弹幕列表一直每隔1-2分钟出现自己发送的"老板大气！点点红包抽礼物"的弹幕，但是我并没有配置这个文本的弹幕(粉丝勋章打卡自定义弹幕为"打卡"), 不知道为什么会发送这个弹幕?
3. 并且该弹幕只有自己的账号可见，我用小号(没有开启BLTH脚本)也挂在相同的直播间，大号右侧的显示了很多条"老板大气！点点红包抽礼物"的弹幕，但是在同一直播间小号看不见大号发送的这个弹幕

### 重现bug

配置了粉丝勋章打卡弹幕为"打卡"，和参与天选和红包抽奖配置，必重现

### 预期行为

1. 当前直播间因为没有正在直播或者抽奖，不会发送"老板大气！点点红包抽礼物"弹幕
2. "老板大气！点点红包抽礼物"弹幕文本不知为何出现
3. 如果该弹幕是抽奖发送的弹幕，应该在对应的抽奖直播间出现不应该在当前直播间，并且别人应该也能看见不是只有自己可以看见

### 截图

![image](https://user-images.githubusercontent.com/32956212/159144256-9dbdc140-59da-46c4-b049-cd13967d6e26.png)

### 运行日志

无错误日志

### 操作系统

win11

### 浏览器

Microsoft Edge 99.0.1150.30

### 用户脚本管理器

Tampermonkey4.14

### 挂机助手版本

5.7.9.7

### 网络情况

好

### 其他浏览器插件/脚本

Bilibili Evolved

**Comment by andywang425** [comment]
这条弹幕出现在挂机的直播间说明你被风控了，关掉红包抽奖歇会吧。

**Comment by FairyWorld** [comment]
> 这条弹幕出现在挂机的直播间说明你被风控了，关掉红包抽奖歇会吧。
下面4个抽奖都取消了，为什么还是会出现这个弹幕
![image](https://user-images.githubusercontent.com/32956212/159144913-11556e88-aa59-47aa-95eb-3b77077ca5ea.png)
![image](https://user-images.githubusercontent.com/32956212/159144920-71dcde53-f9c4-414e-8517-2290eacf813e.png)

**Comment by andywang425** [comment]
？关掉红包抽奖呀，你去关别的抽奖干嘛。

**Comment by FairyWorld** [comment]
> ？关掉红包抽奖呀，你去关别的抽奖干嘛。

已解决
