### ISSUE TITLE
直播间 已关注标签出错

### ISSUE THREAD

**Issue by soyuzom** [andywang425/BLTH#23]
最近几个版本，开启后，已关注的直播间，【粉丝团】变成【关注】，就是【隐藏窗口和提示信息】旁边的标签按钮

**Comment by X-Holmes** [comment]
可能是你开了【隐身入场】，B站就不知道你是不是已关注了。

**Comment by soyuzom** [comment]
> 可能是你开了【隐身入场】，B站就不知道你是不是已关注了。

哈哈哈，原来如此！
