### ISSUE TITLE
天选时刻勾选启用awpush显示连接已关闭导致无法参与天选

### ISSUE THREAD

**Issue by Misaka1096** [andywang425/BLTH#230]
### 描述bug

天选时刻勾选启用awpush显示连接已关闭导致无法参与天选

### 重现bug

同上

### 预期行为

无

### 截图

![QQ截图20220324165931](https://user-images.githubusercontent.com/102289137/159883485-4beb5ed7-e21c-47f4-bc91-8494e7f61b2a.jpg)

### 运行日志

VM981:13 [BLTH][17:13:54:501] XHR出错: 
Array(2)
0: {GM: true, anonymous: true, method: 'GET', url: 'https://andywang.top:3001/api/v1/notice', headers: {…}, …}
1: {readyState: 4, responseHeaders: '', status: 408, statusText: 'Failed to fetch', DONE: 4, …}
length: 2
lastIndex: (...)
[[Prototype]]: Array(0)

### 操作系统

WIN11

### 浏览器

Chrome 99.0.4844.82 64位

### 用户脚本管理器

油猴4.15

### 挂机助手版本

5.7.9.7

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
可能是服务器崩了，等我或者运维上线看一眼。

**Comment by andywang425** [comment]
确实崩了，暂时先关服一段时间吧，我找找原因。

**Comment by Misaka1096** [comment]
> 确实崩了，暂时先关服一段时间吧，我找找原因。

辛苦大佬早日修复了，顺便问问有没有解决红包抽奖功能总是触发风控的办法

**Comment by wind00012345** [comment]
> 

风控是什么样子的？我都是一直没反应，抽不了红包

**Comment by Misaka1096** [comment]
> > 
> 
> 风控是什么样子的？我都是一直没反应，抽不了红包
参考https://github.com/andywang425/BLTH/issues/228效果，具体表现为虽然显示成功参加抽奖但几乎抽不中，我停了一两天又能抽中了。
目前可以抽，今天发现抽奖红包位置移动到天选的地方了可能是这个原因？
