### ISSUE TITLE
咸鱼

### ISSUE THREAD

**Issue by yyzuuz** [andywang425/BLTH#231]
### 描述bug

请问现在直播红包抽取还能用吗，今天好像改位置了，脚本也没用

### 重现bug

请问现在直播红包抽取还能用吗，今天好像改位置了，脚本也没用

### 预期行为

请问现在直播红包抽取还能用吗，今天好像改位置了，脚本也没用

### 截图

![image](https://user-images.githubusercontent.com/89638524/160080852-ab607721-8832-4ea9-9893-dd0330858738.png)

### 运行日志

![image](https://user-images.githubusercontent.com/89638524/160081804-e3367eba-3c7c-42e3-939a-9cb54021b1cc.png)

### 操作系统

windows 10

### 浏览器

99.0.4844.82

### 用户脚本管理器

v4.14

### 挂机助手版本

v5.7.9.7

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
好，有空我测试一下。
