### ISSUE TITLE
关于脚本依赖加载失败的反馈

### ISSUE THREAD

**Issue by bear239510** [andywang425/BLTH#232]
### 描述bug

使用Tampermonkey不显示面板按钮（控制台日志在后面有）
使用暴力猴加载脚本显示脚本依赖加载失败。

### 重现bug

1. 我使用另一台电脑脚本运行正常
2. 我使用我平常练习编程的笔记本出现上述问题

### 预期行为

使用Tampermonkey未加载面板按钮

### 截图

![图片](https://user-images.githubusercontent.com/102409574/160232186-b2243afa-35e9-4e1c-b259-00d7f82550b8.png)

### 运行日志

控制台日志：
@require: couldn't load @require from URL 'https://cdn.jsdelivr.net/gh/andywang425/BLTH@dac0d115a45450e…3f3e17acd4328ab581d0514/assets/js/library/Ajax-hook.min.js': timed out 21380717:13:1037
@require: couldn't load @require from URL 'https://cdn.jsdelivr.net/gh/andywang425/BLTH@d810c0c54546b88addc612522c76ba481285298d/assets/js/library/decode.min.js': timed out 21380717:13:1037
@require: couldn't load @require from URL 'https://cdn.jsdelivr.net/gh/andywang425/BLTH@f50572d570ced20…cc77fe6a0853a1deed3671/assets/js/library/bliveproxy.min.js': timed out 21380717:13:1037
@require: couldn't load @require from URL 'https://cdn.jsdelivr.net/gh/andywang425/BLTH@5c63659de1ebf53…cf04d2554b725c83e/assets/js/library/BilibiliAPI_Mod.min.js': timed out 21380717:13:1037
@require: couldn't load @require from URL 'https://cdn.jsdelivr.net/gh/andywang425/BLTH@4368883c643af57c07117e43785cd28adcb0cb3e/assets/js/library/layer.min.js': timed out 21380717:13:1037

### 操作系统

Windows 10

### 浏览器

Firefox 98.0.2

### 用户脚本管理器

Tampermonkey 4.15.6154

### 挂机助手版本

5.7.9.7

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by ZiuChen** [comment]
我觉得是网络问题导致的

**Comment by andywang425** [comment]
试试看`cdn.jsdelivr.net`这个网站能不能ping通，应该是连不上这个网站导致依赖没加载出来。

**Comment by bear239510** [comment]
> 试试看`cdn.jsdelivr.net`这个网站能不能ping通，应该是连不上这个网站导致依赖没加载出来。

显示请求超时，确实连不上

**Comment by andywang425** [comment]
这个只能你自己想办法解决了，只要加载出来一次就行，之后运行时会有缓存。

**Comment by bear239510** [comment]
好的谢谢
