### ISSUE TITLE
[红包抽奖] 增加抽奖次数上限的设置项（?）

### ISSUE THREAD

**Issue by wind00012345** [andywang425/BLTH#234]
### 描述

描述中的风险较高是指这个吗?是不是这个号再也中不了了？
能不能设置抽奖次数上限后停止抽奖？

**Comment by wind00012345** [comment]
指标中的

**Comment by andywang425** [comment]
如果在你挂着脚本的直播间出现了这条弹幕，那就是黑了。
> 描述中的风险较高是指这个吗?是不是这个号再也中不了了？

一段时间内中不了。把礼物送给自己的大号直播间可能导致无法提现。

> 能不能设置抽奖次数上限后停止抽奖？

以后也许会有这个功能吧。

**Comment by andywang425** [comment]
以后可能会实现issue标题所说的特性。

**Comment by LiaN123456789** [comment]
我试了一下 昨天还不行 今天就可以了 好像每天抽红包有数量限制 直播间人说20个最多 也不知道到底是多少 我今天抽了54电池的礼物

**Comment by LiaN123456789** [comment]
> 

刚刚又能抢到了 啊这，是不是抢红包有CD时间阿
