### ISSUE TITLE
【弹幕修改】弹幕池匹配；保留弹幕属性

### ISSUE THREAD

**Issue by RunFasterThanAnyone** [andywang425/BLTH#235]
### 描述

在一些热门直播间，底端弹幕量非常大，在正中间从下面一直铺到上面，刚好把画面中间的人挡完了。就算开半屏弹幕也没用，开半屏弹幕就是下半屏底端弹幕，上半屏滚动弹幕，还是把中间全挡完了。

不知道这个功能好不好做，作者辛苦了

**Comment by andywang425** [comment]
已经有该功能了。
![image](https://user-images.githubusercontent.com/56548456/160732049-773caa00-1a95-4b54-ba14-fa3db45967b0.png)

**Comment by ToumaLover** [comment]
> 已经有该功能了。 ![image](https://user-images.githubusercontent.com/56548456/160732049-773caa00-1a95-4b54-ba14-fa3db45967b0.png)

使用您的设置会将所有弹幕更改为红色并将大小改为1.2倍的底端弹幕；请问可以麻烦您增加匹配弹幕的更多方式吗？比如本issue需要的弹幕池匹配。
在测试过程中发现修改弹幕的环节会强制更改颜色而且没有保留原颜色的选项（删除颜色一栏之后会有缺省值#FF000），希望您可以增加不修改颜色的选项。谢谢您！

**Comment by andywang425** [comment]
抱歉没能及时回复。
我觉得这个提议不错，以后会实现这个特性。
