### ISSUE TITLE
iPad加载脚本界面文字便乱码

### ISSUE THREAD

**Issue by KKingwang** [andywang425/BLTH#236]
### 描述bug

iPad加载脚本界面文字便乱码

### 重现bug

加载后直接乱码

### 预期行为

修复乱码

### 截图

![image](https://user-images.githubusercontent.com/53444337/161424245-4c03360f-c870-42b0-a3a8-832997fa74e0.png)

### 运行日志

iPad无法打开

### 操作系统

iPados15.4

### 浏览器

safari

### 用户脚本管理器

拦截100

### 挂机助手版本

5.7.9.7

### 网络情况

好

### 其他浏览器插件/脚本

无

### 其他

无

**Comment by andywang425** [comment]
我刚知道ios的safari能运行用户脚本，但我没ipad，所以修不了这个bug。
