### ISSUE TITLE
应援团/粉丝团自动打卡

### ISSUE THREAD

**Issue by PODF-x** [andywang425/BLTH#237]
### 描述

如题，可不可以增加应援团/粉丝团自动打卡的功能？
（因为打卡还有10的亲密度qwq）

**Comment by ToumaLover** [comment]
这个功能已经有了，在设置里的每日任务里

**Comment by andywang425** [comment]
确实，这个功能已经有了哦。

**Comment by PODF-x** [comment]
抱歉，没仔细看qaq，但是亲密度的值确实只有100而不是110.
