### ISSUE TITLE
红包抽奖开始检索能否检测到就抽奖？

### ISSUE THREAD

**Issue by wind00012345** [andywang425/BLTH#239]
### 描述

设置好后再刷新，到第一次抽红包要一个半小时，不能长时间挂机几乎等不到开始抽。能否改为一边检索一边抽？

**Comment by andywang425** [comment]
目前就是一边检索一边抽，长时间抽不了奖可能是Bug，我之后会测试。

**Comment by andywang425** [comment]
我不认为这是个bug，虽然有时候红包比较少，但真的不至于等一个半小时才开始抽。  
不清楚为什么你有这种情况。
