### ISSUE TITLE
自动关注up主，你是认真的？

### ISSUE THREAD

**Issue by sugarnine9** [andywang425/BLTH#24]
由于我使用之前没有认真阅读使用说明，给作者造成了非常不好的影响，我在此向作者郑重道歉，对不起！

**Comment by andywang425** [comment]
因为你开启了天选时刻功能。一些天选时刻的参加条件就是关注UP，所以我才写了保存白名单和取关的功能。

**Comment by andywang425** [comment]
README中也有提到参加天选时会关注很多UP：
> + 【保存当前关注列表为白名单】【取关不在白名单内的UP主】参加天选时会关注很多UP。可以在参加天选前点击【保存当前关注列表为白名单】，参与完天选后再点【取关不在白名单内的UP主】来清理关注列表。不建议频繁清理，可能会被风控。

请问你在使用前是否有阅读过呢？

**Comment by sugarnine9** [comment]
> 因为你开启了天选时刻功能。一些天选时刻的参加条件就是关注UP，所以我才写了保存白名单和取关的功能。

好的，非常感谢作者的回复，我没有认真仔细地阅读使用说明，是我的不对，在此向作者道歉，对不起！

**Comment by andywang425** [comment]
能理解就好😁
