### ISSUE TITLE
建议新增一项关于自动发弹幕的新功能

### ISSUE THREAD

**Issue by arisaka1991** [andywang425/BLTH#240]
### 描述

希望能新增一项可以在指定时间间隔下从文本库里随机发一条弹幕的功能，谢谢唷！

**Comment by arisaka1991** [comment]
我想，这相当于当前自动发弹幕功能的强化版，而它的用途也是广泛的。
对我而言，需要这个功能的原因是，我希望能在挂机的情况下，通过从文本库里随机选取几条弹幕（内容如：点点关注不迷路）然后自动发送出去以达到一种（我认为）更好的宣传效果。这种需求的产生是源于我想要自发地为一位新人主播在她的直播间里做下宣传，同时又希望增添一些新意。
虽然当前版本的插件已经实现了类似的功能，但在仔细了解了说明后，其似乎不具备我所描述的功能。
如有不当之处，请予指正，谢谢！

**Comment by andywang425** [comment]
可以，q群中也有群友表示这个功能有用。  
我自己也认为目前脚本的自动发弹幕过于简陋，无论是界面还是功能，以后会参考你所说的加以改进。

**Comment by andywang425** [comment]
兄弟你别关issue，等这个功能实现了（或者我放弃了）之后我来关闭就行。

**Comment by bk7170** [comment]
> 

不是有独轮车脚本吗
