### ISSUE TITLE
5.8版本开启后会导致B站直播卡顿

### ISSUE THREAD

**Issue by Hankanti** [andywang425/BLTH#243]
### 描述bug

更新到最新的5.8版本后进入直播界面大约10s左右整个网页会静止不动

### 重现bug

启用脚本进入直播页面10s左右网页开始静止不动，停用脚本正常观看。必定复现

### 预期行为

正常观看直播

### 截图

![Uploading jietu.jpg…]()
![Uploading jietu.jpg…]()

### 运行日志

无

### 操作系统

macOS  Monterey 12.3.1

### 浏览器

safari

### 用户脚本管理器

tampermonkey 4.13.6140

### 挂机助手版本

5.8

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by SaguruHakuba** [comment]
+1 同出现类似问题。
还出现了勋章打卡大量遗漏的现象。

**Comment by andywang425** [comment]
应该和 #246 是一样的问题。会尝试修复。
