### ISSUE TITLE
【天选移动UP至分组失败】一个问题

### ISSUE THREAD

**Issue by hellomgithub** [andywang425/BLTH#244]
### 描述bug

在天选参与成功后几秒内会于网页右上角弹出【移动up（uid=abcd）到分组【abcd】失败，请先公开关注后再添加分组】

### 重现bug

配置好脚本后进行天选

### 预期行为

大概就是【成功移动up（uid=abcd）至分组【abcd】】这样子的吧

### 截图

![image](https://user-images.githubusercontent.com/90130881/166106749-2a411b51-077f-46a7-8830-fab1cc2c3c49.png)
![image](https://user-images.githubusercontent.com/90130881/166106781-a429d1d8-4a01-43b4-aec4-3c94043720e3.png)

### 运行日志

无。

### 操作系统

Windows 10专业版 1909

### 浏览器

Microsoft Edge 100.0.1185.50 (正式版本) (64 位)

### 用户脚本管理器

Tampermonkey 4.16

### 挂机助手版本

5.8

### 网络情况

好

### 其他浏览器插件/脚本

已安装并在出现问题时启用：Tampermonkey、百度药丸、Similarsites、Imagus、全能复制、NDM下载插件 个人认为：没有

### 其他

就是，请问被风控了以后会怎么样？会怎么都抽不中礼物红包吗？或者怎么都抽不中天选？还有，被风控了以后怎么解除？

**Comment by andywang425** [comment]
【移动up（uid=abcd）到分组【abcd】通常是风控所导致的。  
风控分几种：
+ 访问被拒绝或者以其他形式出错（可以直接观察到）
+ 可以抽奖但无法中奖（只能靠推测）

触发风控后等待一段时间即可解除风控（半小时到几天不等）。如果是访问被拒绝导致的风控，也可通过更换ip解除。
