### ISSUE TITLE
可以加入直播抽红包的功能吗

### ISSUE THREAD

**Issue by Charlie-can** [andywang425/BLTH#245]
### 描述

![image](https://user-images.githubusercontent.com/45510526/166236947-21cd7bf3-d2cc-45ea-9d59-afd82e067893.png)

![OM4DBB}SE%W379GDS7G IO](https://user-images.githubusercontent.com/45510526/166236667-7c9366bf-407b-4849-a17f-b0a16fd1b0e4.png)

**Comment by andywang425** [comment]
该功能已存在。
