### ISSUE TITLE
直播助手打开时直播间报错，不能正常播放

### ISSUE THREAD

**Issue by ymy2078069948** [andywang425/BLTH#246]
### 描述bug

直播助手打开时直播间报错，错误代码：status:92002
但未打开该脚本时，直播能正常观看。
![image](https://user-images.githubusercontent.com/103635982/166405224-2833e4b2-2e70-4fc9-9d33-06d5beec5248.png)

### 重现bug

1.打开油猴哔哩哔哩直播间挂机助手。
2.点开任意哔站直播间。
3.无法加载  status:92002
![image](https://user-images.githubusercontent.com/103635982/166405237-e643b650-9b73-44bb-8b3b-a0074a784cbe.png)

### 预期行为

在打开挂机助手时也能正常观看

### 截图

![image](https://user-images.githubusercontent.com/103635982/166405214-aaf7c38d-539d-4fa9-a120-5c87790fe8ae.png)

### 运行日志

![image](https://user-images.githubusercontent.com/103635982/166405727-e493a055-f1dc-4aa0-b967-8ba308f3888b.png)
![image](https://user-images.githubusercontent.com/103635982/166405844-e684b9da-12a5-47f8-9ed7-1bbc382eb356.png)

### 操作系统

win7

### 浏览器

Google Chrome 101.0.4951.41（正式版本） （64 位）

### 用户脚本管理器

Tampermonkey 4.16

### 挂机助手版本

5.8

### 网络情况

一般

### 其他浏览器插件/脚本

未添加其他脚本

**Comment by ymy2078069948** [comment]
麻烦大佬了

**Comment by ymy2078069948** [comment]
![image](https://user-images.githubusercontent.com/103635982/166436768-5e0f9262-974d-4e36-bf43-9878586158a6.png)

**Comment by ymy2078069948** [comment]
应该和#243BUG一样

**Comment by andywang425** [comment]
感谢提供日志，会尝试修复这个Bug的。

**Comment by andywang425** [comment]
能否点进去图上标出的两处链接，再点一下左下角的美观输出，然后发一下截图？
![image](https://user-images.githubusercontent.com/56548456/167244316-89036eeb-6b50-468b-8415-67ca3c2cdfb6.png)

**Comment by ymy2078069948** [comment]
第一个（1772）
![image](https://user-images.githubusercontent.com/103635982/167256887-0cc2b04e-652a-4d62-b0f8-c7070950d657.png)
第二个（1784）
![image](https://user-images.githubusercontent.com/103635982/167256908-aa160035-9372-4afe-9aa6-8e470001e7a1.png)
麻烦了。

**Comment by andywang425** [comment]
研究了一下，暂时不清楚为什么会这样。明明是B站js出错怎么还和脚本的库搭上关系了...

**Comment by dong-jpg** [comment]
我这里实验的话在我自己电脑和我的服务器电脑可以取消掉【直播观看体验】中的如下三项来解决，你可以试试
1.拦截直播流
2.拦截直播观看数据
3.禁止p2p
![image](https://user-images.githubusercontent.com/53105222/167978585-a7753d66-f8cc-4aa8-970a-38f45a1c708e.png)
![image](https://user-images.githubusercontent.com/53105222/167978614-847c5b34-4785-4729-98b7-6fa7cb06d88c.png)
![image](https://user-images.githubusercontent.com/53105222/167978652-18dcd37c-44ab-48e9-8a27-d7dd739d0740.png)
