### ISSUE TITLE
【购买粉丝勋章】主播没勋章却开通充电的应对计划

### ISSUE THREAD

**Issue by URGERKING** [andywang425/BLTH#248]
下次更新记得写个如果主播没勋章却开通充电的应对计划

闲来无事在自己直播间试了一下

**Comment by andywang425** [comment]
让脚本在充电前检测一下该直播间是否有粉丝勋章？我觉得可以有，以后会做改进。

**Comment by URGERKING** [comment]
> 让脚本在充电前检测一下该直播间是否有粉丝勋章？我觉得可以有，以后会做改进。

对，突然发现我issue提的好抽象🤧亏你能理解
