### ISSUE TITLE
小心心获取寄了

### ISSUE THREAD

**Issue by IssacsChien** [andywang425/BLTH#249]
### 描述bug

小心心获取功能失效了😭😭

### 重现bug

None

### 预期行为

None

### 运行日志

None

### 操作系统

Windows10

### 浏览器

Google Chrome 版本 100.0.4896.60（正式版本） （64 位）

### 用户脚本管理器

Tampermonkey 4.16

### 挂机助手版本

5.8

### 网络情况

好

### 其他浏览器插件/脚本

None

**Comment by oolmfoo** [comment]
我也一樣

**Comment by Zothany** [comment]
好像没了快一周了，但我把插件关了看直播也没给小心心，是B站把小心心取消了吗？

**Comment by x60809x** [comment]
手机端看才有小心心

**Comment by andywang425** [comment]
大概率是因为你用了带广告拦截功能的浏览器拓展。下个版本中会添加相关的内置说明。
你在**其他浏览器插件/脚本**这里写无，请问你是真的除了油猴什么拓展都没开吗？**运行日志**呢？

**Comment by Zothany** [comment]
确实，反广告插件不拦直播间就可以恢复拿到小心心了，好在直播也没什么广告需要拦截

**Comment by IssacsChien** [comment]
> 大概率是因为你用了带广告拦截功能的浏览器拓展。下个版本中会添加相关的内置说明。 你在**其他浏览器插件/脚本**这里写无，请问你是真的除了油猴什么拓展都没开吗？**运行日志**呢？

收到👀

**Comment by Janet-Baker** [comment]
AdGuard 的 EasyPrivacy 选项屏蔽了 [logreporter.js](https://s1.hdslb.com/bfs/seed/blive/blfe-link-shortassets/dist/component.statistics/log-reporter.js)

把整个直播间加到白名单就好了。

**Comment by fizzz677** [comment]
我的也是，在浏览器插件里面把B站直播加入白名单还是不行

**Comment by URGERKING** [comment]
@andywang425 有没有兴趣做下新版小心心啊🤔

**Comment by andywang425** [comment]
> @andywang425 有没有兴趣做下新版小心心啊🤔

@URGERKING 有，但得等我考完期末考试。

**Comment by pooneyy** [comment]
今天小心心又不行了

**Comment by URGERKING** [comment]
> 今天小心心又不行了

[改版了](link.bilibili.com/p/eden/news#/newsdetail?id=2780),从此往后再无小心心

**Comment by nnryWniudnA** [comment]
> > @andywang425 有没有兴趣做下新版小心心啊🤔
> 
> @URGERKING 有，但得等我考完期末考试。

大佬辛苦了👍

**Comment by jjnnnh** [comment]
> > 今天小心心又不行了
> 
> [改版了](https://link.bilibili.com/p/eden/news#/newsdetail?id=2780),从此往后再无原来的小心心
https://github.com/andywang425/BLTH/issues/253
