### ISSUE TITLE
直播间22474988个人简介的数据格式不符合要求 Not a Array

### ISSUE THREAD

**Issue by wulifuji** [andywang425/BLTH#25]
![image](https://user-images.githubusercontent.com/61496038/96257217-8e5ba000-0fec-11eb-88eb-639a0c0f7ffe.png)

这合理吗？

**Comment by wulifuji** [comment]
咋回事儿，直播间上传的数据不对啊。。。

**Comment by andywang425** [comment]
更新一下脚本即可，刚刚在做新功能的测试。
