### ISSUE TITLE
awpush连接失败

### ISSUE THREAD

**Issue by saorzsa** [andywang425/BLTH#251]
### 描述bug

【awpush】链接失败，但是脚本显示配置成功，并没有搜索高热度房间。也没有开始红包抽奖

### 重现bug

1.选中【awpush】
2.刷新页面
3.显示【[awpush]连接已关闭，30秒后尝试重连】这之后就没反应了，日志显示是脚本载入配置成功，但没有开始抽红包也没有开始检索

### 预期行为

点击【awpush】，刷新后参加直播红包抽奖

### 截图

![image](https://user-images.githubusercontent.com/56815820/168527026-68ebd345-56e3-4649-846f-cdae8a728c3c.png)

### 运行日志

userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=bb7fe641-a6ee-4f81-80cf-4a0c34ebeccc:192 
        
       [BLTH][13:43:26:690] XHR出错: Array(2)0: {GM: true, anonymous: true, method: 'GET', url: 'https://andywang.top:3001/api/v1/notice', headers: {…}, …}1: {readyState: 4, responseHeaders: '', status: 408, statusText: 'Failed to fetch', DONE: 4, …}length: 2[[Prototype]]: Array(0)
MYERROR @ userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=bb7fe641-a6ee-4f81-80cf-4a0c34ebeccc:192

### 操作系统

windows 10

### 浏览器

Microsoft Edge 版本 101.0.1210.47 (正式版本) (64 位)

### 用户脚本管理器

Tampermonkey v4.16

### 挂机助手版本

5.8

### 网络情况

一般

### 其他浏览器插件/脚本

adguard

**Comment by acteds** [comment]
https://link.bilibili.com/p/eden/news#/newsdetail?id=2780
官方继续稀释难度了,我觉得没什么意义了

**Comment by saorzsa** [comment]
是我同时选中了【从高热度房间获取红包抽奖数据】斯密码森o(╥﹏╥)o

**Comment by andywang425** [comment]
昨晚BLTH-server又上线了，你再试试。
