### ISSUE TITLE
Api.getuserinfo获取用户信息失败

### ISSUE THREAD

**Issue by dbcliu** [andywang425/BLTH#252]
### 描述bug

打开所有直播页面都提示 Api.getuserinfo获取用户信息失败 。播放页面起初无控制面板按钮，后续会和issue 219一样反复运行多个脚本。控制台日志里出现三个404报错：
![图片](https://user-images.githubusercontent.com/32696644/168743094-f3a4c68e-429b-44b9-8341-7343695ffbe3.png)

### 重现bug

不明，Firefox 100环境，人在香港。清除缓存，仍然出现问题；**清除Cookie后正常。**

### 预期行为

正常加载脚本。

### 截图

![图片](https://user-images.githubusercontent.com/32696644/168743311-b46d1fba-d6fe-4f50-babb-8f83f820ea3e.png)

### 运行日志

![图片](https://user-images.githubusercontent.com/32696644/168743137-fd2360d2-7a79-4ee9-a1b2-a4810fece9ab.png)

### 操作系统

Windows 11

### 浏览器

Firefox 100.0.1

### 用户脚本管理器

Tampermonkey 4.17.6161

### 挂机助手版本

5.8

### 网络情况

好

### 其他浏览器插件/脚本

无，ublock已关闭

### 其他

前几天工作似乎是正常的，记不清那天开始出现问题的，大约两三天内。清除Cookie后问题解除，不知道怎么回事。

**Comment by andywang425** [comment]
不清楚，或许不是脚本的问题。

**Comment by dbcliu** [comment]
> 个人猜测：B站定时重置cookie

奇怪的是我网页上反复登陆没用，感觉不是b站清除了cookie而是api清除了？
