### ISSUE TITLE
表示小心心改版了 草

### ISSUE THREAD

**Issue by Malus-Mill** [andywang425/BLTH#253]
### 描述bug

小伙伴您好，小心心功能更新了哦，您可以查看公告内的规则哦：
链接https://link.bilibili.com/p/eden/news#/newsdetail?id=2780

### 重现bug

各位B站的UP主和用户，你们好。
 
为了给大家提供更有趣的直播互动体验，我们将在5月16日开始对粉丝团的部分功能做调整。你将看到一些全新的、有趣的直播互动玩法。调整详情如下，希望你能喜欢。
 
调整详情
1）小心心将在5月16日-5月22日期间暂停获取，在5月16日之前用户已获得的小心心不受影响可正常使用，请在23日之前尽快使用。
 
2）小心心将在5月23日起调整为直播间专属道具，即在A直播间获取的小心心只能在A直播间生效，同时不再作为礼物道具送出，主播将自动获得用户在本直播间内通过任务获取的小心心（用户与主播同时获得）。
 
3）粉丝团任务将于5月23日更新，会陆续提供更多与主播互动的玩法，并有更多手段获取小心心与主播亲密度。
 
附小心心更新之后获取方式
 
在已加入主播粉丝团的直播间中，当主播开播时，完成以下任务就能获得对应的小心心。
 
· 发送5条弹幕：+20小心心/弹幕
·  发送5个表情包：+20小心心/表情包
·  连续观看30分钟（累计）：+100小心心/5分钟
·  给主播点赞三次：+100小心心 
·  送100电池的礼物：+1小心心/1电池
·  分享5次直播间：+150小心心
 
新版小心心的有效期为自然周内生效，每周日24点清零。
目前仅支持移动端，仅能在勋章对应的直播间获得小心心，即在A主播直播间里加入粉丝团，需要在A直播间通过完成任务获得小心心，且仅能在A直播间生效。小心心能在直播间的互动玩法中消耗。

### 预期行为

小心心更新之后 ，加入粉丝团后在直播间内通过以下任务可以获得亲密度 
|1、给主播点赞三次：每次增加200亲密度，每天最多三次 
2、分享5次直播间：每次增加100亲密度，每天最多五次 
3、连续观看30分钟：完成后增加100亲密度，每天一次

### 运行日志

200X3+100X5+100=1200
亲密度满为1500

### 操作系统

WIN11 21H2 操作系统版本：22000.282

### 浏览器

Chrome 版本 95.0.4638.69（正式版本） （64 位）

### 用户脚本管理器

 Tampermonkey 4.13

### 挂机助手版本

5.7.9

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by Malus-Mill** [comment]
> 

大佬辛苦了；

**Comment by AnduinWrynn123** [comment]
大佬辛苦了👍

**Comment by jjnnnh** [comment]
> 等B站小心心玩法更新后会重写脚本获取小心心的部分。

小心心现在成了打榜工具，没亲密度
1-20级粉丝勋章有新任务加亲密度，希望替换掉
详见https://t.bilibili.com/663460997172822055

**Comment by Alanwun** [comment]
小心心更新之后 ，加入粉丝团后在直播间内通过以下任务可以获得亲密度

1、给主播点赞三次：每次增加200亲密度，每天最多三次

2、分享5次直播间：每次增加100亲密度，每天最多五次

3、连续观看30分钟：完成后增加100亲密度，每天一次

温馨提示：粉丝勋章21-40级无法通过完成任务提升等级，您可以通过投喂电池礼物、开通（续费）大航海、发送醒目留言提升航海亲密度，每日航海亲密度上限为25万。

By 客服

**Comment by Malus-Mill** [comment]
![image](https://user-images.githubusercontent.com/53999738/170272762-325f9917-892a-4a63-bbd7-531d4fc66236.png)
测试了一下那个分享的10分钟CD应该是全局CD，也就是说2个主播得100分钟才能分享完
——来自B站网友34406191

**Comment by Malus-Mill** [comment]
> > ![图片](https://user-images.githubusercontent.com/53999738/170272762-325f9917-892a-4a63-bbd7-531d4fc66236.png)测试一下那个人才应该一分钟分享CD的10分钟10到2个B站的主播分享CD10到2个B站4406199
> 
> 我去试一下、是单直播间CD10分钟、多个直播间切是可以的

。。。又试了一下、没CD。。。

**Comment by jjnnnh** [comment]
> > > ![图片](https://user-images.githubusercontent.com/53999738/170272762-325f9917-892a-4a63-bbd7-531d4fc66236.png)测试一下那个人才应该一分钟分享CD的10分钟10到2个B站的主播分享CD10到2个B站4406199
> > 
> > 
> > 我去试一下、是单直播间CD10分钟、多个直播间切是可以的
> 
> 。。。又试了一下、没CD。。。

https://github.com/XiaoMiku01/fansMedalHelper/commit/4a9eae7ace1d7a023600c45b32b7c3cd62f47a32

**Comment by DEabcdp** [comment]
为什么更新最新版本后，勾选了点赞分享直播间等没有作用呢？大家也是这样吗？
