### ISSUE TITLE
重新安装脚本后控制面板消失了

### ISSUE THREAD

**Issue by LS0123** [andywang425/BLTH#255]
### 描述bug

重新安装脚本后控制面板消失了，用alt+b也打不开

### 截图

![屏幕截图 2022-05-18 220324](https://user-images.githubusercontent.com/105799751/169060715-bc40592a-d642-410c-beec-7e619a21a2c9.png)
![屏幕截图 2022-05-18 220308](https://user-images.githubusercontent.com/105799751/169060799-aa5af79b-aa30-40c4-ab65-4f11e224b0ff.png)

### 运行日志

wu

### 操作系统

Windows 11

### 浏览器

microsoft edge

### 用户脚本管理器

Tampermonkey 4.13

### 挂机助手版本

5.8

### 网络情况

好

### 其他浏览器插件/脚本

没有

### 其他

No response

**Comment by andywang425** [comment]
我猜可能是依赖没成功获取，试试看你能不能打开这个链接 https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js

如果不能，挂个代理运行一次脚本把依赖获取到即可。

**Comment by worldpresident** [comment]
解决方法有用的 感谢！

**Comment by Sternstundens** [comment]
你好，我目前还是打不开这个插件，我想问一下，就是你发的链接，我打不开，挂了代理（vpn）我也无法打开。

**Comment by andywang425** [comment]
> 你好，我目前还是打不开这个插件，我想问一下，就是你发的链接，我打不开，挂了代理（vpn）我也无法打开。

还有个办法，把链接中的cdn替换成fastly。
或者你也可以等更新，明天或者后天就更新了。

**Comment by Sternstundens** [comment]
好的，链接替换了可以打开，感谢，我等明后天吧
