### ISSUE TITLE
导入数据成功但是脚本无法使用

### ISSUE THREAD

**Issue by peanutjian** [andywang425/BLTH#256]
### 描述bug

无法点击同意 

### 重现bug

重新安装后

### 预期行为

wu

### 截图

![image](https://user-images.githubusercontent.com/84620057/169626778-7550c798-7514-41f7-93bc-aeea3737fd8a.png)

### 运行日志

![image](https://user-images.githubusercontent.com/84620057/169626839-3db681ca-618f-48ef-b9de-8e6c33cebf99.png)

### 操作系统

win10

### 浏览器

铬101.0.1210.47

### 用户脚本管理器

油猴4.16

### 挂机助手版本

5.8

### 网络情况

一般

### 其他浏览器插件/脚本

wu

**Comment by peanutjian** [comment]
补充
![image](https://user-images.githubusercontent.com/84620057/169629160-129ae208-cf4f-4b86-8275-8b592cf375a8.png)

**Comment by andywang425** [comment]
![image](https://user-images.githubusercontent.com/56548456/169809695-2d6797d4-94c3-41b7-99e8-e21033d48114.png)
奇怪，你这里居然报错缺少油猴的内置函数`GM_setValue`，但4.16版本的油猴不可能没这个函数。
暂时不清楚怎么解决。

**Comment by andywang425** [comment]
我今天又进来看了一眼，原来是你把`GM_setValue`换成了`cdn.jsdelivr.net`，改回去就行。
![image](https://user-images.githubusercontent.com/56548456/170811593-283f898e-a0c6-4322-9320-bb41dc829deb.png)
