### ISSUE TITLE
建议增加对当前直播间的半小时状态监测问题处理

### ISSUE THREAD

**Issue by ljhmily** [andywang425/BLTH#259]
### 描述

当前直播间，会监测直播过程是否有键鼠操作，若无，则半小时会自动暂停播放，这对于后台直播听声音的很不友好，也只有B站会这么搞。建议增加对当前直播间的半小时状态监测问题处理

**Comment by andywang425** [comment]
开启了`屏蔽挂机检测`后还是会这样吗？
