### ISSUE TITLE
已关注的主播关注按钮应该是粉丝团但是显示的是关注按钮

### ISSUE THREAD

**Issue by NeroArc** [andywang425/BLTH#26]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README。  
**描述bug**  
简要描述所遇到的bug
其实已经关注了主播，但是页面会显示未关注状态。
**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. 启动插件
2. 打开已关注主播直播间

**预期行为**  
简要描述进行以上操作后预期的脚本行为

**截图**  
如果可以，请提供有关截图  
![image](https://user-images.githubusercontent.com/49861997/96874261-8302eb80-14a8-11eb-99b8-cc25208cbcbb.png)

**运行日志**  
控制台中出现的日志或错误提示。  
可以截图或者直接复制。  

**使用环境:**
 - 浏览器: 搜狗浏览器
 - 浏览器版本: 10.0.0.33218
 - 脚本的版本: 最新版本
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 无
 - bug出现时间: 每时每刻

**其他**  
若您有其他想要补充的内容，请在此说明

**Comment by NeroArc** [comment]
> ### 在反馈bug之前，请确保你已经认真阅读了本项目的README。
> **描述bug**
> 简要描述所遇到的bug
> 其实已经关注了主播，但是页面会显示未关注状态。
> **重现bug**
> 说明您在进行了怎样的操作后出现了bug
> 
> 1. 启动插件
> 2. 打开已关注主播直播间
> 
> **预期行为**
> 简要描述进行以上操作后预期的脚本行为
> 
> **截图**
> 如果可以，请提供有关截图
> 
![image](https://user-images.githubusercontent.com/49861997/96874553-d1b08580-14a8-11eb-9946-a06e0852f0a4.png)

> 
> **运行日志**
> 控制台中出现的日志或错误提示。
> 可以截图或者直接复制。
> 
> **使用环境:**
> 
> * 浏览器: 搜狗浏览器
> * 浏览器版本: 10.0.0.33218
> * 脚本的版本: 最新版本
> * 网络情况(网速): 好
> * 其他浏览器插件/脚本: 无
> * bug出现时间: 每时每刻
> 
> **其他**
> 若您有其他想要补充的内容，请在此说明

**Comment by NeroArc** [comment]
没有显示脚本按钮是因为另一个页面已经启动了

**Comment by X-Holmes** [comment]
你截图要把脚本界面露出来啊，猜测可能是你开了隐身入场。具体可以看下最近几个已关闭的issue，有跟你类似的提问。
