### ISSUE TITLE
[Bug] 无法发送弹幕

### ISSUE THREAD

**Issue by RtYkk** [andywang425/BLTH#261]
### 描述bug

打开脚本后无法发送弹幕

### 重现bug

1、在弹幕发送框中输入弹幕
2、点击“发送”
3、输入框中内容消失，但是实际上没发出来

### 预期行为

正常发送弹幕

### 运行日志

       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'message')
    at 179.75c1a01a5bd04ddfcfe2.js:2:1225913
(匿名) @ 179.75c1a01a5bd04ddfcfe2.js:2
Promise.catch(异步)
(匿名) @ 179.75c1a01a5bd04ddfcfe2.js:2
f @ vendors.7e96dff79d9a2e0f3caa.js:2
(匿名) @ vendors.7e96dff79d9a2e0f3caa.js:2
(匿名) @ vendors.7e96dff79d9a2e0f3caa.js:2
(匿名) @ 179.75c1a01a5bd04ddfcfe2.js:2
e @ vendors.7e96dff79d9a2e0f3caa.js:2
lo @ 179.75c1a01a5bd04ddfcfe2.js:2
n.sendDanmaku @ 179.75c1a01a5bd04ddfcfe2.js:2
n.onKeyDown @ 179.75c1a01a5bd04ddfcfe2.js:2
qt @ vendors.7e96dff79d9a2e0f3caa.js:2
n @ vendors.7e96dff79d9a2e0f3caa.js:2
o._wrapper @ vendors.7e96dff79d9a2e0f3caa.js:2
179.75c1a01a5bd04ddfcfe2.js:2 

### 操作系统

Windows 10

### 浏览器

Microsoft Edge 版本 101.0.1210.53 (正式版本) (64 位)

### 用户脚本管理器

Tampermonkey v4.16.1

### 挂机助手版本

5.8.1

### 网络情况

好

### 其他浏览器插件/脚本

无，都关了

### 其他

之前从来没遇到过相同问题，就更新了最新版之后就炸了。

**Comment by andywang425** [comment]
>    Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'message')
at 179.75c1a01a5bd04ddfcfe2.js:2:1225913

你给出的这些日志是B站js的报错。

你有没有开启`检查弹幕是否发送成功`这个功能？刚刚更新了`5.8.2`版本。你可以先更新试试。

**Comment by andywang425** [comment]
已确认存在该Bug，下个版本修复。
