### ISSUE TITLE
自动完成点赞、分享直播间，观看 30 分钟直播的任务改为白名单或黑名单匹配

### ISSUE THREAD

**Issue by ToumaLover** [andywang425/BLTH#264]
### 描述

目前的“自动完成点赞、分享直播间，观看 30 分钟直播的任务。”功能似乎是对所有直播间生效的；
请求将它们功能的开启合并入有粉丝牌直播间的弹幕打卡中，以方便用户进行更精细的控制。
谢谢！

**Comment by andywang425** [comment]
我个人认为没什么用，点赞分享观看不会影响什么。  
粉丝牌打卡做了黑白名单是因为曾经有一段时间B站规定粉丝牌必须要暗掉超过一定天数才能删除，所以做了这个功能。

**Comment by Only-Mio** [comment]
> 我个人认为没什么用，点赞分享观看不会影响什么。 粉丝牌打卡做了黑白名单是因为曾经有一段时间B站规定粉丝牌必须要暗掉超过一定天数才能删除，所以做了这个功能。

我个人也是很希望有黑白名单过滤，我开启自动完成点赞然后暗掉的粉丝牌都亮了，点赞好像也算是发弹幕
希望能优化，非常感谢~

**Comment by ToumaLover** [comment]
> > 我个人认为没什么用，点赞分享观看不会影响什么。 粉丝牌打卡做了黑白名单是因为曾经有一段时间B站规定粉丝牌必须要暗掉超过一定天数才能删除，所以做了这个功能。
> 
> 我个人也是很希望有黑白名单过滤，我开启自动完成点赞然后暗掉的粉丝牌都亮了，点赞好像也算是发弹幕 希望能优化，非常感谢~
手动点赞时客户端会自动发弹幕；而脚本的点赞是不会自动发弹幕的，牌子亮了是因为亲密度上涨，和以前送小心心类似

**Comment by agni-bumi** [comment]
> 我个人认为没什么用，点赞分享观看不会影响什么。 粉丝牌打卡做了黑白名单是因为曾经有一段时间B站规定粉丝牌必须要暗掉超过一定天数才能删除，所以做了这个功能。

牌子是否点亮可以帮助区分最近常看主播，如果可以的话还是希望能有白名单功能😉；另外牌子太多好像也会影响打卡速度，有时没那么多时间挂
