### ISSUE TITLE
【实物抽奖】获取不到正在进行的抽奖

### ISSUE THREAD

**Issue by funnyyan** [andywang425/BLTH#265]
### 描述bug

显示[实物抽奖] 开始寻找可参加的抽奖，但找不到正在进行的抽奖

### 重现bug

无

### 预期行为

无

### 截图

![image](https://user-images.githubusercontent.com/31022404/170989708-bad32e11-186e-4646-b1e2-80ffb4d61850.png)

### 运行日志

![image](https://user-images.githubusercontent.com/31022404/170991135-1c5eea51-2ab5-4a0e-824a-f7edb77fb87f.png)

### 操作系统

win7

### 浏览器

Chrome 100.0.4896.127

### 用户脚本管理器

Tampermonkey 4.16

### 挂机助手版本

5.82

### 网络情况

好

### 其他浏览器插件/脚本

无

### 其他

希望能跟以前一样，日志会显示开始寻找、寻找结束xx时间后再次寻找。找到后显示抽奖的信息，在抽奖开始后自动参与，是否中奖

**Comment by andywang425** [comment]
请问能提供当时的控制台日志吗

**Comment by funnyyan** [comment]
当时的没截图。我刚又开了一下，跟当时的应该差不多
![image](https://user-images.githubusercontent.com/31022404/171021763-0cfa6ed3-7470-48df-85d3-1dd6dbd66f0a.png)
实物抽奖你那边正常吗，还是只是我的问题

**Comment by andywang425** [comment]
看来你没打开控制台日志。  
我也不清楚实物抽奖在检测到正在进行中的抽奖时能不能做出正确的反应，近期没测试过，实物抽奖太少了。
