### ISSUE TITLE
似乎“连续观看30分钟直播”功能没有成功增加亲密度

### ISSUE THREAD

**Issue by FztTony** [andywang425/BLTH#266]
### 描述bug

牌子数量47，间隔400ms，开脚本挂机一段时间后，所有牌子的亲密度都是1200/1500，并且分享和发弹幕都没有增加亲密度（说明缺的100亲密度是连续观看30分钟给的），重置直播任务，间隔改1000ms，刷新后挂机一段时间，仍然是1200/1500.

看了下一直在发送https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/X请求，这是观看直播的请求吗？是需要牌子数*30*间隔时间这么长的时间才能使得连续观看30分钟的效果生效吗

### 重现bug

-

### 预期行为

-

### 运行日志

-

### 操作系统

win10

### 浏览器

chrome 100.0.4896.127

### 用户脚本管理器

tampermonkey

### 挂机助手版本

5.8.2

### 网络情况

一般

### 其他浏览器插件/脚本

没有

**Comment by FztTony** [comment]
好像挂了更长时间ok了，是需要挂够30分钟吗

**Comment by andywang425** [comment]
`https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/X`这个是观看30分钟任务的心跳。需要挂够30分钟。  
最后一个粉丝勋章完成任务的时间应该是 30min + (粉丝勋章总数 - 1) * 间隔时间 + 网络请求消耗的时间

**Comment by GTVpigs** [comment]
> `https://live-trace.bilibili.com/xlive/data-interface/v1/x25Kn/X`这个是观看30分钟任务的心跳。需要挂够30分钟。 最后一个粉丝勋章完成任务的时间应该是 30min + （粉丝勋章总数 - 1） * 间隔时间 + 网络请求消耗的时间

不过小心心改版前的脚本版本也能完成观看30分钟的任务，而且消耗时间明显短与现在版本。

**Comment by bk7170** [comment]
我也有亲密度没加满的问题
