### ISSUE TITLE
网络正常 获取转盘数据和直播预约数据失败

### ISSUE THREAD

**Issue by xinglideli-1** [andywang425/BLTH#268]
### 描述bug

下面两个请求失败
1.https://gitee.com/java_cn/BILIBLI_RES/raw/master/HNPLATE/activities.json
2.https://gitee.com/java_cn/BILIBLI_RES/raw/master/HNPLATE/reserveSids.json

原因：
现在gitee公开仓库需要作者先进行申请，审核后才能开放匿名访问
导致这两个请求失败  code为 :451

### 重现bug

无操作

### 预期行为

。。

### 截图

![image](https://user-images.githubusercontent.com/10832590/171613749-a9b4331b-edcd-4c98-8e66-aa472027565a.png)

### 运行日志

2022/6/2 下午5:58:01
脚本载入配置成功
2022/6/2 下午5:58:08
[天选时刻] 开始获取关注分组信息
2022/6/2 下午5:58:09
[转盘抽奖] 获取转盘数据失败，请检查网络
2022/6/2 下午5:58:09
[预约抽奖] 获取直播预约数据失败，请检查网络
2022/6/2 下午5:58:10

### 操作系统

Windows 10

### 浏览器

360浏览器 版本号13.1.6000.0

### 用户脚本管理器

4.16

### 挂机助手版本

5.8.2

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
> 现在gitee公开仓库需要作者先进行申请，审核后才能开放匿名访问

还真是，我好久没用gitee了，现在才知道。
但是这个仓库的作者已经两个月没更新数据了，能访问也没用。得想想其他办法，要么就把这两个功能砍掉。
