### ISSUE TITLE
现在白名单只对打卡弹幕有效

### ISSUE THREAD

**Issue by YukinoYu1** [andywang425/BLTH#269]
### 描述

现在亲密度由打卡弹幕、点赞、分享、观看等几部分组成。
但除打卡弹幕外，其他途径似乎只能默认打开（除非不适用挂机功能）。
建议把白名单设置改成全局（同时对全部组成部分生效），或者增加选项，可以设置白名单生效范畴。
![image](https://user-images.githubusercontent.com/75308561/171878790-50e2dc39-b7f0-45f4-8b76-2c5d6faaa696.png)

**Comment by andywang425** [comment]
以后会改成全局的，虽然我自己不需要，但似乎还是有不少用户觉得有用 #264

**Comment by zx001115** [comment]
同求扩展白名单的控制范围，有些牌子不想继续刷亲密度了，但又不舍得删，如果没法单独控制点赞、分享、连续观看30分钟这些功能等白名单的话，还是会给这些牌子继续加亲密度，作者辛苦了。
