### ISSUE TITLE
一个真实事件的描述

### ISSUE THREAD

**Issue by wulifuji** [andywang425/BLTH#27]
**我关注的UP因为我奇妙地操作被清空了，幸好uid名单还在，自己整了个脚本给加回来了，希望大家不要学习。**

## 步骤如下：
1、在“编辑天选时刻白名单里加上一个“uid”，这个up主是你正在刷B站时而后台同时在挂着直播间的情况下想要关注的
2、保存,刷新
3、点那个红色的`取关不在白名单内的UP主`
4、刷的一下，全没了，全没了，心血啊！！！
5、但是，`编辑白名单`里的uid仍然在，只需要一点点魔法加回来就完事了

首先呢，我是个傻子；好吧，我是个傻子。

### 对作者的小建议：
希望作者能把天选需要关注的UP放在一个关注分组里
![image](https://user-images.githubusercontent.com/61496038/96974540-f578d780-154b-11eb-9cfe-829756cdf5a5.png)

新建一个抽奖关注分组，把那些天选的主播关注在一个不同的分组里，对睿智的我会更友好，也会对有更高的容错率吧

**Comment by andywang425** [comment]
你说的这个功能我正在写，以后会更新哒。  
还有根据你的描述，这个取关功能是不是存在bug？

**Comment by wulifuji** [comment]
> 你说的这个功能我正在写，以后会更新哒。
> 还有根据你的描述，这个取关功能是不是存在bug？

要不你也来试试？开心开心，哈哈  /暗示/

**Comment by andywang425** [comment]
> > 你说的这个功能我正在写，以后会更新哒。
> > 还有根据你的描述，这个取关功能是不是存在bug？
> 
> 要不你也来试试？开心开心，哈哈 /暗示/

我自己试过好多次了但没出过bug。说实话我还希望出次bug，否则我都不知道问题在哪

**Comment by wulifuji** [comment]
> > > 你说的这个功能我正在写，以后会更新哒。
> > > 还有根据你的描述，这个取关功能是不是存在bug？
> > 
> > 
> > 要不你也来试试？开心开心，哈哈 /暗示/
> 
> 我自己试过好多次了但没出过bug。说实话我还希望出次bug，否则我都不知道问题在哪

啊，我又把关注清空了

**Comment by wulifuji** [comment]
> > > > 你说的这个功能我正在写，以后会更新哒。
> > > > 还有根据你的描述，这个取关功能是不是存在bug？
> > > 
> > > 
> > > 要不你也来试试？开心开心，哈哈 /暗示/
> > 
> > 
> > 我自己试过好多次了但没出过bug。说实话我还希望出次bug，否则我都不知道问题在哪
> 
> 啊，我又把关注清空了

![image](https://user-images.githubusercontent.com/61496038/96981364-3116a000-1552-11eb-99ca-718de7c08fa5.png)
悲催

**Comment by andywang425** [comment]
刚刚更新的新版本中加了把参加天选时关注的UP移到一个分组的功能，取关的bug也修好了。

**Comment by 715670119** [comment]
> 刚刚更新的新版本中加了把参加天选时关注的UP移到一个分组的功能，取关的bug也修好了。
![`0N 8M8G1 ~H(J1UQY6PI6C](https://user-images.githubusercontent.com/35725595/98223400-fdde0300-1f8c-11eb-88f7-0aba74b2690f.png)
显示：天选检查出错，请检查网络
但是我网络是正常的

**Comment by andywang425** [comment]
> > 刚刚更新的新版本中加了把参加天选时关注的UP移到一个分组的功能，取关的bug也修好了。
> > ![`0N 8M8G1 ~H(J1UQY6PI6C](https://user-images.githubusercontent.com/35725595/98223400-fdde0300-1f8c-11eb-88f7-0aba74b2690f.png)
> > 显示：天选检查出错，请检查网络
> > 但是我网络是正常的

被B站风控了，过半小时会恢复，不想等的话换一个ip也行。把请求间隔调高一点能避免这种情况。  
因为脚本无法判断错误原因是因为网络问题还是被风控，所以被风控时也会显示请检查网络。
