### ISSUE TITLE
请问这种情况是怎么了，已经持续至少一周了

### ISSUE THREAD

**Issue by zhuwei956** [andywang425/BLTH#273]
### 描述bug

![image](https://user-images.githubusercontent.com/65883119/173188794-6b68236c-5604-4b44-ae22-70b8980c1b2c.png)
如图，直播间挂机在挂一会后，会出现多个同时运行的界面

### 重现bug

直播间挂一会

### 预期行为

刚开始正常，后来越开越多

### 截图

![image](https://user-images.githubusercontent.com/65883119/173188823-38ca14cd-8da9-4773-a6e9-60529c9d7842.png)

### 运行日志

日志也是多个
![image](https://user-images.githubusercontent.com/65883119/173188871-fee3f5a4-f98a-4745-9c86-38f6fa3a35a3.png)

### 操作系统

win10

### 浏览器

Microsoft Edge 版本 102.0.1245.33 (正式版本) (64 位)

### 用户脚本管理器

Tampermonkey  大小: 4.4 MB    版本4.16.1

### 挂机助手版本

5.8.2

### 网络情况

好

### 其他浏览器插件/脚本

无，以前是正常的，就是最近出现的

### 其他

我想知道到底是我设置错了什么还是什么其他的原因导致的这个问题，想知道如何解决

**Comment by andywang425** [comment]
暂时不清楚怎么解决，我没遇到过这种情况。

**Comment by dong-jpg** [comment]
我之前用Edge也是这样，然后我换成百分浏览器和猫眼浏览器就没再出这个问题，大盖是Edge自己的刷新或者保活策略的问题吧，你可以换其他浏览器试下

**Comment by lormalduss** [comment]
浏览器edge101.0.1210.53(正式版本) (64 位)
其余信息一致  也是最近开始出现同样问题
没有动任何设置
同时进入直播间会报错  API.getuserinfo获取用户信息失败请先登录

**Comment by andywang425** [comment]
我在edge 102.0.1245.44上测试了下，脚本都没加载出来，而且无论开不开脚本控制台都好几个报错，大概是B站的问题？
![image](https://user-images.githubusercontent.com/56548456/174446216-41c0db36-f3a0-4b92-8e93-ddb95661ce68.png)

**Comment by andywang425** [comment]
已在6.1.3版本中修复该问题。
