### ISSUE TITLE
监听弹幕池实现风控检测并自动暂停功能

### ISSUE THREAD

**Issue by ZiuChen** [andywang425/BLTH#274]
### 描述

挂机抽红包时经常会被风控，弹幕发到了挂机直播间里。
能否实现监听弹幕池内，在命中自己的ID与预设的风控弹幕内容后，自动暂停挂机行为，并且在指定时间后自动恢复呢？

**Comment by andywang425** [comment]
利用这个特性来实现该功能可能不是很合适，我更倾向于设置抽奖次数上限这种方式。

**Comment by Mishasama** [comment]
弹幕发到别的直播间里就是被风控？
这是只有自己才能看到的弹幕吗？貌似弹幕姬上并没有出现？

另外貌似我全程手动抽红包没用过脚本抽也有这种现象，但至少偶尔能中一个。而用了一天脚本反而是一个都没有中。感觉这个脚本现在肯定是缺了点什么东西被直接判定上了。
