### ISSUE TITLE
完成直播区任务无法获取全部亲密度

### ISSUE THREAD

**Issue by slatsyrc** [andywang425/BLTH#276]
### 描述bug

直播区任务完成后亲密度没加满，亲密度只能加到400-500，调整间隔时间均无效，脚本正常运行无报错，询问过客服账号状态，答复账号无异常，移动端手动操作也能正常加亲密度

### 重现bug

每天自动运行后都会出现，间隔时间从400ms调整到10000ms都无法正常增加亲密度

### 预期行为

我两个号相同脚本设置，小号60个牌子正常加，大号248个牌子加不满

### 截图

![image](https://user-images.githubusercontent.com/107987494/174980692-bc3823d5-ee23-4228-ba6e-4efbf0d97fa0.png)

### 运行日志

![image](https://user-images.githubusercontent.com/107987494/174979902-9d1f7bbd-0860-45ec-aea8-952a55b388b8.png)

### 操作系统

Windows11

### 浏览器

Chrome102.0.5005.115

### 用户脚本管理器

Tampermonkey4.9

### 挂机助手版本

5.8.2

### 网络情况

好

### 其他浏览器插件/脚本

无

### 其他

无

**Comment by dong-jpg** [comment]
这个我记得也是老毛病了，牌子太多了导致的，你可以试下我的方法，隔一段时间就刷新浏览器让脚本重新执行，这样大概率是可以全部打满的

**Comment by slatsyrc** [comment]
> 这个我记得也是老毛病了，牌子太多了导致的，你可以试下我的方法，隔一段时间就刷新浏览器让脚本重新执行，这样大概率是可以全部打满的

好像也不是很管用，我大概看了一下点赞分享那些都是只加了一次，还有其他解决方法吗
