### ISSUE TITLE
qq群没了 有新的吗

### ISSUE THREAD

**Issue by 1563652588** [andywang425/BLTH#277]
### 描述

rt

**Comment by andywang425** [comment]
会有的，下次更新脚本的时候会放出新的群号。

**Comment by MClark328** [comment]
有没有电报的呀。

**Comment by andywang425** [comment]
> 有没有电报的呀。

我记得有人建了一个非官方的tg群，但我不知道群号是多少

**Comment by andywang425** [comment]
5.8.3版本已更新，新群 [657763329](https://jq.qq.com/?_wv=1027&k=9refOc8c)

**Comment by NAGATOYUKl** [comment]
什么时候又炸了一次……刚刚才发现，还有新的么XD
