### ISSUE TITLE
bilibili

### ISSUE THREAD

**Issue by EdwardXiaoran** [andywang425/BLTH#28]

**Comment by EdwardXiaoran** [comment]
bilibili更新了，目前是每天给有牌子的直播间发一条弹幕就能获得100亲密度，是不是该考虑一下更新一下脚本了/滑稽
关于标题只有一个biilbili的问题，是我输完英文词组后敲enter的习惯导致了，懒得改了

**Comment by andywang425** [comment]
打卡弹幕的基础功能已经完成了，因为想再加点额外功能（自定义弹幕内容，随机抽取弹幕）所以会晚点更新。预计今明两天内搞定。

**Comment by caisezhaopian** [comment]
> 
> 
> 打卡弹幕的基础功能已经完成了，因为想再加点额外功能（自定义弹幕内容，随机抽取弹幕）所以会晚点更新。预计今明两天内搞定。

自动弹幕功能发现了，希望可以能打卡多个直播间，通过添加房间号或者直接打卡有粉丝牌的直播间的方式

**Comment by andywang425** [comment]
> > 
> 
> > 
> 
> > 打卡弹幕的基础功能已经完成了，因为想再加点额外功能（自定义弹幕内容，随机抽取弹幕）所以会晚点更新。预计今明两天内搞定。
> 
> 
> 
> 自动弹幕功能发现了，希望可以能打卡多个直播间，通过添加房间号或者直接打卡有粉丝牌的直播间的方式

最新版已经有这个功能了，在每日任务设置中开启粉丝勋章打卡弹幕即可。

**Comment by Dududade** [comment]
![2](https://user-images.githubusercontent.com/74051782/98456676-7cb88300-21bb-11eb-9169-709725fcfcc1.png)
小心心一秒全到手，就是我的小心心为啥都是一个一个的。。。。

**Comment by wmx20030618** [comment]
可以给打卡弹幕加个黑名单吗，这样方便删牌子
