### ISSUE TITLE
更新版本后无法使用脚本

### ISSUE THREAD

**Issue by Mars-LLL** [andywang425/BLTH#280]
### 描述bug

更新新版本之后无法使用脚本，无法打开控制面板，重新安装也无法使用

### 重现bug

更新后

### 预期行为

正常使用

### 截图

![1](https://user-images.githubusercontent.com/108523199/176877382-9dd36b4d-6a1f-48ae-aae0-ae063c28280b.png)
![2](https://user-images.githubusercontent.com/108523199/176877393-883cc381-2b6d-4a70-bf86-fbc807a5da33.jpg)

### 运行日志

无法找到有关BLTH的日记

### 操作系统

Windows 10

### 浏览器

搜狗浏览器 11.0.1.34700

### 用户脚本管理器

 Tampermonkey 4.8.14

### 挂机助手版本

5.8.3

### 网络情况

好

### 其他浏览器插件/脚本

无

### 其他

已尝试获取全部依赖

**Comment by andywang425** [comment]
首先根据README，我们不对 Tampermonkey 4.12 以下的版本做任何保证。
其次如果BLTH发出了这个提示的话，那说明你的浏览器的chromium版本小于85，已经是有点老了（至于为什么提示可以正常运行，这个是我判断不准确，我以为chromium45以上就能运行脚本了）。我的建议是直接用win10自带的edge，或者用chrome，国内的浏览器没啥好的。不想换浏览器的话就得看搜狗愿不愿意升级内核版本了。
![image](https://user-images.githubusercontent.com/56548456/176983491-bf7d8af0-c165-4cd4-bd08-e5c2482bdd36.png)

**Comment by Mars-LLL** [comment]
目前搜狗浏览器的UA为Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 SE 2.X MetaSr 1.0
升级油猴版本以及对脚本进行降级之后可以使用，有什么可以屏蔽脚本自动检测更新的方法吗？

**Comment by andywang425** [comment]
你最后一个能用的挂机助手版本是多少？

**Comment by Mars-LLL** [comment]
5.8.2，我更新了内测版的浏览器，现在UA为Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36 SE 2.X MetaSr 1.0

**Comment by andywang425** [comment]
可能是浏览器的关系，按理来说 Chrome/87.0.4280.66 是能正常运行脚本了
