### ISSUE TITLE
一个比较强烈的修改建议，它有可能对使用者造0~20元损失

### ISSUE THREAD

**Issue by futaojing** [andywang425/BLTH#282]
### 描述

“自动领取大会员权益“这个功能是默认打开的，至少我尝试了"重置所有设置为默认“
这个功能不应该默认打开，理由的话现在大会员包括4个卡券，分别是：
B币券（领取后30天内有效）
漫画福利券（领取后30天内有效）
会员购优惠券（领取后15天内有效）
会员购包邮券（领取后15天内有效）

重点就是会员购这两张券，已经从原来的30天改为15天了，对于经常进行会员购的用户，这个一般都是需要的时候才领取，否则会容易产生过期损失

因此强烈建议不要默认开启（新装用户很容易忘了改设置，也可能准备改设置但找设置项的时候已经来不及了）

**Comment by andywang425** [comment]
好的，已将这个功能默认关闭。
