### ISSUE TITLE
在某些直播间，脚本不运行

### ISSUE THREAD

**Issue by someash** [andywang425/BLTH#283]
### 描述bug

https://live.bilibili.com/76
在守望先锋联赛直播间脚本不运行

### 重现bug

直接链接进入，或者通过直播守望先锋区进入，都没有正常运行脚本

### 预期行为

正常运行

### 截图

![image](https://user-images.githubusercontent.com/32922655/177033218-eb28788d-1697-410f-9f02-f073e5c95599.png)

### 运行日志

![image](https://user-images.githubusercontent.com/32922655/177033338-9a9b9e26-090e-47b2-8e91-0cf9ec9d3189.png)

### 操作系统

windows11

### 浏览器

edge 103.0.1264.44 (正式版本) (64 位)

### 用户脚本管理器

Tampermonkey 4.16.1

### 挂机助手版本

5.8.3

### 网络情况

好

### 其他浏览器插件/脚本

无，但是有全局运行的Adguard

**Comment by asf00404** [comment]
+1   英雄联盟直播间也运行不了 https://live.bilibili.com/6

**Comment by andywang425** [comment]
感觉是B站又调整了什么东西，我看到连vue都用上了，暂时不知道怎么解决。

**Comment by TianQiBuTian** [comment]
看了下基本都是带有blanc地址的大概率不能正常运行（有活动页面以及直接打开含blanc的直播间链接均不正常）

**Comment by andywang425** [comment]
我好像明白了，真正的主页面（带播放器的那个小窗口）是个iframe，虽然Tampermonkey会向iframe中注入脚本，但是由于是在顶层窗口的`document-start`时注入的，iframe中很多东西都还没加载好，因此脚本就失效了。

**Comment by andywang425** [comment]
具体是什么时候注入的还有待考证，目前能确定的是在脚本的初始化函数运行之前等待几秒后脚本就能成功运行，但最早可以在什么时候开始执行还不清楚。

**Comment by andywang425** [comment]
找到了比较重要的一个标志，`window.BilibiliLive.UID`，DOM加载完成的时候`window.BilibiliLive`已经有了，但其中的数据还没加载完，等到`UID`不为`0`后加载脚本即可，问题解决。
