### ISSUE TITLE
启用检查弹幕会导致脚本界面消失

### ISSUE THREAD

**Issue by Mishasama** [andywang425/BLTH#286]
### 描述bug

由脚本添加的页面元素，如日志、控制面板等都无法显示了。
而且脚本功能似乎并没有在运行。但是多开页面会提示已经在其它页面运行。

### 重现bug

1. 激活“检查弹幕是否发送成功”
2. 刷新页面。

### 预期行为

一切正常

### 截图

界面消失截个屌图

### 运行日志

出现该问题后控制台没有该脚本相关的日志输出，完全没有。

### 操作系统

WIN10 20H2

### 浏览器

103.0.5060.114

### 用户脚本管理器

Tampermonkey v4.16.1

### 挂机助手版本

5.8.4

### 网络情况

好

### 其他浏览器插件/脚本

没有

**Comment by andywang425** [comment]
这个问题我没能复现出来。控制台日志真的一点没有吗？

**Comment by Mishasama** [comment]
没错的话日志应该有个前缀BLTH吧？
就算勾了控制台输出也是什么都没有。当然指的是没有这个脚本的。data被屏蔽的那些就不用说了吧？

**Comment by Mishasama** [comment]
![image](https://user-images.githubusercontent.com/54498172/178939080-ebcae3c6-d567-4c0c-bfd7-90e9c2d374fc.png)
这是在打开多个直播间分页时唯一的日志内容，正常来说不应该就这吧？

**Comment by Mishasama** [comment]
> 有其它不带BLTH的日志吗，发出来看看

![image](https://user-images.githubusercontent.com/54498172/180362262-cdb54d67-0e54-40b6-bd83-7c1078787a80.png)

认真翻了一下，就这个了

**Comment by andywang425** [comment]
现在又产生了新的Bug，我刚发布新版本才发现。下个版本再修吧。
