### ISSUE TITLE
点赞👍按钮默认显示

### ISSUE THREAD

**Issue by Mishasama** [andywang425/BLTH#287]
### 描述bug

新安装脚本后点赞按钮会默认出现在分享的旁边，但在控制面版里显示并没有打开该功能。

### 重现bug

安装完成后即可见到问题。

### 预期行为

全新安装后默认应该不显示这个按钮？

### 截图

![image](https://user-images.githubusercontent.com/54498172/178492842-e1c1a0f2-2655-429d-973d-89a8f1c8395e.png)

### 运行日志

![image](https://user-images.githubusercontent.com/54498172/178492797-3f06b8a2-6f6f-4cfd-8043-98253905e4b4.png)

什么日志都没有。

### 操作系统

WIN10 20H2

### 浏览器

103.0.5060.114

### 用户脚本管理器

Tampermonkey v4.16.1

### 挂机助手版本

5.8.4

### 网络情况

好

### 其他浏览器插件/脚本

没有

**Comment by andywang425** [comment]
这个功能本来就是默认开启的

**Comment by Mishasama** [comment]
然而并没有默认打勾

**Comment by andywang425** [comment]
明白了，确实有显示上的问题。
