### ISSUE TITLE
打卡黑白名单功能扩展

### ISSUE THREAD

**Issue by Mishasama** [andywang425/BLTH#288]
### 描述

能不能把那个弹幕打卡的功能应用到全部点牌的任务里？
有些牌想灰掉不想点，但现在无法对其做针对性屏蔽。
希望在点牌的同时也能灭牌，谢谢。

**Comment by andywang425** [comment]
#264 #269

**Comment by Mishasama** [comment]
貌似不用了……B站好像又更新了规则，要发弹幕的那+100才能亮牌了😓
