### ISSUE TITLE
打卡弹幕添加黑名单

### ISSUE THREAD

**Issue by andywang425** [andywang425/BLTH#29]
可以给打卡弹幕加个黑名单吗，这样方便删牌子

_Originally posted by @nbwlbw in https://github.com/andywang425/BLTH/issues/28#issuecomment-723585536_

**Comment by X-Holmes** [comment]
个人认为可以直接共用之前送小心心点亮勋章的黑白名单，因为如果开启了自动弹幕打卡，那送小心心点亮的功能就用不到了（发弹幕好像也会点亮）。而不开弹幕打卡的用户依旧可以通过送小心心的方式点亮。
（话说原来那个送小心心点亮粉丝勋章的功能是删掉了吗？为什么呀）

**Comment by andywang425** [comment]
> 个人认为可以直接共用之前送小心心点亮勋章的黑白名单，因为如果开启了自动弹幕打卡，那送小心心点亮的功能就用不到了（发弹幕好像也会点亮）。而不开弹幕打卡的用户依旧可以通过送小心心的方式点亮。
> （话说原来那个送小心心点亮粉丝勋章的功能是删掉了吗？为什么呀）

我觉得有了发弹幕点亮的功能后送小心心点亮的功能就没什么必要了，所以就删啦。   
打卡弹幕黑白名单的功能以后会更新的（咕咕咕

**Comment by X-Holmes** [comment]
好吧，我是想着可以复用代码就不用重新写了。
而且万一有人不想发弹幕也可以多一个选择（虽然可能真的只有万分之一的人会这样……
不过相比之下最左上方的礼物抽奖功能更应该删除吧，这个现在还能抽到辣条吗？

**Comment by andywang425** [comment]
> 好吧，我是想着可以复用代码就不用重新写了。
> 而且万一有人不想发弹幕也可以多一个选择（虽然可能真的只有万分之一的人会这样……
> 不过相比之下最左上方的礼物抽奖功能更应该删除吧，这个现在还能抽到辣条吗？

礼物抽奖还能参加大乱斗所以没删

**Comment by X-Holmes** [comment]
顺便问一下，之前说忘记把弹幕打卡加到【再次执行所有任务】里，现在加上了吗？我偶尔遇到无论怎么点都不能自动发弹幕打卡的问题，可能过一段时间又变的可以打卡了

**Comment by andywang425** [comment]
> 顺便问一下，之前说忘记把弹幕打卡加到【再次执行所有任务】里，现在加上了吗？我偶尔遇到无论怎么点都不能自动发弹幕打卡的问题，可能过一段时间又变的可以打卡了

加上了，点了按钮还是不能运行弹幕打卡嘛

**Comment by X-Holmes** [comment]
在当天还未进行弹幕打卡的前提下，点击再次【再次执行所有任务】，会(随机)出现以下三种情况中的一种。
1. 浮动提示开始打卡但无后续反应，不能发弹幕打卡。(多发于脚本已经执行过一段时间之后再点击)
2. 可以正常打卡，但是打卡两三个房间之后就停了。(多发于所有每日任务之前都未自动运行、刷新脚本后点击再次运行，与应援团签到主站任务等一起被执行时)
3. 正常打卡。(多发于经历过第2种情况之后，再多次刷新等待一段时间或由其他因素随机触发)

(我是通宵挂脚本的，可能凌晨时网不好或者页面崩溃等没自动完成每日任务，想要后来手动点击；批量弹幕打卡的发送时间间隔是1秒左右)
我初步怀疑是【打卡时自动送礼等任务暂停】会不会导致异步的阻塞之类的(我也不知道我在说什么)。自动送礼和弹幕打卡同时运行了会不会出现什么问题？

**Comment by andywang425** [comment]
> 在当天还未进行弹幕打卡的前提下，点击【再次执行所有任务】，会(随机)出现以下三种情况中的一种。
> 
> 1. 浮动提示开始打卡但无后续反应，不能发弹幕打卡。(多发于脚本已经执行过一段时间之后再点击)
> 2. 可以正常打卡，但是打卡两三个房间之后就停了。(多发于所有每日任务之前都未自动运行、刷新脚本后点击再次运行，与应援团签到主站任务等一起被执行时)
> 3. 正常全部打卡。(多发于经历过第2种情况、其他签到送礼任务都已完成之后，再多次刷新且等待一段时间后或由其他因素随机触发)
> 
> (我是通宵挂脚本的，可能因为凌晨时网不好或者页面崩溃等没自动完成每日任务，需要后来手动点击；批量弹幕打卡的发送时间间隔是1秒左右)
> 我初步怀疑【打卡时自动送礼等任务暂停】会不会导致异步的阻塞之类的(我也不知道我在说什么)。自动送礼和弹幕打卡同时运行了会不会出现什么问题？

了解了，我会留心观察一下。

**Comment by X-Holmes** [comment]
补充一下日志文件：

第一种情况只会有一条日志：`runMidnight: 粉丝勋章打卡弹幕 Fri Nov 27 2020 00:01:00 GMT+0800 (中国标准时间)`

第二种情况日志如图所示
![Screenshot 2020-11-26 233408](https://user-images.githubusercontent.com/35630677/100369729-421a6b80-3040-11eb-9ffc-02019c43182a.png)
其中的错误具体展开是：
`Access to XMLHttpRequest at 'https://api.live.bilibili.com/room/v1/Room/get_info?room_id=16405&from=room' from origin 'https://live.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
GET https://api.live.bilibili.com/room/v1/Room/get_info?room_id=16405&from=room net::ERR_FAILED`
```
send	@userscript.html.name...:17
ajax	@userscript.html.name...:17
eval	@userscript.html.name...:38
eval	@userscript.html.name...:38
(anonymous)	@VM570:3
E.z.<computed>	@VM582:43
setTimeout (async)
(anonymous)	@VM570:3
H.<computed>	@VM570:9
(anonymous)	@VM570:3
E	@VM582:43
enhance	@VM582:56
runUntilSucceed	@userscript.html.name...:38
ajax	@userscript.html.name...:38
get_info	@userscript.html.name...:38
sendDanmu	@userscript.html.name...:102
run	@userscript.html.name...:102
async function (async)
run	@userscript.html.name...:102
eval	@userscript.html.name...:102
(anonymous)	@VM570:3
E.z.<computed>	@VM582:43
setTimeout (async)
(anonymous)	@VM570:3
H.<computed>	@VM570:9
(anonymous)	@VM570:3
E	@VM582:43
enhance	@VM582:56
ReDoDailyTasks	@userscript.html.name...:102
eval	@userscript.html.name...:102
dispatch	@userscript.html.name...:16
q.handle	@userscript.html.name...:16
```

**Comment by andywang425** [comment]
> 补充一下日志文件：
> 
> 第一种情况只会有一条日志：`runMidnight: 粉丝勋章打卡弹幕 Fri Nov 27 2020 00:01:00 GMT+0800 (中国标准时间)`
> 
> 第二种情况日志如图所示
> ![Screenshot 2020-11-26 233408](https://user-images.githubusercontent.com/35630677/100369729-421a6b80-3040-11eb-9ffc-02019c43182a.png)
> 其中的错误具体展开是：
> `Access to XMLHttpRequest at 'https://api.live.bilibili.com/room/v1/Room/get_info?room_id=16405&from=room' from origin 'https://live.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. GET https://api.live.bilibili.com/room/v1/Room/get_info?room_id=16405&from=room net::ERR_FAILED`
> 
> 1	2
> send	@userscript.html.name...:17
> ajax	@userscript.html.name...:17
> eval	@userscript.html.name...:38
> eval	@userscript.html.name...:38
> (anonymous)	@VM570:3
> E.z.	@VM582:43
> setTimeout (async)	
> (anonymous)	@VM570:3
> H.	@VM570:9
> (anonymous)	@VM570:3
> E	@VM582:43
> enhance	@VM582:56
> runUntilSucceed	@userscript.html.name...:38
> ajax	@userscript.html.name...:38
> get_info	@userscript.html.name...:38
> sendDanmu	@userscript.html.name...:102
> run	@userscript.html.name...:102
> async function (async)	
> run	@userscript.html.name...:102
> eval	@userscript.html.name...:102
> (anonymous)	@VM570:3
> E.z.	@VM582:43
> setTimeout (async)	
> (anonymous)	@VM570:3
> H.	@VM570:9
> (anonymous)	@VM570:3
> E	@VM582:43
> enhance	@VM582:56
> ReDoDailyTasks	@userscript.html.name...:102
> eval	@userscript.html.name...:102
> dispatch	@userscript.html.name.d..:16
> q.handle	@userscript.html.name...:16

第一种情况暂且没找到原因，因为我这每次都能正常打卡。。。我会继续观察。  
第二种情况就是被风控了，目前已做优化，只有在给短号直播间打卡时才会额外发出一个请求，减少被风控的可能。

**Comment by andywang425** [comment]
如果还有问题的话开新issue或者在discussion讨论吧。
