### ISSUE TITLE
b站新版亲密度任务匹配

### ISSUE THREAD

**Issue by kerriajaponica** [andywang425/BLTH#290]
### 描述

b站又改花样了，点赞变成只有一次100亲密度，分享没了，挂30分钟100亲密度改成5分钟100，如果看直播没有上限的话加上首条弹幕和点赞的200需要挂65分钟才能满1500，不知道之前任务的那种虚拟看直播还有没有用，希望能解决
![image](https://user-images.githubusercontent.com/63228002/179266771-4ceddced-81de-4396-805e-51e9039ed0ec.png)

**Comment by letterk** [comment]
我说怎么今天只有200的亲密度

**Comment by andywang425** [comment]
会适配的
