### ISSUE TITLE
充电获取粉丝牌改为1b币

### ISSUE THREAD

**Issue by ToumaLover** [andywang425/BLTH#291]
### 描述

![image](https://user-images.githubusercontent.com/38182473/179328899-1b27ebc8-6699-4574-9bb0-140322aded74.png)
https://link.bilibili.com/p/help/index#/audience-fans-medal
b站将加入粉丝团的条件改为充电1b币，请求脚本进行修改以适配

**Comment by andywang425** [comment]
收到

**Comment by andywang425** [comment]
只能改成2B币，1B币充不了。

**Comment by catlair** [comment]
众所周知，产品经理不用产品。明明最低充2b币
