### ISSUE TITLE
隐身入场失效

### ISSUE THREAD

**Issue by TianQiBuTian** [andywang425/BLTH#292]
### 描述bug

如题，于5.8.4版本失效

### 重现bug

.

### 预期行为

.

### 运行日志

.

### 操作系统

Windows 10 64-bit

### 浏览器

Chrome 103.0.5060.114

### 用户脚本管理器

Tampermonkey v4.16.1

### 挂机助手版本

5.8.4

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by Mishasama** [comment]
以下情况于 5.8.5 确认

貌似开启后并没有出现帮助信息中描述的那样，直播间并没有都显示禁言和房管发言等问题（老代码缺陷？）
只有无法加载页面下方的动态内容的问题。而弹幕姬似乎也是看不见进场信息的，该功能似乎工作良好。

**Comment by Mishasama** [comment]
> 我的也是这个情况，弹幕姬能看到入场信息

大概是插件太多相互干扰，或者网络问题（不一定是用户方）导致脚本生效时机有问题导致的。

如有强烈刚需可以考虑使用 _另一个脚本_ 进行补充……

**Comment by Mishasama** [comment]
2022年8月4日
重新登入后确认失效……

**Comment by andywang425** [comment]
已修复
