### ISSUE TITLE
天选自动购买勋章

### ISSUE THREAD

**Issue by RAINighty** [andywang425/BLTH#294]
### 描述bug

虽然新版本将购买勋章改为了2B币，但是天选时刻里检测勋章限制自动购买勋章的选项还是5B币

### 重现bug

文字Bug

### 预期行为

天选时刻里检测勋章限制自动购买勋章的选项是2B币

### 截图

![image](https://user-images.githubusercontent.com/97167694/179351965-030cd007-bec8-4661-93a1-c55cde5ef442.png)

### 运行日志

这个就不用了吧

### 操作系统

windows 11

### 浏览器

chrome 102.0.5005.115

### 用户脚本管理器

tampermonkey 4.16.1

### 挂机助手版本

5.8.5

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
感谢指正，实际购买用的2B币但这里的文案忘记改了。

**Comment by RAINighty** [comment]
![YLZ`9X{2CF O M}TK@RAO4I](https://user-images.githubusercontent.com/97167694/179361242-5255c556-5b33-4a17-9d38-dc38870551df.jpg)
