### ISSUE TITLE
5.8.5版本控制面板按钮不显示

### ISSUE THREAD

**Issue by slatsyrc** [andywang425/BLTH#295]
### 描述bug

5.8.5版本控制面板按钮不显示，alt+b也无法调出

### 重现bug

重装5.8.4有控制面板按钮，更新到5.8.5就没了
![791f7376a6ec86eda5932ceec648d4e](https://user-images.githubusercontent.com/107987494/179363826-a0486281-034f-4f91-b06c-b4f85b932da9.png)
![98becc537dce1cdd7e0e63bb5f10e96](https://user-images.githubusercontent.com/107987494/179363805-d2312ae5-0dc2-48e4-8de4-579f3193ae04.png)
上图是5.8.4，下图是5.8.5

### 预期行为

显示控制面板按钮

### 运行日志

![791f7376a6ec86eda5932ceec648d4e](https://user-images.githubusercontent.com/107987494/179363869-bc0099aa-f33b-46e7-ae29-50fdf889a0f3.png)
![98becc537dce1cdd7e0e63bb5f10e96](https://user-images.githubusercontent.com/107987494/179363871-03f3635b-a1b8-4788-910b-d4db74c7eb21.png)

### 操作系统

Windows11

### 浏览器

Chrome103.0.5060.114

### 用户脚本管理器

Tampermonkey4.9

### 挂机助手版本

5.8.5

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
我猜是网络原因，你看控制台会发现有个文件没获取到，科学上网把资源文件加载出来即可。

**Comment by slatsyrc** [comment]
> 我猜是网络原因，你看控制台会发现有个文件没获取到，科学上网把资源文件加载出来即可。

![image](https://user-images.githubusercontent.com/107987494/179364391-f9a3d266-c9b5-4ee5-901d-6b892e138463.png)
这些吗

**Comment by slatsyrc** [comment]
> 我猜是网络原因，你看控制台会发现有个文件没获取到，科学上网把资源文件加载出来即可。

搞定了，感谢
