### ISSUE TITLE
每天获取亲密度只有200

### ISSUE THREAD

**Issue by nanxiangnongjiu** [andywang425/BLTH#296]
### 描述bug

这几天挂的时候才发现的，现在每个牌子每天可以获取的亲密度掉到200了
![image](https://user-images.githubusercontent.com/62825160/179540463-de5240a5-82c6-4881-8885-464f046753d2.png)

### 重现bug

没干什么，顶多是更新了几次脚本吧

### 预期行为

能恢复之前的1200或1300吧

### 截图

![image](https://user-images.githubusercontent.com/62825160/179543962-6abbf657-a2f1-46f9-aa94-885b5aa9f1c1.png)

### 运行日志

![image](https://user-images.githubusercontent.com/62825160/179544210-e1b270b7-7994-481a-a732-34d5f8217186.png)
![image](https://user-images.githubusercontent.com/62825160/179544302-931e21a6-f1fe-4554-a907-0f235b5a9d30.png)
![image](https://user-images.githubusercontent.com/62825160/179544379-5b60cad5-3504-4b5c-80a5-4ef9a0905104.png)
![image](https://user-images.githubusercontent.com/62825160/179544420-af8ce631-80f0-4f04-a1ca-8b9774f7ed4e.png)
![image](https://user-images.githubusercontent.com/62825160/179544464-423fc632-975d-456c-aa13-b15a4282c96b.png)
日志好像没显示不正常的地方

### 操作系统

win 10

### 浏览器

Microsoft Edge 版本 103.0.1264.62 (正式版本) (64 位)

### 用户脚本管理器

Tampermonkey 4.16.1

### 挂机助手版本

5.8.5

### 网络情况

好

### 其他浏览器插件/脚本

广告拦截插件我删了试过，还是不行

**Comment by Kagamirror-han** [comment]
我感觉好像是少了那个模拟观看。

**Comment by andywang425** [comment]
B站的公告：https://link.bilibili.com/p/eden/news#/newsdetail?id=2886

>（高峰时段可能有数值加分延迟或不稳定的情况，均属正常现象哦）

**Comment by pooneyy** [comment]
我今天亲密度直接不增加了
![image](https://user-images.githubusercontent.com/85266337/179897992-177c214f-4911-4205-8347-514608d55d76.png)

**Comment by 2q3e3w3** [comment]
亲密度规则改了，现在每天点赞和打卡弹幕各记一百点，但是观看5分钟就有100而且可以记到上限
