### ISSUE TITLE
希望每日任务自动投币可以指定up主

### ISSUE THREAD

**Issue by X-Holmes** [andywang425/BLTH#3]
希望可以指定某一个up主给他的视频每天投5个硬币。
（获取指定up的视频列表，依次检查是否已经投满2个硬币，找到未投满的视频投出硬币）
（目前自动投币好像是从动态里获取视频进行投币的）

理由：用此脚本刷辣条大多数情况下是为了粉丝勋章亲密度，
而指定某一个up进行投币既可以帮助用户快速投满20硬币获得up的粉丝勋章，
在获取勋章后继续给该up投币又可以增加该勋章的亲密度，
相比于在关注列表里随机投币，定向投币更加符合该脚本刷粉丝勋章亲密度的功能。

**Comment by andywang425** [comment]
这个建议不错。目前正在制作这个功能

**Comment by andywang425** [comment]
已完成✔

**Comment by 15726238368** [comment]
已更新，大佬神速666

**Comment by 15726238368** [comment]
在3.5.4版本中，自动投币功能没有区分联合投稿视频。
导致虽然视频在指定up的视频列表里，硬币却投给了另一个up（联合投稿的发起人）
希望可以细化一下实现逻辑，将非指定up发起的联合投稿视频排除在自动投币范围之外。
未测试3.5.5版本是否有改动（更新日志里没有提）

**Comment by andywang425** [comment]
是我疏忽了，当时没想到这个问题。下个版本会优先修复这个bug。

**Comment by andywang425** [comment]
> 在3.5.4版本中，自动投币功能没有区分联合投稿视频。
> 导致虽然视频在指定up的视频列表里，硬币却投给了另一个up（联合投稿的发起人）
> 希望可以细化一下实现逻辑，将非指定up发起的联合投稿视频排除在自动投币范围之外。
> 未测试3.5.5版本是否有改动（更新日志里没有提）

已修复✔

**Comment by X-Holmes** [comment]
在5.0.1版本中，投币选项无法保存为【给用户(UID)的视频投币】
当选中该选项后手动点击【保存所有设置】再刷新页面，选项会跳回【给动态中的的视频投币】。
即使【重置所有为默认】后再设置也依然无效。且无论【自动投币】是否勾选都是如此。
（我之前虽然设置为了投用户，也并没有自动跳到投动态。但我发现好像从某一天之后并没有成功投出硬币。于是我改了下设置但发现改不回来了。）
![搜狗截图20200923154007](https://user-images.githubusercontent.com/35630677/93982037-4e214d00-fdb3-11ea-958f-6c28dd79680e.png)
———————————————————————
此外，之后我又仔细检查了下硬币记录，发现设置的UID最近一次投稿时，脚本投出了2硬币，之前和之后都没有投过。但我设置的up主总共有600多个投稿，我并没有全部投满。所以不确定前几天脚本没有自动投币是不是因为达到了脚本设置的视频检索数上限？（比如只检测UID对应up主的近100个视频，发现都投过了就结束了，没有完成自动投币）
———————————————————————
我换了一个类似的环境、换了个浏览器和账号测试，发现可以保存。所以也可能是我的脚本运行环境出了问题。
请问有什么方法可以清除脚本在本地的所有数据吗？（我试过在tampermonkey删除脚本再重新安装，但原来的设置数据还在）
———————————————————————
总结一下我其实有3个问题：
1. 为什么【给用户(UID)的视频投币】选项无法保存(可能是我个人原因)
2. 如何清理脚本在本地的数据来重置脚本(【重置所有为默认】好像不太彻底？
3. 为什么【给用户(UID)的视频投币】在up主近期没更新视频的情况下无法投出硬币，是否有视频最大检测数/投稿时间的限制？

**Comment by andywang425** [comment]
1.这是个bug，下次更新会修复。
2.重置所有为默认不会把某些与用户无关的数据重置。如果想全部重置，F12 - Application - Local Storage - https://live.bilibili.com/ - Filter 中输入 `IGIFTMSG`，全部删除即可。  
3.这我不大清楚。脚本通过获取UP主的动态来获取视频列表，但这和UP最近有没有更新视频应该没关系。如果方便的话能否告诉我出现问题的UP主的uid，我好找一下原因。

**Comment by X-Holmes** [comment]
5.0.2版本中问题1.已修复，选项可以保存。
但问题3.无法投出硬币仍未修复。
实测该问题发生的一个条件是 对设定up主的视频已投币的数量较多，具体日志如下：
![1](https://user-images.githubusercontent.com/35630677/94261896-2d98f480-ff65-11ea-8818-7264892becf9.png)
![2](https://user-images.githubusercontent.com/35630677/94261908-312c7b80-ff65-11ea-952e-f369f2580f06.png)
图二中的这种错误随机地夹杂在正常的日志中。
这种日志一直在不停地滚动，搜索未投币视频。但搜了十几分钟都没结果，我的开发者工具都卡崩溃了。
但是通过我对所检索视频aid的抽样调查，好像并没有正常地一直往前搜，而是在某些地方循环回去了。
比如我挑出日志中一个aid，打开发现是8.15发布的；过一会在挑一个，是8.3发布的；再过一会是7.23发布的。
但再过一段时间再挑一个，发布时间又变成了8.17。也就是说有可能因为某些原因从头开始检索了。
（但也不排除是我开发者工具有点崩溃导致显示出了问题。总之如果两次抽查时间比较近还基本是正确的顺序；如果间隔时间长一点再抽就有可能抽到比上次发布更晚的视频。而且抽到的基本都是近3个月的视频，并且确实已经投过币了。但还有更多更早的视频是没有投过的。）
因为日志太长了我也没有办法找到除了图二的错误外还有没有发生其他错误。

并且后来我换了一个没怎么投币过up主的UID就马上正常完成投任务了。

**Comment by X-Holmes** [comment]
接上条。我确认过了，就是因为某些原因导致视频从头开始查找了，日志如下：
![0](https://user-images.githubusercontent.com/35630677/94330742-c37e5f00-fff9-11ea-9d7e-742a312ebb54.png)
错误之前的最后一条av98117343是2020-3-21发布的，而几个错误之后的第一条av754640580则是最新发布的视频。
另外这个错误出现比较频繁，并且不是每次出错都会从头开始检索。而是每次都是到av98117343之后就会重新开始。
（并且av98117343这个视频刚好是第36个视频，恰好是up主页里看投稿的一页所显示的视频数量）
所以也有可能这个错误只是一个烟雾弹，真正导致从头开始的是其他原因。

**Comment by andywang425** [comment]
谢谢反馈，我会尝试去修复的。

**Comment by andywang425** [comment]
找到原因了，顺便还发现对联合投稿的UP是否是指定用户的判断有问题，下个版本一起修复。

**Comment by X-Holmes** [comment]
> Q：为什么【给用户(UID)的视频投币】选项无法保存
> A：这是个bug，下次更新会修复。

我在5.1版本中又遇到了类似的不能保存问题。
自动送礼的【间隔(5)分钟送礼】选项修改文本框里的时间间隔后保存无效，刷新后会变回5分钟。
如果是相同的错误原因的话希望可以修复并排查一下其他选项是否还有类似问题。

**Comment by andywang425** [comment]
> > Q：为什么【给用户(UID)的视频投币】选项无法保存
> > A：这是个bug，下次更新会修复。
> 
> 我在5.1版本中又遇到了类似的不能保存问题。
> 自动送礼的【间隔(5)分钟送礼】选项修改文本框里的时间间隔后保存无效，刷新后会变回5分钟。
> 如果是相同的错误原因的话希望可以修复并排查一下其他选项是否还有类似问题。

谢谢提醒。其它选项我测试了一下应该没有类似问题。

**Comment by X-Holmes** [comment]
> 找到原因了，顺便还发现对联合投稿的UP是否是指定用户的判断有问题，下个版本一起修复。

“对联合投稿的UP是否是指定用户的判断”是成功修复了，但是投币检索问题还是没有修复。
（前两天补投了几个以前判断错的联合投稿视频，现在又开始无限循环了）

**Comment by X-Holmes** [comment]
-

**Comment by X-Holmes** [comment]
5.2.3.1版本已修复✔
