### ISSUE TITLE
12/11 B站直播更新

### ISSUE THREAD

**Issue by lifeiselsewhere** [andywang425/BLTH#30]
最新的B站更新以后 似乎原来的显示/隐藏页面的按钮消失了。加载脚本后打开任意直播间似乎会默认未登录状态，（无法留言，礼物栏不加载，瓜子数为0，粉丝勋章不显示）
![image](https://user-images.githubusercontent.com/4543581/98938585-09c34b00-24e0-11eb-9277-47d991a69420.png)

**Comment by cnoim** [comment]
是的

**Comment by andywang425** [comment]
这个问题会在新版修复。  
以下为临时解决方案（来源于q群公告）：  
> 11/12 脚本不显示控制面板的解决方法
请在代码中搜索114514114514，将其改成22474988（或者任意一个存在的房间号）。
原因：
刚刚B站更新了获取用户信息的api。如果开启了隐身入场，获取用户信息的请求就会出错导致脚本无法运行接下来的代码。
