### ISSUE TITLE
控制面板无法显示

### ISSUE THREAD

**Issue by Eason1428** [andywang425/BLTH#302]
### 描述bug

未显示出控制面板的按钮,在卸载重新安装之后还是没有出现控制面板按钮(只安装了这一个插件)

### 重现bug

在更新了5.8.5之后

### 预期行为

网页中可以显示出控制面板按钮

### 截图

![image](https://user-images.githubusercontent.com/109885741/180631501-229dcb05-7d52-42bc-8443-cd92d03067e5.png)
上图为未显示出控制面板的网页

### 运行日志

![image](https://user-images.githubusercontent.com/109885741/180631558-c5dbb59a-1a69-4dfa-8da0-3954dd51c941.png)
![image](https://user-images.githubusercontent.com/109885741/180631575-cbddd45c-691b-48ee-a536-f652c16ee50a.png)

### 操作系统

win10

### 浏览器

Microsoft Edge103.0.1264.62

### 用户脚本管理器

Tampermonkey v4.16.1

### 挂机助手版本

5.8.5

### 网络情况

好

### 其他浏览器插件/脚本

无其他插件

**Comment by daxiederen2333** [comment]
#295 试试这个解决方法？

**Comment by andywang425** [comment]
> #295 试试这个解决方法？

通过日志可以看出来是某个文件没获取到，科学上网把资源文件加载出来即可。

**Comment by andywang425** [comment]
新版本已换源，请更新。
