### ISSUE TITLE
看不到控制面板

### ISSUE THREAD

**Issue by devilmandare** [andywang425/BLTH#305]
### 描述bug

更新5.8.5后看不到控制面板

### 重现bug

更新5.8.5版本的脚本后就出现了这个问题

### 预期行为

脚本其他功能正常运行，只是看不到控制面板

### 截图

![DC 6T23`ZH2FDD(2P$D7_VQ](https://user-images.githubusercontent.com/52331405/181039702-cd71a306-d481-43d3-9559-babef582d388.png)

### 运行日志

![$VXMV 5$~BYJ~%JUI`_W0I4](https://user-images.githubusercontent.com/52331405/181039795-ce97e297-4f2a-44e1-b3ed-197bf521847d.png)
![HEYGM@YD6K0KJ{88VG`%C_L](https://user-images.githubusercontent.com/52331405/181039811-4d5cf0fe-1e70-410e-a207-38ae2203c810.png)
![KW9I0R }$GKFM4)3W1_O56P](https://user-images.githubusercontent.com/52331405/181039835-38b53e73-3493-49ae-80a3-729b9dbd546d.png)

### 操作系统

windows10

### 浏览器

Chrome 102.0.5005.115 64位

### 用户脚本管理器

Tampermonkey 4.16.1

### 挂机助手版本

5.8.5

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by devilmandare** [comment]
![$VXMV 5$~BYJ~%JUI`_W0I4](https://user-images.githubusercontent.com/52331405/181040398-94bfd157-e9ff-4aba-bd54-545f6753413c.png)
这个图好像没传上来，重新发一下

**Comment by andywang425** [comment]
![image](https://user-images.githubusercontent.com/56548456/181045961-ad52e3fb-a25b-4609-9ad1-6c968205c029.png)
下次用脚本的时候，挂梯子把这个资源文件加载出来（可以只让`fastly.jsdelivr.net`这个网站走代理），之后就能正常用了。

**Comment by Mishasama** [comment]
> ![image](https://user-images.githubusercontent.com/56548456/181045961-ad52e3fb-a25b-4609-9ad1-6c968205c029.png) 下次用脚本的时候，挂梯子把这个资源文件加载出来（可以只让`fastly.jsdelivr.net`这个网站走代理），之后就能正常用了。

建议更换托管，不然还是会不断有人（只要人在大陆）会遇到这个问题。

**Comment by andywang425** [comment]
> 建议更换托管，不然还是会不断有人（只要人在大陆）会遇到这个问题。

现在稳定而且能用的cdn不好找啊，很多cdn只支持加速知名项目的文件。您有什么推荐吗？

**Comment by Mishasama** [comment]
> > 建议更换托管，不然还是会不断有人（只要人在大陆）会遇到这个问题。
> 
> 现在稳定而且能用的cdn不好找啊，很多cdn只支持加速知名项目的文件。您有什么推荐吗？

用GH托管，挂公益反向代理。

**Comment by andywang425** [comment]
新版本已换源，请更新。
