### ISSUE TITLE
热门榜的显示与消失会导致控制面板消失

### ISSUE THREAD

**Issue by Mishasama** [andywang425/BLTH#307]
### 描述bug

如题

### 重现bug

1. 打开控制面板
2. 等待每个30分钟
3. 主播上热门榜，直播间画面弹出热门榜提示窗口
4. **控制面板消失了**
5. 再次手动打开控制面板
6. 热门榜提示窗口超时自动消失
7. **控制面板又消失了**

### 预期行为

不该被其它页面元素的行为干扰啊……不然设置设置着突然就没了多怪呀。

### 运行日志

捕获这个日志太麻烦了……不是错误控制台默认都没有输出的

### 操作系统

WIN10 20H2

### 浏览器

103.0.5060.114

### 用户脚本管理器

Tampermonkey v4.16.1

### 挂机助手版本

5.8.5

### 网络情况

好

### 其他浏览器插件/脚本

没有

**Comment by andywang425** [comment]
收到，等我复现出这个Bug之后再修复。  
感觉复现出来需要点运气啊，我看的主播要么早就在热门榜上，要么就永远上不了热门榜。

**Comment by Mishasama** [comment]
> 收到，等我复现出这个Bug之后再修复。 感觉复现出来需要点运气啊，我看的主播要么早就在热门榜上，要么就永远上不了热门榜。

直接赖在热门榜上的也行……循环连续上都会弹出窗口的

**Comment by andywang425** [comment]
> 直接赖在热门榜上的也行……循环连续上都会弹出窗口的

好的，我有空的时候试试
