### ISSUE TITLE
awpush设置本地化

### ISSUE THREAD

**Issue by Mishasama** [andywang425/BLTH#308]
### 描述

现在awpush的设置基本上1小时内必风控，而且什么都获取不到，没有什么实用价值。
希望能将相应的设置全部本地化，由用户自行平衡这个风险和收益比例。

**Comment by andywang425** [comment]
如果让用户自己决定设置会有偷懒不干活的，现在这样至少偷懒的门槛比较高。

**Comment by andywang425** [comment]
不过我可以把服务端的参数调整一下，现在用户多了，每个人都可以少干点活。

**Comment by Mishasama** [comment]
> 如果让用户自己决定设置会有偷懒不干活的，现在这样至少偷懒的门槛比较高。

我觉得至少可以把怎样处理下发的数据交给用户自行判断。强制上报完全没问题的。
甚至说即便不接收推送的内容也是可以进行上报的，这应该没什么好说的。

毕竟共产主义嘛，产是一定要产的。但每个人自己要吃多少应该还是可以交由个人自行判断的吧？总感觉强制每人每顿必须吃完5斤猪肉这是不是有点不妥？

**Comment by NlVEK** [comment]
提一嘴，awpush抽那个红包没问题，抽实物风控
然后批量取关也会触发风控，不知道什么检测机制

**Comment by andywang425** [comment]
> 我觉得至少可以把怎样处理下发的数据交给用户自行判断。强制上报完全没问题的。 甚至说即便不接收推送的内容也是可以进行上报的，这应该没什么好说的。
> 
> 毕竟共产主义嘛，产是一定要产的。但每个人自己要吃多少应该还是可以交由个人自行判断的吧？总感觉强制每人每顿必须吃完5斤猪肉这是不是有点不妥？

咱现在不是已经有忽略关键字之类的过滤方法了吗。启用awpush不影响如何处理从awpush获取到的数据，只影响怎么从B站获取抽奖数据。
awpush控制的是轮询分区，轮询房间数量，请求间隔和休息时间，让用户决定这些内容不合适。

**Comment by andywang425** [comment]
> 提一嘴，awpush抽那个红包没问题，抽实物风控 然后批量取关也会触发风控，不知道什么检测机制

实物是指天选时刻吗。检测机制我也不清楚，B站的检测越来越严了。以后可能会做相关优化吧。
出于各种原因今后我不会在抽奖方面投入太多精力，望理解。

**Comment by NlVEK** [comment]
> > 提一嘴，awpush抽那个红包没问题，抽实物风控 然后批量取关也会触发风控，不知道什么检测机制
> 
> 实物是指天选时刻吗。检测机制我也不清楚，B站的检测越来越严了。以后可能会做相关优化吧。 出于各种原因今后我不会在抽奖方面投入太多精力，望理解。

嗯，天选会触发。和客服说我账号被风控了客服也就只会说你多设备登录balabala的

**Comment by Mishasama** [comment]
> > 我觉得至少可以把怎样处理下发的数据交给用户自行判断。强制上报完全没问题的。 甚至说即便不接收推送的内容也是可以进行上报的，这应该没什么好说的。
> > 毕竟共产主义嘛，产是一定要产的。但每个人自己要吃多少应该还是可以交由个人自行判断的吧？总感觉强制每人每顿必须吃完5斤猪肉这是不是有点不妥？
> 
> 咱现在不是已经有忽略关键字之类的过滤方法了吗。启用awpush不影响如何处理从awpush获取到的数据，只影响怎么从B站获取抽奖数据。 awpush控制的是轮询分区，轮询房间数量，请求间隔和休息时间，让用户决定这些内容不合适。

那在“轮询房间数量，请求间隔和休息时间”这些地方加入一些随机系数避免大家都去同一批房间抽一样的奖？尽可能的让不同用户形成更多的差异化我觉得这样至少能少命中一些检测条件。

**Comment by andywang425** [comment]
> 那在“轮询房间数量，请求间隔和休息时间”这些地方加入一些随机系数避免大家都去同一批房间抽一样的奖？尽可能的让不同用户形成更多的差异化我觉得这样至少能少命中一些检测条件。

我想还是公平一些比较好，只要收到抽奖数据就推送给每一个用户。

**Comment by Mishasama** [comment]
> 我想还是公平一些比较好，只要收到抽奖数据就推送给每一个用户。

行吧……那大家就自求多福 use at your own risk 吧😂
（PS 我号大概已经无了，爱咋咋滴吧）
