### ISSUE TITLE
已经有段时间不会自动获取小心心了

### ISSUE THREAD

**Issue by LincoXiaoQ** [andywang425/BLTH#31]
**描述bug**  
脚本已经有一段时间(+-10day)不会自动快速获取小心心, 更新后也无效

**重现bug**  
开启脚本, 打开任意非定制页面的直播间
脚本功能正常加载, 但是小心心无法自动快速获取, 只能由零开始按观看时间缓慢累加

**预期行为**  
启用脚本后进入直播页面, 快速取得直播道具小心心

**运行日志**  
控制台输出到" `[IGIFTMSG][0:19:7:602] [小心心]检测到包裹内7天小心心数量: 0`
后不再有内容输出

**使用环境:**
 - 浏览器: Edge
 - 浏览器版本: 新版
 - 脚本的版本: 即时更新版本
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 无
 - bug出现时间: 固定存在

**其他**  
可能是B站API做了变更, 奇怪的是至今未见其他用户提出无法使用的issue, 似乎大家都能正常使用?

**Comment by lifeiselsewhere** [comment]
我似乎没有这个问题，不过我一般都手动点”重新运行所有项目“

**Comment by andywang425** [comment]
少部分用户确实有这个问题，但我一直没找到原因。  
可以去[https://github.com/lzghzr/TampermonkeyJS](https://github.com/lzghzr/TampermonkeyJS)这个项目反馈，客户端心跳代码来源于这个项目的作者，我只是做了一点小小的改进。

**Comment by LincoXiaoQ** [comment]
好的, 我找出错误信息后再向那边反馈

**Comment by acbetter** [comment]
+1，今天突然获取不了小心心了
