### ISSUE TITLE
表示粉丝牌是一个B币、不是俩个

### ISSUE THREAD

**Issue by Malus-Mill** [andywang425/BLTH#310]
### 描述bug

![image](https://user-images.githubusercontent.com/53999738/182771917-9599480a-b634-4dda-a035-3a380d5651c4.png)

### 重现bug

![image](https://user-images.githubusercontent.com/53999738/182771866-bba7a4d1-f21e-4416-bfb8-4505f3569fa6.png)

### 预期行为

![image](https://user-images.githubusercontent.com/53999738/182772037-7bfd496a-0ad2-4054-9d98-ae6751e543bd.png)

### 运行日志

一、降低入团门槛至10电池：
       用户投喂“粉丝团灯牌”礼物（价值10电池），给主播视频充电1B币，或开通主播大航海，即可加入主播粉丝团。原有入团礼物“B坷垃”将同步下线，取消原有单日投喂金额≥9.9元直接入团功能。

### 操作系统

WIN11 

### 浏览器

Chrome 版本 103.0.5060.134（正式版本） （64 位）

### 用户脚本管理器

 Tampermonkey 4.16.1

### 挂机助手版本

5.8.5

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by KudouRan** [comment]
用的是充电，最低要20电池。其实可以改成送粉丝牌继续

**Comment by andywang425** [comment]
使用5B币那里是写错了。目前脚本采用充电的方式买粉丝牌，但B站规定最少充电2B币。
