### ISSUE TITLE
天选时刻参与后无法自动关注up

### ISSUE THREAD

**Issue by daxiederen2333** [andywang425/BLTH#311]
### 描述bug

天选参与后脚本无法自动关注up，转到直播间显示参与天选但没关注，疑似是风控的原因

### 重现bug

无

### 预期行为

天选参与后自动关注up

### 截图

![image](https://user-images.githubusercontent.com/99582028/182881467-b8febf93-f93c-48de-8ee4-e394e69c712c.png)

### 运行日志

![image](https://user-images.githubusercontent.com/99582028/182882083-66550406-55af-4c52-ba09-ca6044c9bd3c.png)

### 操作系统

win11

### 浏览器

chrome 103.0.5060.53

### 用户脚本管理器

tampermonkey 4.16.1

### 挂机助手版本

5.8.5

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
![image](https://user-images.githubusercontent.com/56548456/183238084-0767507c-898b-40eb-8cf5-17645e3bd6e1.png)
这里点一下右上角的链接，然后点左下角按钮格式化代码，把出错的地方发一下。

**Comment by daxiederen2333** [comment]
> ![image](https://user-images.githubusercontent.com/56548456/183238084-0767507c-898b-40eb-8cf5-17645e3bd6e1.png) 这里点一下右上角的链接，然后点左下角按钮格式化代码，把出错的地方发一下。

![image](https://user-images.githubusercontent.com/99582028/183239157-95615db8-217e-4c1c-abe3-0aa87f2f9f42.png)
这样吗？

**Comment by andywang425** [comment]
我更倾向于是你的网络原因，因为B站本身的几个请求也失败了。是不是风控不好说。今天还是这样吗？

**Comment by daxiederen2333** [comment]
> 我更倾向于是你的网络原因，因为B站本身的几个请求也失败了。是不是风控不好说。今天还是这样吗？

还是无法自动关注，今天发现会弹一个这个弹窗，可是关注列表一直是公开的
![image](https://user-images.githubusercontent.com/99582028/183248960-0ea4d627-789f-410d-b902-30582803a3e2.png)

**Comment by mzth** [comment]
被风控了，慢慢等解封吧
