### ISSUE TITLE
大航海列表无法显示  （希望加个功能避免被检测高危）

### ISSUE THREAD

**Issue by ZLlve** [andywang425/BLTH#312]
### 描述bug

大航海列表无法显示

### 重现bug

开启挂机助手

### 预期行为

正常显示大航海列表

### 截图

![Uploading image.png…]()

### 运行日志

![Uploading image.png…]()

### 操作系统

win11

### 浏览器

Microsoft Edge 版本 104.0.1293.47 

### 用户脚本管理器

Tampermonkey BETA 4.18.6166

### 挂机助手版本

5.8.5

### 网络情况

好

### 其他浏览器插件/脚本

Userscript+ : 显示当前网站所有可用的UserJS脚本 Jaeger

### 其他

这段时间经常被检测高危 只留了从BLTH-server获取天选和从关注列表获取天选，参与直播预约抽奖。
今天还是被高危强制下线，不知道什么原因

**Comment by ZLlve** [comment]
![W%`6LT T$7YOIF9 V0LFMWD](https://user-images.githubusercontent.com/89200225/184073396-089beff3-8b9f-4d3d-8fb6-829ed8ba91d2.png)

**Comment by ZLlve** [comment]
![H@_6P2X4LCC$S1EFZHV PHI](https://user-images.githubusercontent.com/89200225/184073434-d97c8bd7-b729-44cc-b18c-4a8aa63a284b.png)

**Comment by daxiederen2333** [comment]
> ![W%`6LT T$7YOIF9 V0LFMWD](https://user-images.githubusercontent.com/89200225/184073396-089beff3-8b9f-4d3d-8fb6-829ed8ba91d2.png)

这个应该是风控给你强制下线了，我被风控也是这样加载不出来。现在b站应该是对天选和实物抽奖改风控规则了

**Comment by ZLlve** [comment]
> > ![W%'6LT T$7YOIF9 V0LFMWD](https://user-images.githubusercontent.com/89200225/184073396-089beff3-8b9f-4d3d-8fb6-829ed8ba91d2.png)
> 
> 这个应该是风控给你强制下线了，我被风控也是这样加载不出来。现在b站应该是对天选和实物抽奖改风控规则了

不是的 把插件关了就能看到了
