### ISSUE TITLE
粉丝勋章打卡加入屏蔽已取关的up主的功能

### ISSUE THREAD

**Issue by kirayomato** [andywang425/BLTH#314]
### 描述

最近发现每天通过点赞和发弹幕打卡能点亮的粉丝牌数量是有上限的（大概是200个？）

超过以后剩下的粉丝牌功能将会受到限制。点赞、发弹幕、挂机均无法获得亲密度和点亮牌子，只有使用付费礼物才能获取亲密度并点亮牌子

很多主播我早就已经取关了，但是粉丝牌还不想删掉，所以想在打卡时排除掉这些

现在虽然有黑名单功能，但是一个一个添加还是有点麻烦

**Comment by KIrayamoto** [comment]
想了下或许可以把这个功能改成**一键将有粉丝勋章但已经取关的up主加入黑名单**

**Comment by ClementLevi** [comment]
什么dd，这上限都能测出来
