### ISSUE TITLE
无法呼出控制台

### ISSUE THREAD

**Issue by inahoz** [andywang425/BLTH#316]
### 描述bug

插件启动后打开直播间无控制台按钮只有右上角日志，使用alt+b也无法呼出控制台。

### 重现bug

1.重装了系统
2.重新在edge的Tampermonkey插件内安装了此脚本
3.打开b站直播间后无法呼出控制台

### 预期行为

打开直播间后应有呼出控制台的按钮

### 截图

![image](https://user-images.githubusercontent.com/112330826/187078885-4cdf8f8b-e3cf-4e57-9989-5f5065ea6395.png)
![image](https://user-images.githubusercontent.com/112330826/187078923-01e64e20-8285-4b5d-b5fb-6e9ec1c3ed02.png)

### 运行日志

无法获得控制台日志

### 操作系统

win10

### 浏览器

edge104.0.1293.70 (正式版本) (64 位

### 用户脚本管理器

Tampermonkey4.16.1

### 挂机助手版本

5.8.5

### 网络情况

好

### 其他浏览器插件/脚本

未安装其他脚本及插件

**Comment by SoulGI** [comment]
控制台加载不出来说明你访问不了fastly.jsdelivr.net，自行挂上工具后打开任意直播间就可以解决

**Comment by andywang425** [comment]
已在新版本中换源。
