### ISSUE TITLE
控制面板中保存获取红包数据间隔不生效

### ISSUE THREAD

**Issue by bix-cy** [andywang425/BLTH#317]
### 描述bug

在控制面板中已经保存了"隔3min获取数据"，但在日志中仍然是"10min获取一次数据"，实际检测是3min

### 重现bug

1.在“控制面板-直播红包抽奖-获取红包数据间隔”中设置间隔3min，并保存设置
2.在日志中仍然是每十分钟获取一次红包数据，实际是3min检测

### 预期行为

能成功显示

### 截图

![时间不匹配](https://user-images.githubusercontent.com/24545756/187888140-72c8a486-dc13-443f-8c93-103f1a23c825.png)

### 运行日志

[live.bilibili.com-1662026968899.log](https://github.com/andywang425/BLTH/files/9468953/live.bilibili.com-1662026968899.log)
![日志](https://user-images.githubusercontent.com/24545756/187889712-a986dec7-8bad-484d-a591-52a054f8d6bf.png)

### 操作系统

Windows10

### 浏览器

Microsoft Edge 版本 104.0.1293.70 (正式版本) (64 位)

### 用户脚本管理器

tampermonkey v4.16.1

### 挂机助手版本

5.8.5

### 网络情况

好

### 其他浏览器插件/脚本

Bilibili Evolved，b站自动续牌，B站共同关注快速查看，Bilibili 解锁杜比全景声 & 8K &开启 HDR &直播画质PRO，解除B站区域限制

**Comment by andywang425** [comment]
确实是bug。
但是我正在打算删除这个脚本里和抽奖有关的功能，累了。
