### ISSUE TITLE
QQ群似乎挂了?

### ISSUE THREAD

**Issue by nyano** [andywang425/BLTH#318]
### 描述bug

找不到该群

### 重现bug

找不到该群

### 预期行为

找不到该群

### 运行日志

找不到该群

### 操作系统

找不到该群

### 浏览器

找不到该群

### 用户脚本管理器

找不到该群

### 挂机助手版本

找不到该群

### 网络情况

好

### 其他浏览器插件/脚本

找不到该群

**Comment by andywang425** [comment]
已经挂了两次了，每次都是因为聊政治被封，暂时不想再建群。
