### ISSUE TITLE
请求增加屏蔽动态的功能

### ISSUE THREAD

**Issue by 1786178749** [andywang425/BLTH#32]
开启抽奖后会关注很多up，动态首页会很乱，勾选未中奖取关的话又会因为重复关注被识别为机器，所以能不能增加一个屏蔽动态首页里天选up分组的动态和左侧正在直播的功能？

**Comment by andywang425** [comment]
屏蔽动态和本脚本的主题无关，而且这个功能实现起来不简单，所以不会加入这个功能。如果可以的话尽量用小号抽奖吧。
