### ISSUE TITLE
[6.0.1] 42行main主页的路径似乎变成了本地路径导致页面加载问题

### ISSUE THREAD

**Issue by raytracesoak** [andywang425/BLTH#321]
### 描述bug

6.0.1 42行主页路径
// @resource       main     file:///D:/Documents/GitHub/BLTH/assets/html/main.html
6.0 42行主页路径
// @resource       main     https://gcore.jsdelivr.net/gh/andywang425/BLTH@9184f99eb673e766999401eb963787d5c72e39c9/assets/html/main.min.html

### 重现bug

。。

### 预期行为

42行修改回6.0页面能正常加载。

### 运行日志

。。

### 操作系统

win10

### 浏览器

Chrome 版本 106.0.5249.40（正式版本）beta （64 位）

### 用户脚本管理器

Violentmokey beta

### 挂机助手版本

6.0.1

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
还真是，我更新的时候忘记改了。
