### ISSUE TITLE
自动送礼无效

### ISSUE THREAD

**Issue by Hiiro570** [andywang425/BLTH#323]
### 描述bug

自动送礼功能无效，右上角显示【[自动送礼]本次送礼结束】但包里的东西没送出去

### 重现bug

1：每天启动的时候都无法送出
2：点击【立即开始送礼】无法送出
3：设置为间隔时间送礼无法送出

### 预期行为

自动送出指定礼物

### 截图

![image](https://user-images.githubusercontent.com/88080039/191149199-bfdb98ff-d4ed-4a49-bd50-1c2e434da5df.png)
![image](https://user-images.githubusercontent.com/88080039/191149228-d2251eda-f7ca-42c6-a0e9-5c9209bb2742.png)

### 运行日志

[BLTH][9:34:38:559] [自动送礼]: 处理前的礼物列表 1,6
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=a7c4f8c2-57a9-4e7c-ad6b-698fddc905cd:188 [BLTH][9:34:38:559] [自动送礼]: 处理后得到的礼物id列表 1,6
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=a7c4f8c2-57a9-4e7c-ad6b-698fddc905cd:188 [BLTH][9:34:38:964] Gift.getBagList: API.gift.bag_list: Objectcode: 0data: {list: Array(7), time: 1663637679}list: (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}]0: {bag_id: 316866046, gift_id: 31531, gift_name: 'PK票', gift_num: 10, gift_type: 5, …}1: {bag_id: 317399608, gift_id: 1, gift_name: '辣条', gift_num: 2, gift_type: 5, …}2: {bag_id: 317449171, gift_id: 31531, gift_name: 'PK票', gift_num: 9, gift_type: 5, …}3: {bag_id: 317399720, gift_id: 31531, gift_name: 'PK票', gift_num: 10, gift_type: 5, …}4: {bag_id: 317313172, gift_id: 1, gift_name: '辣条', gift_num: 50, gift_type: 5, …}5: {bag_id: 317453269, gift_id: 1, gift_name: '辣条', gift_num: 50, gift_type: 5, …}6: {bag_id: 28578748, gift_id: 3, gift_name: 'B坷垃', gift_num: 19, gift_type: 0, …}length: 7lastIndex: (...)[[Prototype]]: Array(0)time: 1663637679[[Prototype]]: Objectmessage: "success"msg: "success"[[Prototype]]: Object
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=a7c4f8c2-57a9-4e7c-ad6b-698fddc905cd:188 [BLTH][9:34:38:966] [自动送礼] else分支 过滤后的礼物: Array(6)
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=a7c4f8c2-57a9-4e7c-ad6b-698fddc905cd:188 [BLTH][9:34:38:966] Gift.bag_list (sorted): Array(6)
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=a7c4f8c2-57a9-4e7c-ad6b-698fddc905cd:188 [BLTH][9:34:38:967] [自动送礼] if分支 过滤后的礼物: Array(0)
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=a7c4f8c2-57a9-4e7c-ad6b-698fddc905cd:188 [BLTH][9:34:38:967] toast-info: [自动送礼] 本次送礼结束

### 操作系统

Windows10 21H1

### 浏览器

Microsoft Edge 版本 105.0.1343.42 (正式版本) (64 位)

### 用户脚本管理器

tampermonkey v4.16.1

### 挂机助手版本

6.0.2

### 网络情况

好

### 其他浏览器插件/脚本

Bilibili Evolved

**Comment by andywang425** [comment]
下个版本会修复的Bug：
- 修复【自动送礼】无法送出当天过期的礼物的 Bug。
- 修复直播区任务执行方式中黑白名单显示不正确的 Bug。
- 修复【隐身入场】失效的 Bug。

你送不出去的礼物是不是当天的？

**Comment by andywang425** [comment]
已修复
