### ISSUE TITLE
主站任务的投币功能无效

### ISSUE THREAD

**Issue by yuijker** [andywang425/BLTH#324]
### 描述bug

****
在每天执行的主站任务里，每次执行时，并没有投币的行为与弹窗提示。

### 重现bug

1.安装脚本
2.勾选主站每日任务的所有选项。投币选项设为给动态中的视频投币
3.重置主站缓存或等到第二天
4.问题出现，除投币之外的主站任务正常，唯独投币没有执行

### 预期行为

在每天执行的主站任务里，每次执行时，出现投币的行为与弹窗提示。

### 截图

![image](https://user-images.githubusercontent.com/72558803/191260547-045c614c-228e-42a4-a9ca-2a2340c96f7b.png)

![image](https://user-images.githubusercontent.com/72558803/191265119-4a126e03-9d09-4802-86f4-18e9b7ff189c.png)

### 运行日志

userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:14:858] toast-info: 正在获取礼物 / 用户 / 账号 / 粉丝勋章数据...
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:17:343] InitData: API.gift.gift_config: {code: 0, msg: '', message: '', data: Array(404)}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:19:246] InitData: API.getuserinfo: {code: 'REPONSE_OK', msg: 'success', message: 'success', data: {…}}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:20:352] InitData: API.x.getAccInfo: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:20:605] Live_info: {room_id: 81435, short_room_id: 81435, uid: 477918756, ruid: 19428259, gift_list: Array(404), …}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:21:73] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:21:208] runTomorrow: 获取粉丝勋章列表 Wed Sep 21 2022 00:01:00 GMT+0800 (香港标准时间)
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:21:208] medla_info: {status: {…}, medal_list: Array(4)}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:21:568] toast-success: CACHE载入成功
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:21:955] MY_API.CONFIG: {AUTO_DANMU: false, AUTO_GIFT: false, AUTO_GIFT_ROOMID: Array(1), AUTO_GROUP_SIGN: false, COIN: true, …}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:21:970] runExactMidnight: 重置统计 Wed Sep 21 2022 00:00:00 GMT+0800 (香港标准时间)
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:28:77] runMidnight: 直播区 - 直播签到 Wed Sep 21 2022 00:01:00 GMT+0800 (香港标准时间)
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:28:434] DailyReward.run: API.DailyReward.exp: {code: 0, message: '0', number: 0}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:189 [BLTH][20:49:29:708] DailyReward.login: API.DailyReward.login: []
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:29:709] toast-success: [自动每日奖励][每日登录]完成
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:29:716] CACHE已保存: {AUTO_SEND_DANMU_TS: Array(0), AUTO_GROUP_SIGH_TS: 0, Silver2Coin_TS: 0, Coin2Sliver_TS: 0, Gift_TS: 0, …}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:29:717] runMidnight: 主站任务 - 登录 Wed Sep 21 2022 00:01:00 GMT+0800 (香港标准时间)
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:31:807] DailyReward.dynamic: API.getuserinfo: {code: 'REPONSE_OK', msg: 'success', message: 'success', data: {…}}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:32:43] DailyReward.dynamic: API.dynamic_svr.dynamic_new: {code: 0, msg: '', message: '', data: {…}}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:32:173] DailyReward.watch: API.DailyReward.watch: {code: 0, message: '0', ttl: 1}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:32:174] toast-success: [自动每日奖励][每日观看]完成(av=985815929)
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:32:184] CACHE已保存: {AUTO_SEND_DANMU_TS: Array(0), AUTO_GROUP_SIGH_TS: 0, Silver2Coin_TS: 0, Coin2Sliver_TS: 0, Gift_TS: 0, …}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:32:189] DailyReward.share: API.DailyReward.share: {code: 0, message: '0', ttl: 1, data: 4}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:32:190] toast-success: [自动每日奖励][每日分享]分享成功(av=985815929)
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:32:201] CACHE已保存: {AUTO_SEND_DANMU_TS: Array(0), AUTO_GROUP_SIGH_TS: 0, Silver2Coin_TS: 0, Coin2Sliver_TS: 0, Gift_TS: 0, …}
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:32:208] runMidnight: 主站任务 - 观看视频 分享视频 投币 Wed Sep 21 2022 00:01:00 GMT+0800 (香港标准时间)
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:195 
        
       [BLTH][20:49:33:290] XHR出错: (2) [{…}, {…}]
MYERROR @ userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:195
onerror @ userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:3602
it @ VM8:14
(匿名) @ VM27:18
it @ VM8:14
a @ VM27:3
(匿名) @ VM27:4
(匿名) @ VM8:6
M @ VM8:6
s @ content.js:107
n @ content.js:108
setTimeout(异步)
setTimeout @ content.js:121
processMessage @ content.js:124
(匿名) @ content.js:128
(匿名) @ content.js:108
it @ VM8:14
D.<computed>.I.<computed> @ VM8:4
it @ VM8:14
y @ VM8:6
send @ VM8:7
r @ VM27:4
setTimeout @ VM27:4
i @ VM27:18
(匿名) @ VM27:26
(匿名) @ VM27:26
te @ VM27:24
(匿名) @ VM27:25
(匿名) @ VM27:9
it @ VM8:14
t @ VM8:15
message @ VM27:9
message @ VM27:10
(匿名) @ VM27:66
M @ VM8:6
s @ content.js:107
send @ content.js:108
postMessage @ content.js:109
(匿名) @ content.js:119
s @ content.js:118
(匿名) @ content.js:118
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:49:33:291] 检查更新 checkUpdate: undefined
userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=d78f4b07-5cf3-443e-8534-01b0b9ae0569:188 [BLTH][20:52:32:288] 屏蔽挂机检测: 触发一次MouseEvent(mousemove)

﻿
[live.bilibili.com-1663678369512.log](https://github.com/andywang425/BLTH/files/9607736/live.bilibili.com-1663678369512.log)

### 操作系统

Windows 10 20H2

### 浏览器

Microsoft Edge 版本 105.0.1343.42 (正式版本) (64 位)

### 用户脚本管理器

tampermokey 4.16.1

### 挂机助手版本

6.0.2

### 网络情况

好

### 其他浏览器插件/脚本

无

### 其他

无

**Comment by andywang425** [comment]
已修复。
刚刚更新完`6.0.3`都准备下班了，看到你这条issue直接加班，目前最新版是`6.0.4`。
