### ISSUE TITLE
开启脚本后特殊直播间直播画面消失

### ISSUE THREAD

**Issue by RtYkk** [andywang425/BLTH#327]
### 描述bug

如题，e.g. https://live.bilibili.com/999

### 重现bug

啥也没做，就开了脚本

### 预期行为

能看见直播间

### 截图

![image](https://user-images.githubusercontent.com/45971730/191288014-ed3939e8-d485-4f24-b7f7-d8822c8a893d.png)

### 运行日志

无

### 操作系统

Windows 10

### 浏览器

chrome 105.0.5195.127

### 用户脚本管理器

tempermonkey 4.16.1

### 挂机助手版本

6.0.4

### 网络情况

好

### 其他浏览器插件/脚本

都分别关闭测试过，确认应该是 BLTH 的 bug

### 其他

上一个版本都好像没事，最新版突然这样了。

**Comment by andywang425** [comment]
把隐身入场关掉就正常了，但我还没搞懂为什么会这样。

**Comment by andywang425** [comment]
> 欸我发现我关了隐身入场也不行，传份配置麻烦你看看。 [BLTH_CONFIG.txt](https://github.com/andywang425/BLTH/files/9616925/BLTH_CONFIG.txt)

把【拦截直播观看数据上报】也关了试试。

**Comment by c1023** [comment]
9月23号发现同样情况，ow联赛直播间也没有播放窗口，其他个人直播间无此问题。解决办法：重装Tampermonkey，重装脚本。

**Comment by RemiDre** [comment]
https://live.bilibili.com/blanc/直播间id    可解决
比如 https://live.bilibili.com/blanc/999
