### ISSUE TITLE
隐身入场和拦截直播观看数据上报均会导致特殊直播间直播画面不显示

### ISSUE THREAD

**Issue by Enterld** [andywang425/BLTH#328]
### 描述bug

隐身入场和拦截直播观看数据上报均会导致特殊直播间直播画面不显示

### 重现bug

隐身入场和拦截直播观看数据上报

### 预期行为

特殊直播间直播画面不显示

### 运行日志

wu

### 操作系统

windows 10 20h2

### 浏览器

chrome 105.0.5195.127

### 用户脚本管理器

Tameermonkey 4.6.1

### 挂机助手版本

6.0.4

### 网络情况

好

### 其他浏览器插件/脚本

wu

**Comment by andywang425** [comment]
#327 确实存在这个问题，但还不知道怎么修复

**Comment by lzghzr** [comment]
> #327 确实存在这个问题，但还不知道怎么修复

[ajax-hook](https://github.com/wendux/ajax-hook)的bug，原作者已经修复了，更新一下就可以

**Comment by andywang425** [comment]
> > #327 确实存在这个问题，但还不知道怎么修复
> 
> ~[ajax-hook](https://github.com/wendux/ajax-hook)的bug，原作者已经修复了，更新一下就可以~
> 
> 看错了，但好像可以解决问题😂

感谢大佬，你又一次帮我解决了问题🤣
