### ISSUE TITLE
自动送礼到期时间计算不准确

### ISSUE THREAD

**Issue by yoyo-uu** [andywang425/BLTH#329]
### 描述bug

`new Date(r.expire_at * 1000 - ts_ms()).getDate()`
自动送礼礼物到期时间因为时区导致计算不准确

建议修改为这样可以不受时区影响
`(r.expire_at * 1000 - ts_ms()) / 86400000`

### 重现bug

受时区影响8:00以前无法送出当天过期的礼物

### 预期行为

每天0点后就可以送出将要过期的礼物

### 运行日志

无

### 操作系统

windows 10

### 浏览器

Chrome 105.0.5195.127

### 用户脚本管理器

暴力猴 v2.13.0

### 挂机助手版本

6.0.4

### 网络情况

好

### 其他浏览器插件/脚本

 无

**Comment by andywang425** [comment]
行，我改一下
