### ISSUE TITLE
不能获取小心心了

### ISSUE THREAD

**Issue by Misaka-master** [andywang425/BLTH#33]
今天打开没有直播的up主的直播间,等了好一会儿也没有小心心了

**Comment by Dududade** [comment]
我也是

**Comment by Misaka-master** [comment]
作者能不能来解决一下这个问题啊😥

**Comment by andywang425** [comment]
我也想解决，但我不会啊😥。  
就看[TampermonkeyJS](https://github.com/lzghzr/TampermonkeyJS)这个项目的作者能不能解决这个问题了。如果那位大佬解决了我也会更新修复。

**Comment by andywang425** [comment]
现已修复
