### ISSUE TITLE
希望恢复黑白名单一键取关功能

### ISSUE THREAD

**Issue by leemmu** [andywang425/BLTH#331]
### 描述

不然每次都要降级到5.8.5才能取关

**Comment by andywang425** [comment]
都没抽奖功能了为什么还要取关，之前关注的没取关完吗？

**Comment by leemmu** [comment]
> 都没抽奖功能了为什么还要取关，之前关注的没取关完吗？

每天用平板刷视频的时候经常会不小心关注一堆人，这个脚本是我用过的最好的批量取关脚本了（虽然会被风控doge

**Comment by andywang425** [comment]
> 每天用平板刷视频的时候经常会不小心关注一堆人，这个脚本是我用过的最好的批量取关脚本了（虽然会被风控doge

我建议用这个 https://greasyfork.org/zh-CN/scripts/428895-bilibili-%E5%85%B3%E6%B3%A8%E7%AE%A1%E7%90%86%E5%99%A8

**Comment by leemmu** [comment]
这个我用过，操作繁琐，我需要去导出最开始的关注列表，然后导出现在的关注列表，然后删掉最开始的内容，再根据UID取关，才达到5.8.5的非白名单取关功能
