### ISSUE TITLE
[Feature Request] 屏蔽左上角小橙车弹窗

### ISSUE THREAD

**Issue by RtYkk** [andywang425/BLTH#332]
### 描述

RT，截图暂缺。可以看看这个[直播间](https://live.bilibili.com/439)

**Comment by andywang425** [comment]
虽然不知道你说的是什么东西，但是不是开播了才会有？我今晚再看看。

**Comment by andywang425** [comment]
> 是，这位晚上六点半开播，您可以看看。我今天早上本来想用 ublock origin 解决的，结果每次选择这玩意最后都变成了背景图片。

好的，我晚上来看看。

**Comment by andywang425** [comment]
> ![image](https://user-images.githubusercontent.com/45971730/194752308-9d8b9e22-11bb-4211-a019-c39342338d85.png) 补图，好像是一天一次。 `<div data-v-3c07b9cc="" class="shop-popover"><div data-v-3c07b9cc="" class="guide"></div><div data-v-3c07b9cc="" class="text">网页端暂不支持购物“小橙车”，麻烦观众老爷移步APP主播直播间内使用“小橙车”哦~</div><div data-v-3c07b9cc="" class="close"></div></div>` 这一块

感谢反馈，那屏蔽`shop-popover`这个class就行了。

**Comment by andywang425** [comment]
已在6.0.6版本中实现该功能。
