### ISSUE TITLE
手机上x浏览器的实现

### ISSUE THREAD

**Issue by xuetu001** [andywang425/BLTH#333]
### 描述

手机上x浏览器可以安装油猴以及本插件，但是进去之后没有控制面板，而且显示上起码完成了一个任务，但是所有 直播间并不会加亲密度，请问这个到底有搞头吗？能实现吗？

**Comment by andywang425** [comment]
我以前在手机上测试过脚本，感觉运行了但又没完全运行，和你说的情况差不多。以后我有空的话会在安卓模拟器上再测试一下，能不能适配看情况。主要还是以电脑的Chrome和最新版Tampermonkey为开发环境，搞适配挺累的。

**Comment by zqdlly** [comment]
记得x浏览器是很拉垮的,很多油猴特性都不兼容.可以试试别的,比如iceraven浏览器
