### ISSUE TITLE
首次打开直播间后依旧为P2P流

### ISSUE THREAD

**Issue by TianQiBuTian** [andywang425/BLTH#334]
### 描述bug

在勾选“禁止p2p上传”时打开直播间，首次视频统计信息里的Player Core后面括号为“SistersFetcher”，刷新或者换画质后才会变为“Fetch”。

### 重现bug

如上。

### 预期行为

打开（或刷新）直播间后Player Core为“Fetch”。

### 运行日志

.

### 操作系统

Windows 10 64-bit

### 浏览器

Edge 106.0.1370.52

### 用户脚本管理器

Tampermonkey v4.16.1

### 挂机助手版本

6.0.5

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
我看了下有些直播间打开后确实显示SistersFetcher，但是通过观察浏览器的上行流量可以看出p2p其实已经被禁用了。
