### ISSUE TITLE
每日领取1电池

### ISSUE THREAD

**Issue by lzghzr** [andywang425/BLTH#335]
### 描述

APP任务
![Screenshot_20221029201003](https://user-images.githubusercontent.com/13391314/198830994-036e5030-76db-43f4-96a3-50efafb5bcc4.png)
![2022-10-29_20-19-16](https://user-images.githubusercontent.com/13391314/198831151-57eb1fc9-e460-436c-9d71-fbe2b1af353b.png)

抓包地址：
`POST https://api.live.bilibili.com/xlive/app-ucenter/v1/userTask/UserTaskReceiveRewards`

不知道是否每个人都有，但我这已经领了好几天了

**Comment by andywang425** [comment]
我把APP更新到最新版看到这个任务了，感谢反馈。下个版本加上这个功能。

**Comment by andywang425** [comment]
有点难搞，我手机是苹果手机抓不了HTTPS的包，安卓模拟器上的哔哩哔哩更新到了最新版又看不到这个功能。

**Comment by andywang425** [comment]
有点难搞，我手机是苹果手机抓不了HTTPS的包，安卓模拟器上的哔哩哔哩更新到了最新版又看不到这个功能。

**Comment by andywang425** [comment]
抓包抓到了，但里面那个sign参数不知道怎么算。我试了下这个api一定要用access_key鉴权，不像点赞的接口可以用web端的cookie。还得看大佬，这功能我不会写啊😭
![image](https://user-images.githubusercontent.com/56548456/198858123-97cbb635-208d-4b2c-b9e1-fce52b48f4bd.png)

**Comment by andywang425** [comment]
已在6.0.6版本中实现该功能，感谢大佬提供的库。
