### ISSUE TITLE
运行脚本后掉登录

### ISSUE THREAD

**Issue by ZedonZzz** [andywang425/BLTH#338]
### 描述bug

运行脚本后掉登录

### 重现bug

运行脚本后掉登录

### 预期行为

运行脚本后掉登录

### 运行日志

无

### 操作系统

win10

### 浏览器

Chrome107.0.5304.87

### 用户脚本管理器

油猴4.18.0

### 挂机助手版本

6.0.6

### 网络情况

一般

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
请关闭【APP用户任务】功能。

**Comment by ZedonZzz** [comment]
没有打开APP用户任务这个功能哦

**Comment by b1xcy** [comment]
把“主站每日任务”下的“登陆”关了试试，我关了这个暂时没有踢我
