### ISSUE TITLE
[APP用户任务] 领取奖励失败

### ISSUE THREAD

**Issue by GTVpigs** [andywang425/BLTH#339]
### 描述bug

APP用户任务领取奖励失败，日志显示领取奖励失败，电池也没有到账。

### 重现bug

粉丝打卡弹幕完成后，日志出现[APP用户任务] 领取奖励失败

### 预期行为

领取app任务奖励成功，收到1电池

### 截图

![image](https://user-images.githubusercontent.com/86565518/200182043-c09d46ef-a44b-492a-b349-d18322680647.png)

### 运行日志

![image](https://user-images.githubusercontent.com/86565518/200182237-945e8673-4fde-4c4c-b2eb-1963b84679f8.png)

### 操作系统

Windows10

### 浏览器

Microsoft Edge 版本 107.0.1418.35 (正式版本) (64 位)

### 用户脚本管理器

Tampermonkey 4.16.1

### 挂机助手版本

6.0.7

### 网络情况

一般

### 其他浏览器插件/脚本

B站自动抢红包，B站共同关注快速查看

**Comment by andywang425** [comment]
![image](https://user-images.githubusercontent.com/56548456/200204872-34cb0cd3-b6b9-49e8-8560-6815e2cf1cfa.png)
这两条日志的Object是什么，把里面的内容展开看一下。

**Comment by GTVpigs** [comment]
> 

重置直播任务缓存后APP用户任务奖励领取不会再运行，只能等0点了。_(:з」∠)_

**Comment by GTVpigs** [comment]
> ![image](https://user-images.githubusercontent.com/56548456/200204872-34cb0cd3-b6b9-49e8-8560-6815e2cf1cfa.png) 这两条日志的Object是什么，把里面的内容展开看一下。

重置直播任务缓存后APP用户任务奖励领取不会再运行，只能等0点了。(:з」∠)

**Comment by andywang425** [comment]
> 重置直播任务缓存后APP用户任务奖励领取不会再运行，只能等0点了。(:з」∠)

没事，不急的 (～￣▽￣)～

**Comment by GTVpigs** [comment]
> > 重置直播任务缓存后APP用户任务奖励领取不会再运行，只能等0点了。(:з」∠)
> 
> 没事，不急的 (～￣▽￣)～
> 
> 我感觉APP用户任务奖励如果重复运行容易导致B站退出登录，所以你重置直播任务缓存后APP用户任务奖励领取不会再运行。

![image](https://user-images.githubusercontent.com/86565518/200357806-b34fb914-9913-4d6b-9100-9cd82aad4436.png)
![image](https://user-images.githubusercontent.com/86565518/200358409-0440fd95-7330-4adb-9524-93497fc0208f.png)
能展开的条目太多了，不知道哪个才是有用的。

**Comment by andywang425** [comment]
> 能展开的条目太多了，不知道哪个才是有用的。

`[[Prototype]]`里面的不用展开，我已经从图里看到想看的东西了，感谢反馈。
![image](https://user-images.githubusercontent.com/56548456/200457854-ba32efb3-06e8-4174-98e4-b066835675e7.png)

按理来说，这里`target`的值应该为`5`（发5条弹幕），`progress`的值是已经发了的弹幕数量。但你这里`target`是`0`。请问你在APP端的直播间里能看到发5条弹幕领1电池的任务吗，也许你的B站账号不支持这个任务？
之后可能需要加个判断，假如`target`值为`0`就不领取奖励。

> 话说能不能加一个领取APP用户奖励的按钮？

可以考虑一下。我觉得如果脚本能正常运行那就没有加这个按钮的必要。

**Comment by GTVpigs** [comment]
> > 能展开的条目太多了，不知道哪个才是有用的。
> 
> `[[Prototype]]`里面的不用展开，我已经从图里看到想看的东西了，感谢反馈。 ![image](https://user-images.githubusercontent.com/56548456/200457854-ba32efb3-06e8-4174-98e4-b066835675e7.png)
> 
> 按理来说，这里`target`的值应该为`5`（发5条弹幕），`progress`的值是已经发了的弹幕数量。但你这里`target`是`0`。请问你在APP端的直播间里能看到发5条弹幕领1电池的任务吗，也许你的B站账号不支持这个任务？ 之后可能需要加个判断，假如`target`值为`0`就不领取奖励。
> 
> > 话说能不能加一个领取APP用户奖励的按钮？
> 
> 可以考虑一下。我觉得如果脚本能正常运行那就没有加这个按钮的必要。

看不到这个任务，更新到最新版也没有。_(:з」∠)_

**Comment by andywang425** [comment]
> 看不到这个任务，更新到最新版也没有。(:з」∠)

可能是你的账号还不能参加这个任务。再等等吧。

**Comment by catlair** [comment]
is_surplus 为-1应该是没有资格

**Comment by andywang425** [comment]
> is_surplus 为-1应该是没有资格

嗯，应该是的

**Comment by nyano** [comment]
唔。我的app奖励，控制台直接显示 用户未登录。好几天了。。但是前台都显示登录了，退出重进也没用
手动在app里打卡可以领取奖励

**Comment by andywang425** [comment]
https://github.com/andywang425/BLTH/pull/356
