### ISSUE TITLE
11.27更新后的bug

### ISSUE THREAD

**Issue by Dududade** [andywang425/BLTH#34]
这次更新的bug：
1.天选经常显示检查出错
2.昨天直播间挂了一天，发现小心心只增加了7个，我更新了页面之后又好了。
3.天选的关注人都被自动移到默认关注组了，而不是BLTH天选关注UP组
4.投币明明选的是5个，但是只投了3个
![4](https://user-images.githubusercontent.com/74051782/100496507-98e28b00-318f-11eb-9a4f-3f61e73acac5.png)
![1](https://user-images.githubusercontent.com/74051782/100496524-bc0d3a80-318f-11eb-9975-8cd979ffd886.png)
![2](https://user-images.githubusercontent.com/74051782/100496526-be6f9480-318f-11eb-84e9-a254b7842dd0.png)
![3](https://user-images.githubusercontent.com/74051782/100496534-c9c2c000-318f-11eb-9175-f37ddc921818.png)

**Comment by andywang425** [comment]
1.天选检查出错是因为B站最近管得严了，可以试着调高请求间隔和获取数据间隔。  
2.小心心的获取会在下个版本修复。  
3.请确认你的版本, 5.6有这个问题，但5.6.1应该是没有的。如果你是5.6.1的话请按README中的操作打开控制台日志，再次运行并搜索含`addUsers`的日志，把这些日志贴上来。 
4.请附上你的投币设置。只投了3个可能是bug，也可能是因为能投币的视频不足。可以按上述操作开启日志，寻找含`DailyReward`或`coin`的日志并把这些日志贴上来。  
[bug_report.md](https://github.com/andywang425/BLTH/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)可以看一下反馈格式。

**Comment by Dududade** [comment]
我重新安装了一下，分组的问题确实好了，不过投币还是有问题，我也不太懂，重新运行还是没投满，就只一个硬币投一个视频，不像之前是投2个视频各2个硬币，剩下一个投一个硬币，我也没改啥啊，挠头！
![7](https://user-images.githubusercontent.com/74051782/100514916-85491b80-31b3-11eb-8f32-74ed2c22f447.png)

**Comment by andywang425** [comment]
> 我重新安装了一下，分组的问题确实好了，不过投币还是有问题，我也不太懂，重新运行还是没投满，就只一个硬币投一个视频，不像之前是投2个视频各2个硬币，剩下一个投一个硬币，我也没改啥啊，挠头！
> ![7](https://user-images.githubusercontent.com/74051782/100514916-85491b80-31b3-11eb-8f32-74ed2c22f447.png)

虽然你没反馈控制台信息，但我大概知道问题出在哪了。。。下个版本修复。

**Comment by X-Holmes** [comment]
当前版本5.6.2
我的天选关注分组也有问题：
```
Access to XMLHttpRequest at 'https://api.live.bilibili.com/live_user/v1/UserInfo/get_anchor_in_room?roomid=12508184' from origin 'https://live.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
GET https://api.live.bilibili.com/live_user/v1/UserInfo/get_anchor_in_room?roomid=12508184 net::ERR_FAILED
Uncaught (in promise) {readyState: 0, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
GET https://live.bilibili.com/8375628 400
```
![tx01](https://user-images.githubusercontent.com/35630677/100862841-a620b200-34ce-11eb-93a3-2c08351e07d9.png)
看起来好像是被风控了？
一旦某个天选参加成功之后，脚本就会停住(主播已关注、天选页面显示已参加、分组没有移动)，后面的房间不再继续检查。
之后即使到了下一次循环的时间也不执行，整个脚本阻塞，除非刷新页面或者点击再次执行所有任务。

如果确实是风控原因导致的分组移动失败那也没办法，但是**一次风控之后脚本假死，不能自动取关、不能参加其他天选**的问题的希望可以解决一下。

另外，`debugSwitch`的开关有没有技术手段可以放在脚本面板上（我安装的是压缩版本，整个代码只有一行修改很麻烦）
其次，页面右上角大航海右侧的**面板日志**希望也可以开关，这个日志多了应该也会占用不少内存吧。

**Comment by andywang425** [comment]
是风控，脚本假死的问题我也找到原因了。  
`debugSwitch`放到面板上去应该是可行的，我自己也觉得改代码开日志有点繁琐，以后会改。  
**面板日志**这个我打算改成，若日志超过一定数量则删除一部分最早的日志。不过这个功能不一定会马上更新。

> 当前版本5.6.2
> 我的天选关注分组也有问题：
> 
> ```
> Access to XMLHttpRequest at 'https://api.live.bilibili.com/live_user/v1/UserInfo/get_anchor_in_room?roomid=12508184' from origin 'https://live.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> GET https://api.live.bilibili.com/live_user/v1/UserInfo/get_anchor_in_room?roomid=12508184 net::ERR_FAILED
> Uncaught (in promise) {readyState: 0, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
> GET https://live.bilibili.com/8375628 400
> ```
> 
> ![tx01](https://user-images.githubusercontent.com/35630677/100862841-a620b200-34ce-11eb-93a3-2c08351e07d9.png)
> 看起来好像是被风控了？
> 一旦某个天选参加成功之后，脚本就会停住(主播已关注、天选页面显示已参加、分组没有移动)，后面的房间不再继续检查。
> 之后即使到了下一次循环的时间也不执行，整个脚本阻塞，除非刷新页面或者点击再次执行所有任务。
> 
> 如果确实是风控原因导致的分组移动失败那也没办法，但是**一次风控之后脚本假死，不能自动取关、不能参加其他天选**的问题的希望可以解决一下。
> 
> 另外，`debugSwitch`的开关有没有技术手段可以放在脚本面板上（我安装的是压缩版本，整个代码只有一行修改很麻烦）
> 其次，页面右上角大航海右侧的**面板日志**希望也可以开关，这个日志多了应该也会占用不少内存吧。

**Comment by andywang425** [comment]
脚本假死已修复，控制台开关也已放到控制面板上。
**面板日志**这个我观察了一下，占的内存并不算多，保守估计10条日志占1.67kb内存，所以不打算做定时清理日志的功能了。  
如果还有问题的话再开一个issue吧。
