### ISSUE TITLE
建议加一个关闭日志栏的功能（调整日志位置）

### ISSUE THREAD

**Issue by davelish** [andywang425/BLTH#340]
### 描述

![image](https://user-images.githubusercontent.com/89334834/200781078-f0858926-776f-4789-bd63-7a33849b822d.png)

**Comment by andywang425** [comment]
请问为什么需要这个功能？日志按钮也不额外占地方呀。

**Comment by FrankHB** [comment]
> 请问为什么需要这个功能？日志按钮也不额外占地方呀。

本来用来点击的 UI 的 1/3 水平空间直接被平时基本用不上的功能占据，减小可用性。

原则上原始界面就不应该被侵入，不得不修改界面默认也不应该到处都是，必要时容易找到即可。这个位置放日志不是个很自然的选择（还不如放控制面板；但控制面板都已经外置了，那还是都放在外面比较好）。

**Comment by andywang425** [comment]
> 本来用来点击的 UI 的 1/3 水平空间直接被平时基本用不上的功能占据，减小可用性。
> 
> 原则上原始界面就不应该被侵入，不得不修改界面默认也不应该到处都是，必要时容易找到即可。这个位置放日志不是个很自然的选择（还不如放控制面板；但控制面板都已经外置了，那还是都放在外面比较好）。

同意，原始界面是不应该被侵入，当初的我还不懂这个道理…… 以后有空了应该改改。
