### ISSUE TITLE
21级以上的粉丝勋章模拟观看不起作用

### ISSUE THREAD

**Issue by lucifere02** [andywang425/BLTH#341]
### 描述bug

【模拟观看直播功能】启用后，我的21级粉丝勋章及以上（也就是开通过大航海的）的UP主的亲密度获取依然为0，但是低等级的模拟观看获取亲密度一切正常，是什么原因呢。

### 重现bug

同上

### 预期行为

21级以上的粉丝牌对应的主播也能完成模拟观看任务获取亲密度

### 截图

![image](https://user-images.githubusercontent.com/86308431/205203587-51127462-bf93-49dc-902f-8fd289f05e8f.png)
如图所示，最上方三个亲密度增加为0的是21级以上的牌子，下面亲密度拉满的是20级以下的粉丝牌子。想知道为什么最上面的三个失效了

### 运行日志

![~VKPJP3(__JG DFCMDKU0GT](https://user-images.githubusercontent.com/86308431/205205172-772c1d91-df50-4bae-93be-456f5ae4b9fb.png)

### 操作系统

Windows11

### 浏览器

Chrome 107.0.5304.123

### 用户脚本管理器

油猴 4.18.1

### 挂机助手版本

6.0.7

### 网络情况

好

### 其他浏览器插件/脚本

bilibili evolved

### 其他

另外还想了解一下，我看到以前是又一个直播天选时刻自动抽奖的功能的，我觉得很有用，为什么去掉了这个功能呢，。
最后感谢一下大佬，这个脚本功能很棒，很有用！

**Comment by andywang425** [comment]
21级以上的粉丝勋章无法通过看直播获取亲密度，详见B站粉丝勋章升级规则：https://link.bilibili.com/p/help/index#/audience-fans-medal

> 以前是又一个直播天选时刻自动抽奖的功能的，我觉得很有用，为什么去掉了这个功能呢

做抽奖功能有法律风险。以前随便搜搜就能找到不少B站的免费抽奖脚本，但后来B站管得严了，开始让各大平台（比如github，greasyfork）下架这些脚本。我以前还收到过B站发的律师警告函让我下架我参与开发的另一个项目。所以我深思熟虑后决定删除BLTH抽奖相关的功能，主要是为了自保。

**Comment by 8MiYile** [comment]
@andywang425 
建议close&not planed

**Comment by andywang425** [comment]
> @andywang425 建议close&not planed

谢谢提醒
