### ISSUE TITLE
APP用户任务失败，显示账号未登录

### ISSUE THREAD

**Issue by unprintable123** [andywang425/BLTH#347]
### 描述bug

APP用户任务领取奖励失败，日志显示用户未登录，但只有APP用户任务运行异常。

### 重现bug

每次进入直播间日志都会报错APP任务

### 预期行为

领取app任务奖励成功，收到1电池

### 运行日志

![image](https://user-images.githubusercontent.com/113123461/210134067-434f1465-d1e8-41b7-909f-4989e6595ee2.png)

### 操作系统

Windows 10

### 浏览器

Chrome 108.0.5359

### 用户脚本管理器

Tampermonkey 4.18.1

### 挂机助手版本

6.0.8

### 网络情况

好

### 其他浏览器插件/脚本

adblock plus, bilibili evolved

**Comment by andywang425** [comment]
请问你在手机上的B站APP里能不能参加看直播领电池的这个活动？

**Comment by andywang425** [comment]
我今天用了下脚本，发现我这APP用户任务也不行了，错误信息是：
> [APP用户任务] 获取进度失败: 鉴权失败，请联系账号组

我再琢磨琢磨怎么解决。

**Comment by andywang425** [comment]
https://github.com/andywang425/BLTH/pull/356
