### ISSUE TITLE
“禁止p2p上传”功能失效

### ISSUE THREAD

**Issue by GTVpigs** [andywang425/BLTH#349]
### 描述bug

勾选“禁止p2p上传”后打开直播间，视频统计信息里的Player Core后面括号为“SistersFetcher”，上传速度超过1MB/s。
刷新直播间或者重新勾选并刷新后依旧无效。

### 重现bug

如上

### 预期行为

打开直播间后Player Core为“Fetch”，且上传速度小于100kb/s

### 截图

![image](https://user-images.githubusercontent.com/86565518/212114447-0a432533-d3d3-4299-a17b-9be5f6b8fb34.png)
![image](https://user-images.githubusercontent.com/86565518/212114570-faff30b1-8a52-4490-932f-e2e383ed54da.png)
![image](https://user-images.githubusercontent.com/86565518/212114920-597990ab-84d8-4afb-8307-b18ea6580531.png)

### 运行日志

![image](https://user-images.githubusercontent.com/86565518/212114267-0e561def-f99a-4cc7-bfac-bf1f698dfff7.png)

### 操作系统

Windows10

### 浏览器

Microsoft Edge 108.0.1462.76 (正式版本) (64 位)

### 用户脚本管理器

Tampermonkey 4.18.1

### 挂机助手版本

6.0.8

### 网络情况

好

### 其他浏览器插件/脚本

uBlock

**Comment by andywang425** [comment]
可能是B站搞了什么新的上传方式，我再研究一下。
