### ISSUE TITLE
打卡弹幕偶尔会显示内容非法

### ISSUE THREAD

**Issue by Decwar** [andywang425/BLTH#35]
**描述bug**  
打卡弹幕偶尔会有反馈内容非法

**重现bug**  
三天中四十多个牌子出现了两次

**截图**  
![image](https://user-images.githubusercontent.com/27797230/101258635-c666a000-375e-11eb-9070-7d3713baf0fd.png)
![image](https://user-images.githubusercontent.com/27797230/101258624-a7680e00-375e-11eb-9908-7ac18fb91dd1.png)

**运行日志**  
![image](https://user-images.githubusercontent.com/27797230/101258674-19d8ee00-375f-11eb-935d-dc8244e35e68.png)

**使用环境:**  
 - 操作系统：Windows 10`
 - 浏览器及浏览器版本: Chrome 87.0.4280.66（正式版本）64位
 - 脚本的版本: 5.6.3.1`
 - 网络情况(网速): 正常
 - 其他浏览器插件/脚本: bilibili evolved

**其他**  
直播中心中确认了该牌没有成功弹幕打卡。
如果是短时间发过多弹幕的原因，是否能增加在收到内容非法的反馈后，几秒后再次尝试发送打卡弹幕的功能

**Comment by andywang425** [comment]
了解了，等我找到原因后会做调整

**Comment by Decwar** [comment]
![image](https://user-images.githubusercontent.com/27797230/101630793-5312a600-3a5e-11eb-81b9-1e3774a2368d.png)

更新后问题仍存在，我试着把延时换成2秒再看看这几天

**Comment by Decwar** [comment]
> ![image](https://user-images.githubusercontent.com/27797230/101630793-5312a600-3a5e-11eb-81b9-1e3774a2368d.png)
> 
> 更新后问题仍存在，我试着把延时换成2秒再看看这几天

今天又出现一次，前几天没有

**Comment by andywang425** [comment]
5.6.4版本加入了打卡弹幕间隔时间设置，你可以把间隔调大一点再试试。

**Comment by Decwar** [comment]
> 5.6.4版本加入了打卡弹幕间隔时间设置，你可以把间隔调大一点再试试。

好的麻烦开发者了 其实2秒的时候抽风率就基本小于0.5%了
