### ISSUE TITLE
建议增加屏蔽直播间送花弹框的功能

### ISSUE THREAD

**Issue by luikhh** [andywang425/BLTH#350]
### 描述

![log](https://user-images.githubusercontent.com/30046009/212457558-298d51e8-4662-4c07-bf04-6db4c7ced13e.jpg)
观看直播时，该弹框会随机在右下方弹出，影响观看体验

**Comment by andywang425** [comment]
我太久不看直播都不知道出了这个，会加上这个功能的。

**Comment by zqdlly** [comment]
> 我太久不看直播都不知道出了这个，会加上这个功能的。

阿b很搞笑,在自己直播间也总是给我弹出这个,即使明明送不出去
