### ISSUE TITLE
部分粉丝牌无法增加亲密度

### ISSUE THREAD

**Issue by szmarcos** [andywang425/BLTH#352]
### 描述bug

部分粉丝牌在挂机的情况下无法增加亲密度，显示为0

### 重现bug

日常点开直播间

### 预期行为

亲密度1500/1500

### 截图

![image](https://user-images.githubusercontent.com/93978296/214468962-efea6c4f-a604-4680-97c6-59125708082f.png)

### 运行日志

![image](https://user-images.githubusercontent.com/93978296/214469235-a9dc1a18-b2a8-45e9-972a-b34fabb6e571.png)

### 操作系统

Win10 22H2

### 浏览器

Chrome  109.0.5414.75

### 用户脚本管理器

Tampermonkey 4.18.1

### 挂机助手版本

6.0.8

### 网络情况

好

### 其他浏览器插件/脚本

bilibili直播间工具

**Comment by Tsingyun** [comment]
我也遇到了这个问题，只能通过反复重置直播任务缓存来解决

**Comment by luikhh** [comment]
我也遇到了，现在只能每天重置几次任务缓存

**Comment by AaronDulles** [comment]
我还以为是我粉丝牌太多了，b站限制，删了好多牌子，原来是Bug

**Comment by hyouice** [comment]
> 我还以为是我粉丝牌太多了，b站限制，删了好多牌子，原来是Bug

BUG吗？我是最后面几个总是无法加满，只有200，其它的偶尔加不满但是可以重置解决。

**Comment by yangyangbuxiangyang** [comment]
![image](https://user-images.githubusercontent.com/114185862/235365010-e9f2c6ad-424f-479b-bd29-b04297c237cf.png)
![image](https://user-images.githubusercontent.com/114185862/235365013-c702c849-8c39-4e0b-adae-ebafaa74974a.png)
我也是，只能一遍遍的重置直播任务缓存，再加上现在有bug打开直播间的时候还总是得不停地刷新才能正常启动。

**Comment by xuwenchao980507** [comment]
我只有卡200亲密度的情况，搞不懂什么原因，重置缓存都没用
