### ISSUE TITLE
可否加上分组功能，奇数天打卡这一组，偶数天打卡另一组

### ISSUE THREAD

**Issue by jakaz1280** [andywang425/BLTH#359]
### 描述

B站粉丝勋章以前有200个的限制，现在放宽到了一千个，但是，很多地方还是限制两百个，比如弹幕打卡只有两百个有效，观看加亲密度也只能同时开两百个，当粉丝勋章超过两百个以后，会有一些粉丝勋章必然没有有效的打卡弹幕而灰掉，观看时长也只有第一个100亲密度能加上，分组后交替打卡起码可以让粉丝勋章不会变灰

**Comment by LRS1638** [comment]
这个好像可以用白名单来实现吧，不过很麻烦就是了

**Comment by andywang425** [comment]
如果目的是让所有粉丝勋章都不会变灰，我想也许有更好的解决办法。这个issue先开着，大伙也可以提点意见。

**Comment by lhz68** [comment]
> 如果目的是让所有粉丝勋章都不会变灰，我想也许有更好的解决办法。这个issue先开着，大伙也可以提点意见。

目前每天的弹幕打卡应该都是按照固定的顺序，导致打不上卡的都是同一批牌子，是否可以每天正序反序轮流来
