### ISSUE TITLE
对代码贡献指南中的疑问

### ISSUE THREAD

**Issue by feiyangbeyond** [andywang425/BLTH#361]
### 描述

> （本步骤可忽略）给资源文件添加用于校验子资源完整性的 md5 值。运行/assets/js/development/目录下的addRequireMd5.js得到新的脚本元数据，结果会被保存到剪切板。用剪切板中的内容覆盖脚本的头部元数据即可。注意，如果部分 md5 计算失败而你想要手动加上 md5 的话，需计算从 cdn 获取到的内容的 md5，不能直接计算本地文件的 md5，因为上传到 cdn 之后文件的 md5 可能会变化（但是内容不会变，可能是换行符之类的导致的）。

这里的md5指的什么？

`// @require        https://gcore.jsdelivr.net/gh/andywang425/BLTH@bca9261faa84ffd8f804c85c1a5153d3aa27a9a3/assets/js/library/Ajax-hook.min.js` 指的是 `bca9261faa84ffd8f804c85c1a5153d3aa27a9a3` 这一串吗？

如果是的话：

每次发布新版本可以打个tag，如：`6.1.0`，这样在元数据引用文件的时候就可以这样：

```
// @require        https://gcore.jsdelivr.net/gh/andywang425/BLTH@bca9261faa84ffd8f804c85c1a5153d3aa27a9a3/assets/js/library/Ajax-hook.min.js


// @require        https://gcore.jsdelivr.net/gh/andywang425/BLTH@6.1.0/assets/js/library/Ajax-hook.min.js
```

**Comment by andywang425** [comment]
是的，之所以不用打tag的方式是因为这个脚本还在[greasyfork](https://greasyfork.org/zh-CN/scripts/406048-b%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B)上发布，但是greasyfork对`@require`的链接是有限制的，具体要求可见<https://greasyfork.org/zh-CN/help/cdns>。

**Comment by feiyangbeyond** [comment]
> 是的，之所以不用打tag的方式是因为这个脚本还在[greasyfork](https://greasyfork.org/zh-CN/scripts/406048-b%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B)上发布，但是greasyfork对`@require`的链接是有限制的，具体要求可见https://greasyfork.org/zh-CN/help/cdns。

好的，是我的问题了
