### ISSUE TITLE
屏蔽网页全屏和全屏时候的礼物栏

### ISSUE THREAD

**Issue by RtYkk** [andywang425/BLTH#362]
### 描述

![chrome_rf7hccJLYY](https://user-images.githubusercontent.com/45971730/226515587-fba5f106-a74b-4336-ab1f-7a119973ac21.png)
![chrome_luy2jUC39E](https://user-images.githubusercontent.com/45971730/226515837-fc85ac05-25dd-4b5c-b550-15a098d5974d.png)

这新 layout 就尼玛离谱，连他妈个折叠选项都没有，跟牛皮藓一样。礼物栏就粘在最下面。

**Comment by eTATr** [comment]
点画质旁边那个🎁图标能关
![屏幕截图 2023-03-27 201934](https://user-images.githubusercontent.com/83582854/227939982-6bd28946-c63f-4cb8-94b2-124a7b6cf510.png)

**Comment by eTATr** [comment]
点画质旁边那个礼物图标🎁能关

**Comment by andywang425** [comment]
行，那就不做了
