### ISSUE TITLE
gcore.jsdelivr.net网站无法访问，无法获取脚本依赖

### ISSUE THREAD

**Issue by yuijker** [andywang425/BLTH#365]
### 描述bug

当安装版本6.1.0时，脚本依赖gcore.jsdelivr.net现在已经无法连接，无法获取脚本依赖文件。

### 重现bug

1.安装脚本6.1.0
2.试图进入直播间
3.脚本没有依赖，无法启动。

### 预期行为

脚本正常启动

### 截图

ping gcore.jsdelivr.net 检测结果
![image](https://user-images.githubusercontent.com/72558803/227776790-e9237c97-a15e-4f31-97ea-33cb6e5322b1.png)

![image](https://user-images.githubusercontent.com/72558803/227776813-edf6182f-ed7c-449d-a7e5-a8a882b86c0f.png)

curl 访问结果
![image](https://user-images.githubusercontent.com/72558803/227776839-4ee7d4d1-360a-447f-9570-ca3dd55e4f79.png)

访问直播间10分钟后，仍然未出现设置界面
![image](https://user-images.githubusercontent.com/72558803/227776952-ea06f4bc-c9a1-49f7-8f5d-b4bc5697a5ad.png)

### 运行日志

无法运行，无法导出日志

### 操作系统

windows 10

### 浏览器

edge 111.0.1661.54

### 用户脚本管理器

Tampermonkey 4.18.1

### 挂机助手版本

6.1.0

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
看来大陆是都连不上了，晚点我更新一个版本把gcore.jsdelivr.net换成fastly.jsdelivr.net

**Comment by andywang425** [comment]
已更新 #366
