### ISSUE TITLE
和扩展程序 Minyami 冲突

### ISSUE THREAD

**Issue by YuukiHibiki** [andywang425/BLTH#369]
### 描述bug

扩展程序 Minyami 与 blth 脚本同时启动时，无法看到自己发送的弹幕，需要刷新
发生冲突的chrome插件项目地址
**插件地址** https://chrome.google.com/webstore/detail/minyami/cgejkofhdaffiifhcohjdbbheldkiaed** 
**该插件搭配的后端nodejs项目** https://github.com/Last-Order/Minyami 

### 重现bug

1. 同时启动插件Minyami和blth脚本
2. 在任意直播间发送弹幕
3. 无法看到自己发送的弹幕，其他用户发送的弹幕正常
4. 刷新网页才可看到刚才自己发送的弹幕

### 预期行为

和 minyami 插件可以同时使用，并正常显示发送的弹幕

### 运行日志

**前面运行是正常的就不导过来了**
[BLTH][22:9:57:90] API.x.vip.privilege.my response: {code: 0, message: '0', ttl: 1, data: {…}}

**在发送弹幕后，console只多出现了本条日志**
[BLTH][22:10:3:642] API.xlive.wearMedal: {code: 0, message: '佩戴成功', ttl: 1, data: {…}}

**刷新后的日志**
sentry-5.2.1.min.js:2 [BLTH][22:11:30:81] toast-info: 正在获取礼物 / 用户 / 账号 / 粉丝勋章数据...
sentry-5.2.1.min.js:2 [BLTH][22:11:30:896] InitData: API.gift.gift_config: {code: 0, msg: '', message: '', data: Array(551)}
sentry-5.2.1.min.js:2 [BLTH][22:11:31:146] InitData: API.getuserinfo: {code: 'REPONSE_OK', msg: 'success', message: 'success', data: {…}}
sentry-5.2.1.min.js:2 [BLTH][22:11:31:283] InitData: API.x.getAccInfo: {code: 0, message: '0', ttl: 1, data: {…}}
sentry-5.2.1.min.js:2 [BLTH][22:11:31:285] Live_info: {room_id: 10112, short_room_id: 10112, uid: 11568509, ruid: 1590370, gift_list: Array(551), …}bili_jct: "faed5effcfa7de8997de8f2450f2ae7d"danmu_length: undefinedgift_list: (551) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, …]level: 6medal: undefinedrnd: 1680790286room_id: 10112ruid: 1590370short_room_id: 10112tid: 1590370uid: 11568509uname: "結城ひびき"user_level: 15vipStatus: 1visit_id: "1v48t28ma4gw"[[Prototype]]: Object
sentry-5.2.1.min.js:2 [BLTH][22:11:31:437] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
sentry-5.2.1.min.js:2 [BLTH][22:11:31:768] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
sentry-5.2.1.min.js:2 [BLTH][22:11:31:769] runTomorrow: 获取粉丝勋章列表 Fri Apr 07 2023 00:01:00 GMT+0800 (中国标准时间)
sentry-5.2.1.min.js:2 [BLTH][22:11:31:769] medla_info: {status: {…}, medal_list: Array(15)}
sentry-5.2.1.min.js:2 [BLTH][22:11:31:791] chatLog: 脚本载入配置成功
sentry-5.2.1.min.js:2 [BLTH][22:11:31:791] toast-success: CACHE载入成功
sentry-5.2.1.min.js:2 [BLTH][22:11:31:808] MY_API.CONFIG: {AUTO_DANMU: false, AUTO_GIFT: false, AUTO_GIFT_ROOMID: Array(6), AUTO_GROUP_SIGN: true, COIN: false, …}
sentry-5.2.1.min.js:2 [BLTH][22:11:31:810] runExactMidnight: 重置统计 Fri Apr 07 2023 00:00:00 GMT+0800 (中国标准时间)
sentry-5.2.1.min.js:2 [BLTH][22:11:36:860] runMidnight: 粉丝勋章打卡弹幕 Fri Apr 07 2023 00:01:00 GMT+0800 (中国标准时间)
sentry-5.2.1.min.js:2 [BLTH][22:11:37:55] runTomorrow: 应援团签到 Fri Apr 07 2023 08:01:00 GMT+0800 (中国标准时间)
sentry-5.2.1.min.js:2 [BLTH][22:11:37:255] runMidnight: 主站任务 - 登录 Fri Apr 07 2023 00:01:00 GMT+0800 (中国标准时间)
sentry-5.2.1.min.js:2 [BLTH][22:11:37:256] runMidnight: 主站任务 - 观看视频 分享视频  Fri Apr 07 2023 00:01:00 GMT+0800 (中国标准时间)
sentry-5.2.1.min.js:2 [BLTH][22:11:37:455] runMidnight: 直播区 - 直播签到 Fri Apr 07 2023 00:01:00 GMT+0800 (中国标准时间)
sentry-5.2.1.min.js:2 [BLTH][22:11:37:456] toast-info: [观看直播] 开始模拟观看直播
sentry-5.2.1.min.js:2 [BLTH][22:11:37:459] runMidnight: 直播区 - 点赞 Fri Apr 07 2023 00:01:00 GMT+0800 (中国标准时间)
sentry-5.2.1.min.js:2 [BLTH][22:11:38:727] API.x.vip.privilege.my response: {code: 0, message: '0', ttl: 1, data: {…}}

### 操作系统

windows11

### 浏览器

chrome 111.0.5563.148

### 用户脚本管理器

暴力猴 2.14.0

### 挂机助手版本

BLTH 6.1.2

### 网络情况

好

### 其他浏览器插件/脚本

仅Minyami，关闭后就正常了

**Comment by andywang425** [comment]
好的，以后会排查原因
