### ISSUE TITLE
脚本运行失败，控制台提示接口存在跨域情况

### ISSUE THREAD

**Issue by 7NishinoNanase** [andywang425/BLTH#370]
### 描述bug

控制台爆红，粉丝牌经验不增加

### 重现bug

挂机无操作

### 预期行为

粉丝牌经验增加

### 截图

![image](https://user-images.githubusercontent.com/51400361/231053803-4a36c4f7-d528-416c-89d4-f98d7147b693.png)

### 运行日志

[BLTH][12:1:40:666] toast-info: 正在获取礼物 / 用户 / 账号 / 粉丝勋章数据...
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:41:670] InitData: API.gift.gift_config: {code: 0, msg: '', message: '', data: Array(545)}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:42:57] InitData: API.getuserinfo: {code: 'REPONSE_OK', msg: 'success', message: 'success', data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:42:305] InitData: API.x.getAccInfo: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:42:321] Live_info: {room_id: 5749545, short_room_id: 5749545, uid: 33878056, ruid: 208130286, gift_list: Array(545), …}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:42:508] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:43:354] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:43:648] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:43:937] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:44:255] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:44:620] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:44:915] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:45:202] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:45:484] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:45:765] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:46:48] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:46:347] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:46:654] before init() getMedalList: API.i.medal: {code: 0, message: '0', ttl: 1, data: {…}}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:46:654] runTomorrow: 获取粉丝勋章列表 Wed Apr 12 2023 00:01:00 GMT+0800 (中国标准时间)
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:46:654] medla_info: {status: {…}, medal_list: Array(124)}
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:46:700] chatLog: 脚本载入配置成功
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:46:703] toast-success: CACHE载入成功
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:46:720] MY_API.CONFIG: {APP_TASK: false, AUTO_DANMU: false, AUTO_CHECK_DANMU_TIMEOUT: 3000, AUTO_GIFT: false, AUTO_GIFT_ROOMID: Array(1), …}APP_TASK: falseAUTO_CHECK_DANMU_TIMEOUT: 3000AUTO_DANMU: falseAUTO_GIFT: falseAUTO_GIFT_ROOMID: ['0']AUTO_GROUP_SIGN: trueCOIN: falseCOIN2SILVER: falseCOIN2SILVER_NUM: 1COIN_NUMBER: 0COIN_TYPE: "COIN_DYN"COIN_UID: ['0']DANMU_CONTENT: ['这是一条弹幕']DANMU_INTERVAL_TIME: ['10m']DANMU_MODIFY_COLOR: ['#f7335d']DANMU_MODIFY_POOL: [4]DANMU_MODIFY_REGEX: ['/【/']DANMU_MODIFY_SIZE: [1.2]DANMU_MODIFY_UID: [0]DANMU_ROOMID: ['22474988']GET_PRIVILEGE: falseGIFT_ALLOW_TYPE: (2) ['1', '6']GIFT_INTERVAL: 5GIFT_LIMIT: 1GIFT_METHOD: "GIFT_SEND_TIME"GIFT_SEND_HOUR: 23GIFT_SEND_METHOD: "GIFT_SEND_BLACK"GIFT_SEND_MINUTE: 59GIFT_SEND_ROOM: ['0']GIFT_SORT: "GIFT_SORT_HIGH"LIKE_LIVEROOM: trueLIKE_LIVEROOM_INTERVAL: 400LIVE_SIGN: trueLIVE_TASKS_METHOD: "LIVE_TASKS_BLACK"LIVE_TASKS_ROOM: (2) ['22726745', '7211707']LOGIN: trueMEDAL_DANMU: falseMEDAL_DANMU_CONTENT: ['6']MEDAL_DANMU_INTERVAL: 2REMOVE_ELEMENT_2233: falseREMOVE_ELEMENT_anchor: falseREMOVE_ELEMENT_ecommerce: falseREMOVE_ELEMENT_flipView: trueREMOVE_ELEMENT_pk: falseREMOVE_ELEMENT_pkBanner: trueREMOVE_ELEMENT_playerIcon: trueREMOVE_ELEMENT_rank: trueREMOVE_ELEMENT_rightSideBar: falseRND_DELAY_END: 5RND_DELAY_START: 2SEND_ALL_GIFT: falseSHARE: falseSILVER2COIN: falseSPARE_GIFT_ROOM: "0"TIME_RELOAD: falseTIME_RELOAD_MINUTE: 120UPDATE_TIP: trueWATCH: falseWatchLive: trueWatchLiveInterval: 400WatchLiveTime: 75[[Prototype]]: Object
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:46:721] runExactMidnight: 重置统计 Wed Apr 12 2023 00:00:00 GMT+0800 (中国标准时间)
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:52:106] runTomorrow: 应援团签到 Wed Apr 12 2023 08:01:00 GMT+0800 (中国标准时间)
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:52:304] runMidnight: 主站任务 - 登录 Wed Apr 12 2023 00:01:00 GMT+0800 (中国标准时间)
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:52:505] runMidnight: 直播区 - 直播签到 Wed Apr 12 2023 00:01:00 GMT+0800 (中国标准时间)
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:52:505] toast-info: [观看直播] 开始模拟观看直播
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:1:52:509] runMidnight: 直播区 - 点赞 Wed Apr 12 2023 00:01:00 GMT+0800 (中国标准时间)
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:5:0:673] 屏蔽挂机检测: 触发一次MouseEvent(mousemove)
userscript.html?id=1a5ccda1-7eea-4239-9b99-29b8d281f83b:214 [BLTH][12:8:20:668] 屏蔽挂机检测: 触发一次MouseEvent(mousemove)

### 操作系统

win10

### 浏览器

Microsoft Edge 112.0.1722.34 (正式版本) (64 位)

### 用户脚本管理器

Tampermonkey 4.5

### 挂机助手版本

6.1.2

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by andywang425** [comment]
我在Chrome下测试正常。有其他人存在这个情况吗？

**Comment by 7NishinoNanase** [comment]
> 我在Chrome下测试正常。有其他人存在这个情况吗？

今天没报错，可以正常使用
