### ISSUE TITLE
控制面板不显示

### ISSUE THREAD

**Issue by gsdfqaq** [andywang425/BLTH#371]
### 描述bug

进入直播间后不显示控制面板按键

### 重现bug

进入直播间后不显示控制面板按键

### 预期行为

出现控制面板修改内容

### 截图

![MQA~4}DYE MD0R1G_5O(0O7](https://user-images.githubusercontent.com/130563908/231449803-6baaa538-3f6a-4842-b8f8-1c751e7d228a.png)

### 运行日志

-
![QQ截图20230412195324](https://user-images.githubusercontent.com/130563908/231449261-b72d2e1f-0e6e-443e-90b3-a82f62c052f1.png)

### 操作系统

win10

### 浏览器

Microsoft Edge版本 112.0.1722.34 (正式版本) (64 位)

### 用户脚本管理器

油猴4.18.1

### 挂机助手版本

6.1.2

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by hejanward** [comment]
![Snipaste_2023-04-21_21-03-03](https://user-images.githubusercontent.com/62329855/233642873-3390c040-f210-4712-8877-b16bfc936ef5.png)
挺好的，我每隔5分钟出来一个控制面板

**Comment by hejanward** [comment]
![Uploading Snipaste_2023-04-21_21-21-31.png…]()

**Comment by benaify** [comment]
+1

**Comment by wfile-gt** [comment]
> ![Snipaste_2023-04-21_21-03-03](https://user-images.githubusercontent.com/62329855/233642873-3390c040-f210-4712-8877-b16bfc936ef5.png) 挺好的，我每隔5分钟出来一个控制面板

我也是，突然有一天更新就有了。很难受
