### ISSUE TITLE
报错API.x.getAccinfo获取账号信息失败 状态码200

### ISSUE THREAD

**Issue by lhz68** [andywang425/BLTH#372]
### 描述bug

4月20日突发无规律报 “API.x.getAccinfo获取账号信息失败 状态码200” 且不出现控制按钮，多次尝试打开直播间有时成功加载，有时报错

### 重现bug

使用了多台设备、不同浏览器、不同账号、不同网络尝试打开直播间均有出现报错情况

### 预期行为

打开直播间后正常加载脚本

### 截图

![image](https://user-images.githubusercontent.com/55624298/233310453-5ce805cb-f312-4d44-997a-51a8b2eeef61.png)

### 运行日志

InitData: API.x.getAccInfo: {code: 200, message: '状态码: 200', msg: '状态码: 200', netError: true}

### 操作系统

windows11 22H2 / server 2022 21H2

### 浏览器

Edge 112.0.1722.48 / Chrome 112.0.5615.138

### 用户脚本管理器

Tampermonkey v4.18.1

### 挂机助手版本

6.1.2

### 网络情况

好

### 其他浏览器插件/脚本

Bilibili Evolved	2.7.0 / AdBlock 5.4.1

**Comment by tskyan** [comment]
好快，刚出问题想来看看就发现有人提了

**Comment by andywang425** [comment]
发现一个有意思的事情，如果开着开发者控制打开页面就不会有这个问题，反之一定会出问题。正在进一步排查中。

**Comment by andywang425** [comment]
大概明白为什么了，B站限制了`//api.bilibili.com/x/space/acc/info`这个接口的请求速率，所以频繁刷新页面的话就会出现这个问题。先再观望一下，之后会想办法解决。
```json
{"code":-509,"message":"请求过于频繁，请稍后再试","ttl":1}
```

**Comment by RAINighty** [comment]
> 这个问题好像还会导致同时出现多个控制面板……最高遇到过三个 ![chrome_qQ9dBAFkq9](https://user-images.githubusercontent.com/45971730/233351287-477d2b41-7944-460e-8c28-697128ca7c26.png)
![K{$)LWA92V8W`F)_AS_48Y6](https://user-images.githubusercontent.com/97167694/233425249-4e8db190-c9cb-437d-9f4d-343b779f075b.png)
是的我也遇到了这个问题

**Comment by letterk** [comment]
我也遇到了, 多个控制面板, 还有油猴多出来了许多脚本

**Comment by FiaoxR** [comment]
遇到了同样的问题

**Comment by lytDARK** [comment]
这个现在有什么解决办法吗？
比如降低调用频率之类的？

**Comment by As-Newbie** [comment]
会报错但是过一会儿能够正常运行

**Comment by plokid** [comment]
![图片](https://user-images.githubusercontent.com/72876162/233590241-44c3aadb-bcb8-4c94-8e1f-20be8b495000.png)
地狱绘图

**Comment by qhmorz** [comment]
win10 edge也出现这种情况

**Comment by prediction63** [comment]
> 发现一个有意思的事情，如果开着开发者控制台打开页面就不会有这个问题，反之一定会出问题。正在进一步排查中。

特意注册来感谢作者，确实F12打开控制台再刷新网页可以正常使用

**Comment by FiaoxR** [comment]
> > 这个问题好像还会导致同时出现多个控制面板……最高遇到过三个 ![chrome_qQ9dBAFkq9](https://user-images.githubusercontent.com/45971730/233351287-477d2b41-7944-460e-8c28-697128ca7c26.png)
> 
> ![K{$)LWA92V8W`F)_AS_48Y6](https://user-images.githubusercontent.com/97167694/233425249-4e8db190-c9cb-437d-9f4d-343b779f075b.png) 是的我也遇到了这个问题，而且无法关闭 而且右上角的油猴会显示加载了20个脚本，但实际上这个页面统共6个脚本，只有4个是开启的

![image](https://user-images.githubusercontent.com/35568304/233692523-5a65a5ea-3dc8-4674-90ed-b6ec2d39f26b.png)

**Comment by Mayi233** [comment]
问题相同问题，报错码200，长期挂直播间会多个控制面板。环境：win10 2004, chrome 109.0.5414.121
#373 [](url)

**Comment by luikhh** [comment]
开着控制台打开页面会报错
ntry-5.2.1.min.js:2 /getLeftEntryList error 请求失败，请您稍后再试：未获取到 code 值, 疑似接口格式错误或网络已断开 (´；ω；`)

但是200那个报错就没有了
![image](https://user-images.githubusercontent.com/30046009/233781094-65575689-eedf-4cd6-a7ad-69d5e0c7c47f.png)

**Comment by GongT** [comment]
我这里开不开控制台都这样

**Comment by LRS1638** [comment]
这个好像在后台挂一会就好了

**Comment by gsdfqaq** [comment]
我也是，脚本也偶尔用不了

**Comment by lhfhybxm** [comment]
![56_msedge_day23](https://user-images.githubusercontent.com/98946561/233841950-40534671-282e-4536-8a66-9fcd7aa76b95.png)
同上，等待解决中……

**Comment by Hiiro570** [comment]
+1，前几天刷新多几次还能加载出来现在刷新很多次都刷新不出来了，关掉其他所有插件和开着控制台刷新都没用
![QQ截图20230425203022](https://user-images.githubusercontent.com/88080039/234278509-65834f9d-f8ed-43bf-af98-1b769c7cef59.png)

**Comment by Hiiro570** [comment]
> +1，前几天刷新多几次还能加载出来现在刷新很多次都刷新不出来了，关掉其他所有插件和开着控制台刷新都没用 ![QQ截图20230425203022](https://user-images.githubusercontent.com/88080039/234278509-65834f9d-f8ed-43bf-af98-1b769c7cef59.png)

但是挂着一段时间后开始群魔乱舞，但是还是会弹错误《[报错API.x.getAccinfo获取账号信息失败 状态码200]》，打开日志看是一片空白的
![QQ截图20230425204228](https://user-images.githubusercontent.com/88080039/234280402-36e521d9-d0d8-45ae-8357-d5c978b3603a.png)
![QQ截图20230425204234](https://user-images.githubusercontent.com/88080039/234280433-e56b294d-285b-44e1-90fb-0fb8340e686f.png)
![QQ截图20230425204422](https://user-images.githubusercontent.com/88080039/234280462-4dd7a158-f1dd-48e1-91de-082d44b2c24b.png)

**Comment by Zeddddd** [comment]
![image](https://user-images.githubusercontent.com/37978030/234618856-d2322e9c-23e7-4341-8853-b66de21674cd.png)
现在这个堆积有些多了

**Comment by OpportunityLiu** [comment]
感觉还是B站的问题，这个响应直接变成一个错误响应和一个正常响应混在一起了，限制调用频率哪有这么限的。。
![image](https://user-images.githubusercontent.com/13471233/235057508-5403fcb2-3973-4428-8820-254694d35075.png)

**Comment by andywang425** [comment]
该问题已在6.1.3版本中修复。
