### ISSUE TITLE
时不时会自动弹出设置窗口

### ISSUE THREAD

**Issue by grandsong** [andywang425/BLTH#374]
### 补充

我手动照着 https://github.com/andywang425/BLTH/pull/375/files 修改了我浏览器中的脚本后，目前似乎解决问题了。

多谢补丁贡献者 kinabcd 。希望 andywang425 能及早发布。

### 再补充

@SameIe 说“改完后亲密度加很慢后面甚至开始不加”。

我是不在意的，但如果你在意，那么可以这样：用扩展 Stylus 覆盖CSS，把弹出窗口的 `display` 设为 "none"。毕竟我们很少会修改设置，所以干脆屏蔽算了。万一需要修改，那么临时禁用 Stylus 的规则即可。

----

我试着反反复复调整了设置的各种组合，但目前还没有发现禁用哪一项可以避免本bug……

今天弹出的频率变低了，但依然有。

有时候，按 Alt+B 无法弹出正常的窗口。即使重启浏览器也如此。

### 描述bug

我在Edge浏览器中，使用本脚本几个月了。但最近半个月以来，时不时会自动弹出设置窗口。

大部分情况下，弹出的是虚假的：该窗口中，所有选项都是初始状态。但有时又是真正的……

当存在虚假的窗口时，如果我按`Alt+B` ，会在该窗口下方弹出真正的设置窗口。后者被遮挡，幸好，阴影效果让我得以看出区别。我用开发者工具修改前者的css left属性，可以让后者露出来。

再按`Alt+B` ，只会收起真正的。

这种虚假的设置窗口，会越来越多。

### 重现bug

触发时机没有规律。一般会间隔几分钟，但也有短时间里接连出现的情况。

跟同时开几个直播页面无关。

跟我的操作无关。

跟页面打开的时长无关。比如，我先开一个直播页面，没有弹出。然后打开一个新的，后者很快弹出了。过一阵子，前者也弹出了。

就在我在Firefox里打这些字的时候，Edge浏览器的唯一一个直播页面中，一口气连续弹了两个这种窗口……

有时候，在弹出的同时，右上角会弹出“Cache 载入成功”的绿色通知。但很多时候则没有通知。

把所有直播页面（标签页）都关闭（但不关闭 Edge 浏览器）后再打开直播间，问题依旧。

把Edge 浏览器关闭并重新运行后，等了较长的时间后，还是弹出了……

### 预期行为

不会自动弹出设置窗口。

### 运行日志

控制台过滤"BLTH"后没有任何内容……

在大航海右侧，出现了多个【日志】标签，但里面都是一片空白。

这似乎是因为没有正常地“获取礼物/用户/账号/粉丝勋章数据”？

但我的一个直播页面，加载时，失败（"API.x.getAccInfo 获取账号信息失败"），但过了几分钟后，又获取了一次，并成功了。右上角出现了正常的【日志】，内容为绿色的成功说明。但过了一阵子，弹出了虚假的设置窗口，并且右上角存在3个【日志】，内容都是空白……

### 操作系统

Windows 10

### 浏览器

Edge 最新版本 112.0.1722.48

### 用户脚本管理器

Tampermonkey 4.18.1

### 挂机助手版本

6.1.2

### 网络情况

好

### 其他浏览器插件/脚本

无

**Comment by benaify** [comment]
+1

**Comment by unlimitwhitenight** [comment]
今天我也遇到了，感觉应该是直播页面有改动

**Comment by NAGATOYUKl** [comment]
直播页面退出登录重新登陆刷新ck可以试试，同 #348 [https://github.com/andywang425/BLTH/issues/348](url) 中的尝试。我这边目前又正常了。

**Comment by weiyiwuxian** [comment]
+1

**Comment by grandsong** [comment]
> 直播页面退出登录重新登陆刷新ck可以试试，同 #348 [https://github.com/andywang425/BLTH/issues/348](url) 中的尝试。我这边目前又正常了。

但我遇到过这样的情况：先是获取失败，后来成功了，再后来弹出窗口。这说明获取失败与弹出窗口的关系不是那么必然。

**Comment by Nenot233** [comment]
+1

**Comment by IskandarZhang** [comment]
+1 所有弹出的窗口会叠在一起，对应的“显示/隐藏控制面板”以及弹幕框上方的日志栏也会随着每次弹出被重复生成一遍

**Comment by IskandarZhang** [comment]
> +1 所有弹出的窗口会叠在一起，对应的“显示/隐藏控制面板”以及弹幕框上方的日志栏也会随着每次弹出被重复生成一遍

![image](https://user-images.githubusercontent.com/57842153/233769600-1c396b47-02a6-4d39-aeb1-d916c834dfa0.png)

具体如上所示，之前有issue说清除b站的cookie，测试过没有效果。

**Comment by 280chan** [comment]
chrome 也有这个问题

**Comment by WorldlineChanger** [comment]
同样问题，重新登陆未解决

**Comment by 25802580nmsl** [comment]
+1

**Comment by xijunji-jie** [comment]
+1

**Comment by SameIe** [comment]
我也这样，我还因为这原因加上自动打卡 被禁言了，大概因为不停冒出于是不停刷打卡了，郁闷也不知会被禁多久，看来打卡只能看着比较好唉

**Comment by SameIe** [comment]
> #375 试试手动改js 目前改了还没出现这个情况

兄弟怎改的，能说下吗？

**Comment by letterk** [comment]
> > #375 试试手动改js 目前改了还没出现这个情况
> 
> 兄弟怎改的，能说下吗？

切换到Files changed选项卡, 把里面修改过的代码按照对应的位置修改就行了

**Comment by SameIe** [comment]
> > > #375 试试手动改js 目前改了还没出现这个情况
> > 
> > 
> > 兄弟怎改的，能说下吗？
> 
> 切换到Files changed选项卡, 把里面修改过的代码按照对应的位置修改就行了

额我直接在油猴那改的，也可以改确实不会多控制台了，但我发现改完后亲密度加很慢后面甚至开始不加，最后我还是用原来的了。

**Comment by SameIe** [comment]
其实我之前没发现 “补充

我手动照着 https://github.com/andywang425/BLTH/pull/375/files 修改了我浏览器中的脚本后，目前似乎解决问题了。

多谢补丁贡献者 kinabcd 。希望 andywang425 能及早发布。” 所以不知道改什么

**Comment by grandsong** [comment]
> 其实我之前没发现 “补充
> 
> 我手动照着 https://github.com/andywang425/BLTH/pull/375/files 修改了我浏览器中的脚本后，目前似乎解决问题了。
> 
> 多谢补丁贡献者 kinabcd 。希望 andywang425 能及早发布。” 所以不知道改什么

哈哈，我是看了你那句话之后，才去尝试修改脚本的。

**Comment by grandsong** [comment]
> > > > #375 试试手动改js 目前改了还没出现这个情况
> > > 
> > > 
> > > 兄弟怎改的，能说下吗？
> > 
> > 
> > 切换到Files changed选项卡, 把里面修改过的代码按照对应的位置修改就行了
> 
> 额我直接在油猴那改的，也可以改确实不会多控制台了，但我发现改完后亲密度加很慢后面甚至开始不加，最后我还是用原来的了。

我是不在意的，但如果你在意，那么可以这样：用扩展 Stylus 覆盖CSS，把弹出窗口的 display 设为 "none"。毕竟我们很少会修改设置，所以干脆屏蔽算了。万一需要修改，那么临时禁用 Stylus 的规则即可。

**Comment by SameIe** [comment]
> > > > > #375 试试手动改js 目前改了还没出现这个情况
> > > > 
> > > > 
> > > > 兄弟怎改的，能说下吗？
> > > 
> > > 
> > > 切换到Files changed选项卡, 把里面修改过的代码按照对应的位置修改就行了
> > 
> > 
> > 额我直接在油猴那改的，也可以改确实不会多控制台了，但我发现改完后亲密度加很慢后面甚至开始不加，最后我还是用原来的了。
> 
> 我是不在意的，但如果你在意，那么可以这样：用扩展 Stylus 覆盖CSS，把弹出窗口的 display 设为 "none"。毕竟我们很少会修改设置，所以干脆屏蔽算了。万一需要修改，那么临时禁用 Stylus 的规则即可。

hhh看起来又是我不会的东西，我目前只能分两部分挂机，第一部分挂机亲密度绝对不开自动签到，然后加Tab Reloader (page auto refresh) 插件每8分钟刷新一次页面，另外按F12 开启开发者页面确实可以让窗口不出来那么多，第二部分挂机一定看着自动签到拿电池

**Comment by andywang425** [comment]
> 作者早点修复并更新嘛，这用得好难受

这两天光是处理学校里的事情就已经忙不过来了。。。五一放假期间会尝试修复。

**Comment by moyaoyi666** [comment]
老哥们老哥们，把控制面板里面第一个登录任务选项取消掉就可以了，亲测有用

**Comment by SameIe** [comment]
> 老哥们老哥们，把控制面板里面第一个登录任务选项取消掉就可以了，亲测有用

好我试试看

**Comment by SameIe** [comment]
> 老哥们老哥们，把控制面板里面第一个登录任务选项取消掉就可以了，亲测有用

还是有 API.x.getAccInfo 获取账号信息失败 ，感觉还差点？不过控制面板不多个了？

**Comment by SameIe** [comment]
> > 老哥们老哥们，把控制面板里面第一个登录任务选项取消掉就可以了，亲测有用
> 
> 还是有 API.x.getAccInfo 获取账号信息失败 ，感觉还差点？不过控制面板不多个了？

还是多个控制面板，看来没用阿

**Comment by Cheng605** [comment]
![image](https://user-images.githubusercontent.com/69993203/235183258-72c195e7-a82d-4d07-8e62-4958d91cd73d.png)
老哥是这样的问题吗？

**Comment by SameIe** [comment]
> ![image](https://user-images.githubusercontent.com/69993203/235183258-72c195e7-a82d-4d07-8e62-4958d91cd73d.png) 老哥是这样的问题吗？

是阿，只能等作者五一修复

**Comment by andywang425** [comment]
该问题已在6.1.3版本中修复。
