### ISSUE TITLE
更新6.1.3版本之后控制面板不出现且不发送弹幕

### ISSUE THREAD

**Issue by SiWuDao** [andywang425/BLTH#379]
### 描述bug

更新至6.1.3版本之后控制面板不出现且不发送弹幕 但是模拟观看增加亲密度的效果正常

### 重现bug

1.更新更新至6.1.3版本之后控制面板不出现
2.重新安装脚本
3.问题仍然存在

### 预期行为

打开直播间后正常出现控制面板，并自动发送打卡弹幕，模拟观看。

### 截图

![XS0@)D76{C5ILV)D3KYI(VJ](https://user-images.githubusercontent.com/126878220/235400081-60222378-e2e0-41f6-a632-1507abc9058c.png)
![%}R8)ZDD$X}5DZH`7BNN$6F](https://user-images.githubusercontent.com/126878220/235400143-bf4c65ff-6340-4bdc-bdac-b9ebd78858e1.png)

### 运行日志

```
content.js:8  injected: @resource: can't load @resource 'main' from URL 'https://fastly.jsdelivr.net/gh/andywang425/BLTH@16ad988dce34491d8479416911a2ac4691df45c3/assets/html/main.min.html': unknown error
```

### 操作系统

Windows 10

### 浏览器

Microsoft Edge 版本 112.0.1722.64 (正式版本) (64 位)

### 用户脚本管理器

Tampermonkey 4.18.1

### 挂机助手版本

6.1.3

### 网络情况

好

### 其他浏览器插件/脚本

无

### 其他

fastly.jsdelivr.net可以正常访问
shift+F5等方式也都已经尝试

**Comment by andywang425** [comment]
说到底还是cdn有问题，现在想找个在国内能稳定使用的github cdn真挺难的。

暂时没有好的解决办法。只能是想办法让
<https://fastly.jsdelivr.net/gh/andywang425/BLTH@16ad988dce34491d8479416911a2ac4691df45c3/assets/html/main.min.html>
这个依赖被获取到。目前发现部分情况下jsdelivr会重定向到raw，即
<https://raw.githubusercontent.com/andywang425/BLTH/16ad988dce34491d8479416911a2ac4691df45c3/assets/html/main.min.html>

**Comment by b1xcy** [comment]
似乎并不是cdn的问题，我尝试将jsdelivr.net和raw.githubusercontent.com都添加到规则列表中，也试过切换到全局代理，均无法显示控制面板，甚至无法正常打卡。

**Comment by b1xcy** [comment]
> > 似乎并不是cdn的问题，我尝试将jsdelivr.net和raw.githubusercontent.com都添加到规则列表中，也试过切换到全局代理，均无法显示控制面板，甚至无法正常打卡。
> 
> 我这边开全局代理重新加载一遍之后就可以正常使用了，也许你可以看一下是不是代理设置出问题了

找到问题了，不运行的原因是和`高亮个别用户的弹幕`这个插件冲突了

**Comment by sxc1234** [comment]
@b1xcy  怎么解决的哇 小哥
