### ISSUE TITLE
[Bug] 脚本无法运行，提示`API.x.getAccInfo 获取账号信息失败 访问权限不足`

### ISSUE THREAD

**Issue by RtYkk** [andywang425/BLTH#381]
### 描述bug

每次一打开直播间就会出现`API.x.getAccInfo 获取账号信息失败 访问权限不足` & `缺少必要的数据，挂机助手停止运行`

### 重现bug

1. 打开脚本
2.  正常打开任意直播间

### 预期行为

脚本正常运行

### 运行日志

![chrome_yg59J5WBwE](https://github.com/andywang425/BLTH/assets/45971730/c90079d8-2096-439e-8346-fc346c84788e)

### 操作系统

Windows 10

### 浏览器

Chrome 113.0.5672.127

### 用户脚本管理器

Tempermonkey 4.18.1

### 挂机助手版本

6.1.3

### 网络情况

好

### 其他浏览器插件/脚本

无

### 其他

换过好几个 IP 了，代理软件关了依然稳定复现。昨晚在部分直播间首次观测到，我还在想为什么，今天就蔓延到所有直播间了。

2023/05/22 13:11 update: 是通病我就放心了，排查了好久以为是我个人的问题……我还想这 issue 区怎么没人提

**Comment by YiBaiLudovicus** [comment]
大概是B站又更新了

**Comment by ClementLevi** [comment]
同样状况。注意到最近直播播放页面的加关注按钮位置发生变动，大概应该就是这次更新导致的

**Comment by wjt912580065** [comment]
我不是一个人就好

**Comment by prediction63** [comment]
好像最近几天报同样的错误，刷新两下就绿了，结果今天完全不能用

**Comment by daxiederen2333** [comment]
还有脚本按钮加载不出来，换过多个ip都不行，前两天同样报错刷新两三次能成功载入也有按钮的，今天完全无法加载

**Comment by SawyerSong223** [comment]
把下面这两行注释掉可以跑，勉强...
531              window.toast(`API.x.getAccInfo 获取账号信息失败 ${re.message}`, 'error');
532              reqFailed = true;

**Comment by prediction63** [comment]
> 

亲测注释后，一次点亮

**Comment by gsdfqaq** [comment]
和你一样，不知道怎么解决

**Comment by qingtianyu11111** [comment]
> 把下面这两条注解掉可以跑，勉强... 531 window.toast( `API.x.getAccInfo 获取账号信息失败 ${re.message}`, 'error'); 第532话

游泳

**Comment by GTVpigs** [comment]
我的临时解决办法是回滚到旧版6.1.1，可能会提示获取次数过多，多刷新几次就能正常载入了。
不过至少能用，昨天我就回滚旧版挂满了。
![1](https://github.com/andywang425/BLTH/assets/86565518/2e21632c-712f-4706-8014-a57260109666)

**Comment by wyjzp** [comment]
> 把下面这两条注解掉可以跑，勉强... 531 window.toast( `API.x.getAccInfo 获取账号信息失败 ${re.message}`, 'error'); 第532话

有用的！！！

**Comment by Zeddddd** [comment]
> 把下面这两行注释掉可以跑，勉强... 531 window.toast(`API.x.getAccInfo 获取账号信息失败 ${re.message}`, 'error'); 532 reqFailed = true;

请问这两句原本是用来干什么的呀

**Comment by sheyao89** [comment]
> > 把下面这两行注释掉可以跑，勉强... 531 window.toast(`API.x.getAccInfo 获取账号信息失败 ${re.message}`, 'error'); 532 reqFailed = true;
> 
> 请问这两句原本是用来干什么的呀

获取用户信息失败就中止脚本，用来确认用户信息正确的
记得上版本报错也是请求这接口失败的问题，当时也把这个接口给注掉继续跑了

**Comment by RtYkk** [comment]
@GTVpigs 请问你这个挂满是一个直播间在前台开着剩下的不开也行，还是每个直播间都要开一个挂着。如果是前者，等这 bug 修了我就要研究下为什么我每天不开的直播间只能挂 200(点赞 100 + 发弹幕 100)了。

**Comment by GTVpigs** [comment]
> @GTVpigs 请问你这个挂满是一个直播间在前台开着剩下的不开也行，还是每个直播间都要开一个挂着。如果是前者，等这 bug 修了我就要研究下为什么我每天不开的直播间只能挂 200(点赞 100 + 发弹幕 100)了。

随便找一个直播间前台挂着就可以，确实有时候会有一些直播间没涨，一般来说重置直播任务缓存再刷新一下就可以。

**Comment by szmarcos** [comment]
前两天还有一个情况就是打开运行后没一段时间整个b站就掉线了，需要重新登陆一次。

**Comment by xuwenchao980507** [comment]
> > > 把下面这两行注释掉可以跑，勉强... 531 window.toast(`API.x.getAccInfo 获取账号信息失败 ${re.message}`, 'error'); 532 reqFailed = true;
> > 
> > 
> > 请问这两句原本是用来干什么的呀
> 
> 获取用户信息失败就中止脚本，用来确认用户信息正确的 记得上版本报错也是请求这接口失败的问题，当时也把这个接口给注掉继续跑了

我的w11的电脑最多显示53条注释，没法改咋办，w10的本子倒是显示完全了试了下确实能用

**Comment by Ponyonyope** [comment]
> > > > 把下面这两行注释掉可以跑，勉强... 531 window.toast(`API.x.getAccInfo 获取账号信息失败 ${re.message}`, 'error'); 532 reqFailed = true;
> > > 
> > > 
> > > 请问这两句原本是用来干什么的呀
> > 
> > 
> > 获取用户信息失败就中止脚本，用来确认用户信息正确的 记得上版本报错也是请求这接口失败的问题，当时也把这个接口给注掉继续跑了
> 
> 我的w11的电脑最多显示53条注释，没法改咋办，w10的本子倒是显示完全了试了下确实能用
因为你的脚本源是github，在greasyfork重新装一下就行了

**Comment by StarsDream00** [comment]
把
```js
return window.toast("缺少必要的数据，挂机助手停止运行", "error");
```
前面的`return`注释掉就行了

**Comment by xuwenchao980507** [comment]
> 把
> 
> ```js
> return window.toast("缺少必要的数据，挂机助手停止运行", "error");
> ```
> 
> 前面的`return`注释掉就行了

真是，多谢了！

**Comment by xuwenchao980507** [comment]
> > > > > 把下面这两行注释掉可以跑，勉强... 531 window.toast(`API.x.getAccInfo 获取账号信息失败 ${re.message}`, 'error'); 532 reqFailed = true;
> > > > 
> > > > 
> > > > 请问这两句原本是用来干什么的呀
> > > 
> > > 
> > > 获取用户信息失败就中止脚本，用来确认用户信息正确的 记得上版本报错也是请求这接口失败的问题，当时也把这个接口给注掉继续跑了
> > 
> > 
> > 我的w11的电脑最多显示53条注释，没法改咋办，w10的本子倒是显示完全了试了下确实能用
> > > 因为你的脚本源是github，在greasyfork重新装一下就行了

真是，多谢了！

**Comment by lhfhybxm** [comment]
注释以后点赞打卡都提示crsf校验失败……看来只能等版本更新了

**Comment by Misaka9967** [comment]
> 把
> 
> ```js
> return window.toast("缺少必要的数据，挂机助手停止运行", "error");
> ```
> 
> 前面的`return`注释掉就行了

这个可以，我试了，虽然提示失败，但是还是正常加载了

**Comment by gsdfqaq** [comment]
> 

怎么滚回旧版的

**Comment by dmxf964260** [comment]
默默加一，等待处理方法
