### ISSUE TITLE
自动切换最高画质问题

### ISSUE THREAD

**Issue by Mishasama** [andywang425/BLTH#385]
### 描述bug

开启功能后，进入直播间在播放器获取到默认清晰度流后就马上触发切换了，导致第二播放器没能获取到原画的串流，从而一直卡着。

### 重现bug

1. 开启功能
2. 刷新页面

### 预期行为

模拟手动切换，正常传递串流地址。

### 截图

![image](https://github.com/andywang425/BLTH/assets/54498172/218cd679-ee2e-4e54-b76b-727464fb467c)

### 运行日志

没有BUG日志

### 操作系统

WIN10 21H2

### 浏览器

Chrome 114.0.5735.90

### 用户脚本管理器

Tampermonkey v4.19.0

### 挂机助手版本

6.1.3

### 网络情况

好

### 其他浏览器插件/脚本

没有

### 其他

建议先等网页完全加载完再切换，不然第二播放器可能还没准备好。

**Comment by andywang425** [comment]
行，看来不能切换地太快。
