### ISSUE TITLE
访问权限不足，无法使用

### ISSUE THREAD

**Issue by xiahantian** [andywang425/BLTH#386]
### 描述bug

显示“API.x.getAccInfo获取账号信息失败，访问权限不足”，“缺少必要的数据，挂机助手停止”
即使停用其他脚本，刷新网页或重启电脑都无用

### 重现bug

未进行任何其他操作

### 预期行为

无预期

### 截图

![image](https://github.com/andywang425/BLTH/assets/34604526/bb5121c3-3264-4538-a493-f7673444866e)

### 运行日志

https://live.bilibili.com/731234
vendors.40f88367949b4bddffe2.js:2 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vendors.40f88367949b4bddffe2.js:2 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
179.cb95fb6c552b519f674f.js:2 Bilibili Live V4.0.0 "Life Experience" Lovingly By © 2014 - 2023 Bilibili Live Department  ...(●'◡'●)ﾉ♥   # Renascence #
179.cb95fb6c552b519f674f.js:2 Version: V4.0.0 "Life Experience", CodeName: Neptune.
179.cb95fb6c552b519f674f.js:2 [Vue warn]: Cannot find element: #fans-medal-popover
console.error @ 179.cb95fb6c552b519f674f.js:2
vt @ vendors.40f88367949b4bddffe2.js:2
Yo @ vendors.40f88367949b4bddffe2.js:2
ro.$mount @ vendors.40f88367949b4bddffe2.js:2
(匿名) @ 179.cb95fb6c552b519f674f.js:2
d @ 179.cb95fb6c552b519f674f.js:2
(匿名) @ 179.cb95fb6c552b519f674f.js:2
(匿名) @ 179.cb95fb6c552b519f674f.js:2
(匿名) @ 179.cb95fb6c552b519f674f.js:2
e @ vendors.40f88367949b4bddffe2.js:2
mj @ 179.cb95fb6c552b519f674f.js:2
Lj @ 179.cb95fb6c552b519f674f.js:2
(匿名) @ 179.cb95fb6c552b519f674f.js:2
d @ 179.cb95fb6c552b519f674f.js:2
(匿名) @ 179.cb95fb6c552b519f674f.js:2
(匿名) @ 179.cb95fb6c552b519f674f.js:2
a @ 179.cb95fb6c552b519f674f.js:2
179.cb95fb6c552b519f674f.js:2 /getLeftEntryList error 请求失败，请您稍后再试：未获取到 code 值, 疑似接口格式错误或网络已断开 ＞△＜
console.error @ 179.cb95fb6c552b519f674f.js:2
(匿名) @ app.98008bf14a63c5dbee6f.js:2
p @ app.98008bf14a63c5dbee6f.js:2
(匿名) @ app.98008bf14a63c5dbee6f.js:2
(匿名) @ app.98008bf14a63c5dbee6f.js:2
a @ app.98008bf14a63c5dbee6f.js:2
179.cb95fb6c552b519f674f.js:2 false 'log===log===official===relation'
179.cb95fb6c552b519f674f.js:2 /getLeftEntryList error 请求失败，请您稍后再试：未获取到 code 值, 疑似接口格式错误或网络已断开 ●︿●
console.error @ 179.cb95fb6c552b519f674f.js:2
(匿名) @ app.98008bf14a63c5dbee6f.js:2
p @ app.98008bf14a63c5dbee6f.js:2
(匿名) @ app.98008bf14a63c5dbee6f.js:2
(匿名) @ app.98008bf14a63c5dbee6f.js:2
a @ app.98008bf14a63c5dbee6f.js:2
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:13210 scheduled bundle update
remoteEntry.js:7 Unsatisfied version 2.0.7 from liveroom_activity_pendant of shared singleton module @blink-live/awesome-api (required ^1.2.5-0)
u @ remoteEntry.js:7
s @ remoteEntry.js:7
(匿名) @ remoteEntry.js:7
(匿名) @ remoteEntry.js:7
39749 @ remoteEntry.js:7
(匿名) @ remoteEntry.js:7
n.f.consumes @ remoteEntry.js:7
(匿名) @ remoteEntry.js:7
n.e @ remoteEntry.js:7
./routes @ remoteEntry.js:7
i @ remoteEntry.js:7
(匿名) @ bilibili.5176fc77176d5039029b.js:2
remoteEntry.js:7 Unsatisfied version 2.0.7 from liveroom_activity_pendant of shared singleton module @blink-live/awesome-api (required ^1.2.5-0)
u @ remoteEntry.js:7
s @ remoteEntry.js:7
(匿名) @ remoteEntry.js:7
(匿名) @ remoteEntry.js:7
44719 @ remoteEntry.js:7
(匿名) @ remoteEntry.js:7
n.f.consumes @ remoteEntry.js:7
(匿名) @ remoteEntry.js:7
n.e @ remoteEntry.js:7
./routes @ remoteEntry.js:7
i @ remoteEntry.js:7
(匿名) @ bilibili.5176fc77176d5039029b.js:2
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:13210 draw button = null
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:13210 live watch
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:13210 leave feeds tab
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:13210 scheduled bundle update
sentry-5.2.1.min.js:2 sw register success!
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:13210 downloading bundle
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:13210 downloading bundle
sentry-5.2.1.min.js:2 medal t Array(10)
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:154 Uncaught (in promise) Error: Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html
    at d.readEndOfCentral (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:154:6876)
    at d.load (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:154:8588)
    at chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:153:11837
    at async ResourceManager.checkUpdates (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:13210:2659853)
readEndOfCentral @ userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:154
load @ userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:154
(匿名) @ userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:153
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:154 Uncaught (in promise) Error: Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html
    at d.readEndOfCentral (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:154:6876)
    at d.load (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:154:8588)
    at chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:153:11837
    at async ResourceManager.checkUpdates (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:13210:2659853)
readEndOfCentral @ userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:154
load @ userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:154
(匿名) @ userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:153
2app.98008bf14a63c5dbee6f.js:2 Uncaught TypeError: r is not a function
    at app.98008bf14a63c5dbee6f.js:2:2725707
    at Array.forEach (<anonymous>)
    at IntersectionObserver.<anonymous> (app.98008bf14a63c5dbee6f.js:2:2725519)
(匿名) @ app.98008bf14a63c5dbee6f.js:2
(匿名) @ app.98008bf14a63c5dbee6f.js:2
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:13210 enter feeds tab
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:13210 Array(10)
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:13210 bundle request timeout, saving onlineData to cache...
userscript.html?name=Bilibili%2520Evolved%2520(Preview).user.js&id=392c0e8f-0adc-4d33-a37f-e7a76ca62423:13210 bundle request timeout, saving onlineData to cache...
2DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: 系統錯誤: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/sm/3d96fbc9c4b130ad115376d0c7b95546d355bb7fbeaa7676f9f25f30c6ddc4bc.map: 系統錯誤: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: 系統錯誤: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/sm/3d96fbc9c4b130ad115376d0c7b95546d355bb7fbeaa7676f9f25f30c6ddc4bc.map: 系統錯誤: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/bundle.min.js.map: HTTP 錯誤：狀態碼為 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE

### 操作系统

windows11

### 浏览器

Chrome  114.0.5735.110 (正式版本) (64 位元)

### 用户脚本管理器

Tempermonkey v4.18.1

### 挂机助手版本

6.1.3

### 网络情况

好

### 其他浏览器插件/脚本

Bilibili Evolved (Preview)

**Comment by a776058959** [comment]
我也是这样哈哈
