### ISSUE TITLE
自动送礼送不了PK票

### ISSUE THREAD

**Issue by Mishasama** [andywang425/BLTH#387]
### 描述bug

如题

### 重现bug

在送礼类型里加入字段“PK票”或者“31531”

### 预期行为

应该都送出去

### 截图

![image](https://github.com/andywang425/BLTH/assets/54498172/1fbb259e-63fd-4c5f-bd03-273e9d54a065)

### 运行日志

![image](https://github.com/andywang425/BLTH/assets/54498172/857a9ed6-97e7-449d-b138-95b94bcb2cef)

### 操作系统

WIN10 21H2

### 浏览器

Chrome 	114.0.5735.110

### 用户脚本管理器

Tampermonkey v4.19.0

### 挂机助手版本

6.1.3

### 网络情况

好

### 其他浏览器插件/脚本

不知道

### 其他

我知道它没啥作用，但我就不想它丢那过期。

**Comment by andywang425** [comment]
脚本只送亲密度大于0的礼物，所以不会送PK票。想送还是自己手动送吧。
