### ISSUE TITLE
所有房间都显示我是房管 

### ISSUE THREAD

**Issue by C1lova** [andywang425/BLTH#388]
### 描述bug

我不知道是什么导致了这个问题，我只能描述我看到的现象：
我发弹幕的时候在我的牌子和id之间显示一个房管的标志，点击其他用户的弹幕也可以选择禁言，然后是否确定禁言选择是的时候会告诉我没有权限。
上面还有一个禁言按钮，可以设置禁言和屏蔽词什么的。
就像我是一个真的房管，但是只有我自己看得见。

### 重现bug

我在三个直播间有房管，不知道有没有关系，不过我只要开了脚本进直播间，无论哪里都显示我是房管，哪怕我没关注，没牌子。

### 预期行为

就希望恢复成没开脚本那样的界面。

### 截图

![111](https://github.com/andywang425/BLTH/assets/114104239/194fa5e6-ee90-483f-90a7-31b90d035193)

### 运行日志

没搜到BLTH，都复制给你吧只好。
DevTools failed to load source map: Could not load content for chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/sm/3d96fbc9c4b130ad115376d0c7b95546d355bb7fbeaa7676f9f25f30c6ddc4bc.map: System error: net::ERR_BLOCKED_BY_CLIENT
navbar-v3.min.js:178 https://live.bilibili.com/23817749?visit_id=1mbdpxr8rdcw
vendors.2d01bb96d08acfcc3776.js:2 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vendors.2d01bb96d08acfcc3776.js:2 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
room-player.min.js:33 Hls7Player v1.82
room-player.min.js:33 Chrome verion: 114
room-player.min.js:71 [SistersPlayer] Misaka Network Check: Supported
room-player.min.js:71 [SistersPlayer] NAT Kakushin Mode (Preload): true.
room-player.min.js:71 [SistersPlayer] NAT TYPE (Preload): PortRestrictedCone.
room-player.min.js:71 [SistersPlayer] Last Order (re)connecting.
room-player.min.js:71 [SistersPlayer] Environment: production
room-player.min.js:71 [SistersPlayer] Build Time: 2022-12-23 03:40:09
room-player.min.js:71 [SistersPlayer] Version: 1.4.36-69d81050-master
room-player.min.js:71 [SistersPlayer] Misaka has been created. >w<
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
room-player.min.js:33 track 1 start dts: 7905
room-player.min.js:71 [SistersPlayer] Last Order (re)connect done.
room-player.min.js:71 [SistersPlayer] Last Order is Connected.
179.7d2929181976a0d43359.js:2 Bilibili Live V4.0.0 "Life Experience" Lovingly By © 2014 - 2023 Bilibili Live Department  ...(●'◡'●)ﾉ♥   # Renascence #
179.7d2929181976a0d43359.js:2 Version: V4.0.0 "Life Experience", CodeName: Neptune.
179.7d2929181976a0d43359.js:2 [Vue warn]: Cannot find element: #fans-medal-popover
console.error @ 179.7d2929181976a0d43359.js:2
vt @ vendors.2d01bb96d08acfcc3776.js:2
Yo @ vendors.2d01bb96d08acfcc3776.js:2
ro.$mount @ vendors.2d01bb96d08acfcc3776.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
d @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
wj @ 179.7d2929181976a0d43359.js:2
Lj @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
d @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
a @ 179.7d2929181976a0d43359.js:2
Promise.then (async)
s @ 179.7d2929181976a0d43359.js:2
a @ 179.7d2929181976a0d43359.js:2
Promise.then (async)
s @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
wj @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
Aj @ 179.7d2929181976a0d43359.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
p @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
g @ app.c0d57c22bfbe40a42f2d.js:2
b @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
p @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
g @ app.c0d57c22bfbe40a42f2d.js:2
y @ app.c0d57c22bfbe40a42f2d.js:2
48744 @ app.c0d57c22bfbe40a42f2d.js:2
o @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
o.O @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
c @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
179.7d2929181976a0d43359.js:2 /getLeftEntryList error 请求失败，请您稍后再试：未获取到 code 值, 疑似接口格式错误或网络已断开 ＞︿＜
console.error @ 179.7d2929181976a0d43359.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
p @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
D @ app.c0d57c22bfbe40a42f2d.js:2
B @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
p @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
D @ app.c0d57c22bfbe40a42f2d.js:2
t.getRemoteInfo @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
d @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
Dt @ 179.7d2929181976a0d43359.js:2
qt @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
zt @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
d @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
a @ 179.7d2929181976a0d43359.js:2
Promise.then (async)
s @ 179.7d2929181976a0d43359.js:2
a @ 179.7d2929181976a0d43359.js:2
Promise.then (async)
s @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
wj @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
Aj @ 179.7d2929181976a0d43359.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
p @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
g @ app.c0d57c22bfbe40a42f2d.js:2
b @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
p @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
g @ app.c0d57c22bfbe40a42f2d.js:2
y @ app.c0d57c22bfbe40a42f2d.js:2
48744 @ app.c0d57c22bfbe40a42f2d.js:2
o @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
o.O @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
c @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
179.7d2929181976a0d43359.js:2 false 'log===log===official===relation'
179.7d2929181976a0d43359.js:2 /getLeftEntryList error 请求失败，请您稍后再试：未获取到 code 值, 疑似接口格式错误或网络已断开 ＞△＜
console.error @ 179.7d2929181976a0d43359.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
p @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
D @ app.c0d57c22bfbe40a42f2d.js:2
B @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
p @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
D @ app.c0d57c22bfbe40a42f2d.js:2
t.getRemoteInfo @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
d @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
Dt @ 179.7d2929181976a0d43359.js:2
Kt @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
zt @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
d @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
a @ 179.7d2929181976a0d43359.js:2
Promise.then (async)
s @ 179.7d2929181976a0d43359.js:2
a @ 179.7d2929181976a0d43359.js:2
Promise.then (async)
s @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
wj @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
Aj @ 179.7d2929181976a0d43359.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
p @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
g @ app.c0d57c22bfbe40a42f2d.js:2
b @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
p @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
g @ app.c0d57c22bfbe40a42f2d.js:2
y @ app.c0d57c22bfbe40a42f2d.js:2
48744 @ app.c0d57c22bfbe40a42f2d.js:2
o @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
o.O @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
c @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
DevTools failed to load source map: Could not load content for chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/sm/3d96fbc9c4b130ad115376d0c7b95546d355bb7fbeaa7676f9f25f30c6ddc4bc.map: System error: net::ERR_BLOCKED_BY_CLIENT
bili-theme.min.js:1 stringifyAttributes ; path=/
VM1189:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at $ (app.c0d57c22bfbe40a42f2d.js:2:1000409)
    at app.c0d57c22bfbe40a42f2d.js:2:1001596
    at f (app.c0d57c22bfbe40a42f2d.js:2:981445)
    at Generator.<anonymous> (app.c0d57c22bfbe40a42f2d.js:2:982768)
    at Generator.next (app.c0d57c22bfbe40a42f2d.js:2:981790)
    at a (app.c0d57c22bfbe40a42f2d.js:2:987467)
$ @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
f @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
Y @ app.c0d57c22bfbe40a42f2d.js:2
et @ app.c0d57c22bfbe40a42f2d.js:2
Ej @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
Promise.then (async)
(anonymous) @ 179.7d2929181976a0d43359.js:2
d @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
a @ 179.7d2929181976a0d43359.js:2
Promise.then (async)
s @ 179.7d2929181976a0d43359.js:2
a @ 179.7d2929181976a0d43359.js:2
Promise.then (async)
s @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
wj @ 179.7d2929181976a0d43359.js:2
(anonymous) @ 179.7d2929181976a0d43359.js:2
Aj @ 179.7d2929181976a0d43359.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
p @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
g @ app.c0d57c22bfbe40a42f2d.js:2
b @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
p @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
g @ app.c0d57c22bfbe40a42f2d.js:2
y @ app.c0d57c22bfbe40a42f2d.js:2
48744 @ app.c0d57c22bfbe40a42f2d.js:2
o @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
o.O @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
c @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
remoteEntry.js:7 Unsatisfied version 2.0.7 from liveroom_activity_pendant of shared singleton module @blink-live/awesome-api (required ^1.2.5-0)
u @ remoteEntry.js:7
s @ remoteEntry.js:7
(anonymous) @ remoteEntry.js:7
(anonymous) @ remoteEntry.js:7
39749 @ remoteEntry.js:7
(anonymous) @ remoteEntry.js:7
n.f.consumes @ remoteEntry.js:7
(anonymous) @ remoteEntry.js:7
n.e @ remoteEntry.js:7
./routes @ remoteEntry.js:7
i @ remoteEntry.js:7
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
Promise.then (async)
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
Promise.then (async)
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
Promise.then (async)
getExposeModule @ bilibili.af80e5f8496a6efb4213.js:2
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
Promise.then (async)
t.import @ bilibili.af80e5f8496a6efb4213.js:2
component @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
h @ bilibili.af80e5f8496a6efb4213.js:2
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
o @ vendors.2d01bb96d08acfcc3776.js:2
a @ vendors.2d01bb96d08acfcc3776.js:2
(anonymous) @ vendors.2d01bb96d08acfcc3776.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
(anonymous) @ vendors.2d01bb96d08acfcc3776.js:2
onMount @ bilibili.af80e5f8496a6efb4213.js:2
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
Promise.then (async)
mounted @ bilibili.af80e5f8496a6efb4213.js:2
xe @ vendors.2d01bb96d08acfcc3776.js:2
mr @ vendors.2d01bb96d08acfcc3776.js:2
insert @ vendors.2d01bb96d08acfcc3776.js:2
I @ vendors.2d01bb96d08acfcc3776.js:2
(anonymous) @ vendors.2d01bb96d08acfcc3776.js:2
t._update @ vendors.2d01bb96d08acfcc3776.js:2
r @ vendors.2d01bb96d08acfcc3776.js:2
Dr.get @ vendors.2d01bb96d08acfcc3776.js:2
Dr @ vendors.2d01bb96d08acfcc3776.js:2
hr @ vendors.2d01bb96d08acfcc3776.js:2
ro.$mount @ vendors.2d01bb96d08acfcc3776.js:2
ro.$mount @ vendors.2d01bb96d08acfcc3776.js:2
hr @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
d @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
ar @ app.c0d57c22bfbe40a42f2d.js:2
fr @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
p @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
g @ app.c0d57c22bfbe40a42f2d.js:2
y @ app.c0d57c22bfbe40a42f2d.js:2
48744 @ app.c0d57c22bfbe40a42f2d.js:2
o @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
o.O @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
c @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
remoteEntry.js:7 Unsatisfied version 2.0.7 from liveroom_activity_pendant of shared singleton module @blink-live/awesome-api (required ^1.2.5-0)
u @ remoteEntry.js:7
s @ remoteEntry.js:7
(anonymous) @ remoteEntry.js:7
(anonymous) @ remoteEntry.js:7
44719 @ remoteEntry.js:7
(anonymous) @ remoteEntry.js:7
n.f.consumes @ remoteEntry.js:7
(anonymous) @ remoteEntry.js:7
n.e @ remoteEntry.js:7
./routes @ remoteEntry.js:7
i @ remoteEntry.js:7
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
Promise.then (async)
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
Promise.then (async)
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
Promise.then (async)
getExposeModule @ bilibili.af80e5f8496a6efb4213.js:2
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
Promise.then (async)
t.import @ bilibili.af80e5f8496a6efb4213.js:2
component @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
h @ bilibili.af80e5f8496a6efb4213.js:2
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
o @ vendors.2d01bb96d08acfcc3776.js:2
a @ vendors.2d01bb96d08acfcc3776.js:2
(anonymous) @ vendors.2d01bb96d08acfcc3776.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
(anonymous) @ vendors.2d01bb96d08acfcc3776.js:2
onMount @ bilibili.af80e5f8496a6efb4213.js:2
(anonymous) @ bilibili.af80e5f8496a6efb4213.js:2
Promise.then (async)
mounted @ bilibili.af80e5f8496a6efb4213.js:2
xe @ vendors.2d01bb96d08acfcc3776.js:2
mr @ vendors.2d01bb96d08acfcc3776.js:2
insert @ vendors.2d01bb96d08acfcc3776.js:2
I @ vendors.2d01bb96d08acfcc3776.js:2
(anonymous) @ vendors.2d01bb96d08acfcc3776.js:2
t._update @ vendors.2d01bb96d08acfcc3776.js:2
r @ vendors.2d01bb96d08acfcc3776.js:2
Dr.get @ vendors.2d01bb96d08acfcc3776.js:2
Dr @ vendors.2d01bb96d08acfcc3776.js:2
hr @ vendors.2d01bb96d08acfcc3776.js:2
ro.$mount @ vendors.2d01bb96d08acfcc3776.js:2
ro.$mount @ vendors.2d01bb96d08acfcc3776.js:2
hr @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
d @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
a @ app.c0d57c22bfbe40a42f2d.js:2
Promise.then (async)
u @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
ar @ app.c0d57c22bfbe40a42f2d.js:2
fr @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
p @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
e @ vendors.2d01bb96d08acfcc3776.js:2
g @ app.c0d57c22bfbe40a42f2d.js:2
y @ app.c0d57c22bfbe40a42f2d.js:2
48744 @ app.c0d57c22bfbe40a42f2d.js:2
o @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
o.O @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
c @ 23817749?visit_id=1mbdpxr8rdcw:15
(anonymous) @ app.c0d57c22bfbe40a42f2d.js:2
sentry-5.2.1.min.js:2 sw register success!

### 操作系统

Windows10

### 浏览器

Chrome114.0.5735.134

### 用户脚本管理器

Tampermonkey v4.19.0

### 挂机助手版本

6.1.3

### 网络情况

好

### 其他浏览器插件/脚本

我没开其他任何脚本

**Comment by RtYkk** [comment]
你开隐身入场了
![chrome_K5A9tPL3FD](https://github.com/andywang425/BLTH/assets/45971730/ca627086-8965-4ff4-87ab-9bc29a2726ad)

**Comment by yangyangbuxiangyang** [comment]
服了，把大家喊出来就为了这事啊？

**Comment by 36EMiyuki** [comment]
这不影响使用吧

**Comment by andywang425** [comment]
如楼上所说，这确实不是一个bug。因为包含房管数据的API和进入直播间的提示有关联，所以暂时只能这样。
