### ISSUE TITLE
请问有没有办法可以在发弹幕前，自动切换粉丝牌吗？

### ISSUE THREAD

**Issue by ngklsapcp** [andywang425/BLTH#39]
比如：
1）我在直播间A发弹幕时。
2）它会自动检测现在是否戴着这个直播间的牌子。
3）如果没戴的话，查看自己有没有这直播间的牌子。
4）如果有的话，自动换牌子再发弹幕。
5）然后我去直播间B发弹幕时，它会重新执行②③④。

我不清楚会不会很难，如果很难不用执意于我这个问题也可以。
打扰了。谢谢辛苦你了。

**Comment by andywang425** [comment]
不算难，但挺麻烦的。目前会优先处理一些更重要的问题，你这个需求我先记着。

**Comment by X-Holmes** [comment]
我也觉得带着别人的牌子(粉丝勋章)很尴尬，所以我现在直接不带牌子哈哈哈

**Comment by xzk-kokodayo** [comment]
想法不错，这样开多个直播间就很方便发弹幕

**Comment by andywang425** [comment]
时隔五个多月总算填坑了，说实话这个功能比我想象的要复杂一点
