### ISSUE TITLE
[Bug] 大乱斗屏蔽相关功能失效

### ISSUE THREAD

**Issue by RtYkk** [andywang425/BLTH#390]
### 描述bug

如题

### 重现bug

1. 打开移除大乱斗弹窗及进度条
2. 功能未生效

### 预期行为

功能生效不显示进度条

### 运行日志

![chrome_iUJOitFKFu](https://github.com/andywang425/BLTH/assets/45971730/de90b217-18e0-4cc8-bcd3-6443fb953ea8)

### 操作系统

Windows 10

### 浏览器

Chrome latest

### 用户脚本管理器

latest

### 挂机助手版本

6.1.4

### 网络情况

好

### 其他浏览器插件/脚本

无

### 其他

应该是因为样式变了？

**Comment by ADJazzzz** [comment]
pk相关的div class改成了awesome-pk-box
可以在927行改成`rmJQpath: ['.awesome-pk-box'],`试试

**Comment by RtYkk** [comment]
生效，感谢提供解决方法。有空的话你提个 PR？Issue 我先不关了。
https://github.com/andywang425/BLTH/blob/8485b130e3bce5970e7dec443834adf4f286097a/B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.js#L927

**Comment by RtYkk** [comment]
![chrome_Zl4VZgKnYy](https://github.com/andywang425/BLTH/assets/45971730/40e976a6-5230-4a3e-81d1-3f9564000139)
说起来还多了个这个弹窗，不过倒是无伤大雅。

**Comment by andywang425** [comment]
已修复 #391 #393，感谢@ADJazzzz

**Comment by ADJazzzz** [comment]
> ![chrome_Zl4VZgKnYy](https://user-images.githubusercontent.com/45971730/250350832-40e976a6-5230-4a3e-81d1-3f9564000139.png) 说起来还多了个这个弹窗，可能需要单独处理一下，不过不处理的话倒也是无伤大雅。

实在不好意思，因为我看的主播基本上是电子播放器，不开pk的😂所以没注意到

解决方法的话，因为是中间的toast可以修改953和954行：
```         
            addCss: '',
            eval: `setInterval(() => {$(".link-toast.info.center-animation").remove()}, 200)`,
```

不过有点暴力，会直接把中间的toast都去掉，但好像目前也就只有它会在中间？

**Comment by ADJazzzz** [comment]
> Owner



> > 说起来还多了个这个弹窗，可能需要单独处理一下，不过不处理的话倒也是无伤大雅。
> 
> setInterval里面再套一个jQuery selector对性能影响比较大，而且如果要更准确一点的话还得去判断toast的文字。
> 
> 现在凑合能用就行，目前正在重写整个脚本，到时候看看有没有更好的办法。

那我就不交pr了，先凑合用着吧😂

**Comment by RtYkk** [comment]
凑合一下没关系，我也姑且只是提一下，修不修随意。这个弹窗显示时间不长就消失了。
