### ISSUE TITLE
定时刷新功能未生效

### ISSUE THREAD

**Issue by geekscloud** [andywang425/BLTH#394]
### 描述bug

控制面板底部的定时刷新功能设置到达间隔时间未刷新页面

### 重现bug

1. 设置任意分钟数
2. 勾选定时刷新
3. 刷新页面
4. 到达间隔时间页面未刷新

### 预期行为

应该刷新页面

### 截图

![CleanShot 2023-07-12 at 22 08 33@2x](https://github.com/andywang425/BLTH/assets/24413839/314727e2-617b-4c2f-9406-a1f99bc5964d)

### 运行日志

配置日志:
`{
    "APP_TASK": true,
    "AUTO_DANMU": false,
    "AUTO_CHECK_DANMU_TIMEOUT": 3000,
    "AUTO_GIFT": false,
    "AUTO_GIFT_ROOMID": [
        "22755636"
    ],
    "AUTO_GROUP_SIGN": true,
    "COIN": false,
    "COIN_NUMBER": 2,
    "COIN_TYPE": "COIN_UID",
    "COIN_UID": [
        "27565758"
    ],
    "COIN2SILVER": false,
    "COIN2SILVER_NUM": 1,
    "DANMU_CONTENT": [
        "_(:3」∠)_",
        "(^・ω・^ )",
        "(●￣(ｴ)￣●)",
        "ε=ε=(ノ≧∇≦)ノ",
        "⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄",
        "←◡←"
    ],
    "DANMU_ROOMID": [
        "22803603",
        "650",
        "452138",
        "22755636",
        "22465490",
        "544843",
        "23141761",
        "10918",
        "5520",
        "3749977",
        "942246",
        "1023"
    ],
    "DANMU_INTERVAL_TIME": [
        "60m"
    ],
    "DANMU_MODIFY_REGEX": [
        "/【/"
    ],
    "DANMU_MODIFY_UID": [
        0
    ],
    "DANMU_MODIFY_POOL": [
        4
    ],
    "DANMU_MODIFY_COLOR": [
        "#f7335d"
    ],
    "DANMU_MODIFY_SIZE": [
        1.2
    ],
    "GIFT_LIMIT": 5,
    "GIFT_SEND_HOUR": 23,
    "GIFT_SEND_MINUTE": 59,
    "GIFT_INTERVAL": 5,
    "GIFT_METHOD": "GIFT_INTERVAL",
    "GIFT_SORT": "GIFT_SORT_HIGH",
    "GIFT_ALLOW_TYPE": [
        "1"
    ],
    "GIFT_SEND_METHOD": "GIFT_SEND_WHITE",
    "GIFT_SEND_ROOM": [
        "452138",
        "22755636"
    ],
    "GET_PRIVILEGE": true,
    "LIVE_SIGN": true,
    "LOGIN": true,
    "LIKE_LIVEROOM": true,
    "LIKE_LIVEROOM_INTERVAL": 400,
    "LIVE_TASKS_ROOM": [
        "22803603",
        "650",
        "740",
        "452138",
        "544843",
        "22755636",
        "22465490",
        "10918",
        "23141761",
        "5520",
        "3749977",
        "942246",
        "1023",
        "11258437",
        "22957791"
    ],
    "LIVE_TASKS_METHOD": "LIVE_TASKS_WHITE",
    "MEDAL_DANMU_INTERVAL": 5,
    "MEDAL_DANMU": true,
    "MEDAL_DANMU_CONTENT": [
        "(⌒▽⌒)",
        "（￣▽￣）",
        "(=・ω・=)",
        "(｀・ω・´)",
        "(〜￣△￣)〜",
        "(･∀･)",
        "(°∀°)ﾉ",
        "╮(￣▽￣)╭",
        "_(:3」∠)_",
        "(^・ω・^ )",
        "(●￣(ｴ)￣●)",
        "ε=ε=(ノ≧∇≦)ノ",
        "⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄",
        "←◡←"
    ],
    "REMOVE_ELEMENT_2233": true,
    "REMOVE_ELEMENT_pkBanner": true,
    "REMOVE_ELEMENT_rank": true,
    "REMOVE_ELEMENT_rightSideBar": true,
    "REMOVE_ELEMENT_flipView": true,
    "REMOVE_ELEMENT_anchor": true,
    "REMOVE_ELEMENT_pk": true,
    "REMOVE_ELEMENT_playerIcon": true,
    "REMOVE_ELEMENT_ecommerce": true,
    "RND_DELAY_END": 5,
    "RND_DELAY_START": 2,
    "SEND_ALL_GIFT": false,
    "SHARE": true,
    "SILVER2COIN": true,
    "SPARE_GIFT_ROOM": "22755636",
    "TIME_RELOAD": true,
    "TIME_RELOAD_MINUTE": 1,
    "UPDATE_TIP": true,
    "WATCH": true,
    "WatchLive": true,
    "WatchLiveInterval": 400,
    "WatchLiveTime": 100
}`
[live.bilibili.com-1689171104256.log](https://github.com/andywang425/BLTH/files/12028820/live.bilibili.com-1689171104256.log)

### 操作系统

win11/  macOS 13-14

### 浏览器

edge 114.0.1823.79 

### 用户脚本管理器

暴力猴v2.14.0

### 挂机助手版本

6.1.5

### 网络情况

好

### 其他浏览器插件/脚本

no

### 其他

刷新功能在之前版本就一直未生效过

**Comment by andywang425** [comment]
收到。不过我想问下为什么需要每隔一段时间刷新页面呢，是因为长时间运行会页面卡顿吗。

**Comment by geekscloud** [comment]
> 收到。不过我想问下为什么需要每隔一段时间刷新页面呢，是因为长时间运行会页面卡顿吗。

因为如果不每日刷新, 每天的挂机只有100亲密度

**Comment by geekscloud** [comment]
> 收到。不过我想问下为什么需要每隔一段时间刷新页面呢，是因为长时间运行会页面卡顿吗。

如果能修复挂第二天开始不刷新页面, 也能正常挂满所有牌子1500 亲密度 也行.

**Comment by andywang425** [comment]
> 好耶, 新版要是能挂在docker里就更好了, 省的开浏览器了

这个项目的定位就是用户脚本，让大家不需要什么复杂的配置就能在看直播的同时把任务做了。所以不可能支持docker。

我能理解一部分高级用户更喜欢命令行程序，搞docker容器什么的。但肯定也有些用户做一些简单的环境配置（装Python，配置Docker等等）都费劲。我的目标就是做一个即使是小白也能轻松上手的脚本。

**Comment by geekscloud** [comment]
> > 好耶, 新版要是能挂在docker里就更好了, 省的开浏览器了
> 
> 这个项目的定位就是用户脚本，让大家不需要什么复杂的配置就能在看直播的同时把任务做了。所以不可能支持docker。
> 
> 我能理解一部分高级用户更喜欢命令行程序，搞docker容器什么的。但肯定也有些用户做一些简单的环境配置（装Python，配置Docker等等）都费劲。我的目标就是做一个即使是小白也能轻松上手的脚本。

ok，可以的，等你新版我研究一下，我也是开发者， 我试试看弄个docker版本，哈哈哈

**Comment by SameIe** [comment]
> > 收到。不过我想问下为什么需要每隔一段时间刷新页面呢，是因为长时间运行会页面卡顿吗。
> 
> 因为如果不每日刷新, 每天的挂机只有100亲密度

你可以现在暂时用一下 Tab Reloader 的插件，我设置7分半一次自动刷新。等作者更新了就就更好

**Comment by SameIe** [comment]
> 

我也有一个问题，那就是挂机直播间增加亲密度不是所有直播间同步一起增加的，总是有一部分在增加一部分不加，所以需要过一段时间刷新一次页面来达到让所有直播间都能够增加亲密度！ 还有那个获得电池的app任务无效了，不过那应该是因为b站没活动了，我就提一句。

**Comment by SameIe** [comment]
> 收到。不过我想问下为什么需要每隔一段时间刷新页面呢，是因为长时间运行会页面卡顿吗。

我也有一个问题，那就是挂机直播间增加亲密度不是所有直播间同步一起增加的，总是有一部分在增加一部分不加，所以需要过一段时间刷新一次页面来达到让所有直播间都能够增加亲密度！ 还有那个获得电池的app任务无效了，不过那应该是因为b站没活动了，我就提一句。
