### ISSUE TITLE
直播间的SC打开后无法折叠

### ISSUE THREAD

**Issue by Shichimiyasatone** [andywang425/BLTH#40]
![image](https://user-images.githubusercontent.com/35890954/102681158-20a13f80-41fa-11eb-9b98-a141689b6f84.png)
谷歌浏览器，不仅SC（醒目留言）折叠存在问题，SC到时消失貌似也存在问题

**Comment by andywang425** [comment]
等我找到个有SC的直播间后就去测试一下。  
另外这个问题是不是由脚本引起的？把脚本关掉以后就不存在这个问题了吗。

**Comment by Shichimiyasatone** [comment]
> 等我找到个有SC的直播间后就去测试一下。
> 另外这个问题是不是由脚本引起的？把脚本关掉以后就不存在这个问题了吗。

是由脚本引起的，一般虚拟主播分区的SC会很多，辛苦了

**Comment by andywang425** [comment]
我刚刚在团长的直播间（[https://live.bilibili.com/21396545](https://live.bilibili.com/21396545)）测试，没发现任何问题。SC显示，折叠，消失都很正常。  
我在下一个新版本（5.6.4）中会尝试做一些修改，如果还有问题的话请告诉我。

**Comment by Shichimiyasatone** [comment]
我发现了，问题不是出在脚本上。
我用的Tampermonkey BETA，版本4.9.5941，换到Tampermonkey 4.11问题消失了。
在BETA上，除了SC，还有很多其他的点击失效问题。
不好意思，搞了个乌龙XD

**Comment by andywang425** [comment]
没事，解决了就好
