### ISSUE TITLE
直播隐身入场功能

### ISSUE THREAD

**Issue by NekoKuro6011** [andywang425/BLTH#408]
### 描述

请问隐身入场功能在新版本会加上吗？

**Comment by andywang425** [comment]
这个功能不是很想加，一是这个需要拦截B站API请求且副作用大，二是效果不好，因为贡献值的关系你还是会被主播发现。 
https://github.com/lzghzr/TampermonkeyJS/issues/51

**Comment by u2shana** [comment]
https://greasyfork.org/zh-CN/scripts/463629-b%E7%AB%99%E7%9B%B4%E6%92%AD%E9%9A%90%E8%BA%AB%E8%A7%82%E7%9C%8B
这个脚本我之前用过，能完全隐身主播的直播姬也没进场提示

**Comment by andywang425** [comment]
> https://greasyfork.org/zh-CN/scripts/463629-b%E7%AB%99%E7%9B%B4%E6%92%AD%E9%9A%90%E8%BA%AB%E8%A7%82%E7%9C%8B 这个脚本我之前用过，能完全隐身主播的直播姬也没进场提示

我看了下代码：
```js
(function() {
    'use strict';
    ah.proxy({
        onRequest: (config, handler) => {
            //console.log(config)
            if (config.url.includes('/xlive/web-room/v1/index/getInfoByUser')) {
                config.url=config.url.replace('&not_mock_enter_effect=0','')+'&not_mock_enter_effect=1'
                handler.next(config);
            }
            else if(config.url.includes('/xlive/data-interface/v1/x25Kn/X')){
                return
            }
            else{
                handler.next(config);
            }
        },
    },unsafeWindow);
 
})();
```

确实有收获，看起来把`not_mock_enter_effect`设置成`1`就能不触发入场效果。
不过`/xlive/data-interface/v1/x25Kn/X`这个API是脚本要用到的（观看直播功能），不能全部都给拦截了。这就有点难办。

**Comment by NekoKuro6011** [comment]
好的 感谢！我试试这个插件！
