### ISSUE TITLE
隐身进直播间功能

### ISSUE THREAD

**Issue by ztca** [andywang425/BLTH#409]
### 描述

隐身进直播间功能无了,请问以后考虑加上吗?

**Comment by ADJazzzz** [comment]
看这个 #408

**Comment by andywang425** [comment]
现在暂时不打算加，但 issue 就先开着吧。

**Comment by andywang425** [comment]
受限于一些架构上的问题这类功能不好实现。今天下午花了不少时间，但最后我还是放弃了。建议用 https://github.com/lzghzr/TampermonkeyJS/blob/master/BiLiveNoVIP/BiLiveNoVIP.user.js 。
