### ISSUE TITLE
［非BUG］能否做成不需要浏览器的形式？

### ISSUE THREAD

**Issue by wangmanv2** [andywang425/BLTH#41]
bilibili直播页面有时候经常出现加载不出来的情况。

想知道能否只是运行一个程序挂在服务器或者nas上就能实现一样的操作呢？

**Comment by andywang425** [comment]
我目前没那么多精力去把这个脚本重写成nodejs项目😥，也就是你说的不需要浏览器的形式。抱歉啦。

**Comment by wangmanv2** [comment]
噢噢，感谢您的回复。
