### ISSUE TITLE
重置任务功能

### ISSUE THREAD

**Issue by Only-Mio** [andywang425/BLTH#412]
### 描述

重置任务缓存功能

**Comment by andywang425** [comment]
以后不会有了。

**Comment by Only-Mio** [comment]
有时执行完一遍，会发现亲密度没满的粉丝牌，需要把这些没满的再执行一下

**Comment by andywang425** [comment]
> 有时执行完一遍，会发现亲密度没满的粉丝牌，需要把这些没满的再执行一下

亲密度没满可以看作Bug。如果你确定有粉丝勋章被执行任务后亲密度还是没满，且直播间正常（设置了分区等等），请提交issue并详细说明情况。

**Comment by Only-Mio** [comment]
还在使用6.的版本，不知新版本有没有这样的问题。1、打卡使用白名单，大概超过50个直播间，就会发现获取不全和重复获取问题（因为控制台可以看到获取到的直播间和数量，每次刷新后可能都不一样，才发现这个问题）。2、点赞使用白名单，因为只设置30个左右，获取正常，但会出现点赞亲密度没加上（模拟观看同）。以上通过重复执行就能满亲密度，所以才想说能不能加上这个功能T_T

**Comment by Only-Mio** [comment]
原来新版白名单变成勾选了啊，可观性很好，但不灵活了T_T用的多组白名单用习惯了

**Comment by andywang425** [comment]
> 原来新版白名单变成勾选了啊，可观性很好，但不灵活了T_T用的多组白名单用习惯了

高级用户可以自己改油猴的存储。最终存储的数据还是房间号数组，你可以把以前的配置填进去用。
![image](https://github.com/andywang425/BLTH/assets/56548456/fe553409-8686-4fa6-992f-02120128be66)

**Comment by Only-Mio** [comment]
好的谢谢！
