### ISSUE TITLE
粉丝勋章相关任务不忽略已注销账户 

### ISSUE THREAD

**Issue by xiaoBingge114514** [andywang425/BLTH#413]
### 描述

![image](https://github.com/andywang425/BLTH/assets/105868119/af9bbde5-7039-4bca-a4ca-50c4b2429c63)
真的我很需要这个功能，旧版还有来着（指旧版可以填直播间），直播间也在，就是白名单里不显示。。。
只是为了一个纪念。。
😥😥

**Comment by xiaoBingge114514** [comment]
![image](https://github.com/andywang425/BLTH/assets/105868119/da5dcc93-2504-446a-aa5f-206f7dd5773b)

**Comment by andywang425** [comment]
行
