### ISSUE TITLE
直播任务未完成，但是脚本显示任务已完成

### ISSUE THREAD

**Issue by kevinkejc** [andywang425/BLTH#418]
### 描述bug

直播任务未完成，但是脚本显示任务已完成

![image](https://github.com/andywang425/BLTH/assets/75735934/11e72574-23e4-4dbe-b3b0-5894a4b69ec9)
![image](https://github.com/andywang425/BLTH/assets/75735934/bcd76e2d-2b74-4fc1-bf9f-328f7ca63023)

PS: 那个有200亲密值的是我挂机的直播间

### 重现bug

没有进行操作，打开电脑之后就发现这样了

### 预期行为

粉丝牌亲密度全满

### 运行日志

![image](https://github.com/andywang425/BLTH/assets/75735934/a30c41ac-1714-42b3-b0ec-5bcc0344cbce)

### 操作系统

Windows10 21H2

### 浏览器

Google Chrome 115.0.5790.171（正式版本）（64 位）

### 用户脚本管理器

Tampermonkey v4.19.0

### 脚本版本号

7.0.4 

### 网络情况

好

### 其他

在旧版本遇到这种问题的时候 重置一下直播任务缓存就恢复正常了

**Comment by andywang425** [comment]
我先问几个问题，方便我们接下来排查原因。
- 请问您所在的地区是位于哪个时区？
- 脚本上一次执行任务的时候正常吗？
- 脚本上一次完成任务的时候大概是几点开始几点结束？

**Comment by kevinkejc** [comment]
时区 北京时间 UTC+8

上一次也是这种情况，显示完成任务了但是亲密度实际没加

这都得追溯到上上次执行任务了，也确实是记不起来了

**Comment by andywang425** [comment]
好吧，我也不知道为什么了。加个help wanted的tag看看有没有大佬明白。

**Comment by andywang425** [comment]
最后说个临时解决方案，可以打开脚本的存储：
![image](https://github.com/andywang425/BLTH/assets/56548456/6bdeac12-04e3-4cca-95ff-f5e798e3ac60)

然后把想要再执行一次的任务的`_lastCompleteTime`改成`0`，或者把原来的数字给它删掉一位也行。之后刷新页面脚本就会把这个任务再执行一遍。

至于每个配置项对应哪个任务，你就看着来吧，都是可读的英语单词。改错了也没事，大不了多执行一次。

**Comment by kevinkejc** [comment]
我试了一下这个临时解决方法，把再执行一次的任务的`_lastCompleteTime`改成0 保存之后刷新了直播页面，但貌似是没效果的，依然是显示任务完成，然后刷新脚本存储页面之后`_lastCompleteTime`又变回了之前的数值，难不成是我操作的方法不对吗

**Comment by andywang425** [comment]
任务是执行了，但是立刻就完成了。很奇怪，这种情况说明没有能执行任务的粉丝勋章。黑白名单设置得对吗？以及你有没有等级小于20且直播间存在的粉丝勋章。

**Comment by kevinkejc** [comment]
闹了个大乌龙，这波是我的问题了，黑名单设置错误导致的，上次设置黑名单的时候全勾上了，又忘记把黑名单给改回去，才导致的这乌龙，实在是抱歉！

**Comment by andywang425** [comment]
没事，解决了就好。
