### ISSUE TITLE
更新5.6.4版本后，无法正常工作

### ISSUE THREAD

**Issue by ToumaLover** [andywang425/BLTH#43]
**描述bug**  
更新最新版本BLTH后，
进入直播间后BLTH界面不出现，且bilibili-evolved也不出现
禁用bilibili-evolved后BLTH同样无法工作

**重现bug**  
进入某个直播间

**预期行为**  
出现BLTH的按钮

**截图**  
如果可以，请提供有关截图  

**运行日志**  
以下日志为仅运行BLTH的日志
`控制台已清除。 player-loader-latest.min.js:27:254
构建时间：Fri Dec 25 2020 14:19:55 GMT+0800 (中国标准时间) player-loader-latest.min.js:25:75083
fMp4Player v1.18 player-loader-latest.min.js:27:120328
即使其 MIME 类型（“text/html”）不是有效的 JavaScript MIME 类型，仍已加载来自“https://www.bilibili.com/plus/widget/ajaxGetCaptchaKey.php?js”的脚本。
22566228
某些 Cookie 滥用推荐的“sameSite“属性 3
Object { team_id: 0, rank_type: 2, daily_score: 0, daily_rank: 0, total_score: 0, total_rank: 0, rank_type_status: 0, rank_type_value: 0, is_settle: 0, is_static: 1, … }
activity-entry.7b08d02cb2dac72bf49c.js:16:123705
[Player] Tracking STATISTICS_PLAYURL_LOADED (342). player-loader-latest.min.js:44:13223
[Player] Tracking STATISTICS_LIVE_PLAYER_INIT (364). player-loader-latest.min.js:44:13223
Bilibili Live V4.0.0 "Life Experience" Lovingly By © 2014 - 2020 Bilibili Live Department  ...(●'◡'●)ﾉ♥   # Renascence # main.127bb8a6856ee77de078.js:68:1028304
Version: V4.0.0 "Life Experience", CodeName: Neptune. main.127bb8a6856ee77de078.js:68:1028464
[Player] Tracking UV (0). player-loader-latest.min.js:44:13223
此网站似乎使用 scroll-linked 定位效果。这可能无法与异步平移一起使用；参见 https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects 详细了解，也可加入我们一起讨论相关的工具和功能！ 22566228
Object { team_id: 0, rank_type: 2, daily_score: 0, daily_rank: 0, total_score: 0, total_rank: 0, rank_type_status: 0, rank_type_value: 0, is_settle: 0, is_static: 1, … }
`

**使用环境:**  
 - 操作系统：`Windows 10`
 - 浏览器及浏览器版本: 如`Firefox 78.6.0esr`
 - 脚本的版本: `5.6.4`
 - 网络情况(网速): `一般`
 - 其他浏览器插件/脚本: `bilibili-evolved 1.11.5`  `Tampermonkey 4.11.6120`

**其他**  
上个版本BLTH无此问题

**Comment by andywang425** [comment]
5.6.4版本中有部分资源并没有直接写在脚本中而是从远程获取，然后再借助Tampermonkey保存。我觉得可能和这个有关。  

请先打开Tampermonkey，在设置中把`配置模式`改为`高级`，然后在已安装脚本中找到并打开本脚本，点上方的`外部`。  
正常情况下`要求`中应该有以下几个库文件：Ajax-hook.min.js，BilibiliAPI_Mod.min.js，layer.js，libBilibiliToken.min.js，libWasmHash.min.js，base64.min.js。  

`资源`中应该有以下几个文件：layer.css，myCss-min.css，main-min.html，eula-min.html。  
请检查一下是否有文件没获取成功。

**Comment by Gensokyo1995** [comment]
同样遇到5.6.4版本按钮加载不出来无法工作的情况，已确认外部中的文件都存在

**Comment by andywang425** [comment]
正在找这个问题的原因，目前还不大清楚具体是什么原因导致的。可以安装一下我刚写的[测试脚本(5.6.4.1)](https://cdn.jsdelivr.net/gh/andywang425/BLTH@6e71f43aeacfcd752fbc3073b5d6c0bd960b63fa/test/B站直播间挂机助手-测试.js)试试看。需要手动复制到Tampermonkey新建脚本安装。

**Comment by ToumaLover** [comment]
> 
> 
> 正在找这个问题的原因，目前还不大清楚具体是什么原因导致的。可以安装一下我刚写的[测试脚本(5.6.4.1)](https://cdn.jsdelivr.net/gh/andywang425/BLTH@6e71f43aeacfcd752fbc3073b5d6c0bd960b63fa/test/B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B-%E6%B5%8B%E8%AF%95.js)试试看。需要手动复制到Tampermonkey新建脚本安装。

5.6.4.1工作正常

**Comment by andywang425** [comment]
> > 正在找这个问题的原因，目前还不大清楚具体是什么原因导致的。可以安装一下我刚写的[测试脚本(5.6.4.1)](https://cdn.jsdelivr.net/gh/andywang425/BLTH@6e71f43aeacfcd752fbc3073b5d6c0bd960b63fa/test/B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B-%E6%B5%8B%E8%AF%95.js)试试看。需要手动复制到Tampermonkey新建脚本安装。
> 
> 5.6.4.1工作正常

谢谢反馈，那我找到原因了，以后的版本会做修改。

**Comment by ToumaLover** [comment]
> 
> 
> > > 正在找这个问题的原因，目前还不大清楚具体是什么原因导致的。可以安装一下我刚写的[测试脚本(5.6.4.1)](https://cdn.jsdelivr.net/gh/andywang425/BLTH@6e71f43aeacfcd752fbc3073b5d6c0bd960b63fa/test/B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B-%E6%B5%8B%E8%AF%95.js)试试看。需要手动复制到Tampermonkey新建脚本安装。
> > 
> > 
> > 5.6.4.1工作正常
> 
> 谢谢反馈，那我找到原因了，以后的版本会做修改。

5.6.4.2版本出现了同样错误，无法正常加载

**Comment by andywang425** [comment]
> 5.6.4.2版本出现了同样错误，无法正常加载

这个版本只是在脚本里加了个新的q群链接，并没有动过加载逻辑。你现在还能用5.6.4.1吗。

**Comment by ToumaLover** [comment]
> 
> 
> > 5.6.4.2版本出现了同样错误，无法正常加载
> 
> 这个版本只是在脚本里加了个新的q群链接，并没有动过加载逻辑。你现在还能用5.6.4.1吗。

5.6.4.1可以使用，是否我先挂个代理等待顺利加载之后使用比较好？
或者您可以参考bilibili-evolved推出离线版来避免网络环境导致的加载问题
