### ISSUE TITLE
点赞直播间新选项：包含等级≥20的粉丝勋章

### ISSUE THREAD

**Issue by kevinkejc** [andywang425/BLTH#436]
### 描述

![image](https://github.com/andywang425/BLTH/assets/75735934/747c5a0b-8621-4133-882e-e66dfa395911)
我目前是有一个满级牌一个舰长牌，更新新版本之后就熄灭了，不知道是我的问题还是说新版本就略过了满级粉丝牌和舰长粉丝牌(黑名单设置也是没问题的)，如果是直接略过的话，就想着可不可以给脚本增加一个仅点亮这两种牌子的功能
![image](https://github.com/andywang425/BLTH/assets/75735934/8af98e1d-b3f3-4740-a168-06b95fa736b1)
根据帮助中心给的点亮方式，脚本可以每隔几天往满级牌和舰长牌直播间发条弹幕或者点个赞，不进行直播观看任务

**Comment by andywang425** [comment]
> 如果是直接略过的话，就想着可不可以给脚本增加一个仅点亮这两种牌子的功能

BLTH默认过滤等级大于等于20的粉丝勋章。我感觉加一个选项“为等级大于等于20的粉丝勋章点赞”是不是能满足你的需求？

> 据帮助中心给的点亮方式，脚本可以每隔几天往满级牌和舰长牌直播间发条弹幕或者点个赞，不进行直播观看任务

每隔几天做起来麻烦，频率还是每天吧。

**Comment by kevinkejc** [comment]
>我感觉加一个选项“为等级大于等于20的粉丝勋章点赞”是不是能满足你的需求？

对于我而言只要可以点亮牌子，无论是点赞还是发弹幕都是可以满足需求的

**Comment by andywang425** [comment]
在做了<https://github.com/andywang425/BLTH/commit/8f0d6d4b18f7624473afabbb93f05eff1b706c4e>。

**Comment by lucifere02** [comment]
> 在做了[8f0d6d4](https://github.com/andywang425/BLTH/commit/8f0d6d4b18f7624473afabbb93f05eff1b706c4e)。

光点赞似乎无法点亮勋章，希望加上支持20级以上的粉丝勋章的每天自动发弹幕功能，感谢！！！

**Comment by andywang425** [comment]
> 光点赞似乎无法点亮勋章，希望加上支持20级以上的粉丝勋章的每天自动发弹幕和模拟观看功能，感谢！！！

嗯，以后可能会做个自动发弹幕点亮20级以上的粉丝勋章的功能。
