### ISSUE TITLE
领取年度大会员权益功能测试

### ISSUE THREAD

**Issue by andywang425** [andywang425/BLTH#441]
由于我这个月已经领过了，下次领要等31天，故放出测试版让大伙测试一下。

需要有年度大会员且这个月还没领过权益 https://account.bilibili.com/account/big/myPackage 。

可以前往dev分支自行编译，或者下载下面的压缩包然后手动在用户脚本管理器中安装。压缩包里有两个脚本，分别是压缩的和未压缩的，选一个安装就行。测试完领取年度大会员权益功能后在本issue下回复你的测试结果即可，最好是能带上相关控制台日志，谢谢。

[dist.zip](https://github.com/andywang425/BLTH/files/12311381/dist.zip)

**Comment by kevinkejc** [comment]
已试 成功领取

![image](https://github.com/andywang425/BLTH/assets/75735934/a632720f-b635-4711-aa53-931da964aeda)

**Comment by andywang425** [comment]
> 已试 成功领取

感谢测试，那我就准备发布新版本了。
