### ISSUE TITLE
脚本无法召出控制面板

### ISSUE THREAD

**Issue by kawaiishiro** [andywang425/BLTH#447]
### 描述bug

从github,greasyfork各安装了一次脚本，也把其他所有插件都下了，也在F12的源代码中找到了bilibili live tasks helper,但就是没有控制面板的UI，alt+b也是没法召出。在版本更新前，用了好久也是没有问题的（我清楚这个应该是个人环境原因，但始终无法找到解决办法）

### 重现bug

重启浏览器，随机打开一个直播间，等待5分钟后没有反应，刷新后仍然无法看见控制面板UI，也没有自动执行任务

### 预期行为

出现控制面板并弹出右上角的日志

### 截图

![image](https://github.com/andywang425/BLTH/assets/98079313/34e84591-04e0-4249-8f2b-1b724c46687a)

### 运行日志

按README的步骤操作，找不到开头为BLTH的
![image](https://github.com/andywang425/BLTH/assets/98079313/826867a7-bae1-4076-bd21-c5bd0c2e3327)

### 操作系统

Win 11

### 浏览器

Chrome 97.0.4692.71

### 用户脚本管理器

Tampermonkey 4.20.6185

### 脚本版本号

7.0.8

### 网络情况

好

### 其他浏览器拓展/用户脚本

Bilibili Evolved(已尝试禁用)

**Comment by kawaiishiro** [comment]
刚刚看了以前的issue看到有类似问题，但我并不是高级用户，程序知识甚少，所以求个解决办法

**Comment by andywang425** [comment]
> F12的源代码中找到了bilibili live tasks helper

是不是指找到了类似`<div id="BLTH" data-v-app>`的代码？

找不到带BLTH日志的话，就把所有日志发出来吧，我再分析一下。

**Comment by kawaiishiro** [comment]
我不是特别懂控制台的操作，如果需要补充可以再截图
![image](https://github.com/andywang425/BLTH/assets/98079313/8e879afe-fec1-4c9e-b4b3-561dea198df6)
![image](https://github.com/andywang425/BLTH/assets/98079313/3044b906-b9f4-41cc-9417-b311d3145220)

**Comment by kawaiishiro** [comment]
等待数分钟后，又出现了以下日志：
sentry-5.2.1.min.js:2 [Vue warn]: $attrs is readonly.

found in

---> <LazyLoadCom>
       <St>
         <TransitionGroup>
           <Anonymous>
             <AsyncLoadComp>
               <Anonymous>
                 <ActivityEntry>
                   <HeadInfo>
                     <Root>
（匿名） @ sentry-5.2.1.min.js:2
console.error @ 179.63a9b7ec3cddaec5cb3c.js:2
vt @ vendors.94f5b7d271ebc428b727.js:2
（匿名） @ vendors.94f5b7d271ebc428b727.js:2
set @ vendors.94f5b7d271ebc428b727.js:2
Rn @ remoteEntry.js:28
prepatch @ remoteEntry.js:28
j @ remoteEntry.js:28
O @ remoteEntry.js:28
j @ remoteEntry.js:28
（匿名） @ remoteEntry.js:28
Ln.e._update @ remoteEntry.js:28
r @ remoteEntry.js:28
ar.get @ remoteEntry.js:28
ar.run @ remoteEntry.js:28
er @ remoteEntry.js:28
（匿名） @ remoteEntry.js:28
dt @ remoteEntry.js:28
Promise.then（异步）
ut @ remoteEntry.js:28
yt @ remoteEntry.js:28
ir @ remoteEntry.js:28
ar.update @ remoteEntry.js:28
ye.notify @ remoteEntry.js:28
set @ remoteEntry.js:28
pr @ vendors.94f5b7d271ebc428b727.js:2
prepatch @ vendors.94f5b7d271ebc428b727.js:2
R @ vendors.94f5b7d271ebc428b727.js:2
C @ vendors.94f5b7d271ebc428b727.js:2
R @ vendors.94f5b7d271ebc428b727.js:2
（匿名） @ vendors.94f5b7d271ebc428b727.js:2
t._update @ vendors.94f5b7d271ebc428b727.js:2
_update @ vendors.94f5b7d271ebc428b727.js:2
r @ vendors.94f5b7d271ebc428b727.js:2
Dr.get @ vendors.94f5b7d271ebc428b727.js:2
Dr.run @ vendors.94f5b7d271ebc428b727.js:2
Cr @ vendors.94f5b7d271ebc428b727.js:2
（匿名） @ vendors.94f5b7d271ebc428b727.js:2
Me @ vendors.94f5b7d271ebc428b727.js:2
Promise.then（异步）
Se @ vendors.94f5b7d271ebc428b727.js:2
De @ vendors.94f5b7d271ebc428b727.js:2
Ir @ vendors.94f5b7d271ebc428b727.js:2
Dr.update @ vendors.94f5b7d271ebc428b727.js:2
Ot.notify @ vendors.94f5b7d271ebc428b727.js:2
set @ vendors.94f5b7d271ebc428b727.js:2
（匿名） @ 7929.a4e09146.js:1
await in （匿名）（异步）
mergeBroadcast @ 7929.a4e09146.js:1
（匿名） @ 7929.a4e09146.js:1
$emit @ 1370.28ccf1ea.js:14
l @ 7929.a4e09146.js:1
（匿名） @ app.ec369d50545b7c6b9411.js:2
Promise.then（异步）
Sn @ app.ec369d50545b7c6b9411.js:2
（匿名） @ room-player.min.js:20
emit @ room-player.min.js:20
emit @ room-player.min.js:198
（匿名） @ room-player.min.js:198
（匿名） @ room-player.min.js:20
emit @ room-player.min.js:20
（匿名） @ room-player.min.js:92
onReceivedMessage @ room-player.min.js:92
t.onMessageReply @ room-player.min.js:90
（匿名） @ room-player.min.js:90
t.onMessageReply @ room-player.min.js:90
t.onMessage @ room-player.min.js:90
sentry-5.2.1.min.js:2 [Vue warn]: $listeners is readonly.

found in

---> <LazyLoadCom>
       <St>
         <TransitionGroup>
           <Anonymous>
             <AsyncLoadComp>
               <Anonymous>
                 <ActivityEntry>
                   <HeadInfo>
                     <Root>
（匿名） @ sentry-5.2.1.min.js:2
console.error @ 179.63a9b7ec3cddaec5cb3c.js:2
vt @ vendors.94f5b7d271ebc428b727.js:2
（匿名） @ vendors.94f5b7d271ebc428b727.js:2
set @ vendors.94f5b7d271ebc428b727.js:2
Rn @ remoteEntry.js:28
prepatch @ remoteEntry.js:28
j @ remoteEntry.js:28
O @ remoteEntry.js:28
j @ remoteEntry.js:28
（匿名） @ remoteEntry.js:28
Ln.e._update @ remoteEntry.js:28
r @ remoteEntry.js:28
ar.get @ remoteEntry.js:28
ar.run @ remoteEntry.js:28
er @ remoteEntry.js:28
（匿名） @ remoteEntry.js:28
dt @ remoteEntry.js:28
Promise.then（异步）
ut @ remoteEntry.js:28
yt @ remoteEntry.js:28
ir @ remoteEntry.js:28
ar.update @ remoteEntry.js:28
ye.notify @ remoteEntry.js:28
set @ remoteEntry.js:28
pr @ vendors.94f5b7d271ebc428b727.js:2
prepatch @ vendors.94f5b7d271ebc428b727.js:2
R @ vendors.94f5b7d271ebc428b727.js:2
C @ vendors.94f5b7d271ebc428b727.js:2
R @ vendors.94f5b7d271ebc428b727.js:2
（匿名） @ vendors.94f5b7d271ebc428b727.js:2
t._update @ vendors.94f5b7d271ebc428b727.js:2
_update @ vendors.94f5b7d271ebc428b727.js:2
r @ vendors.94f5b7d271ebc428b727.js:2
Dr.get @ vendors.94f5b7d271ebc428b727.js:2
Dr.run @ vendors.94f5b7d271ebc428b727.js:2
Cr @ vendors.94f5b7d271ebc428b727.js:2
（匿名） @ vendors.94f5b7d271ebc428b727.js:2
Me @ vendors.94f5b7d271ebc428b727.js:2
Promise.then（异步）
Se @ vendors.94f5b7d271ebc428b727.js:2
De @ vendors.94f5b7d271ebc428b727.js:2
Ir @ vendors.94f5b7d271ebc428b727.js:2
Dr.update @ vendors.94f5b7d271ebc428b727.js:2
Ot.notify @ vendors.94f5b7d271ebc428b727.js:2
set @ vendors.94f5b7d271ebc428b727.js:2
（匿名） @ 7929.a4e09146.js:1
await in （匿名）（异步）
mergeBroadcast @ 7929.a4e09146.js:1
（匿名） @ 7929.a4e09146.js:1
$emit @ 1370.28ccf1ea.js:14
l @ 7929.a4e09146.js:1
（匿名） @ app.ec369d50545b7c6b9411.js:2
Promise.then（异步）
Sn @ app.ec369d50545b7c6b9411.js:2
（匿名） @ room-player.min.js:20
emit @ room-player.min.js:20
emit @ room-player.min.js:198
（匿名） @ room-player.min.js:198
（匿名） @ room-player.min.js:20
emit @ room-player.min.js:20
（匿名） @ room-player.min.js:92
onReceivedMessage @ room-player.min.js:92
t.onMessageReply @ room-player.min.js:90
（匿名） @ room-player.min.js:90
t.onMessageReply @ room-player.min.js:90
t.onMessage @ room-player.min.js:90

**Comment by andywang425** [comment]
我看了下，问题出在这：
![image](https://github.com/andywang425/BLTH/assets/56548456/6cd95471-f096-43d7-9a80-67f697ae9781)

然后你说你的用户脚本管理器是Tampermonkey 4.20.6185，但是现在Tampermonkey的正式版的版本号才到4.19（图标是黑色的），但是Tampermonkey测试版最新版本是4.20（图标是红色）。你用的是正式版的Tampermonkey还是测试版？

测试版在4.20这个版本有一项重大改动，我怀疑可能是这项改动引起的。如果你现在用的是测试版，可以先换回正式版的Tampermonkey试试。

**Comment by andywang425** [comment]
![image](https://github.com/andywang425/BLTH/assets/56548456/5a8546fa-21f2-4b58-830c-57707bd08a9d)
看来确实是。

**Comment by ADJazzzz** [comment]
昨天我也是这个情况，看日志后其实是unpkg的一个库在国内网络（至少是我的网）加载不出来，改个host就出来了

**Comment by andywang425** [comment]
> 昨天我也是这个情况，看日志后其实是unpkg的一个库在国内网络（至少是我的网）加载不出来，改个host就出来了

你说得对，我漏看一条日志，确实是网络问题。

**Comment by kawaiishiro** [comment]
那么请教一下该怎么操作呢？

**Comment by kawaiishiro** [comment]
尝试了回退测试版Tampermonkey，无效

**Comment by kawaiishiro** [comment]
好像真是代理问题，我直接把代理软件退了，控制面板玄学的出现了

**Comment by ADJazzzz** [comment]
> 那么请教一下该怎么操作呢？

可以用`UsbEAm Hosts Editor`改

**Comment by andywang425** [comment]
理论上来说`unpkg.com`这个网站应该全国都能正常访问的，直连就可以不用代理。
![image](https://github.com/andywang425/BLTH/assets/56548456/2811b373-68e9-4466-bbd1-7e25f8986fbf)

**Comment by andywang425** [comment]
> 好像真是代理问题，我直接把代理软件退了，控制面板玄学的出现了

解决了就好，那我关issue了。

**Comment by andywang425** [comment]
也许以后可以在README里加一段因为网络问题获取不到依赖的解决办法。

**Comment by andywang425** [comment]
```
// @require         https://unpkg.com/vue@3.3.4/dist/vue.global.prod.js
// @require         data:application/javascript,window.Vue%3DVue%2Cwindow.VueDemi%3DVue%3B
// 省略...
```
突然又有个想法，或许可以稍微改一下上面的第二行，如果`Vue`这个变量不存在（遇到了网络问题，前面一个依赖没获取到），就提示一下什么的。

**Comment by Cloud-wish** [comment]
> 也许以后可以在README里加一段因为网络问题获取不到依赖的解决办法。

卡巴斯基的网络防护会阻止脚本运行，表现与该issue相似，关闭后脚本正常加载。需要关闭这两项设置：

<img width="527" alt="ka" src="https://github.com/andywang425/BLTH/assets/30196172/af37b0d3-57cc-4e90-85c6-040de1b3f417">
