### ISSUE TITLE
没有控制面板

### ISSUE THREAD

**Issue by a776058959** [andywang425/BLTH#455]
### 描述bug

没有控制面板，用老版本的时候是有控制面板的，刚才装了新版，删掉了老版本，还把浏览器重启了也不行
其他所有脚本都关掉了，包括去广告插件也关掉试过，还有梯子也关掉试过

### 重现bug

打开就直接没有

### 预期行为

出现控制面板

### 截图

![image](https://github.com/andywang425/BLTH/assets/58454818/d56c29c5-cb85-4e24-99a1-11387e6553b3)

### 运行日志

![image](https://github.com/andywang425/BLTH/assets/58454818/2d8efa17-dc6b-4edd-94cf-851b5e68ae0e)
![image](https://github.com/andywang425/BLTH/assets/58454818/13855e34-5700-4b89-8441-3dec779db63e)

### 操作系统

windows11

### 浏览器

Microsoft Edge 117.0.2045.9 (正式版本)

### 用户脚本管理器

Violentmonkey

### 脚本版本号

7.0.9

### 网络情况

一般

**Comment by andywang425** [comment]
这个问题已经有头绪了，https://github.com/andywang425/BLTH/discussions/453

下个版本一定修好。
