### ISSUE TITLE
防挂机检测功能

### ISSUE THREAD

**Issue by ADJazzzz** [andywang425/BLTH#457]
### 描述

建议加个挂机检测功能

**Comment by andywang425** [comment]
我觉得行。目前B站没有检测事件的`isTrusted`属性，最简单的方法就是定时触发个鼠标移动事件什么的。

**Comment by ADJazzzz** [comment]
今天头疼躺床上挂着直播间听歌大概一个小时跳窗口，不知道是不是这个时间，如果是可以30分钟触发，应该能减少性能损失

**Comment by andywang425** [comment]
> 今天头疼躺床上挂着直播间听歌大概一个小时跳窗口，不知道是不是这个时间，如果是可以30分钟触发，应该能减少性能损失

触个事件导致的性能损失几乎没有，性能损失的大头还是B站写的垃圾代码。1分钟，5分钟还是半小时触发一次都行。

是阳了吗，祝早日康复。

**Comment by ADJazzzz** [comment]
> > 今天头疼躺床上挂着直播间听歌大概一个小时跳窗口，不知道是不是这个时间，如果是可以30分钟触发，应该能减少性能损失
> 
> 触个事件导致的性能损失几乎没有，性能损失的大头还是B站写的垃圾代码。1分钟，5分钟还是半小时触发一次都行。
> 
> 是阳了吗，祝早日康复。

阳倒没有，可能是睡眠不足，PR已经提交了
