### ISSUE TITLE
调整获取粉丝勋章相关逻辑

### ISSUE THREAD

**Issue by onlyaparsee** [andywang425/BLTH#461]
### 描述

新版本脚本执行的直播任务只有前100个，我的牌子很多，100个不太够用，以前的旧版本现在用着还能挂全部牌子，但是要刷新好几次才能挂完，能不能给新版本加一个是否只为前100个粉丝勋章执行直播任务的功能

**Comment by andywang425** [comment]
每天最多就能为199个粉丝勋章完成任务，这是B站的限制。BLTH设置最多100个是防止用户自己看直播、点赞触及199限制导致当天完全拿不到亲密度。

这个功能还是不加了，我们现在只做必要的功能，功能做太多新用户会用不明白的。

**Comment by onlyaparsee** [comment]
那可以优化一下黑白名单的显示吗，很多17、18级的牌子在黑白名单选项里根本看不到，给一个像旧版本那样手动输直播间号的备选也可以

**Comment by andywang425** [comment]
> 很多17、18级的牌子在黑白名单选项里根本看不到

是吗，我这从来没出现过这种情况。按理来说只有没有直播间的粉丝勋章不显示。

> 给一个像旧版本那样手动输直播间号的备选

可以直接在脚本管理器里改BLTH的存储，修改`modules.DailyTasks.LiveTasks.medalTasks.roomidList`这个数组即可。

**Comment by Cheng605** [comment]
> > 可能是我牌子太多的缘故，黑白名单就只能显示牌子到100个，能在上面看到的基本上就是执行任务的那些，用火狐或者chrome只能看到这么多
> 
> 我牌子确实不多，不到40个。刚才又看了一遍代码，也没有找到有问题的地方，按理说不应该只显示100个的。

我的也是这样，而且通过换佩戴刷首位勾选的名单总是不保存的样子

**Comment by andywang425** [comment]
刚刚又看了一遍代码，确实只会获取前100个粉丝勋章，当时主要的考虑是如果全部获取耗时可能会很长。我想想怎么调整比较好。
