### ISSUE TITLE
新版的粉丝牌总是无法挂满

### ISSUE THREAD

**Issue by xlxb1001** [andywang425/BLTH#464]
### 描述bug

新版的粉丝牌总是无法挂满，老版的没什么问题，粉丝牌一共199，舰长牌子80个，剩下都是普通粉丝牌。老版能挂到1400左右，剩下100刷新挂一下就好， 新版只能挂粉丝牌等级靠后的那几十个，剩下的全是0。老版挂的经验基本都是同步的，不会一个1400一个是0

### 操作系统

win11

### 浏览器

chrome

### 用户脚本管理器

黑猴 4.19

### 脚本版本号

7.1.1

**Comment by andywang425** [comment]
#461 目前有个问题就是脚本只会获取前100个粉丝勋章，下个版本会改。不过执行任务的粉丝勋章数量目前还是100，我本来是想给它改成B站的上限199，但又担心出问题。
