### ISSUE TITLE
0点时候有一些直播间没有发弹幕保持活跃

### ISSUE THREAD

**Issue by CyanTailwinds** [andywang425/BLTH#467]
### 描述bug

直播间发弹幕打卡功能没有在每一个有粉丝勋章的直播间发弹幕

### 重现bug

我有34个粉丝勋章，0点在一个粉丝勋章熄灭的直播间查看F12日志，看到日志里执行了2轮发送弹幕任务，两轮的直播间数量、直播间范围是相同的，都没有覆盖到我当前所在的直播间

### 预期行为

发送弹幕任务覆盖所有粉丝勋章直播间

### 运行日志

![image](https://github.com/andywang425/BLTH/assets/26496027/75260455-1d34-4c7e-b200-0fc9b9e70935)

### 操作系统

windows 11

### 浏览器

Microsoft Edge	117.0.2045.31

### 用户脚本管理器

tampermonkey 4.19.0

### 脚本版本号

7.1.2

### 网络情况

好

### 其他

发送弹幕模块是否会跳过粉丝等级>21级的？ 没点亮的粉丝勋章都是21以上的

**Comment by andywang425** [comment]
> 发送弹幕模块是否会跳过粉丝等级>21级的？ 没点亮的粉丝勋章都是21以上的

会跳过等级大于等于20的粉丝勋章。

**Comment by CyanTailwinds** [comment]
> > 发送弹幕模块是否会跳过粉丝等级>21级的？ 没点亮的粉丝勋章都是21以上的
> 
> 会跳过等级大于等于20的粉丝勋章。

原来是这样 我还以为旁边那个【包含等级≥20的粉丝勋章】是对发弹幕也生效的。目前≥20级别的发弹幕就是不支持是吧

**Comment by andywang425** [comment]
> 原来是这样 我还以为旁边那个【包含等级≥20的粉丝勋章】是对发弹幕也生效的。目前≥20级别的发弹幕就是不支持是吧

是的。以后可能会做。
