### ISSUE TITLE
5.6.4.3版本不显示“显示窗口和提示信息”的按钮

### ISSUE THREAD

**Issue by snowoneyebrow** [andywang425/BLTH#47]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README和脚本的内置说明。  
**描述bug**  
5.6.4.3版本不显示“显示窗口和提示信息”的按钮，降级到5.6.4.2版本就可以了。

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. 正常打开直播间

**预期行为**  
显示“显示窗口和提示信息”的按钮

**截图**  
如果可以，请提供有关截图  

**运行日志**  
控制台中出现的日志或错误提示。  
可以截图或者直接复制。  

**使用环境:**  
 - 操作系统：`Windows 10`
 - 浏览器及浏览器版本: 如`Microsoft Edge 版本 88.0.705.29 (官方内部版本) beta (64 位)`
 - 脚本的版本: 如`5.6.4.3`
 - 网络情况(网速): `好`
 - 其他浏览器插件/脚本: violentmonkey v2.12.9 Bilibili-Evolved v1.11.5

**其他**  
若您有其他想要补充的内容，请在此说明

**Comment by andywang425** [comment]
目前我还不清楚是什么原因造成的，可以先安装一下[测试脚本(5.6.4.1)](https://raw.githubusercontent.com/andywang425/BLTH/master/test/B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B-%E6%B5%8B%E8%AF%95.js)试试看，看看能不能正常使用

**Comment by snowoneyebrow** [comment]
好的 已降级到5.6.4.2正常使用 这个测试脚本先不装了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "andywang425/BLTH"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月3日(星期天) 凌晨0:14
收件人:&nbsp;"andywang425/BLTH"<BLTH@noreply.github.com&gt;;
抄送:&nbsp;"千城忆梦"<770117459@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [andywang425/BLTH] 5.6.4.3版本不显示“显示窗口和提示信息”的按钮 (#47)





 
目前我还不清楚是什么原因造成的，可以先安装一下测试脚本(5.6.4.1)试试看，看看能不能正常使用
