### ISSUE TITLE
希望加入自动领取大乱斗票的功能

### ISSUE THREAD

**Issue by neariver** [andywang425/BLTH#473]
### 描述

观看直播15分钟能免费领取大乱斗票，希望加入
![屏幕截图 2023-10-12 073703](https://github.com/andywang425/BLTH/assets/16076552/8760a511-0833-4779-a6a0-bed7701d7ed0)
![屏幕截图 2023-10-12 075404](https://github.com/andywang425/BLTH/assets/16076552/191ad1b1-3ea2-41fa-9659-8ad4d617b04d)

**Comment by andywang425** [comment]
这个活动在web端还是在app，每个直播间都有吗？我这边没找到这个窗口。

**Comment by neariver** [comment]
> 这个活动在web端还是在app，每个直播间都有吗？我这边没找到这个窗口。

在web端，每个直播间都有，你可以在娱乐区随便找的直播间比较常见，加载完在右上角
![屏幕截图 2023-11-24 080547](https://github.com/andywang425/BLTH/assets/16076552/3bb0b274-01a0-425a-bc79-f1c1c350a246)
