### ISSUE TITLE
移除直播间幻星派对标志有BUG

### ISSUE THREAD

**Issue by neariver** [andywang425/BLTH#479]
### 描述bug

选择移除直播间幻星派对标志，会使互动游戏直播间的右下角紫色操作杆也被屏蔽掉
![111](https://github.com/andywang425/BLTH/assets/16076552/989345cc-b43a-4d9e-98f2-c292c69325fc)

### 重现bug

可以在这个互动游戏区随便选一个钓鱼游戏的直播间来测试
[https://live.bilibili.com/p/eden/area-tags?parentAreaId=15&areaId=0&visit_id=83iztdgpmh80](url)

### 预期行为

选择移除直播间幻星派对标志后会误屏蔽

### 运行日志

无

### 操作系统

WIN11

### 浏览器

Chrome

### 用户脚本管理器

暴力猴

### 脚本版本号

7.1.2

### 网络情况

好

**Comment by ADJazzzz** [comment]
那个紫色操作杆就是幻星派对的标志
