### ISSUE TITLE
自动切换粉丝徽章后清晰度会变回超清，即使设置了自动切换画质

### ISSUE THREAD

**Issue by 6ur9er** [andywang425/BLTH#487]
### 描述bug

打开直播间，自动切换画质正常生效，但是发送弹幕任务+自动切换徽章，在切换徽章后会画质变成超清

### 重现bug

打开直播间，自动切换画质为原画，执行发送弹幕任务+自动切换徽章，在切换徽章后会画质变成超清

### 预期行为

画质仍为设定的原画画质

### 运行日志

![image](https://github.com/andywang425/BLTH/assets/103239502/9f9307c1-0529-466f-a9ec-936a0fd07be9)

### 操作系统

Windows 11

### 浏览器

Microsoft Edge 版本 122.0.2365.66 (正式版本) (64 位)

### 用户脚本管理器

Tampermonkey 5.0.1

### 脚本版本号

7.1.3

### 网络情况

好

**Comment by andywang425** [comment]
分析一下报错：
![image](https://github.com/andywang425/BLTH/assets/56548456/0c13ff30-22c9-4914-a2c3-450f54370bb0)
上面这三条日志是B站的报错，不知道为啥。

![image](https://github.com/andywang425/BLTH/assets/56548456/e6bb4725-7800-4858-a7e7-f8fb20d7e173)
按理来说不可能找不到，不清楚为什么。

![image](https://github.com/andywang425/BLTH/assets/56548456/4b01e20f-37e5-4e20-b29f-e2faa7d68eac)
说明`response.data.list`为`undefined`。不知道你有没有加入过应援团。也许没有应援团的时候这个属性为`undefined`？

![image](https://github.com/andywang425/BLTH/assets/56548456/c8b7037f-f618-4eac-9383-65885211dc03)
不清楚是哪里的问题。有可能是App.vue的下面这段：
```ts
      button = dce('button')
      button.setAttribute('class', 'blth_btn')
      button.onclick = throttleButtoOnClick
      button.innerText = uiStore.isShowPanelButtonText
      playerHeaderLeft.append(button)
```

![image](https://github.com/andywang425/BLTH/assets/56548456/b535f28f-1977-49ee-bab0-07beedb7056f)
还是不清楚。有可能是src\modules\dailyTasks\liveTasks\signTask.ts中的这段：
```ts
        // 移除直播签到按钮
        const checkinBtn = dq('.checkin-btn')
        if (checkinBtn) {
          checkinBtn.remove()
        }
```

总结，很多不知道原因的报错，“自动切换粉丝徽章后清晰度会变回超清”也不知道是咋回事。

**Comment by andywang425** [comment]
安装最新版本的BLTH后你还存在这个问题吗，如果没问题的话我关issue了。

**Comment by 6ur9er** [comment]
> 安装最新版本的BLTH后你还存在这个问题吗，如果没问题的话我关issue了。

没有问题了，您关iss吧，谢谢您
