### ISSUE TITLE
粉丝勋章列表无法加载

### ISSUE THREAD

**Issue by mrrrrabit** [andywang425/BLTH#488]
### 描述bug

粉丝勋章列表点击之后一直在加载，但是等很久也加载不出来，尝试使用加速器和梯子也不行

### 重现bug

点击“编辑名单”后不停加载

### 预期行为

展开粉丝勋章列表

### 截图

![图片](https://github.com/andywang425/BLTH/assets/163745624/ac9cb034-d3e4-4da1-8e5f-8a47e77a5f03)

### 运行日志

![图片](https://github.com/andywang425/BLTH/assets/163745624/9ec3406a-06b1-4091-b864-0d8c16947713)

### 操作系统

win10

### 浏览器

火狐123.0.1

### 用户脚本管理器

油猴5.0.1

### 脚本版本号

7.1.2

### 网络情况

好

**Comment by andywang425** [comment]
这应该和加速器和梯子没关系，上B站的时候还是不要随便换ip好，容易被风控。

感谢反馈，之后我看看为什么。

**Comment by mrrrrabit** [comment]
当天问题就得到了解决，现在可以正常使用，作者大大nb

**Comment by andywang425** [comment]
> 当天问题就得到了解决，现在可以正常使用，作者大大nb

我啥都没干呢，就好啦？😂

**Comment by mrrrrabit** [comment]
啊？反馈完转天晚上就有更新，更新完就能用了发自我的 iPhone在 2024年3月20日，10:43，andywang425 ***@***.***> 写道：﻿

当天问题就得到了解决，现在可以正常使用，作者大大nb

我啥都没干呢，就好啦？😂

**Comment by vhorng** [comment]
我也遇到了相同的問題，就是點了"編輯名單'，出現了與[mrrrrabit]一樣的畫面
有什麼排除或測試的方法嗎？

**Comment by andywang425** [comment]
> 我也遇到了相同的問題，就是點了"編輯名單'，出現了與[mrrrrabit]一樣的畫面 有什麼排除或測試的方法嗎？

我刚刚看了眼提交记录，发现其实在两个月前的时候我在开发分支里尝试修复了，但因为最近太忙一直没发布正式版。

下面是开发中脚本的代码，你可以试试：

- 压缩：[bilibili-live-tasks-helper.min.user.js.txt](https://github.com/andywang425/BLTH/files/14886346/bilibili-live-tasks-helper.min.user.js.txt)
- 未压缩：[bilibili-live-tasks-helper.user.js.txt](https://github.com/andywang425/BLTH/files/14886349/bilibili-live-tasks-helper.user.js.txt)
