### ISSUE TITLE
想要一个 B币换金瓜子的功能

### ISSUE THREAD

**Issue by xiaoBingge114514** [andywang425/BLTH#489]
### 描述

因为本人有几年的**b站大会员**，每个月自动送**5个B币**且可以拿来换_**金瓜子**_，所以想要一个每月B币自动换金瓜子的功能.....(希望可以调自动兑换数量！

**Comment by andywang425** [comment]
你指的是电池吧？
![image](https://github.com/andywang425/BLTH/assets/56548456/195f2c3e-4510-48c1-9ef6-54a6a5da847b)

说实话我不太想做这个功能，因为要是出bug了（比如兑换了错误的数量）可能会造成经济损失。会考虑。

**Comment by andywang425** [comment]
考虑到潜在的风险还是决定不做这个功能，请谅解。
