### ISSUE TITLE
希望增加设置每日任务开始时间入口

### ISSUE THREAD

**Issue by ken-otonashi** [andywang425/BLTH#49]
人在国外，每天早上10点才是国内0点新的一天。

**Comment by andywang425** [comment]
抱歉，我以前没考虑到这种情况。我打算在以后的版本中让脚本自动适配世界各地的本地时间，这样就不用手动填时间了。

**Comment by andywang425** [comment]
`5.6.4.6`中尝试修复了这个问题，你再试试。

**Comment by andywang425** [comment]
这个issue我先关了，如果还有问题的话你可以再开。
