### ISSUE TITLE
直播间每日任务显示完成，但是实际没有完成

### ISSUE THREAD

**Issue by MythallarEra** [andywang425/BLTH#497]
### 描述bug

直播间每日任务显示完成，但是实际没有完成

### 重现bug

貌似是挂着直播间过12点出现的。晚上一直挂着直播间，主播并没有开播。到了0点20分左右，看了下直播间挂机进度，就显示给主播点赞和发送弹幕的任务已经是完成状态了，观看直播任务也是进行中，但是看了下粉丝牌，亲密度还是0。刷新房间和重新登录也不行。之前以为是油猴的问题，新下了暴力猴安装脚本，今天还是出现这个问题了。

### 预期行为

给主播点赞、发送弹幕、观看直播的任务正常增加粉丝牌亲密度

### 运行日志

![image](https://github.com/andywang425/BLTH/assets/93830485/f5dfa32d-9d98-45fd-86f4-25614c244508)
![image](https://github.com/andywang425/BLTH/assets/93830485/b7e4e7da-ee15-4be7-b958-8bccaa5ec07e)

### 操作系统

win11

### 浏览器

Google Chrome版本 126.0.6452.3（正式版本）dev （64 位）

### 用户脚本管理器

暴力猴 2.18.0和篡改猴测试版 5.2.6195

### 脚本版本号

7.1.4

### 网络情况

好

### 其他浏览器拓展/用户脚本

ACG助手：专为bilibili定制的综合辅助扩展 2.6.19(Official)

### 其他

填完信息想重新截图的时候，看粉丝牌亲密度开始涨了，不知道是不是前一个小时跟b站有网络问题，导致这样。最好是有个明确结果，因为我经常这样横跨午夜12点的，要是老出这种问题，总会感觉很难受。谢谢了。

**Comment by lixueshu** [comment]
我就也有类似问题不过我的报错是这个：
 POST https://data.bilibili.com/v2/log/web?content_type=pbrequest&logid=021436&disable_compression=true net::ERR_BLOCKED_BY_CLIENT index.js:2
