### ISSUE TITLE
为直播任务”发送弹幕“添加子选项”包含等级≥20的粉丝勋章“

### ISSUE THREAD

**Issue by andywang425** [andywang425/BLTH#498]
### 描述

给粉丝勋章发弹幕可以点亮勋章。需要点亮20级以上的粉丝勋章的用户可以勾选该功能。

**Comment by yangyangbuxiangyang** [comment]
我20级牌子已经全灰了
![屏幕截图 2024-07-11 035132](https://github.com/andywang425/BLTH/assets/114185862/05ecaad4-f7ea-443d-a5ad-6cec9d3aee04)

**Comment by jakaz1280** [comment]
我现在都是只开观看直播，不开发送弹幕，然后每天手动点亮几个牌子，毕竟只靠观看直播也能拿够亲密度
