### ISSUE TITLE
B站直播相关功能规则更新

### ISSUE THREAD

**Issue by X-Holmes** [andywang425/BLTH#5]
B站粉丝勋章规则今天发生了较多更新，希望可以针对性推出新功能
https://link.bilibili.com/p/help/index#/audience-fans-medal

重点改变：

如何入团并获得粉丝勋章
当日在直播间内消费满9.9元或直接投喂B坷垃，即可加入粉丝团并且获得主播的粉丝勋章。

如何升级我的粉丝团内的粉丝勋章
在直播间内观看5min即可获得1个小心心，对主播投喂小心心或投喂道具，即可增加亲密度。1小心心=50亲密度，100瓜子=1 亲密度。达到当前等级升级所需的亲密度，即可升级哦～

如何点亮我的勋章
7天内未完成点亮任务（投喂小心心或金瓜子礼物）则对应的勋章就会熄灭哦～熄灭后的勋章不会掉亲密度，等级也不会降低哦～
在勋章对应的直播间内，投喂小心心或任意金瓜子礼物均可点亮熄灭的勋章哦～

**Comment by 15726238368** [comment]
在客服那里询问到的一些帮助中心没写的内容：
只有在拥有对应粉丝勋章、且主播正在直播(轮播不算)的直播间内观看5分钟，才能获得小心心，每天上限24个，每个增加50亲密度。
7天内未完成点亮任务（投喂小心心或金瓜子礼物）则对应的勋章就会熄灭，熄灭后将不再展示在弹幕互动区及粉丝榜单中，熄灭后重新完成点亮任务（投喂小心心或金瓜子礼物）即可再次点亮勋章。

所以希望脚本可以实现【每天获得24个小心心】（寻找粉丝勋章对应的正在直播的直播间进行观看，如果太麻烦就算了，可以让用户自己把脚本挂在对应的直播间）；【将小心心分别送给不同的主播】这样可以保持勋章的点亮状态，并且要在送辣条之前赠送以免亲密度溢出上限

**Comment by andywang425** [comment]
感谢反馈~ 如果还有下一次更新的话，会尝试加入这些功能。b站这波操作太让我失望了。  
最近比较忙，可能更新会慢一点。

**Comment by andywang425** [comment]
> 在客服那里询问到的一些帮助中心没写的内容：
> 只有在拥有对应粉丝勋章、且主播正在直播(轮播不算)的直播间内观看5分钟，才能获得小心心，每天上限24个，每个增加50亲密度。
> 7天内未完成点亮任务（投喂小心心或金瓜子礼物）则对应的勋章就会熄灭，熄灭后将不再展示在弹幕互动区及粉丝榜单中，熄灭后重新完成点亮任务（投喂小心心或金瓜子礼物）即可再次点亮勋章。
> 
> 所以希望脚本可以实现【每天获得24个小心心】（寻找粉丝勋章对应的正在直播的直播间进行观看，如果太麻烦就算了，可以让用户自己把脚本挂在对应的直播间）；【将小心心分别送给不同的主播】这样可以保持勋章的点亮状态，并且要在送辣条之前赠送以免亲密度溢出上限

【每天获得24个小心心】✔  （貌似还有bug，以后会试着修一下）  
【将小心心分别送给不同的主播】❔ 这个暂时先不做，如果有更多人认为这个功能有用才会做（因为懒_(:3」∠)_）。如果有能力的话欢迎提交PR ~

**Comment by 15726238368** [comment]
今天在帮助冲浪发现，粉丝勋章更新只是第一步，7月还会陆续对大航海、友爱社、签到、双端观看、成就、宝箱都进行改版，详见公告：
https://link.bilibili.com/p/eden/news#/newsdetail?id=1309
![gonggao](https://i0.hdslb.com/bfs/vc/37428fc425b8c546eb3377e69855bbf4cd4e4419.png)

**Comment by X-Holmes** [comment]
好像现在大航海(舰长)不能获得辣条了，如果B站不再更改的话，检查小时榜功能后续可以关闭掉了

**Comment by Jefferyu** [comment]
我说最近怎么辣条收益变这么低了 原来阿b改版了 看来是要从源头上打击啊 作者现在有什么想法吗

**Comment by andywang425** [comment]
> 我说最近怎么辣条收益变这么低了 原来阿b改版了 看来是要从源头上打击啊 作者现在有什么想法吗

我也没办法啊。以后把抽奖功能删了，专心搞其它功能。

**Comment by X-Holmes** [comment]
> > 我说最近怎么辣条收益变这么低了 原来阿b改版了 看来是要从源头上打击啊 作者现在有什么想法吗
> 
> 我也没办法啊。以后把抽奖功能删了，专心搞其它功能。

抽奖还是可以抽大乱斗的辣条的，虽然数量聊胜于无。

另外8月起取消了每日双端观看任务，相关功能的选项可以关闭了
