### ISSUE TITLE
无法自动完成”每日分享视频“任务

### ISSUE THREAD

**Issue by kevinkejc** [andywang425/BLTH#503]
### 描述bug

在跨过0点或者我的电脑休眠之后启动（个人使用电脑的习惯是断电休眠，开机之后会保留休眠前开启的软件和进程之类的，我的浏览器都是一直挂着），脚本自动执行这个任务之后表面是显示已经完成（任务后面打对勾），但去B站个人中心查看却是没有完成的，必须得去脚本的存储里重置“_lastCompleteTime”值之后重新执行任务才会完成分享视频
并且感觉是概率发生，昨天看还显示完成了，但无法完成的概率较高
最后也发现了连直播任务都不会自动完成，必须得刷新页面之后才行，以及在直播任务里的”给主播点赞“、”发送弹幕"，这类也和"每日分享视频“任务出现了同样的问题，显示完成但实际没完成，还是得去存储里重置下“_lastCompleteTime”值才能正常完成

### 重现bug

没什么操作，就是跨0点或者电脑休眠之后启动让脚本自动执行任务

### 预期行为

完成每日分享视频任务

### 截图

![image](https://github.com/andywang425/BLTH/assets/75735934/6185420c-3875-4a57-9aa2-19c1871da618)

### 运行日志

[live.bilibili.com-1719533145907.log](https://github.com/user-attachments/files/16022382/live.bilibili.com-1719533145907.log)
[live.bilibili.com-1719533281649.log](https://github.com/user-attachments/files/16022384/live.bilibili.com-1719533281649.log)
第一个是重置“_lastCompleteTime”值之前的日志，第二个则是重置之后的日志。
第一个日志只有0点6分之后的记录了
由于日志很长就以文件形式发出

### 操作系统

Windows 10 专业版 22H2

### 浏览器

Google Chrome 126.0.6478.114

### 用户脚本管理器

Tampermonkey v5.1.1

### 脚本版本号

7.1.4

### 网络情况

好

### 其他浏览器拓展/用户脚本

扩展：Adblock Plus、ZeroOmega，脚本：Bilibili Evolved

### 其他

最后也发现了连直播任务都不会自动完成，必须得刷新页面之后才行，以及在直播任务里的”给主播点赞“、”发送弹幕"，这类也和"每日分享视频“任务出现了同样的问题，显示完成但实际没完成，还是得去存储里重置下“_lastCompleteTime”值才能正常完成

**Comment by andywang425** [comment]
以前也有人反馈脚本在跨天的时候会遇到问题，但我一直没搞清楚过是什么原因。此外休眠可能导致浏览器的计时器不准确，会影响脚本的执行（通过看你的第一个日志可以看出来），这一点也没有什么好的解决办法。我之后有空的时候会注意观察脚本在跨天时的表现。

**Comment by kevinkejc** [comment]
其实还是建议考虑像前代一样添加一个重置任务缓存的按键，毕竟手动去存储内修改终究是有点麻烦，虽然重置缓存治标不治本，但在目前无法解决的情况下搞个重置还是感觉很有必要的

**Comment by andywang425** [comment]
你说得对，我本来是计划搞个设置页面，让用户能调整脚本控制面板宽度什么的，同时也加个重置缓存的功能，但最近太忙真没空做。

**Comment by kevinkejc** [comment]
有这计划就可以了，不着急的。我也用这脚本搞了好几个20级牌子了，感谢能维护至今

**Comment by kevinkejc** [comment]
测试了一下跨天日志
这回测试跨天执行主站任务的结果是每日登录、每日观看视频、每日分享视频都没完成，这就不得不想是不是之前也是同样不会完成所有的主站任务，会完成登录和看视频也是因为我每天都会使用B站，然后只差分享视频的任务。

[live.bilibili.com-1719936120372.log](https://github.com/user-attachments/files/16072265/live.bilibili.com-1719936120372.log)
[live.bilibili.com-1719941233642.log](https://github.com/user-attachments/files/16072266/live.bilibili.com-1719941233642.log)
第一个日志是跨天前的，过0点的时候在电脑前等了两分钟没看到脚本有自动执行任务，就把网页手动刷新了
第二个日志就是手动刷新网页之后脚本执行任务的日志了

**Comment by andywang425** [comment]
不知道你有没有等到过0点5分？很多任务都是在这个点执行，而不是刚好0点的时候。

日志里也会提示各个模块下次运行的时间，你给出的日志里就有。

**Comment by kevinkejc** [comment]
原来是这样，我确实是没认真看日志 记不住，之后有机会我会观察下

**Comment by andywang425** [comment]
#531
