### ISSUE TITLE
设置显示错误

### ISSUE THREAD

**Issue by mzth** [andywang425/BLTH#51]
图中这些设置的勾勾点击取消并保存后，刷新网页任然显示勾勾还在
![屏幕截图 2021-01-21 073113](https://user-images.githubusercontent.com/53244094/105253988-8c8d1400-5bbb-11eb-993e-6ca393cfd4fb.png)
win10
edge浏览器   版本 87.0.664.75
脚本5.6.4.5

只是显示错误。比如取消移除2233模型的勾勾后再刷新，2233模型未被移除，但是脚本上的勾还在

**Comment by andywang425** [comment]
了解了，下个版本修复。

**Comment by andywang425** [comment]
`5.6.4.6`中修复了✔
