### ISSUE TITLE
b站亲密度规则修改

### ISSUE THREAD

**Issue by woquliunian** [andywang425/BLTH#518]
### 描述

b站亲密度规则已修改，每日50个点赞、10条弹幕、20分钟观看，插件的每日功能请求更新

**Comment by andywang425** [comment]
收到，会适配的

**Comment by cyb233** [comment]
这改动真的是难受死人了，拆东墙补西墙，别最后墙全塌了

**Comment by jaxMineKa** [comment]
> ### 描述
> 
> b站亲密度规则已修改，每日50个点赞、10条弹幕、20分钟观看，插件的每日功能请求更新

在线观看亲密度是改成只有直播生效还是改了接口，以前的方式加不了亲密度

**Comment by jaxMineKa** [comment]
> 这改动真的是难受死人了，拆东墙补西墙，别最后墙全塌了
> 
> 按现在这个200免费亲密度，纯免费亲密度部分，1升20级牌子从原本的667天变成5000天

看来只能去抢红包和天选了，上个月我用小号试着一个号抢到每日红包上限也有100左右的电池，
风控不清楚，好的ip和欧皇账号容易中奖，实名无加成，该被限制就限制。

**Comment by ADJazzzz** [comment]
这个改动太脑浆了😅🤮

**Comment by jakaz1280** [comment]
50点赞和10条弹幕只生效一次了。
不过，如果可行的话，弹幕这个建议直接改成指定间隔指定次数在一个列表里循环发的功能，毕竟现在主播那里有个任务是直播间里观众发了多少弹幕，一堆主播求着观众发弹幕。

**Comment by cyb233** [comment]
> > 这改动真的是难受死人了，拆东墙补西墙，别最后墙全塌了
> > 按现在这个200免费亲密度，纯免费亲密度部分，1升20级牌子从原本的667天变成5000天
> 
> 看来只能去抢红包和天选了，上个月我用小号试着一个号抢到每日红包上限也有100左右的电池， 风控不清楚，好的ip和欧皇账号容易中奖，实名无加成，该被限制就限制。

我现在已经是每次抽红包必点验证码了，已经懒得再点红包了

**Comment by lixueshu** [comment]
不知道为什么，规则改动后打卡只在挂着的直播间生效了

**Comment by mzth** [comment]
观看每天上限才80，懒得挂了😅

**Comment by lixueshu** [comment]
> 观看每天上限才80，懒得挂了😅

用插件每天挂，蚊子肉再小也是肉

**Comment by fuackingname** [comment]
这从改动纯纯司马玩意

**Comment by Janet-Baker** [comment]
粉丝牌点亮规则也变了，3天无互动就变灰，灰了之后想再次点亮就得付费（或者在大航海有效期内）

> 如何点亮我的勋章
> 为何熄灭： 3天内未完成任何升级任务（发弹幕、点赞或投喂电池礼物）则该房间对应的勋章就会熄灭，熄灭后的勋章不会减少亲密度，等级也不会降低，但佩戴后无法在互动区显示哦～
> 如何点亮： 在勋章对应的直播间内，产生投喂付费灯牌和电池礼物等消费，均可点亮熄灭的勋章。大航海身份存续期间，粉丝勋章不会熄灭。

**Comment by jakaz1280** [comment]
> 粉丝牌点亮规则也变了，3天无互动就变灰，灰了之后想再次点亮就得付费（或者在大航海有效期内）
> 
> > 如何点亮我的勋章
> > 为何熄灭： 3天内未完成任何升级任务（发弹幕、点赞或投喂电池礼物）则该房间对应的勋章就会熄灭，熄灭后的勋章不会减少亲密度，等级也不会降低，但佩戴后无法在互动区显示哦～
> > 如何点亮： 在勋章对应的直播间内，产生投喂付费灯牌和电池礼物等消费，均可点亮熄灭的勋章。大航海身份存续期间，粉丝勋章不会熄灭。

3天没完成升级任务就会灰掉对牌子多的人真是个噩梦

**Comment by miao-wang-aoao** [comment]
您好。新版外掛有着不少瑕疵，如：

一）明明当下直播主已開播营业，但怎样也掛不满当天所観看的亲密度（+80）包括有些只能掛到20点等；
二）明明当下直播主已開播营业，但怎样也掛不上点赞的亲密度（+50）；（経常遇到此问题）
三）弾幕密度実在太可怕！已有一些直播主，反映不满在她們营业時，突然收到一堆弾幕。（希望能尽快有调节弾幕密度）

谨希望以上问题能尽快解决，以免粉丝灯牌不易熄掉。謝謝。

補：像我此等只控制粉丝牌在四十枚以内的，已完全受不了這新制度。祈愿新版外掛能尽量保障每天+200個亲密度。否則，真的很难玩下去。

**Comment by zqdlly** [comment]
叔叔的吃相真是越来越难看了，本人已经决定即日起无限期停止挂牌子。

**Comment by Janet-Baker** [comment]
叔叔又改回去了，可以洗洗睡了🤣

**Comment by andywang425** [comment]
已更新至7.1.7
