### ISSUE TITLE
能不能添加一个自定义什么时间触发任务的选项，0点05还是有很多up在直播

### ISSUE THREAD

**Issue by lixueshu** [andywang425/BLTH#523]
### 描述

能不能添加一个自定义什么时间触发任务的选项，0点05还是有很多up在直播

**Comment by GongT** [comment]
间隔检查，发现没有开播再执行，感觉会比较好，毕竟有主播专门后半夜播

**Comment by andywang425** [comment]
你是担心发弹幕会刷屏吗？这个问题我们计划用别的方法来解决，比如等主播下播再发，支持自定义发送时间间隔等等。

任务触发时间不太适合交给用户来填写。

**Comment by GongT** [comment]
强烈支持 主播下播再发 这个功能

**Comment by andywang425** [comment]
在最新的粉丝勋章亲密度规则下没有弹幕刷屏问题，关了
