### ISSUE TITLE
关于每日发送弹幕 能否添加发送弹幕时间间隔功能

### ISSUE THREAD

**Issue by NagiKugi** [andywang425/BLTH#525]
### 描述

目前是每天0点自动刷10条弹幕，在人少的直播间可能会造成刷屏，有被禁言的风险，能否加一个发送弹幕时间间隔的功能

**Comment by GongT** [comment]
除了几个顶流直播间，全都是刷屏的效果。。。

**Comment by andywang425** [comment]
可以有，这是在计划里的功能

**Comment by NagiKugi** [comment]
> 可以有，这是在计划里的功能

感谢 发完反馈才在更新计划里看到会更新 不好意思

**Comment by cyb233** [comment]
确实挺必要的，而且感觉挺急需的，经常我PC任务进行同时，我自己电脑看的直播就发不出消息了，手机发一下消息才恢复，感觉是因为牌子多

**Comment by andywang425** [comment]
在最新的粉丝勋章亲密度规则下没有弹幕刷屏问题，关了
