### ISSUE TITLE
弹幕打卡任务未完成退出直播间后，过一段时间再进入直播间无法读取任务进度

### ISSUE THREAD

**Issue by Maizitao** [andywang425/BLTH#526]
### 描述

今天尝试在打卡到已开播主播前退出直播间中断任务，等待下播后到已完成任务的直播间继续脚本打卡，发现无法继续之前的进度，在已完成任务的直播间依然出现了打卡弹幕

**Comment by lixueshu** [comment]
我也遇到了，不一样的是在直播间发几条不发了，跳到下一个直播间去了

**Comment by andywang425** [comment]
确实会这样，以后可以做个保存任务进度的功能

**Comment by andywang425** [comment]
现在的情况是，虽然还是不保存点亮熄灭勋章的任务进度，但由于只会去点亮熄灭的勋章，所以不存在重复点亮的问题。观看直播任务有进度记录。
