### ISSUE TITLE
你B偷偷给所有亲密度改动回退了，只需要把刷屏这个问题解决就好了

### ISSUE THREAD

**Issue by Garyllis** [andywang425/BLTH#527]
### 描述

幽默🤣👉

**Comment by Janet-Baker** [comment]
速速 revert changes 🤣👉
不过说明介绍没改回来……

**Comment by lixueshu** [comment]
只是点赞和发弹幕不能获取亲密了·

**Comment by jakaz1280** [comment]
现在只需要把插件的发弹幕功能点成关闭，就可以了

**Comment by woquliunian** [comment]
b站亲密度又改版后现在观看无法像以前一样所有直播间同时上涨亲密度，只有个别直播间偶尔涨亲密度，有一样的吗？

**Comment by andywang425** [comment]
> b站亲密度又改版后现在观看无法像以前一样所有直播间同时上涨亲密度，只有个别直播间偶尔涨亲密度，有一样的吗？

据群友说是这样的，只能一个一个涨。

**Comment by andywang425** [comment]
今天太累了，明天适配新版本

前几天我还在思考发弹幕任务的调度算法，想着怎么保证不刷屏又能尽快完成任务，这下全白写🤣👉

**Comment by jakaz1280** [comment]
好消息,不光发弹幕能点亮牌子,点赞也能点亮牌子了,坏消息,发弹幕和点赞没亲密度了.
好消息,现在观看25分钟就能拿到1500亲密度了,坏消息,只加一个直播间的亲密度了.

**Comment by DeAthBo** [comment]
亲密度只能一个一个涨.
所以有以下问题:
我即使当前正在看这个主播,也会先涨其他人的亲密度,当前看的不涨

**Comment by lixueshu** [comment]
> 今天太累了，明天适配新版本
> 
> 前几天我还在思考发弹幕任务的调度算法，想着怎么保证不刷屏又能尽快完成任务，这下全白写🤣👉

没事把代码备份着，说不定哪天B站直播部又抽风了

**Comment by andywang425** [comment]
> 没事把代码备份着，说不定哪天B站直播部又抽风了

仓库有版本管理的，可以随时回滚

**Comment by jakaz1280** [comment]
我试了下,点赞30点亮牌子那个,很多时候30下之后还要再点几下才能亮,而且一天依然有一千次的上限,没办法靠点赞做到毫无打扰的点亮牌子

**Comment by andywang425** [comment]
已更新至7.1.7

**Comment by Janet-Baker** [comment]
总观看时间还是120分钟？几百个牌子完全不够用……

**Comment by andywang425** [comment]
> 总观看时间还是120分钟？几百个牌子完全不够用……

我的问题，没写清楚，现在设置的是每个直播间的观看时间。建议设置成任务要求的25分钟。
