### ISSUE TITLE
点赞数量和弹幕发送数量及间隔自定义

### ISSUE THREAD

**Issue by cyb233** [andywang425/BLTH#529]
### 描述

类似选择`观看直播时长`一样，自定义`点赞数量`和`弹幕发送数量及间隔`，这样再有类似规则修改，只要接口不变，就可以自己调整

**Comment by andywang425** [comment]
不打算做这个。BLTH在7.0.0之前像你说的一样，每个功能都有大量可自定义的参数，但这对新手用户很不友好，很多人不会填合适的配置。7.0.0之后我们倾向于尽可能少地提供自定义配置，一切从简。

如果有规则修改脚本跟着改就完事了。
