### ISSUE TITLE
无法正常进行自动观看直播

### ISSUE THREAD

**Issue by NagiKugi** [andywang425/BLTH#530]
### 描述bug

观看25分钟直播这项任务无法完成，每天在界面会显示正在完成，但最后粉丝牌亲密度都是0

### 重现bug

1.打开直播间 2.显示观看任务在转圈 3.显示已完成 4.但是除打开的直播间在涨亲密度，剩下开播的直播间都是0

### 预期行为

完成所有开播直播间的1500亲密度，哪怕一个一个完成

### 截图

![76da25aaab98904a2aed5026ccc7a5ef](https://github.com/user-attachments/assets/e88b4ff4-fe83-45f3-ad19-c53d15e783fe)
![95d83972b37cee0ec930ce1184c3ad3b](https://github.com/user-attachments/assets/92b4404d-f549-4d20-aff3-43d9ff33e130)

### 运行日志

BLTH[2024/8/4 03:46:59][Main]: document.readyState loading [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:46:59][Main]: 当前脚本的类型为 Main [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:46:59][EnhanceExperience][BanP2P]: 禁用P2P模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:46:59][EnhanceExperience][Invisibility]: 隐身入场模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:46:59][EnhanceExperience][NoReport]: 拦截日志数据上报模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:46:59][Default][BilibiliLive]: unsafeWindow.BilibiliLive 
Object { INIT_TIME: 1722714419478, RND: 1722714419, UID: 650199, ROOMID: 21756924, ANCHOR_UID: 56748733, COLORFUL_LOGGER: false, SHORT_ROOMID: 21756924, AREA_ID: 371, PARENT_AREA_ID: 9 }
[Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
Hls7Player v1.99 [room-player.prod.min.js:16:18194](https://s1.hdslb.com/bfs/blive-engineer/live-web-player/room-player.prod.min.js)
Misaka Network Check: Supported 2 [room-player.prod.min.js:29:265488](https://s1.hdslb.com/bfs/blive-engineer/live-web-player/room-player.prod.min.js)
BLTH[2024/8/4 03:47:00][Default][UserInfo]: BAPI.main.nav response 
Object { code: 0, message: "0", ttl: 1, data: {…} }
[Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:00][EnhanceExperience][NoSleep]: 屏蔽挂机检测模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:00][EnhanceExperience][SwitchLiveStreamQuality]: 自动切换画质模块开始运行

### 操作系统

Windows 10 22H2

### 浏览器

Firefox 128.0.3 (64 位)

### 用户脚本管理器

Tampermonkey 5.1.1

### 脚本版本号

7.1.6

### 网络情况

好

### 其他浏览器拓展/用户脚本

Bilibili-Evolved

**Comment by NagiKugi** [comment]
运行日志
BLTH[2024/8/4 03:47:02][DailyTask][OtherTask][GroupSignTask]: 应援团签到模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][DailyTask][OtherTask][GroupSignTask]: 昨天的应援团签到任务已经完成过了，等到今天早上八点零五分再次执行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][DailyTask][OtherTask][GroupSignTask]: 距离应援团签到模块下次运行时间: 4小时17分钟57秒 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][DailyTask][OtherTask][SilverToCoinTask]: 银瓜子换硬币模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][DailyTask][OtherTask][SilverToCoinTask]: 银瓜子换硬币模块下次运行时间: 20小时17分钟57秒 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][RemoveElement][RemoveActivityBanner]: 移除活动入口模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][RemoveElement][RemoveComboCard]: 移除直播间相同弹幕连续提示模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][RemoveElement][RemoveFlipView]: 移除礼物栏下方广告模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][RemoveElement][RemoveGameParty]: 移除直播间幻星派对标志模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][RemoveElement][RemoveGiftPlanet]: 移除礼物星球模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][RemoveElement][RemoveGiftPopover]: 移除礼物赠送提示弹窗模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][RemoveElement][RemoveLiveMosaic]: 移除直播间马赛克模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][RemoveElement][RemoveLiveWaterMark]: 移除直播间水印模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][RemoveElement][RemoveMicPopover]: 移除连麦状态提示模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][RemoveElement][RemovePKBanner]: 移除大乱斗入口模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][RemoveElement][RemovePKBox]: 移除大乱斗元素模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][RemoveElement][RemoveRank]: 移除排行榜模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][RemoveElement][RemoveRecommendRoom]: 移除礼物栏下方推荐直播间模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][RemoveElement][RemoveShopPopover]: 移除直播间小黄车弹窗模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][DailyTask][LiveTask][WatchTask]: 观看直播模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][DailyTask][LiveTask][WatchTask]: 今天已经完成过观看直播任务了 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][DailyTask][LiveTask][WatchTask]: 距离观看直播模块下次运行时间: 20小时17分钟57秒 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][EnhanceExperience][ShowContributionUserNum]: 显示高能用户数量模块开始运行 [Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
BLTH[2024/8/4 03:47:02][EnhanceExperience][ShowContributionUserNum]: 未找到高能用户标签 [Bilibili-Live-Tasks-Helper.user.js:7993:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
Bilibili Evolved live watch [Bilibili-Evolved.user.js:226:1389](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Evolved.user.js?id=a9a87b2b-faf9-4b93-a95a-35a94999308c)
BLTH[2024/8/4 03:47:04][EnhanceExperience][SwitchLiveStreamQuality]: 已将画质切换为高清 
Object { qn: "150", desc: "高清" }
[Bilibili-Live-Tasks-Helper.user.js:7990:15](moz-extension://ac438e55-823a-4eab-81df-82281df66e58/userscripts/Bilibili-Live-Tasks-Helper.user.js?id=52832075-6f0b-4805-b91f-8dc0a2cedfa6)
Unsatisfied version 2.0.7 from liveroom_activity_pendant of shared singleton module @blink-live/awesome-api (required ^1.2.5-0)

**Comment by mihuru** [comment]
没自动观看是不是因为那个直播间没开播？

**Comment by NagiKugi** [comment]
> 没自动观看是不是因为那个直播间没开播？

开播了

**Comment by andywang425** [comment]
脚本还没适配最新的任务规则，等下个版本吧。最近比较忙，更新会慢，请谅解

**Comment by miao-wang-aoao** [comment]
我也遇上类似問題。就是経常在電脳端、怎么掛都掛不出親密度（明明当家正营业中）。但是有時候又不知为何，某些房内（甚至在没有营业下）可以掛到一部分。因此，暂時只能電脳和APP一起用上（APP可确保取得某家親密度，只要其营业時、有进其直播房内）。謝謝了

**Comment by andywang425** [comment]
> 我也遇上类似問題。就是経常在電脳端、怎么掛都掛不出親密度（明明当家正营业中）。但是有時候又不知为何，某些房内（甚至在没有营业下）可以掛到一部分。因此，暂時只能電脳和APP一起用上（APP可确保取得某家親密度，只要其营业時、有进其直播房内）。謝謝了

如果在一个正在直播的直播间内使用脚本，观看直播功能可能不会增加任何亲密度（从技术角度猜测，当前直播间的心跳覆盖了脚本发出的心跳），这一点在脚本的内置说明里也有描述。

**Comment by andywang425** [comment]
已更新至7.1.7
