### ISSUE TITLE
无法完成主站任务

### ISSUE THREAD

**Issue by kevinkejc** [andywang425/BLTH#531]
### 描述bug

主站任务内的每日登录、每日观看视频、每日分享视频均无法完成
去存储里重置了好几遍任务也反复执行了好几遍依旧无法完成
每日投币任务执行正常

### 重现bug

正常执行任务无法完成

### 预期行为

完成主站任务内的每日登录、每日观看视频、每日分享视频任务

### 运行日志

[live.bilibili.com-1722793232382.log](https://github.com/user-attachments/files/16488446/live.bilibili.com-1722793232382.log)

### 操作系统

Windows 10 专业版 22H2

### 浏览器

Chrome 127.0.6533.89

### 用户脚本管理器

Tampermonkey v5.1.1

### 脚本版本号

7.1.6

### 网络情况

好

### 其他浏览器拓展/用户脚本

拓展：Adblock Plus、ZeroOmega，脚本：Bilibili Evolved、图片下载器

**Comment by kevinkejc** [comment]
主站没问题了，现在这个会员每日领取10经验的任务可以正常完成吗？我这重置几次都没法领取。这个领取10经验的条件B站是不是有更改过？我手机端显示的是会员观看1分钟视频即可领取10经验，在没完成领取条件的情况下脚本无法领取经验，但我看完1分钟视频的时候重置任务就可以领取10经验，我就怀疑是不是脚本领取没问题，而是B站把领取经验条件更改了
![IMG_6644(20240809-021638)](https://github.com/user-attachments/assets/23d9a429-68fb-45f9-8a8e-29ab20464651)

**Comment by andywang425** [comment]
> 主站没问题了，现在这个会员每日领取10经验的任务可以正常完成吗？我这重置几次都没法领取。这个领取10经验的条件B站是不是有更改过？我手机端显示的是会员观看1分钟视频即可领取10经验，在没完成领取条件的情况下脚本无法领取经验，但我看完1分钟视频的时候重置任务就可以领取10经验，我就怀疑是不是脚本领取没问题，而是B站把领取经验条件更改了 ![IMG_6644(20240809-021638)](https://private-user-images.githubusercontent.com/75735934/356335097-23d9a429-68fb-45f9-8a8e-29ab20464651.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjgyNTksIm5iZiI6MTcyMzE2Nzk1OSwicGF0aCI6Ii83NTczNTkzNC8zNTYzMzUwOTctMjNkOWE0MjktNjhmYi00NWY5LThhOGUtMjlhYjIwNDY0NjUxLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAxNDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYmM2YTkwOWY5NWI1ZDY3YmQ1NjFmYTQ5ODM1MTBjNmNiNWM0NGIxNWE2YjA5ZGIwMmQ5OTFjYjgxYWI4NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aAbxEPk0LqBIyW0AXjtVN6-jSaE3uFadlpgj9S9TM6Y)

应该是领取条件变化的关系。开个新的issue吧。

不过这个功能我真不太好测试，因为我每次写脚本代码之前肯定已经刷过B站视频了。
