### ISSUE TITLE
发送弹幕点亮失败

### ISSUE THREAD

**Issue by kirayomato** [andywang425/BLTH#536]
### 描述bug

部分直播间脚本无法发送弹幕点亮牌子

### 重现bug

开启脚本进行发送弹幕打卡

### 预期行为

弹幕发送，牌子点亮

### 运行日志

返回msg为'k'，此时脚本仍会判断为弹幕发送成功，但是实际上并没有
```
BLTH[2024/8/14 15:00:12][DailyTask][LiveTask][LightTask]: BAPI.live.sendMsg((⌒▽⌒), 4788550) {code: 0, data: {…}, message: 'k', msg: 'k'}code: 0data: {mode_info: {…}, dm_v2: null}message: "k"msg: "k"[[Prototype]]: Object
BLTH[2024/8/14 15:00:12][DailyTask][LiveTask][LightTask]: 点亮熄灭勋章-发送弹幕 在直播间 4788550 发送弹幕 (⌒▽⌒) 成功
```

### 操作系统

windows 11

### 浏览器

Chrome 127

### 用户脚本管理器

Tampermonkey 5.1.1

### 脚本版本号

7.1.7

### 网络情况

好

**Comment by andywang425** [comment]
看来仅通过code判断是否发送成功还不够啊。你觉得是因为什么原因失败的？

**Comment by BARUBORA** [comment]
以前满级20级,依然可以发送弹幕点亮.
上一个版本,没有点赞点亮的版本,似乎可以成功发送弹幕到20级的直播室,成功点亮.
此后一直存在20级满级的勋章,均不发送弹幕点亮的问题.

**Comment by kirayomato** [comment]
> 看来仅通过code判断是否发送成功还不够啊。你觉得是因为什么原因失败的？

似乎是弹幕内容被拦截了，我复制了弹幕去直播间手动发送也发不出来

**Comment by andywang425** [comment]
> 似乎是弹幕内容被拦截了，我复制了弹幕去直播间手动发送也发不出来

我在自己直播间测试了一下发现弹幕包含屏蔽词时msg确实为k

**Comment by zqdlly** [comment]
现在为什么只有第一个牌子可以刷满1500亲密度呢，其他都没动静

**Comment by kirayomato** [comment]
> > 似乎是弹幕内容被拦截了，我复制了弹幕去直播间手动发送也发不出来
> 
> 我在自己直播间测试了一下发现弹幕包含屏蔽词时msg确实为k

可以把发弹幕改成发表情点亮，有些直播间似乎是屏蔽了颜文字的
