### ISSUE TITLE
可以考虑添加隐藏底部弹幕功能吗

### ISSUE THREAD

**Issue by nochiyan** [andywang425/BLTH#537]
### 描述

如题

**Comment by andywang425** [comment]
我记得远古版本有类似功能。这个功能真的很不好做，要拦截、分析和修改websocket弹幕流，挺有挑战性的。我觉得短期内没戏。

**Comment by andywang425** [comment]
可以看看这个 https://github.com/xmcp/pakku.js ，但是需要一点编程基础
