### ISSUE TITLE
请问还有更新的计划吗

### ISSUE THREAD

**Issue by aa9578123** [andywang425/BLTH#538]
### 描述

b站逆天操作以后刷不了亲密度了，还会更新吗，还是说现在只能一个一个刷不能一起刷了

**Comment by andywang425** [comment]
b站不改那就只能一个一个刷，没办法

**Comment by zqdlly** [comment]
> b站不改那就只能一个一个刷，没办法

真诚希望您考虑一下，如果增加一个定时器功能，每满25分钟，就改变网址到另一位主播的直播间里，这样不知是否可以持续增加其他人的亲密度。

**Comment by andywang425** [comment]
> 真诚希望您考虑一下，如果增加一个定时器功能，每满25分钟，就改变网址到另一位主播的直播间里，这样不知是否可以持续增加其他人的亲密度。

请不要在issue里聊无关的话题。这个问题我们已经在 #535 讨论过，不会考虑做。

你在另一个issue #536 里提到：

> 现在为什么只有第一个牌子可以刷满1500亲密度呢，其他都没动静

那就开个新的issue反馈。把你的日志、配置等你觉得有用的信息发出来，大家一起看看是什么原因。

**Comment by kirayomato** [comment]
在开脚本刷亲密度的时候如果也开了其他直播间可能就会导致亲密度加不了
