### ISSUE TITLE
edge浏览器更新后，脚本在零点零五分时直接刷新今日直播已看完

### ISSUE THREAD

**Issue by lixueshu** [andywang425/BLTH#543]
### 描述bug

edge浏览器更新后，脚本在零点零五分时直接刷新今日直播已看完，但实际一分钟都没看

### 重现bug

Microsoft Edge
版本 128.0.2739.54 (正式版本) (64 位)

### 预期行为

在谷歌浏览器脚本依然可以正常运行

### 运行日志

无

### 操作系统

win10专业版

### 浏览器

Microsoft Edge 版本 128.0.2739.54 (正式版本) (64 位)

### 用户脚本管理器

tampermonkey

### 脚本版本号

5.1.1

### 网络情况

好

**Comment by andywang425** [comment]
是跨天用脚本，到00:05就会这样吗？

**Comment by lixueshu** [comment]
> 是跨天用脚本，到00:05就会这样吗
是的，到00：05后就会刷新今日直播已观看完

**Comment by andywang425** [comment]
好，我找找原因

**Comment by NagiKugi** [comment]
我用的火狐 也这样。。。

**Comment by lixueshu** [comment]
> 是跨天用脚本，到00:05就会这样吗？
我今天刷新了一下，发现今天脚本可以看直播了，和前两天不同的是前两天会有统计失败的提示

**Comment by lixueshu** [comment]
> 好，我找找原因

我有两个号，大号放edge上挂，小号放谷歌上挂。现在是大号能挂，小号就不能挂直接显示直播观看已完成，这什么情况

**Comment by andywang425** [comment]
7.1.9已更新，可以测试一下好不好用

**Comment by lixueshu** [comment]
> 7.1.9已更新，可以测试一下好不好用

欧克
