### ISSUE TITLE
希望可以在面板里放一个关闭（X）按钮

### ISSUE THREAD

**Issue by nico-katsu** [andywang425/BLTH#544]
### 描述

我找了半天，都不知道怎么把面板关掉。。。

**Comment by andywang425** [comment]
不打算放，说明里已经写得挺清楚了

> 隐藏/显示控制面板：点击位于直播画面上方的蓝底白字按钮即可开/关控制面板。你也可以使用键盘快捷键alt+b。

再说，如果有人找不到关闭的按钮，点X关了，问题就变成了找不到打开面板的按钮...
