### ISSUE TITLE
希望在取关BLTH天选关注UP分组里面的UP之前查询一遍白名单再取关

### ISSUE THREAD

**Issue by qicheBoy** [andywang425/BLTH#55]
本人用主号运行这个脚本，每次定时清理人的时候会把自己之前关注的UP也一并取关（自己关注的UP主开天选也会移到这个分组）
希望取关之前查询一次白名单后再取关

**Comment by andywang425** [comment]
挺好的建议，我会在日后的版本加入这个特性。

**Comment by andywang425** [comment]
已添加该特性。
