### ISSUE TITLE
部分特殊直播间脚本无效

### ISSUE THREAD

**Issue by Iseason2000** [andywang425/BLTH#56]
如有大横幅的直播间，问题直播间id:388 （2021年1月30日）
无其他直播间的条件下显示
![image](https://user-images.githubusercontent.com/65019366/106349123-46942680-6306-11eb-9152-7a6df43dae5f.png)

![image](https://user-images.githubusercontent.com/65019366/106349108-1a78a580-6306-11eb-8efd-ff3492c2f4ec.png)

**Comment by andywang425** [comment]
了解了，我会试着修复。

**Comment by andywang425** [comment]
已修复
