### ISSUE TITLE
有些主播直播不显示画面，黑屏也没有声音，只能看到别人的弹幕

### ISSUE THREAD

**Issue by tskyan** [andywang425/BLTH#58]
比如https://live.bilibili.com/680，或者https://www.bilibili.com/blackboard/activity-xlqtJZLnM.html。关掉插件就会恢复正常。怀疑是不是跟直播间背景有关

**Comment by andywang425** [comment]
目前发现在有背景的直播间，B站的js会和脚本冲突，我在以后的版本中会修复这个问题。
目前先找个普通的直播间挂机吧。
