### ISSUE TITLE
开了插件直播间画面无法切换原画

### ISSUE THREAD

**Issue by dalaoMTS** [andywang425/BLTH#61]
如题，不知道有没有其他伙伴会这样？

**Comment by dalaoMTS** [comment]
默认原画的直播间不影响

**Comment by andywang425** [comment]
请问在哪些直播间遇到了这种情况？我测试时没遇到这种问题。

**Comment by MrCutey** [comment]
我开了直接黑屏 让我关广告插件 关了还是一样

**Comment by MrCutey** [comment]
https://live.bilibili.com/blanc/6直播间

**Comment by andywang425** [comment]
> https://live.bilibili.com/blanc/6 直播间

这个直播间我关了脚本和广告拦截插件后也看不了，默认是超清。  
我感觉可能不是脚本的问题？

**Comment by MrCutey** [comment]
之前看不了的时候把插件关了就能看 应该是插件原因吧 (昨晚到后面又可以看了 )

**Comment by dalaoMTS** [comment]
啊，更新后可以了
