### ISSUE TITLE
似乎屏蔽挂机检测(自动移动鼠标)失效

### ISSUE THREAD

**Issue by nita0318** [andywang425/BLTH#62]
**描述bug**  
长时间电脑无操作后会提示移动鼠标，不然自动终止播放

**重现bug**  
随便开个直播间挂着，不动鼠标，保持chrome在前台，持续60分钟左右就出现提示

**预期行为**  
正常情况下直播间不会自动停止播放
  
**使用环境:**  
 - 操作系统：Windows 10 19042.746
 - 浏览器及浏览器版本: Google Chrome 88.0.4324.150
 - 脚本的版本: 5.6.5

**其他**  
其他和B站相关的脚本
Bilibili Evolved (Preview) 预览版1.11.16
哔哩哔哩(b站)显示UID和注册时间 0.4.6
Bilibili Evolved 已启用延后加载和Ajax Hook API
如果是脚本兼容问题我就先换回稳定版试试？有空能否测试一下，谢谢了

**Comment by andywang425** [comment]
我知道目前存在这个问题，但实在是没能力修复。我试着去分析过B站的前端js，但没看懂挂机检测这块具体是怎么运作的。  
等找到方法后我一定及时修复，抱歉啦。

**Comment by nita0318** [comment]
5.6.5.3版本屏蔽挂机检测仍然失效，屏蔽后不会出现对话框提示移动鼠标，但是直播实际已停止播放，弹幕仍然能正常获取并显示。而移动鼠标并不能恢复正常，需要手动刷新(网页播放器内置的就行)才能继续观看直播
附上浏览器日志

[live.bilibili.com.log](https://github.com/andywang425/BLTH/files/5983132/live.bilibili.com.log)

**Comment by andywang425** [comment]
看了下日志似乎没什么有用的信息。我再观察一阵看看。

**Comment by andywang425** [comment]
最新版是否还存在这个问题？从前几个版本开始脚本采用了另一种模拟鼠标移动的方式。

**Comment by nita0318** [comment]
2021/3/4晚5.6.5.7版本测试，可以正常播放至少2小时53分长的直播流，正常播放期间弹幕可以正常获取，页面不会弹出其他提示窗口

**Comment by andywang425** [comment]
感谢测试，那这个问题应该是解决了
