### ISSUE TITLE
在Safari运行的时候总是会出现抽风现象

### ISSUE THREAD

**Issue by block-ship** [andywang425/BLTH#64]
**描述bug**
新版本（即此版本）在Safari浏览器中无法运行，而在运行旧版挂机助手时一切正常，很神奇

**重现bug**  
更新助手后发现无法启动，在关闭了所有插件与重装后仍无效

**使用环境:**  
 - 操作系统：系统为macOS Catalina 10.15.7（即最新版本）
 - 浏览器及浏览器版本: Safari 14.0.3（也是最新版本）
 - 脚本的版本: 5.6.5.3

**Comment by block-ship** [comment]
刚刚拿历史版本试了一下，5.6.4.4可以运行，而更高版本不行

**Comment by andywang425** [comment]
抱歉，由于我没mac所以还没在macOS上测试过这个脚本。可能得先装个macOS的的虚拟机。  
如果可以的话能否先打开脚本的控制台日志，然后再运行一下新版本脚本，把控制台日志发出来？能直接看出错误原因的话我就不费那劲折腾虚拟机了。

**Comment by block-ship** [comment]
Syntax error @ "B站直播间挂机助手"!
##########################
JSHINT output:
##########################

eval@[native code]
https://live.bilibili.com/740509:3:103
c@https://live.bilibili.com/740509:2:147
https://live.bilibili.com/740509:3:270
na
create
d
runListeners

P@https://live.bilibili.com/740509:11:135
dispatchEvent@[native code]
send@safari-extension://85F5DBA0-5E6F-4FB9-9413-85E8544303FC/f34dc7ed/content.js:7:278
safari-extension://85F5DBA0-5E6F-4FB9-9413-85E8544303FC/f34dc7ed/content.js:27:157
processQueue@safari-extension://85F5DBA0-5E6F-4FB9-9413-85E8544303FC/f34dc7ed/content.js:3:121
a@safari-extension://85F5DBA0-5E6F-4FB9-9413-85E8544303FC/f34dc7ed/content.js:9:397

**Comment by block-ship** [comment]
这是Safari的日志，下面还有几行没办法复制

**Comment by block-ship** [comment]
看样子是Safari自己的查错

**Comment by block-ship** [comment]
（着重号是显示的问题）
error： 
4925: n || a.errors ? ma**(**`Syntax error @ "${e.name}"!\n##########################\n${c}##########################\n\n${f}`**)**
3659:  b**(**a)****
224:     a && (c = L[a]) && (c**(**b**)**, delete L[a])
228:  "message.response" == b.m ? I**(**b.r, b.a**)** : m && !1 === m(b, b.r ? a => {
dispatchEvent:
content.js:275:  d.dispatchEvent.apply**(**d, [a]**)**  
topee-content.js:2277:  d**(**c**)**;

**Comment by block-ship** [comment]
error：
匿名脚本1 4925: n || a.errors ? ma(`Syntax error @ "${e.name}"!\n##########################\n${c}##########################\n\n${f}`) : ma(`Syntax error @ "${e.name}"!\n\n`,
匿名脚本1 3659:   b(a)
I 224: a && (c = L[a]) && (c(b), delete L[a])
P 228:  "message.response" == b.m ? I(b.r, b.a) : m && !1 === m(b, b.r ? a => {
dispatchEvent:
content.js:275:   d.dispatchEvent.apply(d, [a])
topee-content.js:2277: d(c);

SyntaxError: Invalid regular expression: invalid group specifier name
匿名脚本1 2955: c.stopImmediatePropagation();

差不多是这样

**Comment by andywang425** [comment]
谢谢，但看不懂为什么出错了😭。看来这虚拟机还是得装。  
过年期间会试着修复这个问题。辛苦你啦，除夕还在反馈bug，新年快乐！

**Comment by block-ship** [comment]
没事，反正闲着也是闲着，不如找点事做(｀・ω・´)

**Comment by andywang425** [comment]
今天调试了很久也没看出问题在哪，这个bug恐怕短期内修不好了。

**Comment by andywang425** [comment]
今天又琢磨了一会，发现其实只是一个正则出错了。
>const roomid = i.link.match(/(?<=https?:\/\/live\.bilibili\.com\/)\d+/)[0],  

这个正则在Chrome中能执行但在Safari中会出错，改为如下即可：  

>const roomid = i.link.match(/^https?:\/\/live\.bilibili\.com\/(\d+)$/)[1],

下个版本不会立刻发布，如果想自己修复的话请在脚本中搜索`(/(?<=https?:\/\/live\.bilibili\.com\/)\d+/)[0]`，将其替换为`(/^https?:\/\/live\.bilibili\.com\/(\d+)$/)[1]`。

参考了Stackoverflow上的一个帖子 https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

**Comment by block-ship** [comment]
这个好诶，我去试试

**Comment by andywang425** [comment]
> 这个好诶，我去试试

有用不，有用的话告诉我一声。

**Comment by block-ship** [comment]
> > 这个好诶，我去试试
> 
> 有用不，有用的话告诉我一声。

这个有用的，替换之后就能正常使用了

**Comment by andywang425** [comment]
> > > 这个好诶，我去试试
> > 
> > 
> > 有用不，有用的话告诉我一声。
> 
> 这个有用的，替换之后就能正常使用了

那就好，买Tampermonkey拓展的12块没白花🤣

**Comment by block-ship** [comment]
> > > > 这个好诶，我去试试
> > > 
> > > 
> > > 有用不，有用的话告诉我一声。
> > 
> > 
> > 这个有用的，替换之后就能正常使用了
> 
> 那就好，买Tampermonkey拓展的12块没白花🤣

😂
