### ISSUE TITLE
关于粉丝勋章打卡

### ISSUE THREAD

**Issue by ThreeCatsLoveFish** [andywang425/BLTH#67]
### 需求描述

b站上过一次舰长后就会到21级，在21级以上粉丝勋章打卡是没用的（不会增加亲密度）
我暂时是放入黑名单不打卡，但是这样又很奇怪，而且我每次上舰长还要记得加进去

### 实现

1. 在拉取粉丝勋章的时候多判断一次等级数，大于20自动跳过
2. 可以做成开关配置，默认关闭，有需要的开启

**Comment by andywang425** [comment]
谢谢反馈，我现在才知道21级以上粉丝勋章打卡不加亲密度😂  
下个版本会加等级判断，等级大于20的不打卡。

**Comment by X-Holmes** [comment]
虽然不加亲密度，但是好像可以点亮粉丝勋章吧(21级以上的粉丝勋章难道不会熄灭吗)

**Comment by ThreeCatsLoveFish** [comment]
> 虽然不加亲密度，但是好像可以点亮粉丝勋章吧(21级以上的粉丝勋章难道不会熄灭吗)

没想到吧，真的不会

**Comment by ThreeCatsLoveFish** [comment]
> 虽然不加亲密度，但是好像可以点亮粉丝勋章吧(21级以上的粉丝勋章难道不会熄灭吗)

有钱真的可以为所欲为

**Comment by konglinSoul** [comment]
掉船以后就会熄灭了，20级以上都掉船之后就得手动点亮了
