### ISSUE TITLE
该脚本无法每次都在直播页面运行

### ISSUE THREAD

**Issue by cyslm** [andywang425/BLTH#71]
**描述bug**  
基本只有在有版本更新时设置页面才会弹出脚本才会运行

**重现bug**  
大概在三四个版本前就有这个bug，中间好了一阵子，后来又开始不启动了，关掉了abp并且检查了google脚本设置问题依旧存在

**预期行为**
正常情况下打开直播间应该运行脚本并弹出设置框和按钮
  
**使用环境:**  
 - 操作系统：Windows 10
 - 浏览器及版本: Chrome 88.0.4324.190（正式版本） （64 位）
 - 用户脚本管理器及版本：Tampermonkey 4.12.6128
 - 脚本的版本: 5.6.5.7
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 
哔哩哔哩(B站|Bilibili)收藏夹Fix
解除B站区域限制
跳过bilibili充电鸣谢

**Comment by cyslm** [comment]
尝试了“一些建议”里最后一条之后问题解决

**Comment by cyslm** [comment]
今天再次出现控制栏不弹出和脚本不运行问题，并且重复昨日reset all后依旧无法运行

**Comment by cyslm** [comment]
在chrome://flags中输入Reduce default 'referer' header granularity，都显示No matching experiments

**Comment by andywang425** [comment]
> 在chrome://flags中输入Reduce default 'referer' header granularity，都显示No matching experiments

最新版把这个特性移除了，可以用edge的方法通过装拓展（[referer-control](https://chrome.google.com/webstore/detail/referer-control/hnkcfpcejkafcihlgbojoidoihckciin)）来实现。  

至于为什么不运行暂时不清楚原因，短期内没法解决（因为我这边没法复现出这个bug）。  
以后可能会发布测试版，到时候会在这个issue里通知你。

**Comment by cyslm** [comment]
> > 在chrome：// flags中输入减少默认的“ referer”标头粒度，都显示没有匹配的实验
> 
> 最新版把这个特性移除了，可以用edge的方法通过安装扩展（[referer-control](https://chrome.google.com/webstore/detail/referer-control/hnkcfpcejkafcihlgbojoidoihckciin)）来实现。
> 
> 因为为什么不运行暂时不清楚原因，短期内没法解决（因为我这边没法复现出这个bug）。
> 以后可能会发布测试版，到时候会在这个issue里通知你。

最近通过开机后一段时间，把梯子代理全局调整为pac后关闭所有网页再打开来解决脚本不启动的问题，不知道这条信息是否有帮助

**Comment by cyslm** [comment]
> > 在chrome://flags中输入Reduce default 'referer' header granularity，都显示No matching experiments
> 
> 最新版把这个特性移除了，可以用edge的方法通过装拓展（[referer-control](https://chrome.google.com/webstore/detail/referer-control/hnkcfpcejkafcihlgbojoidoihckciin)）来实现。
> 
> 至于为什么不运行暂时不清楚原因，短期内没法解决（因为我这边没法复现出这个bug）。
> 以后可能会发布测试版，到时候会在这个issue里通知你。

刚刚尝试了三种方式
1.梯子开机自启状态下开机，浏览器窗口弹出，脚本未运行，关闭浏览器再打开，脚本未运行，梯子全局调整为pac再打开浏览器，脚本运行
2.梯子开机自启状态下开机，浏览器窗口弹出，脚本未运行，梯子全局调整为pac然后刷新页面脚本未运行
3.关掉了梯子的开机自启权限后开机，浏览器弹出窗口，脚本未运行，关闭浏览器再打开，脚本运行

**Comment by cyslm** [comment]
> > 在chrome://flags中输入Reduce default 'referer' header granularity，都显示No matching experiments
> 
> 最新版把这个特性移除了，可以用edge的方法通过装拓展（[referer-control](https://chrome.google.com/webstore/detail/referer-control/hnkcfpcejkafcihlgbojoidoihckciin)）来实现。
> 
> 至于为什么不运行暂时不清楚原因，短期内没法解决（因为我这边没法复现出这个bug）。
> 以后可能会发布测试版，到时候会在这个issue里通知你。

然后有些情况下通过梯子更改为pac再重启浏览器，脚本窗口会在所有直播页面弹出

**Comment by andywang425** [comment]
感谢提供信息，因为我没设置梯子开机自启所以一直没往这方面想。等我有空了琢磨一下原因。

**Comment by andywang425** [comment]
我发现当网速特别慢的时候脚本会无法运行，感觉可能是Tampermonkey的问题，因为脚本完全没被注入到页面上。  
最近Tampermoenkey更新了一次，其中有提到优化了注入，也许更新一下Tampermoenkey会有所改善？
