### ISSUE TITLE
如何在无图形界面的Linux系统运行此脚本？

### ISSUE THREAD

**Issue by LiuYiLin-CA** [andywang425/BLTH#72]
我想使用Linux终端使用这个脚本，怎么样能够实现？

**Comment by andywang425** [comment]
无图形界面连浏览器都运行不了，不可能运行这个脚本的。  
如果你只是想做做每日任务，我推荐用以下几个项目：
+ https://github.com/RayWangQvQ/BiliBiliTool
+ https://github.com/srcrs/BilibiliTask
+ https://github.com/JunzhouLiu/BILIBILI-HELPER

如果还想抽天选时刻的话推荐用这个：
+ https://github.com/happy888888/BiliExp
