### ISSUE TITLE
功能建议：希望可以有屏蔽天选时刻和PK结果弹窗的功能

### ISSUE THREAD

**Issue by somelee** [andywang425/BLTH#78]
首先，这个助手非常的棒！

但是，还是希望可以有屏蔽天选时刻和PK结果弹窗的功能。

只想单纯的看直播，不想界面上出现影响观看的弹窗，也不想参加任何活动。

感谢开发者！

**Comment by andywang425** [comment]
好的，日后会加这两个功能。

**Comment by andywang425** [comment]
已在最新版中添加这两个功能，目前仍有欠缺，等我想到更好的办法后会再做改进。

**Comment by somelee** [comment]
感谢！
