### ISSUE TITLE
日志会挡住动态等功能

### ISSUE THREAD

**Issue by SakuraSayaka** [andywang425/BLTH#82]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README和脚本的内置说明。  
**描述bug**  
日志会将直播间内展开的动态等悬浮窗遮住，并且高能榜和大航海在未被选中时标题无法看见

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. 点击日志
2. 鼠标移动到动态

**预期行为**  
动态悬浮窗挡住日志

**截图**  
![2021-04-05 10 46 58](https://user-images.githubusercontent.com/15071507/113531798-482ae500-95fc-11eb-85bf-b2e952cfe820.png)
![2021-04-05 10 47 05](https://user-images.githubusercontent.com/15071507/113531800-49f4a880-95fc-11eb-93c5-9a4c91074e0a.png)

**日志**
chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=B%25E7%25AB%2599%25E7%259B%25B4%25E6%2592%25AD%25E9%2597%25B4%25E6%258C%2582%25E6%259C%25BA%25E5%258A%25A9%25E6%2589%258B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:21:945] InitData: API.gift.gift_config: Object
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:22:426] InitData: API.getuserinfo: {code: "REPONSE_OK", msg: "success", message: "success", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:22:627] InitData: API.x.getAccInfo: {code: 0, message: "0", ttl: 1, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:22:630] Live_info: {room_id: 10101, uid: 3076858, ruid: 597396, gift_list: Array(306), rnd: 1617590658, …}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:22:862] before init() getMedalList: API.i.medal: {code: 0, msg: "", message: "", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:22:864] medla_info: {status: {…}, medal_list: Array(8)}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:22:890] MY_API.GIFT_COUNT: {COUNT: 0, ANCHOR_COUNT: 5, MATERIAL_COUNT: 0, CLEAR_TS: 1617568162511}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:22:896] toast-success: CACHE载入成功
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:22:908] MY_API.CONFIG: {AUTO_DANMU: false, AUTO_GIFT: false, AUTO_GIFT_ROOMID: Array(1), AUTO_GROUP_SIGN: true, ANCHOR_LOTTERY: false, …}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:22:909] runExactMidnight: 重置统计 Tue Apr 06 2021 00:00:00 GMT+0800 (中国标准时间)
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:23:877] 直播间列表: {code: 0, msg: "success", message: "success", data: Array(8)}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:472] 直播间列表: {code: 0, msg: "success", message: "success", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:660] 直播间列表: {code: 0, msg: "success", message: "success", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:667] 直播间列表: {code: 0, msg: "success", message: "success", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:707] 直播间列表: {code: 0, msg: "success", message: "success", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:709] 直播间列表: {code: 0, msg: "success", message: "success", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:709] 直播间列表: {code: 0, msg: "success", message: "success", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:710] 直播间列表: {code: 0, msg: "success", message: "success", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:711] 直播间列表: {code: 0, msg: "success", message: "success", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:722] 获取弹幕服务器信息 网游区: {code: 0, msg: "ok", message: "ok", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:886] 获取弹幕服务器信息 手游区: {code: 0, msg: "ok", message: "ok", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:888] 获取弹幕服务器信息 单机游戏区: {code: 0, msg: "ok", message: "ok", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:890] 获取弹幕服务器信息 娱乐区: {code: 0, msg: "ok", message: "ok", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:892] 获取弹幕服务器信息 虚拟主播区: {code: 0, msg: "ok", message: "ok", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:894] 获取弹幕服务器信息 电台区: {code: 0, msg: "ok", message: "ok", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:896] 获取弹幕服务器信息 学习区: {code: 0, msg: "ok", message: "ok", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:24:897] 获取弹幕服务器信息 生活区: {code: 0, msg: "ok", message: "ok", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:25:473] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS_NEW", pk_id: 201854353, pk_status: 201, timestamp: 1617590665, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:25:479] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS", pk_id: 201854353, pk_status: 201, timestamp: 1617590665, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:27:994] runMidnight: 粉丝勋章打卡弹幕 Tue Apr 06 2021 00:01:00 GMT+0800 (中国标准时间)
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:28:192] runTomorrow: 应援团签到 Tue Apr 06 2021 08:00:00 GMT+0800 (中国标准时间)
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:28:389] runMidnight: 每日任务 Tue Apr 06 2021 00:01:00 GMT+0800 (中国标准时间)
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:28:592] runMidnight: 直播签到 Tue Apr 06 2021 00:01:00 GMT+0800 (中国标准时间)
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:29:394] runMidnight: 获取小心心 Tue Apr 06 2021 00:01:00 GMT+0800 (中国标准时间)
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:42:590] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS_NEW", pk_id: 201854353, pk_status: 201, timestamp: 1617590682, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:42:590] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS", pk_id: 201854353, pk_status: 201, timestamp: 1617590682, data: {…}}cmd: "PK_BATTLE_PROCESS"data: {battle_type: 1, init_info: {…}, match_info: {…}}pk_id: 201854353pk_status: 201timestamp: 1617590682__proto__: Object
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:54:742] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS_NEW", pk_id: 201854353, pk_status: 201, timestamp: 1617590694, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:54:748] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS", pk_id: 201854353, pk_status: 201, timestamp: 1617590694, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:55:952] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS_NEW", pk_id: 201854353, pk_status: 201, timestamp: 1617590695, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:44:55:956] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS", pk_id: 201854353, pk_status: 201, timestamp: 1617590695, data: {…}}cmd: "PK_BATTLE_PROCESS"data: {battle_type: 1, init_info: {…}, match_info: {…}}pk_id: 201854353pk_status: 201timestamp: 1617590695__proto__: Object
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:9:855] 弹幕公告娱乐区: {cmd: "ROOM_REAL_TIME_MESSAGE_UPDATE", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:9:860] 弹幕公告学习区: {cmd: "ROOM_REAL_TIME_MESSAGE_UPDATE", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:9:863] 弹幕公告电台区: {cmd: "ROOM_REAL_TIME_MESSAGE_UPDATE", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:9:898] 弹幕公告网游区: {cmd: "ROOM_REAL_TIME_MESSAGE_UPDATE", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:14:906] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS_NEW", pk_id: 201854353, pk_status: 201, timestamp: 1617590714, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:14:911] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS", pk_id: 201854353, pk_status: 201, timestamp: 1617590714, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:40:270] 弹幕公告网游区: {cmd: "HOT_RANK_CHANGED", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:45:250] 弹幕公告网游区: {cmd: "HOT_RANK_CHANGED", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:50:273] 弹幕公告网游区: {cmd: "HOT_RANK_CHANGED", data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:50:313] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS_NEW", pk_id: 201854353, pk_status: 201, timestamp: 1617590750, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:50:322] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS", pk_id: 201854353, pk_status: 201, timestamp: 1617590750, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:52:515] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS_NEW", pk_id: 201854353, pk_status: 201, timestamp: 1617590752, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:52:521] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS", pk_id: 201854353, pk_status: 201, timestamp: 1617590752, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:53:3] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS_NEW", pk_id: 201854353, pk_status: 201, timestamp: 1617590752, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:53:12] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS", pk_id: 201854353, pk_status: 201, timestamp: 1617590752, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:53:225] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS_NEW", pk_id: 201854353, pk_status: 201, timestamp: 1617590753, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:53:231] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS", pk_id: 201854353, pk_status: 201, timestamp: 1617590753, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:53:409] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS_NEW", pk_id: 201854353, pk_status: 201, timestamp: 1617590753, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:53:418] 弹幕公告单机游戏区: {cmd: "PK_BATTLE_PROCESS", pk_id: 201854353, pk_status: 201, timestamp: 1617590753, data: {…}}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:55:805] 弹幕公告电台区: {cmd: "NOTICE_MSG", id: 2, name: "分区道具抽奖广播样式", full: {…}, half: {…}, …}
userscript.html?name=B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.user.js&id=7927c26b-aa2d-4188-b922-b66cd651da12:125 [IGIFTMSG][10:45:55:903] 检查房间返回信息: {code: 0, message: "0", ttl: 1, data: {…}}

**使用环境:**  
 - 操作系统：Windows 10
 - 浏览器及版本: Cent Browser 版本 4.3.9.248（正式版本） （64 位） (Chromium 86.0.4240.198)
 - 用户脚本管理器及版本：Tampermonkey 4.11
 - 脚本的版本: 5.6.6.3
 - 网络情况(网速): 一般
 - 其他浏览器插件/脚本: Bilibili Evolved (Preview) 1.12.3

**Comment by SakuraSayaka** [comment]
关于高能榜和大航海在未被选中时标题无法看见的问题确认是Bilibili Evolved的问题

**Comment by andywang425** [comment]
目前的日志窗口其实是个独立的弹窗所以会挡住页面元素。以后会想办法用其他方式插入日志。
