### ISSUE TITLE
创建分组遇到的问题

### ISSUE THREAD

**Issue by xielhz** [andywang425/BLTH#83]
**描述bug**  
不确定是不是
创建分组提示失败，但是实际上有创建。
之后也有日志但都是检查，在右上角出现蓝色提示框：小心心

**重现bug**  

1. 加载脚本
2. 提示分组已达上限
3. 删除一个分组
4. 重新加载
5. 出现bug

**预期行为**  
脚本正常运行
**截图**  

![image](https://user-images.githubusercontent.com/43595642/113665508-299e1a00-96e0-11eb-88ba-e9a872b61108.png)
![image](https://user-images.githubusercontent.com/43595642/113665552-3ae72680-96e0-11eb-9789-6373f8b8dfbf.png)
![image](https://user-images.githubusercontent.com/43595642/113665559-3de21700-96e0-11eb-871d-2896bf04e564.png)

**运行日志**  
2021/4/6下午1:52:17
脚本载入配置成功
2021/4/6下午1:52:17
——————连接弹幕服务器成功——————
房间号: 5279 分区: 网游区
2021/4/6下午1:52:17
——————连接弹幕服务器成功——————
房间号: 47867 分区: 单机游戏区
2021/4/6下午1:52:17
——————连接弹幕服务器成功——————
房间号: 22528847 分区: 电台区
2021/4/6下午1:52:17
——————连接弹幕服务器成功——————
房间号: 22094081 分区: 学习区
2021/4/6下午1:52:17
——————连接弹幕服务器成功——————
房间号: 22348429 分区: 虚拟主播区
2021/4/6下午1:52:17
——————连接弹幕服务器成功——————
房间号: 3670448 分区: 娱乐区
2021/4/6下午1:52:18
——————连接弹幕服务器成功——————
房间号: 203396 分区: 生活区
2021/4/6下午1:52:19
——————连接弹幕服务器成功——————
房间号: 34348 分区: 手游区
2021/4/6下午1:52:23
检查网游小时榜房间的礼物
2021/4/6下午1:52:23
检查手游小时榜房间的礼物
2021/4/6下午1:52:24
检查单机游戏小时榜房间的礼物
2021/4/6下午1:52:24
检查娱乐小时榜房间的礼物
2021/4/6下午1:52:24
检查电台小时榜房间的礼物
2021/4/6下午1:52:24
[天选时刻] 开始获取关注分组信息
2021/4/6下午1:52:24
检查虚拟主播小时榜房间的礼物
2021/4/6下午1:52:24
检查生活小时榜房间的礼物
2021/4/6下午1:52:24
[天选时刻] 创建分组【BLTH天选中奖UP】出错 分组数量已达上限
2021/4/6下午1:52:24
检查学习小时榜房间的礼物
2021/4/6下午2:02:17
检查网游小时榜房间的礼物
2021/4/6下午2:02:17
检查手游小时榜房间的礼物
2021/4/6下午2:02:18
检查单机游戏小时榜房间的礼物
2021/4/6下午2:02:18
检查娱乐小时榜房间的礼物
2021/4/6下午2:02:18
检查电台小时榜房间的礼物
2021/4/6下午2:02:18
检查虚拟主播小时榜房间的礼物
2021/4/6下午2:02:18
检查生活小时榜房间的礼物
2021/4/6下午2:02:18
检查学习小时榜房间的礼物
**使用环境:**  
 - 操作系统：Windows 10`
 - 浏览器及版本: Chrome 89.0.4389.82（正式版本）`
 - 用户脚本管理器及版本：Tampermonkey 4.12
 - 脚本的版本: 5.6.6.3
 - 网络情况(网速): `一般
 -

**Comment by andywang425** [comment]
我个人更倾向于是b站的问题，`分组数量已达上限`这句话来源于访问b站api所得的返回值。可能是b站服务器出了点小问题导致的。等我有空了也会再测试一下。

**Comment by xielhz** [comment]
每一次刷新页面他都提示一次。还有就是
![image](https://user-images.githubusercontent.com/43595642/113725004-7bb55e80-9725-11eb-9aef-cc84efb99b7c.png)

**Comment by xielhz** [comment]
每一次刷新页面他都提示一次。还有就是
![image](https://user-images.githubusercontent.com/43595642/113725004-7bb55e80-9725-11eb-9aef-cc84efb99b7c.png)

**Comment by andywang425** [comment]
> 每一次刷新页面他都提示一次。还有就是
> ![image](https://user-images.githubusercontent.com/43595642/113725004-7bb55e80-9725-11eb-9aef-cc84efb99b7c.png)

这个问题在最新版中应该已经被修复了，如果仍有问题可另开issue反馈。
