### ISSUE TITLE
在电脑锁屏后不再参加天选，直至退出锁屏

### ISSUE THREAD

**Issue by MaxIkaros** [andywang425/BLTH#86]
**描述bug**  
Chrome浏览器上的脚本在电脑锁屏或离开直播界面10分钟之后不再参加天选，“日志”栏内的内容不再更新，在“控制台”内只能见到“屏蔽挂机检测: 触发一次MouseEvent(mousemove)”的记录。直至退出锁屏才会继续运行。在Microsoft Edge和Firefox上可以正常运行不中断，在Chrome上从今年3月起出现这种情况，多次重装仍无效果。

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. 在“参加天选时刻抽奖”处打勾；
2. 在“屏蔽挂机检测处”处打勾。

**预期行为**  
在电脑锁屏或离开直播界面后回来可以看到其后台运行时在“日志”上留下的记录，而非突兀的时间跳跃。

**截图**  
![image](https://user-images.githubusercontent.com/73374769/114300960-2b5b4980-9af5-11eb-9526-eb0490362775.png)
![image](https://user-images.githubusercontent.com/73374769/114300970-37dfa200-9af5-11eb-8dc9-099e812ca0c8.png)
 
**运行日志**  
![image](https://user-images.githubusercontent.com/73374769/114300999-475eeb00-9af5-11eb-85d4-17f1691d104f.png)
![image](https://user-images.githubusercontent.com/73374769/114301014-59408e00-9af5-11eb-8e96-e6bfde06b910.png)  

**使用环境:**  
 - 操作系统：`Windows 10 专业版`
 - 浏览器及版本: `Chrome  89.0.4389.114（正式版本） （64 位）`、`Microsoft Edge 89.0.774.68 (官方内部版本) (64 位)`
 - 用户脚本管理器及版本：`Tampermonkey 4.11`
 - 脚本的版本: `5.6.6.5`
 - 网络情况(网速): `好`
 - 其他浏览器插件/脚本: `Bilibili Evolved（版本1.12.4）` 

**其他**  
Firefox卸了，不知道版本是什么了。

**Comment by andywang425** [comment]
关于锁屏后不运行的问题我建议试试看这里提到的方法https://zhidao.baidu.com/question/1834608120007383060.html 可能有帮助。  
离开直播界面 是不是指开着直播间的标签但是在浏览其他标签页？  

![image](https://user-images.githubusercontent.com/56548456/114305929-bbf15400-9b0c-11eb-97bd-07054cd2d6fd.png)

---------

我的建议是拖动直播间的标签页使其变成一个独立的窗口  

---------

![image](https://user-images.githubusercontent.com/56548456/114306055-2dc99d80-9b0d-11eb-9142-02981ff5cafd.png)

然后在地址栏输入`chrome://flags/`，搜索`Calculate window occlusion on Windows`，把这项设为enable，重启浏览器。之后你就一直把直播间的窗口放在后台就行。

**Comment by MaxIkaros** [comment]
好了，现在终于正常了。感谢。

**Comment by jkluio78** [comment]
> 好了，现在终于正常了。感谢。

楼主，请问锁屏后插件运行异常的问题你解决了吗？

**Comment by jkluio78** [comment]
所以你在chrome安装最新版的插件，锁屏后也能正常运行吗？能请教下你在chrome是具体是怎么解决的吗？是按照这个页面https://zhidao.baidu.com/question/1834608120007383060.html的第一个答案来做就行了吗？

**Comment by MaxIkaros** [comment]
> 所以你在chrome安装最新版的插件，锁屏后也能正常运行吗？能请教下你在chrome是具体是怎么解决的吗？是按照这个页面https://zhidao.baidu.com/question/1834608120007383060.html 的第一个答案来做就行了吗？

能正常运行。我把Owner发的步骤（https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895）都做了一遍后就可以了。

**Comment by jkluio78** [comment]
> > 所以你在chrome安装最新版的插件，锁屏后也能正常运行吗？能请教下你在chrome是具体是怎么解决的吗？是按照这个页面https://zhidao.baidu.com/question/1834608120007383060.html 的第一个答案来做就行了吗？
> 
> 能正常运行。我把Owner发的步骤（[https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895）都做了一遍后就可以了。](https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895%EF%BC%89%E9%83%BD%E5%81%9A%E4%BA%86%E4%B8%80%E9%81%8D%E5%90%8E%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BA%86%E3%80%82)

### 我看谷歌浏览器和egde浏览器的运行日志发现了一个小规律（但可能没什么用）
13：43我开启了天选和控制台日志，然后锁屏
![image](https://user-images.githubusercontent.com/74967641/120893571-8d908080-c646-11eb-8cf4-71b9f104be5f.png)
经过大约5分钟，也就是13：48，天选的请求频率从**一分钟内数次**（_红线之上_）变成**一分钟一次**（_红线之下_）
![image](https://user-images.githubusercontent.com/74967641/120894166-9df62a80-c649-11eb-9a9f-0e9a10f116d3.png)
14：33：59我解除锁屏，进入浏览器，请求频率恢复**一分钟内数次**（_红线之下_）
![image](https://user-images.githubusercontent.com/74967641/120893712-3b039400-c647-11eb-98ce-664b6250bcce.png)

### 结论
![image](https://user-images.githubusercontent.com/74967641/120894032-e234fb00-c648-11eb-8241-144a77dce72e.png)
我花了2天时间对谷歌浏览器和egde浏览器做了相同的测试，同时测试了锁屏和最小化的情况，发现情况基本一致：

1.锁屏/最小化
2.五分钟后请求频率降低（疑似电脑休眠）
3.解除 锁屏/最小化，立刻恢复正常

我按照作者的步骤做完之后还是没有改善，但把电脑的休眠关闭以后谷歌浏览器就可以长时间锁屏运行了，edge浏览器也能保持一段时间的运行，但是经过4-6小时以后又进入每分钟只执行一次天选的情况，也许是和edge浏览器自身有关。

### 其他情况
1.测试的时候偶尔出现的报错
![image](https://user-images.githubusercontent.com/74967641/120894307-4dcb9800-c64a-11eb-95aa-a369cd020068.png)

2.与楼主提出此问题的日志做对比，当时谷歌浏览器锁屏，请求频率是降低到**两分钟一次**，我测试的时候都是降低到**一分钟一次**
![image](https://user-images.githubusercontent.com/74967641/120894447-f974e800-c64a-11eb-923c-a057295ce4dd.png)
对比
![image](https://user-images.githubusercontent.com/74967641/120894506-52448080-c64b-11eb-8ecd-d23550dc5f6f.png)

**Comment by MaxIkaros** [comment]
> > 所以你在chrome安装最新版的插件，锁屏后也能正常运行吗？能请教下你在chrome是具体是怎么解决的吗？是按照这个页面https://zhidao.baidu.com/question/1834608120007383060.html 的第一个答案来做就行了吗？
> 
> 能正常运行。我把Owner发的步骤（[https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895）都做了一遍后就可以了。](https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895%EF%BC%89%E9%83%BD%E5%81%9A%E4%BA%86%E4%B8%80%E9%81%8D%E5%90%8E%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BA%86%E3%80%82)

我在Greasy Fork上看到作者对类似问题的解决方法是把**Calculate window occlusion on Windows**设为**Disabled**。照做后，edge上的同类问题解决了。

**Comment by jkluio78** [comment]
> > > 所以你在chrome安装最新版的插件，锁屏后也能正常运行吗？能请教下你在chrome是具体是怎么解决的吗？是按照这个页面https://zhidao.baidu.com/question/1834608120007383060.html 的第一个答案来做就行了吗？
> > 
> > 
> > 能正常运行。我把Owner发的步骤（[https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895）都做了一遍后就可以了。](https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895%EF%BC%89%E9%83%BD%E5%81%9A%E4%BA%86%E4%B8%80%E9%81%8D%E5%90%8E%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BA%86%E3%80%82)
> 
> 我在Greasy Fork上看到作者对类似问题的解决方法是把**Calculate window occlusion on Windows**设为**Disabled**。照做后，edge上的同类问题解决了。

你好，我在edge://flags里面没有找到相关设置，网上搜到的只有这篇文章，https://answers.microsoft.com/zh-hans/microsoftedge/forum/msedge_video-msedge_win10/如何让edge允许/130753c4-b191-4564-b05b-e37a3b8d5d7c
能否说明下你是如何在edge浏览器里面设置的呢

**Comment by MaxIkaros** [comment]
> > > > 所以你在chrome安装最新版的插件，锁屏后也能正常运行吗？能请教下你在chrome是具体是怎么解决的吗？是按照这个页面https://zhidao.baidu.com/question/1834608120007383060.html 的第一个答案来做就行了吗？
> > > 
> > > 
> > > 能正常运行。我把Owner发的步骤（[https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895）都做了一遍后就可以了。](https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895%EF%BC%89%E9%83%BD%E5%81%9A%E4%BA%86%E4%B8%80%E9%81%8D%E5%90%8E%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BA%86%E3%80%82)
> > 
> > 
> > 我在Greasy Fork上看到作者对类似问题的解决方法是把**Calculate window occlusion on Windows**设为**Disabled**。照做后，edge上的同类问题解决了。
> 
> 你好，我在edge://flags里面没有找到相关设置，网上搜到的只有这篇文章，[https://answers.microsoft.com/zh-hans/microsoftedge/forum/msedge_video-msedge_win10/如何让edge允许/130753c4-b191-4564-b05b-e37a3b8d5d7c](https://answers.microsoft.com/zh-hans/microsoftedge/forum/msedge_video-msedge_win10/%E5%A6%82%E4%BD%95%E8%AE%A9edge%E5%85%81%E8%AE%B8/130753c4-b191-4564-b05b-e37a3b8d5d7c)
> 能否说明下你是如何在edge浏览器里面设置的呢

依照你的链接，我也去尝试了，和我修改的是一样的，最后导向的也是**Calculate window occlusion on Windows**。
![_5WN1~1NK0(`~6G$TFM)CA0](https://user-images.githubusercontent.com/73374769/121631518-d36b9f80-cab1-11eb-81ea-c71e6cdd02a6.png)

**Comment by jkluio78** [comment]
> > > 所以你在chrome安装最新版的插件，锁屏后也能正常运行吗？能请教下你在chrome是具体是怎么解决的吗？是按照这个页面https://zhidao.baidu.com/question/1834608120007383060.html 的第一个答案来做就行了吗？
> > 
> > 
> > 能正常运行。我把Owner发的步骤（[https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895）都做了一遍后就可以了。](https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895%EF%BC%89%E9%83%BD%E5%81%9A%E4%BA%86%E4%B8%80%E9%81%8D%E5%90%8E%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BA%86%E3%80%82)
> 
> 我在Greasy Fork上看到作者对类似问题的解决方法是把**Calculate window occlusion on Windows**设为**Disabled**。照做后，edge上的同类问题解决了。

请问你的edge浏览器是什么版本，我的是93.0.910.5，在edge://flags里面没有找到**Calculate window occlusion on Windows**

**Comment by MaxIkaros** [comment]
> > > > 所以你在chrome安装最新版的插件，锁屏后也能正常运行吗？能请教下你在chrome是具体是怎么解决的吗？是按照这个页面https://zhidao.baidu.com/question/1834608120007383060.html 的第一个答案来做就行了吗？
> > > 
> > > 
> > > 能正常运行。我把Owner发的步骤（[https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895）都做了一遍后就可以了。](https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895%EF%BC%89%E9%83%BD%E5%81%9A%E4%BA%86%E4%B8%80%E9%81%8D%E5%90%8E%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BA%86%E3%80%82)
> > 
> > 
> > 我在Greasy Fork上看到作者对类似问题的解决方法是把**Calculate window occlusion on Windows**设为**Disabled**。照做后，edge上的同类问题解决了。
> 
> 请问你的edge浏览器是什么版本，我的是93.0.910.5，在edge://flags里面没有找到**Calculate window occlusion on Windows**

91.0.864.48
![image](https://user-images.githubusercontent.com/73374769/121854866-49c40800-cd25-11eb-8a73-f7fa7b21fe73.png)

**Comment by jkluio78** [comment]
> > > > > 所以你在chrome安装最新版的插件，锁屏后也能正常运行吗？能请教下你在chrome是具体是怎么解决的吗？是按照这个页面https://zhidao.baidu.com/question/1834608120007383060.html 的第一个答案来做就行了吗？
> > > > 
> > > > 
> > > > 能正常运行。我把Owner发的步骤（[https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895）都做了一遍后就可以了。](https://github.com/andywang425/BLTH/issues/86#issuecomment-817308895%EF%BC%89%E9%83%BD%E5%81%9A%E4%BA%86%E4%B8%80%E9%81%8D%E5%90%8E%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BA%86%E3%80%82)
> > > 
> > > 
> > > 我在Greasy Fork上看到作者对类似问题的解决方法是把**Calculate window occlusion on Windows**设为**Disabled**。照做后，edge上的同类问题解决了。
> > 
> > 
> > 请问你的edge浏览器是什么版本，我的是93.0.910.5，在edge://flags里面没有找到**Calculate window occlusion on Windows**
> 
> 91.0.864.48
> ![image](https://user-images.githubusercontent.com/73374769/121854866-49c40800-cd25-11eb-8a73-f7fa7b21fe73.png)

好吧，我的是dev，怪不得找不到
![image](https://user-images.githubusercontent.com/74967641/121856034-9e1bb780-cd26-11eb-8e3f-d3755967c0cf.png)
