### ISSUE TITLE
有粉丝牌无直播间的牌子会自动送礼物

### ISSUE THREAD

**Issue by brainbush** [andywang425/BLTH#88]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README和脚本的内置说明。  
**描述bug**  
有粉丝牌无直播间的牌子会自动送礼物

**重现bug**  
说明您在进行了怎样的操作后出现了bug
1. 给一个有粉丝牌没有直播间的账号点亮牌子，比如 https://space.bilibili.com/439420557
2. 在自动送小心心时，提示系统错误并循环

**预期行为**  
自动跳过没开通直播间的用户的牌子点亮

**使用环境:**  
 - 操作系统：Widnows10 
 - 浏览器及版本:  Chrome 89.0.4389.114
 - 用户脚本管理器及版本：Tampermonkey 4.12
 - 脚本的版本: 5.6.6.6
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 无

**Comment by andywang425** [comment]
了解了，当时没想到有这种情况。

**Comment by andywang425** [comment]
已修复
