### ISSUE TITLE
无法参加天选

### ISSUE THREAD

**Issue by handsomebubu** [andywang425/BLTH#90]
**描述bug**  
天选获取完分区及房间信息后就会卡死

**重现bug**  
正常刷新网页

**预期行为**  
正常情况下获取了分区和房间后就会开始判别天选是否参加
![QQ图片20210414233021](https://user-images.githubusercontent.com/37483901/114739869-de3cd900-9d7b-11eb-8e24-a241a1d28618.png)
![QQ图片20210414233025](https://user-images.githubusercontent.com/37483901/114739878-e0069c80-9d7b-11eb-8c5e-5636360e3208.png)
![QQ图片20210414233029](https://user-images.githubusercontent.com/37483901/114739880-e09f3300-9d7b-11eb-8859-dd8d9e8aaf97.png)
![QQ图片20210414233033](https://user-images.githubusercontent.com/37483901/114739882-e137c980-9d7b-11eb-8021-57408a141676.png)

使用环境:
操作系统：如Windows 10 ltsb
浏览器及版本: 如Chrome 89.0.4389.114
用户脚本管理器及版本：如Tampermonkey 4.12
脚本的版本: 如5.665
网络情况(网速): 好
其他浏览器插件/脚本: Bilibili Evolved (Preview Offline)，哔哩哔哩助手

**Comment by andywang425** [comment]
![image](https://user-images.githubusercontent.com/56548456/114847550-653b9100-9e10-11eb-97c1-ea7801d1d89e.png)

能发一下在获取完了所有直播间后所输出的控制台日志？你可以先在过滤器里输`BLTH`把脚本日志过滤出来，再通过日志前面所显示的时间找一下相关日志。

**Comment by handsomebubu** [comment]
在5.67已经修复了
