### ISSUE TITLE
【新功能】请求添加 pushplus 推送渠道

### ISSUE THREAD

**Issue by wangmanv2** [andywang425/BLTH#97]
Server酱 停用了以后不支持微信公众号推送渠道，需要通过其他途径（企业微信、钉钉、WebHook）来实现推送，为此需要安装其他软件过程比较麻烦，目前发现 pushplus 还支持微信公众号推送渠道，所以想问一下能否添加这个渠道作为推送呢？
官网链接 [http://www.pushplus.plus/](http://www.pushplus.plus/)

**Comment by andywang425** [comment]
这个可以有。

**Comment by andywang425** [comment]
已在最新版5.6.7.4中添加此功能。
